### ISSUE TITLE
How to remove and Import private keys into geth

### ISSUE THREAD

**Issue by cullsin** [ethereum/web3.py#1001]
* Version: x.x.x
* Python: 3.6
* OS: all

### What was wrong?

I would like to import and delete private keys ( wallet )  in the geth. Can you suggest me which API signature I suppose to use?

Thanks,
Raja K

**Comment by pipermerriam** [comment]
There is no API for deleting keys.

You can import keys using this API which is only available via the go-ethereum client.

https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_importrawkey
