### ISSUE TITLE
Infura Method not Allowed for w3.eth.filter()

### ISSUE THREAD

**Issue by rbval** [ethereum/web3.py#1003]
* Version: 4.4.1
* Python: 3.5
* OS: osx

### What was wrong?
Doesn't let filter by an address on Rinkeby. Should this be signed? How exactly? Shouldn't this be a normal lookup, creating no transaction?

* The code which produced the error
```
provider = HTTPProvider(<infura_token>)
w3 = Web3(provider)
filt = w3.eth.filter('address': <CONTRACT_ADDRESS>)
```
* The full output of the error
```
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: <infura_token>
```
* What type of node you were connecting to.
Infura / Rinkeby

**Comment by voith** [comment]
@rbval Filters are not supported on Infura. 
This is not a bug in `web3.py`

**Comment by pipermerriam** [comment]
@rbval we have a feature in the works to fix this but it isn't complete yet.  See https://github.com/ethereum/web3.py/issues/551

cc @dylanjw
