### ISSUE TITLE
Rename middleware_stack to middleware_onion

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#1022]
### How can it be fixed?

see #1020

**Comment by carver** [comment]
I'm half-joking when suggesting `onion`. But I haven't come up with anything better. Maybe...

- `middleware_layers`
- `middleware_pipeline`

But I'm seriously okay with `onion` if we don't like anything else better.

**Comment by dylanjw** [comment]
I prefer `middleware_onion` to layers or pipeline.  It gets the point across better I think.  The onion analogy is pretty common.

**Comment by carver** [comment]
This doesn't seem to have actually been closed in #1020

**Comment by fubuloubu** [comment]
What about... just `middleware`? lol

**Comment by jMyles** [comment]
Is `middleware` better than `middleware_onion`?

**Comment by dylanjw** [comment]
middleware_onion helps distinguish the class that ochestrates the middlewares from the middleware functions themselves.

@njgheorghita Can this issue be closed?

**Comment by njgheorghita** [comment]
@dylanjw 👍
