### ISSUE TITLE
Replace ConciseContract with ContractCaller

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#1025]
`ConciseContract` shouldn't be a factory, it should be it's own calling API. meta-tracking in #722 

### How can it be fixed?

Add deprecation warning to ConciseContract and ImplicitContract.  Add a new api: ContractReader.

one proposed api: 

```
contract = w3.eth.contract(address, abi=abi)
reader = contract.reader({'from': caller_addr, ...})  # essentially ConciseContract(contract) with sugar
reader.balanceOf(address)  # or whatever call you want to make
```

Note that there will be internal breakage when removing `ConciseContract`, notably in the `ens` module. So part of this change will be updating ENS to use the new reader API. Brief discussion at https://github.com/ethereum/web3.py/pull/1118#discussion_r226800528

**Comment by Exef** [comment]
Should ContractReader have access to ContractEvents? In my opinion - yes, because events are also part of __reading__ contract data from blockchain.

**Comment by carver** [comment]
Hm, I'm not sure we'd be making the events API any easier to call. Maybe name it `ContractCaller` for semantic alignment?

**Comment by dylanjw** [comment]
I like ContractCaller.  So the idea is that ContractCaller can only make calls, and removing the ability to use modifiers to make transactions.

For example, this would not be possible:

```
contract.withdraw(amount, transact={'from': eth.accounts[1], 'gas': 100000, ...})
```

I was confused by the name ContractReader, which I thought could be an api to read public variables.

**Comment by pipermerriam** [comment]
for @kclowes

`contract.reader.getThing()`

**Comment by carver** [comment]
Note that's a slight change from the API in the OP: `contract.reader(transaction_dict).getThing()`. (where `transaction_dict` has fields like `from`, `gas`, `gasPrice`, etc that can affect the function call.

I think I like the OP API better, but highly open to persuasion or alternatives

**Comment by pipermerriam** [comment]
@carver I'm inclined to do something like this.

- `contract.reader.getThing()`
  - equivalent to `contract.functions.getThing().call()`
- contract.reader(transaction_dict).getThing()
  - equivalent to `contract.functions.getThing().call(transaction_dict)`

And maybe to alias `contract.r` to `contract.reader` for convenience.

**Comment by carver** [comment]
The non-parenthetical API option looks good to me. :+1: 

---

One-letter variables would be super out-of-character for the tool suite.

I think I could get behind it (same for `f` for functions, etc), but then I would probably want to have a big warning in the docs saying something like "These aliases are intended for 'quick-and-dirty' usage at a terminal, it's highly discouraged to use in production code. Use the full names instead".

... or maybe just not have the alias. Maybe we could shorten `reader` to `read` or have it be `get` instead?

**Comment by pipermerriam** [comment]
Lets just leave out the alias.
