### ISSUE TITLE
Whisper: test_shh_filter does not work to send messages to another node.

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1031]
* geth version: 1.8.15-unstable
* Python: 3.5
* OS: osx/linux
* Web3.py version: 4.4.1

### What was wrong?

I have followed following [ssh-mode code](https://github.com/ethereum/web3.py/blob/master/tests/core/shh-module/test_shh_filter.py), which lets each node to send message to itself but different nodes are not able to catch/filter the already sent messages from other nodes. 

**Overall, I am able to send/receive from the same node, but not from two different ones.**

On this approach I observe that each node can only sends message to itself and other nodes don't filter/see those messages. For example, when `node-1` sends a message to the network; it won't show up on the `node-2` such that node-2's `web3.shh.info{memory}` remains 0, where I assume that it never catches the message.

### How can it be fixed? Please see the example case:

`Node_1` runs `shh_filter.get_new_entries()
` to catch messages but `len(received_messages)` returns 0, where there is no message is received.

```
from web3 import Web3, HTTPProvider
web3 = Web3(HTTPProvider('http://localhost:8545'))
from web3.shh import Shh
Shh.attach(web3, "shh")

import time, sys;

from hexbytes import (
    HexBytes,
)

receiver = web3.shh.newKeyPair()
receiver_pub = web3.shh.getPublicKey(receiver)
print('receiverPubK: ' + receiver_pub);

topic = '0x13370000'

shh_filter = web3.shh.newMessageFilter({
    'privateKeyID': receiver,
    'topics': [topic]
})

input("Press Enter to continue...");

received_messages = [];
received_messages = shh_filter.get_new_entries()
print(len(received_messages)) # Returns '0'
print(web3.shh.info.memory)  # Returns '0'
```

Output:

```
receiverPubK: 0x04226d96bf9857ac0ba429c1e8b480a2811ce47cb526dbd3829d7586e5cae740198ba291f3eca0f279f82db8a136be90ea9ec629ed6cd1d45cc7f873159811757d
Press Enter to continue...
```

----------

After `Node_1`'s messages are sent; I have copied printed `receiverPublicKey` into `receiver_pub` variable on the following code. I run following code on `Node 2`. `Node 2` sends a message to the network. Later I press enter on the `Node_1` and any of those messages does not show up on the`Node_1`:

```
from web3 import Web3, HTTPProvider
web3 = Web3(HTTPProvider('http://localhost:8545'))
from web3.shh import Shh
Shh.attach(web3, "shh")

import time, sys;

from hexbytes import (
    HexBytes,
)

receiver_pub='0x04226d96bf9857ac0ba429c1e8b480a2811ce47cb526dbd3829d7586e5cae740198ba291f3eca0f279f82db8a136be90ea9ec629ed6cd1'; # obtained from node_1 and assigned here.

topic = '0x13370000'
payloads = [web3.toHex(text="test message :)"), web3.toHex(text="2nd test message")]

web3.shh.post({
        'powTarget': 2.5,
        'powTime': 2,
        'ttl': 60,
        'payload': payloads[0],
        'pubKey': receiver_pub
})
time.sleep(1)

web3.shh.post({
        'powTarget': 2.5,
        'powTime': 2,
        'ttl': 60,
        'payload': payloads[1],
        'topic': topic,
        'pubKey': receiver_pub
})
```

**[Q]** How could I able to make `node-2` to filter `node-1`'s messages? Is it possible?

Also asked at [ethereum.stackexchange](https://ethereum.stackexchange.com/q/57693/4575) but I couldn't reach anyone.

**Comment by avatar-lavventura** [comment]
Ah, I am not sure the reason. I have a small private network. I have delete the chain-data of both nodes and rsync from 0th block. I verify that both nodes have `net.peerCount` that is minimum 1 on both nodes and now it works.

**Comment by avatar-lavventura** [comment]
I verify that both nodes are connected to the network. net.peerCount returns 3 on both nodes.

=> Currently, I am able to send/receive from the same node, but not from two different ones.

**Comment by marcgarreau** [comment]
Stale issue, but Whisper was officially dropped from Geth and Parity/OE, so support has been removed from Web3.py in #1791.

**Comment by avatar-lavventura** [comment]
@marcgarreau  In the latest `web3.py` versions still can I use it since I was able to use it on its previous versions?

Do you know the reason why is it dorpped from Geth and Parity? and is there any alternative for it?

**Comment by marcgarreau** [comment]
@avatar-lavventura my limited understanding is that Whisper is discontinued or abandoned; I don't know the reasons why. You should look into the Status team's effort, [Waku](https://our.status.im/peer-to-peer-messaging-where-whisper-falls-short-and-waku-picks-up/).

**Comment by avatar-lavventura** [comment]
@marcgarreau `Whisper` is abandoned over a year, but it was working fine for basic stuff to send messages based on a topic. The issues I open never responded. The main goal in peer-to-peer messaging should considered [Does go-ethereum/whisper provides any kind of Public Key Server to obtain other nodes' public key](https://ethereum.stackexchange.com/questions/83968/does-go-ethereum-whisper-provides-any-kind-of-public-key-server-to-obtain-other), which is not inclueded in `Waku`.


Ah also `Waku` seems like only focus on the mobil-app solution, so it would be difficult to integrate it with `Python` :-(

**Comment by marcgarreau** [comment]
Ah, sorry to hear that Waku isn't an option for you. I don't believe its reasonable for this team to commit to maintaining an interface to a discontinued Whisper, but we are working to make it easier to introduce custom methods in web3.py. I think this interface is still evolving, but @kclowes is there anything we can share about it yet?

**Comment by kclowes** [comment]
@avatar-lavventura [this](https://github.com/ethereum/web3.py/pull/1797) is the WIP PR for the documentation, but use with caution as it's not public quite yet and is subject to breaking changes. But you should be able to use that in a pinch

**Comment by avatar-lavventura** [comment]
@kclowes  Thanks, I am manage to make Whisper work, basic example: ( https://ethereum.stackexchange.com/a/58299/4575 ), by many trial-error and using @pipermerriam 's [example-file](https://github.com/ethereum/web3.py/blob/master/tests/core/shh-module/test_shh_filter.py) (but the link is gone right now)

I am just get lost, where not sure whisper (`w3.geth.shh`) be available on  the changed version of `web3.py` or will there be alternative to `Whisper`.

If it will be available , I will keep up my work related to whisper on my project; if not I need to find out different solution for peer-to-peer messaging.

Anyway Whisper is/was nice but sender's public key is not included on the message-info and also the Ethereum address of the sender (which would be actually the real benefit of using it).
