### ISSUE TITLE
Rinkeby websocket connection on getting pending txns is flaky

### ISSUE THREAD

**Issue by FYJen** [ethereum/web3.py#1035]
* Version: 4.6.0
* Python: 3.6.5
* OS: osx/linux/win

### What was wrong?

This is a followup of #1009. WebSocket connection to Rinkey network using Infura is flaky

```python
In [79]: web = Web3(Web3.WebsocketProvider('wss://rinkeby.infura.io/ws'))

In [80]: new_transaction_filter = web.eth.filter('pending')

In [81]: web = Web3(Web3.WebsocketProvider('wss://rinkeby.infura.io/ws'))

In [82]: new_transaction_filter = web.eth.filter('pending')






# this hangs.
```

Mainnet and Ropsten are fairly stable for me. Is anyone experiencing the same issue on Rinkeby? 

### How can it be fixed?

TBD.

**Comment by voith** [comment]
@FYJen can you test again by installing web3 from my branch
```
pip install -e git+https://github.com/voith/voith.git@fix-1009#egg=web3
```
If it works then it's a problem with and you should probably report it to them

**Comment by carver** [comment]
Just to be clear, when you say "this hangs", you mean only occasionally, right? And it reproduces only on `pending` not on other filters, like `latest`?

**Comment by FYJen** [comment]
@voith: I tested again today. It fairly stable now on the Rinkeby network.
@carver: Yeah only occasionally. I have only used `pending`, didn't try `latest`.

Thanks all for looking into it. I am closing this ticket because I can no longer reproduce the error.
