### ISSUE TITLE
How to get the confirmation number of a transaction?

### ISSUE THREAD

**Issue by ztlovemst11** [ethereum/web3.py#1060]
I want to get the transaction timestamp  when I get the transaction details, just like using the api query, but I don't see a similar value.

**Comment by pipermerriam** [comment]
transactions don't have timestamps.  Once the transaction is mined, you can get the block's timestamp.  This can be looked up using the `blockNumber` or `blockHash` attributes returned on the transaction and looking up the given block which will have a `timestamp` attribute.

**Comment by ztlovemst11** [comment]
thanks.by the way,how to use web3 to quickly query the transaction record of an address?

**Comment by pipermerriam** [comment]
@ztlovemst11 I recommend spending some time reading the documentation which can be found here.

https://web3py.readthedocs.io/en/stable/

Alternatively you can ask your question here: https://ethereum.stackexchange.com/
