### ISSUE TITLE
How do I decode the transaction's log?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1061]
- Web3.py version: 4.4.1
- Python: 3.7.0
- OS: linux
- geth version: 1.8.15-unstable

--------------

I can filter my events ([please see][1]), but instead of that if I know only the `transaction hash` and if its already deployed, is it possible to obtain and parse the transaction's log data using `Web3.py`? Please see the [solution for web3.js][2]. Is there any[ web3.eth.abi.decodeLog](https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#decodelog) function under `Web3.py`?

For example, from receipt we can obtain the `logs.data`.

    > tx = '0x5c7e74a21419a6ff825aca9b54df1a86599b4b1ee82e60e6410e8d54cbb58b2c'    
    > web3.eth.getTransactionReceipt(tx).logs
        [{
            address: "0x611dc53934550684825f3477ecb68029b1b908f3",
            blockHash: "0x356829b068046b6d44147663f8bd6c187e9507c578d9ec9d69e65d7a248ff368",
            blockNumber: 1180103,
            data: "0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000002e516d52736142454763717851634a6242784369314c4e39697a3562444147445752364878375a76577167716d64520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007536369656e636500000000000000000000000000000000000000000000000000",
            logIndex: 0,
            removed: false,
            topics: ["0x711007a4be830d68a6d2a7b6546227b676bf9e7d7a0e3c248552ed72cfec2441", "0x0000000000000000000000004e4a0750350796164d8defc442a712b7557bf282"],
            transactionHash: "0x5c7e74a21419a6ff825aca9b54df1a86599b4b1ee82e60e6410e8d54cbb58b2c",
            transactionIndex: 0
        }]

Example log I have is, where `string` has a dynamic size. If possible, I want to decode `web3.eth.getTransactionReceipt(tx).logs[<index>]['data]` and `web3.eth.getTransactionReceipt(tx).logs[<index>]['topics]`.

    event LogJob(address indexed clusterAddress,
                 string indexed key,
                 uint index,
                 uint8 fileID,
                 string desc,
                 string hash
                 );

  [1]: https://web3py.readthedocs.io/en/stable/filters.html
  [2]: https://ethereum.stackexchange.com/q/1381/4575

**Comment by pipermerriam** [comment]
I believe you can do it as follows.

```python
>>> receipt = web3.eth.getTransactionReceipt(tx_hash)
>>> logs = my_contract.events.myEvent.processReceipt(receipt)
...
```

The `logs` output should be a tuple of the decoded log objects from that receipt.  However, I would be ideal to have a `processLog(log)` method which did this for a single log entry.

**Comment by avatar-lavventura** [comment]
```shell
>>> tx_hash = '0xdf9ead46baefd6774b230a7286d510bceec04fb33200c9ac9b6934e5cf46f6c7'
>>> receipt = web3.eth.getTransactionReceipt(tx_hash)
>>> print(my_contract.events.LogJob)
>>> logs = my_contract.events.LogJob.processReceipt(receipt)
```

Error I am having:

```
Traceback (most recent call last):
  File "dd.py", line 13, in <module>
    logs = eBlocBroker.events.LogJob.processReceipt(receipt)
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/utils/decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/contract.py", line 1270, in processReceipt
    return self._parse_logs(txn_receipt)
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
TypeError: _parse_logs() missing 1 required positional argument: 'txn_receipt'


```

**Comment by ShreySatapara** [comment]
The function name is always myEvent()

Or it changes as per the functions of your contract because in both the cases I'm getting error that MismatchedABI

**Comment by luolixuan** [comment]
> I believe you can do it as follows.
> 
> ```python
> >>> receipt = web3.eth.getTransactionReceipt(tx_hash)
> >>> logs = my_contract.events.myEvent.processReceipt(receipt)
> ...
> ```
> 
> The `logs` output should be a tuple of the decoded log objects from that receipt. However, I would be ideal to have a `processLog(log)` method which did this for a single log entry.

@pipermerriam 
I am wondering what is my_contract, is this under any library or you define it yourself?

**Comment by voith** [comment]
@ShreySatapara @luolixuan `my_contract` here is just a placeholder and should be replaced by the name of the smart contract deployed by you. The same holds true for `myEvent`. It is the name of the event in your smart contract that you're interested in.

**Comment by kclowes** [comment]
@ShreySatapara can you provide a sample please? It will be easier to see what exactly is going on

**Comment by luolixuan** [comment]
> @ShreySatapara @luolixuan `my_contract` here is just a placeholder and should be replaced by the name of the smart contract deployed by you. The same holds true for `myEvent`. It is the name of the event in your smart contract that you're interested in.

Thanks vioth. If I want to decode the log of a existing block on the chain, what should I do? I know the block number, the transaction hash...

**Comment by voith** [comment]
> MISMATCHED ABI
Could it be possible that you're trying to decode logs of an event that was not emitted by your smart contract? I'm not sure how `processReceipt(receipt)` handles errors in such a case.

@luolixuan Do you have the ABI of the smart contract whose logs you're trying to decode? 
Btw, You can join the [gitter](https://gitter.im/ethereum/web3.py) channel of web3.py or you can ask a question on [ethereum.stackexchange](https://ethereum.stackexchange.com/). `stackexchange` has more ppl who'll be willing to help you.

**Comment by pipermerriam** [comment]
@luolixuan take a look at this section of the documentation:

https://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.ContractEvents.myEvent

**Comment by iraj-jelo** [comment]
> I believe you can do it as follows.
> 
> ```python
> >>> receipt = web3.eth.getTransactionReceipt(tx_hash)
> >>> logs = my_contract.events.myEvent.processReceipt(receipt)
> ...
> ```
> 
> The `logs` output should be a tuple of the decoded log objects from that receipt. However, I would be ideal to have a `processLog(log)` method which did this for a single log entry.

what if the contract have no `event`? see this question please https://ethereum.stackexchange.com/questions/113819/decoding-transaction-logs-of-pancakeswaps-router-by-web3-py

**Comment by avatar-lavventura** [comment]
@iraj-jelo  If the tx has no `event`, logs should return empty list (`[]`).

**Comment by iraj-jelo** [comment]
> @iraj-jelo If the tx has no `event`, logs should return empty list (`[]`).

my `contract.events` object just has a property named `named`. there is no other event in that `events`.  the `logs` is not empty. there are 5 logs there

**Comment by BoboTiG** [comment]
Let's say you want to decode logs from a transfer (using any `swap*()` function):

```python
# The minimal router for the use case
minimal_abi = [
    # Transfer
    {
        "name": "Transfer",
        "type": "event",
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "name": "from",
                "type": "address",
            },
            {
                "indexed": True,
                "name": "to",
                "type": "address",
            },
            {
                "indexed": False,
                "name": "value",
                "type": "uint256",
            },
        ],
    },
]

# Here, router is Trader Joe, PancakeSwap, etc.
router = web3.eth.contract(address=router_address, abi=minimal_ab)
receipt = web3.eth.get_transaction_receipt(tx_hash)
decoded_logs = router.contract.events.Transfer().processReceipt(receipt)

# Access details as simply as:
for log in decoded_logs:
    print(log.args["from"], "->", log.args["to"], log.args["value"])
```

Hope that will help (and here is a [french version more complete](https://www.tiger-222.fr/luma/python/web3py-decoder-logs-transfert.html)) :)

**Comment by kala0427** [comment]
hello, but this is custom abi, how to get abi without initialize from contract address or something?

**Comment by remort** [comment]
Is it possible to read transaction logs without any requests to blockchain (no contract creation, no getting receipt)? Because it utilizes resources of your blockchain provider pretty quick.
