### ISSUE TITLE
installation error for web3.py in ubuntu linux

### ISSUE THREAD

**Issue by danielho95** [ethereum/web3.py#1071]
* Version: latest
* Python:3.6.6
* OS: ubuntu 18.04.1 linux

### What was wrong?

Having followed the installation documentation [https://web3py.readthedocs.io/en/stable/troubleshooting.html#setup-environment](https://web3py.readthedocs.io/en/stable/troubleshooting.html#setup-environment)

I receive the following error 
`Collecting web3
  Using cached https://files.pythonhosted.org/packages/a3/b1/68aad32a1e4ebbb374e01a5f6e86fd41f4e626c2e8bdfe6e51af27073b4c/web3-4.7.1-py3-none-any.whl
Collecting eth-abi<2.0.0,>=1.2.0 (from web3)
  Using cached https://files.pythonhosted.org/packages/3d/4e/66d711f39c892c295cd61d2a241d26e4fa253e483382bdb34e39ea4c4d96/eth_abi-1.2.0-py3-none-any.whl
Collecting hexbytes<1.0.0,>=0.1.0 (from web3)
  Using cached https://files.pythonhosted.org/packages/18/bd/21697d93ee2153c8c12253262b740f571e94341d4cee411504032fff3f56/hexbytes-0.1.0-py3-none-any.whl
Collecting lru-dict<2.0.0,>=1.1.6 (from web3)
  Using cached https://files.pythonhosted.org/packages/00/a5/32ed6e10246cd341ca8cc205acea5d208e4053f48a4dced2b1b31d45ba3f/lru-dict-1.1.6.tar.gz
Collecting eth-account<0.4.0,>=0.2.1 (from web3)
  Using cached https://files.pythonhosted.org/packages/a3/d8/6118bc0e00d6ec092bb02b012989d1018893755eb84da53266412ac359e3/eth_account-0.3.0-py3-none-any.whl
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0 (from web3)
  Using cached https://files.pythonhosted.org/packages/0d/d8/0f0c8d4ccaa4c8d25524fd1ed9f5c6d9551b52b74b973f338de3f0a23111/eth_hash-0.2.0-py3-none-any.whl
Collecting cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython" (from web3)
  Using cached https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz
Collecting requests<3.0.0,>=2.16.0 (from web3)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting eth-utils<2.0.0,>=1.0.1 (from web3)
  Using cached https://files.pythonhosted.org/packages/97/35/6e41ccfecfdd422bb386f186c7288a3176af29d380419645723f5f0b534f/eth_utils-1.2.2-py3-none-any.whl
Collecting websockets<7.0.0,>=6.0.0 (from web3)
  Using cached https://files.pythonhosted.org/packages/5c/fe/99aeaf97985585baefca8d56125ec828ef5549276324ec319b63a4da686d/websockets-6.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting eth-typing<=2 (from eth-abi<2.0.0,>=1.2.0->web3)
  Using cached https://files.pythonhosted.org/packages/88/df/19e17ca63aa0285ef0c2e95231f2f6a8d99a69ee58817c22b6b417067460/eth_typing-2.0.0-py3-none-any.whl
Collecting parsimonious==0.8.0 (from eth-abi<2.0.0,>=1.2.0->web3)
Collecting eth-rlp<1,>=0.1.2 (from eth-account<0.4.0,>=0.2.1->web3)
  Using cached https://files.pythonhosted.org/packages/56/4b/b309fb44dd9bb975e84f3d626392eec1eeed0108e55a51cd7dd8956a73ad/eth_rlp-0.1.2-py3-none-any.whl
Collecting eth-keyfile<0.6.0,>=0.5.0 (from eth-account<0.4.0,>=0.2.1->web3)
  Using cached https://files.pythonhosted.org/packages/eb/a5/3615d100b62fbf20fe5d5c0d1d4d7326eac861d260b0cd2a36af2bf8ccb1/eth_keyfile-0.5.1-py3-none-any.whl
Collecting attrdict<3,>=2.0.0 (from eth-account<0.4.0,>=0.2.1->web3)
Collecting eth-keys<0.3.0,>=0.2.0b3 (from eth-account<0.4.0,>=0.2.1->web3)
  Using cached https://files.pythonhosted.org/packages/9b/96/bec507291a2ecac65358b4485282ce02e8c0cdd30980a232791b355a1f5b/eth_keys-0.2.0b3-py3-none-any.whl
Collecting pycryptodome<4,>=3.6.6; extra == "pycryptodome" (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3)
  Using cached https://files.pythonhosted.org/packages/40/83/f195ab14348cc957d5cc6ae195918b1ce012ce2df4f4b9a52e260a8e3ed0/pycryptodome-3.6.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting toolz>=0.8.0 (from cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython"->web3)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.16.0->web3)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3.0.0,>=2.16.0->web3)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0.0,>=2.16.0->web3)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.16.0->web3)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting six>=1.9.0 (from parsimonious==0.8.0->eth-abi<2.0.0,>=1.2.0->web3)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting rlp<2,>=0.6.0 (from eth-rlp<1,>=0.1.2->eth-account<0.4.0,>=0.2.1->web3)
  Using cached https://files.pythonhosted.org/packages/35/f7/e5df3c3d71c90bfe74718be9ae24704abc8b8ef04d58c1065e1cbcedc240/rlp-1.0.2-py2.py3-none-any.whl
Building wheels for collected packages: lru-dict, cytoolz
  Running setup.py bdist_wheel for lru-dict ... error
  Complete output from command /home/daniel/.venv-py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ndzffrz5/lru-dict/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-06zt5gmw --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/daniel/.venv-py3/include/python3.6m -c lru.c -o build/temp.linux-x86_64-3.6/lru.o
  lru.c:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Running setup.py bdist_wheel for cytoolz ... error
  Complete output from command /home/daniel/.venv-py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ndzffrz5/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7d18f4he --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/_version.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz
  creating build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  creating build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cytoolz
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/daniel/.venv-py3/include/python3.6m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.6/cytoolz/dicttoolz.o
  cytoolz/dicttoolz.c:17:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
Failed to build lru-dict cytoolz
eth-utils 1.2.2 has requirement eth-typing<2.0.0,>=1.3.0, but you'll have eth-typing 2.0.0 which is incompatible.
Installing collected packages: eth-typing, six, parsimonious, toolz, pycryptodome, eth-hash, cytoolz, eth-utils, eth-abi, hexbytes, lru-dict, rlp, eth-rlp, eth-keys, eth-keyfile, attrdict, eth-account, certifi, idna, urllib3, chardet, requests, websockets, web3
  Running setup.py install for cytoolz ... error
    Complete output from command /home/daniel/.venv-py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ndzffrz5/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-q3cfbbjn/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/.venv-py3/include/site/python3.6/cytoolz:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz
    creating build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    creating build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cytoolz
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/daniel/.venv-py3/include/python3.6m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.6/cytoolz/dicttoolz.o
    cytoolz/dicttoolz.c:17:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/daniel/.venv-py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ndzffrz5/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-q3cfbbjn/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/.venv-py3/include/site/python3.6/cytoolz" failed with error code 1 in /tmp/pip-install-ndzffrz5/cytoolz/
`

**Comment by dylanjw** [comment]
lru-dict and cytoolz requires the python headers to build, which can be installed with:

```
sudo apt-get install python3-dev
```
