### ISSUE TITLE
ENS Ropsten

### ISSUE THREAD

**Issue by randomlogin** [ethereum/web3.py#1078]
It seems it's not possible (at least in easy way) to use Ropsten ENS. 

web3py has hardcoded ens registry for mainnet:

`>>> ns.ens.address`
`'0x314159265dD8dbb310642f98f50C066173C1259b'`
What is the workaround to this issue?

**Comment by carver** [comment]
You would [initialize the `ENS()` class directly](https://github.com/ethereum/web3.py/blob/master/ens/main.py#L51), like:

```py
from ens import ENS
from web3 import Web3

ropsten_ns = ENS(Web3.IPCProvider(...), "0xF00BAA...")
```

Where `F00BAA...` is replaced by the Ropsten ENS registry's address.

**Comment by filips123** [comment]
@carver Shouldn't ENS class also detect current network and use correct registry's address by default? This is already used in Web3.js.
