### ISSUE TITLE
HTTPProvider does not call CannotHandleRequest on failure

### ISSUE THREAD

**Issue by ciripel** [ethereum/web3.py#1092]
* Version: 4.7.2
* Python: 3.6
* OS: linux

If the `HTTPProvider` used produces an error, `make_request` does not raise `CannotHandleRequest`. This makes the connection pool not work because it does not detect that a provider has failed. `make_post_request` should be wrapped in a try/except block and re-raise the exception as `CannotHandleRequest`.

**Comment by carver** [comment]
Seems reasonable. Although it's worth noting that we are probably dropping to a single provider in v5, so it might not be wise to lean too heavily on the provider pool. Either way, it still makes sense to have a unified, provider-specific failure, though. So the change makes sense to me.

**Comment by fselmo** [comment]
Closing as stale. `web3.py` uses a single provider and there is no connection pool anymore.
