### ISSUE TITLE
Dissallow python 3.5.1

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1094]
### What was wrong?

It looks like `typing.NewType` may not be available in python 3.5.1

https://github.com/ethereum/web3.py/issues/1091

### How can it be fixed?

Check what version `NewType` was added and restrict our python versions as declared in `setup.py` to be `>=` that version

**Comment by pipermerriam** [comment]
Fixed by #1095

**Comment by carver** [comment]
Reminder to backport to v4

**Comment by pipermerriam** [comment]
https://github.com/ethereum/web3.py/issues/1096
