### ISSUE TITLE
Backport 1094 to v4 branch

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1096]
### What was wrong?

https://github.com/ethereum/web3.py/issues/1094#issuecomment-428259232 needs to be backported to the v4 branch.

**Comment by carver** [comment]
Also, because of https://github.com/ethereum/web3.py/issues/1012#issuecomment-415183759 maybe we should require >=3.5.3

**Comment by carver** [comment]
Thanks @stefanmendoza !
