### ISSUE TITLE
Update minimum `eth-utils` requirement.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1102]
### What was wrong?

The current lower bound for `eth-utils` is `1.0.1`.  The `eth_utils.toolz` module is only fully available in `eth-utils>=1.2.0`

### How can it be fixed?

Bump the `eth-utils` minimum requirement to be `eth-utils>=1.2.0`

**Comment by carver** [comment]
This was included in v4 in #1085
