### ISSUE TITLE
Remove unused `web3._utils.six` module

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1111]
### What is the problem

The `web3._utils.six` module is a leftover from when we supported python 2 and *should* no longer be used.

### How can it be fixed.

Remove the module and update the `web3._utils.caching` module to no longer use it.

**Comment by vindard** [comment]
This looks simple enough. I'll start tackling this in a couple of hours.

**Comment by 6ug** [comment]
@pipermerriam is this eligible to bounty?

**Comment by pipermerriam** [comment]
@6ug No.  Unless an issue is already bountied when you start on it (or there's some other pre-arranged aggrement you shouldn't expect a bounty.
