### ISSUE TITLE
web3 send tx  noneffective

### ISSUE THREAD

**Issue by purplecity** [ethereum/web3.py#1114]
* Version: new
* Python: 3.6
* OS:  linux

### What was wrong?

I use web3 connect to infura and send tx  with  Local Private Keys.   I receive tx hash.  but when I use getTransactionReceipt or getTransaction method will return None.  what's wrong?

CODE:

 w3=Web3(Web3.HTTPProvider("https://mainnet.infura.io/v3/xxxx",request_kwargs={"timeout":10}))                                            
                                                   
  nonce=w3.eth.getTransactionCount(addr)                                     
                                               
 25 transaction={                                                                  
         "nonce":nonce,                                        
         'from': '0xF222F2eC6D2b71Ee81ee2F1166266dB92DBC8901',               
         'to': safeaddr,                                                       
         'value': 999000000000000,                                             
         'gas': 210000,                                                         
        'gasPrice': 1000000000                                               
       }                                                                    
signed = w3.eth.account.signTransaction(transaction, private_key)              
 result=w3.eth.sendRawTransaction(signed.rawTransaction)

x=w3.eth.getTransactionReceipt(result.hex())

x is None

**Comment by pipermerriam** [comment]
`getTransactinReceipt` is expected to return `None` until the transaction has been mined into a block.  Your transaction is likely still pending.
