### ISSUE TITLE
Better error message when calling contract with wrong types

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#1117]
### What was wrong?

People struggle with what types to send when calling an argument. Especially for complex things like lists of types. #527 can partially address this, but it would be cool if they didn't *have* to go to the docs

### How can it be fixed?

In the case where there is exactly one function of the given name, and the types are wrong, the error message could include an *example* of how to call it correctly. If someone gets the type error on, say `myfunc(address[],bytes4[],int8,uint8)`:

```
ValidationError: ...

Some examples of the correct way to invoke this:
myfunc(
  [
    '0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa',
    '0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB',
  ],
  [
    b'gggg',
    b'hhhh',
  ],
  127,
  256,
)

myfunc([], [], -128, 0)
```

Just a random thought from reading gitter.

**Comment by pipermerriam** [comment]
Maybe we can include a link to the docs in the error message.

**Comment by carver** [comment]
Also see: "Handle things going wrong" in https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46

**Comment by carver** [comment]
In order to deal with cases like #1127 we could also describe the way in which the value they sent is incorrect (eg~ expected 10 elements in this part of the type, but got 20).

**Comment by fselmo** [comment]
duplicated by and tracked in #964
