### ISSUE TITLE
Open call for Devcon Workshop assistance

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#1122]
### What was wrong?

@carver is preparing a Python workshop for Devcon4: "Deploying your first contract with Python"

Workshops are most effective when hosts walk around and assist participants who are stuck. The room holds 150, so we could use quite a few hosts but only have a couple.

### How can it be fixed?

You!

I'm looking for volunteers to help. The workshop is aimed at beginners, so if you've ever deployed a contract using web3py, you're qualified. :)

So far these people have volunteered:

- johnsBeharry
- cburgdorf (maybe partial)
- fubuloubu (2nd half-ish)
- dylanjw

If you can assist, please comment on this issue saying so. Thanks!

**Comment by cburgdorf** [comment]
I'm happy to assist. Maybe not for the entire duration of the workshop (would like to ad least attend the talk on Pantheon) but I'll try my best to help out!

**Comment by dylanjw** [comment]
I'll volunteer.

**Comment by carver** [comment]
@johnsbeharry @cburgdorf @fubuloubu @dylanjw 

Here is a preview of the slides: https://docs.google.com/presentation/d/1nTeJbyOTh7WJjVoBRPYI-HI0kHVS9CabLrQloXNAqyQ/edit?usp=sharing

I'd love any feedback you have. Taking a look ahead of time could help work out any bugs. I'll PM you each a QR code with some ropsten ether.

**Comment by veox** [comment]
OK to close, I guess.
