### ISSUE TITLE
Contract.functions.balanceOf.call() considerable memory usage

### ISSUE THREAD

**Issue by marioBZ7** [ethereum/web3.py#1126]
* Python: 3.5 / 3.6
* OS: osx/linux

```
asn1crypto==0.24.0
attrdict==2.0.0
base58==1.0.0
bit==0.4.3
bitcoinlib==0.3.36
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
coincurve==7.1.0
cryptography==2.3.1
cycler==0.10.0
cytoolz==0.9.0.1
ecdsa==0.13
eth-abi==1.2.2
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
graphviz==0.9
hexbytes==0.1.0
idna==2.6
jwt==0.5.4
kiwisolver==1.0.1
lru-dict==1.1.6
matplotlib==2.2.2
memory-profiler==0.52.0
mysql-connector==2.1.6
numpy==1.15.0
objgraph==3.4.0
pandas==0.23.3
parsimonious==0.8.0
pbkdf2==1.3
psutil==5.4.6
pyaes==1.6.1
pycparser==2.18
pycryptodome==3.6.6
PyJWT==1.6.4
pyparsing==2.2.0
python-bitcoinlib==0.10.1
python-dateutil==2.7.3
pytz==2018.5
redis==2.10.6
requests==2.18.4
rlp==1.0.1
scrypt==0.8.6
six==1.11.0
SQLAlchemy==1.2.5
toolz==0.9.0
urllib3==1.22
web3==4.7.2
websockets==6.0
xdot==1.0
```

### Memory usage is increasing linearly proportional when running Contract.functions.balanceOf.call() inside for loop

Code:

```
 def balanceOf(self, web3Conn, addressToCheck,logger):
        try:
            if web3Conn.isConnected():
                contractAddress = contractAddressDictionary[self.token_name]
                contractAddressCS = web3Conn.toChecksumAddress(contractAddress)
                contract = web3Conn.eth.contract(address=contractAddressCS, abi=self.abi_json['abi'])
                address_in_question = web3Conn.toChecksumAddress(addressToCheck)
       *         balance = contract.functions.balanceOf(address_in_question).call()
                #decimals = contract.functions.decimals().call()
                final_balance = balance / (float(10)**float(15))
                return final_balance
            else:
                '''
                print("------------------------ERROR!------------------------")
                print("ERROR: Blockchain connection failed.")
                print("------------------------------------------------------")
                '''
                return -2
        except:
            logger.info("ERROR: getting balance of ERC20:...")
            return -2
```

This script is meant to be running forever but after a few hours RAM usage is around 5GB. After debugging I realized this module is what is causing the leakage of memory, specifically all contracts functions requests (contract.decimals and contract.balanceOf).
This happens when requests are made to the TAU, SEAL and DRGN tokens in mainnet.

![sinmultiprocesos](https://user-images.githubusercontent.com/24484246/47538282-1f7d5d80-d890-11e8-8f57-41caca1ea34d.png)

vertical axis: memory usage (RES)
horizontal axis: number of cycles (sampling at 2 seconds)

first of all:
is this the right place to post this?
I'm concerned about this since it's causing a lot of trouble and I'm almost sure this is related to the web3 package.

can you help me with this? any workaround  to mitigate this increasing memory usage?

Thanks in advance

**Comment by pipermerriam** [comment]
It appears this is part of a larger application.  We need to know whether the memory leak is part of our code or yours.  Can you provide a [Minimal verifiable example](https://stackoverflow.com/help/mcve) for this?

**Comment by marioBZ7** [comment]
Hello there again.
Although the problems was indeed part of our code, it is weird that it happened with a line of code of the web3 library.

```python
class a(object):  
    def __init__(self):
        self.connection = Web3(HTTPProvider(host_IP_port))
        self.contract = self.connection.eth.contract(address=self.contractAddressCS, abi=self.abi_json['abi'])
```

After multiple tests I found out that the problem was that we were calling `self.contract = self.connection.eth.contract(address=self.contractAddressCS, abi=self.abi_json['abi'])` a lot of times. Not sure why RAM usage increased over time but I think Python should handle this without any problem. I moved that line of code to the __init__ method and now the RAM usage never goes above 49000kB. Yes, it was a mistake of us but this brought me a lot of confusion while debugging.

**Comment by pipermerriam** [comment]
This should have been fixed with https://github.com/ethereum/web3.py/pull/1135 which identified and fixed the memory leak.  cc @kclowes if you can inform what v4 and v5 versions have this fix in it (if they've been released).

**Comment by kclowes** [comment]
v4.8.2 should have a fix. It hasn't been released to v5 yet.

**Comment by carver** [comment]
(notably, no version of v5 has been released yet)
