### ISSUE TITLE
Implementation for calling JSON RPC calls using asyncio, round-robin public nodes, and increasing gas prices

### ISSUE THREAD

**Issue by amitkot** [ethereum/web3.py#1131]
@pipermerriam following our conversation on devcon4, this is the implementation we developed at Kyber for calling one of our smart contracts.

It calls the nodes directly using json rpc and handles various error cases we faced including nodes being non-responsive and increasing gas prices if we find our transactions do not get mined fast enough.

https://github.com/KyberNetwork/sanity-price-monitor/blob/master/pricemonitor/storing/web3_connector.py

**Comment by carver** [comment]
We may be able to just wait this problem out. I think it's mostly solved if this EIP makes it into an upcoming hard-fork https://github.com/ethereum/EIPs/issues/1559

**Comment by carver** [comment]
I'm probably not going to build this, since I'll hope that the previous EIP ^ will happen in not too long (next ~year?).

But if I were going to build it, my first stab at the API would be launch the daemon:

```py
from eth_gas import Daemon

gas_daemon = Daemon(ip, port, accounts=[eth_account.Account], etc...)
gas_daemon.run_server()  # probably asyncio under the hood
```
Then this in the transaction-sending script:
```py
from eth_gas import price_strategies
from ._utils import gas_daemon

PRICE_STRATEGY = price_strategies.exponential(per_hour=1.2)
...
txn_hash = w3.eth.sendTransaction(...)
gas_daemon.add(txn_hash, PRICE_STRATEGY)

**Comment by fselmo** [comment]
EIP-1559 saved the day
