### ISSUE TITLE
huge difference in TPS performance when bypassing web3.py in favor of a direct RPC call

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/web3.py#1133]
* Version: web3py 4.7.2
* Python: python 3.5.3 
* OS: linux
* `pip freeze` output: see [requirements.txt](https://github.com/drandreaskrueger/chainhammer/blob/a5ab58faf70d39cc1b6e22afc5883ae0a24cb571/requirements.txt)

### What was wrong?
Nothing wrong.

*But* I see a huge difference in TPS performance!

**Bypassing web3.py and sending via RPC `eth_sendTransaction`, I can get ~twice as fast TPS!**

* experimental results: [log.md](https://github.com/drandreaskrueger/chainhammer/blob/master/log.md#sending-via-web3-versus-sending-via-rpc)
* code explanation of the two alternative routes: [FAQ.md](https://github.com/drandreaskrueger/chainhammer/blob/master/FAQ.md#send-via-web3py-versus-send-via-direct-rpc-call-eth_sendtransaction)
* what type of node you were connecting to: quorum, geth, parity

### How can it be fixed?

Dunno. But I thought it's worthwhile giving you this feedback.

**Comment by pipermerriam** [comment]
Thanks for the feedback.  web3.py is designed to be high level which typically means incurring some level of additional overhead compared to the "bare-metal" approach.  That isn't to say that performance doesn't matter.

I'm closing this because it's not actionable but not because I don't find it valuable.  I'd love to improve our efficiency/performance so if you dig in and find any low hanging fruit where we could cut out some overhead please let us know.

**Comment by drandreaskrueger** [comment]
Thanks a lot. For your feedback - and for your very moving speech on devcon4 ;-)

I completely get your perspective, and why/that you close this. Your web3py is a very helpful library, it makes our life so much easier. And of course it has a different goal.

However, to make this possibly useful for the future, some ideas:

* create a performance.html in the web3py documentation which collects similar ideas ?
* tag this issue with a tag `potential perfomance improvements` ?

My chainhammer tool might at a later stage help to identify such "low hanging fruits" ?

Thanks anyways, keep up the good work.

**Comment by CWalton16** [comment]
Hey, I know this is closed but do you know where I can read up on how to bypass web3.py via direct rpc calls?

**Comment by drandreaskrueger** [comment]
My FAQ.md had been moved here: https://github.com/drandreaskrueger/chainhammer/blob/master/docs/FAQ.md#send-via-web3py-versus-send-via-direct-rpc-call-eth_sendtransaction
