### ISSUE TITLE
WebsocketProvider issues

### ISSUE THREAD

**Issue by arshdeeptinna** [ethereum/web3.py#1134]
* Version: 4.6.1
* Python: 3.6
* OS: osx
* `pip freeze` output

```
apsw==3.9.2.post1
astroid==1.6.5
attrdict==2.0.0
attrs==18.2.0
bitcoin==1.1.42
boto3==1.5.31
botocore==1.8.50
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
Click==7.0
coverage==4.5.1
cytoolz==0.9.0.1
deepdiff==3.3.0
docutils==0.14
dpath==1.4.2
eth-abi==1.2.2
eth-account==0.2.2
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b21
eth-testrpc==1.3.3
eth-typing==1.3.0
eth-utils==1.2.2
ethereum==1.6.1
hexbytes==0.1.0
idna==2.6
isort==4.3.4
jmespath==0.9.3
json-rpc==1.11.1
jsonpickle==1.0
jsonschema==2.6.0
lazy-object-proxy==1.3.1
lru-dict==1.1.6
mccabe==0.6.1
parsimonious==0.8.0
pbkdf2==1.3
pluggy==0.6.0
psutil==5.4.5
py==1.7.0
py-solc==2.1.0
pycodestyle==2.4.0
pycparser==2.19
pycryptodome==3.7.0
pyethash==0.1.27
pylint==1.9.3
pysha3==1.0.2
pytest==3.4.2
pytest-cov==2.5.1
python-dateutil==2.7.5
python-json-logger==0.1.8
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
s3transfer==0.1.13
scrypt==0.8.6
secp256k1==0.13.2
semantic-version==2.6.0
six==1.11.0
structlog==18.1.0
tendo==0.2.8
timeout-decorator==0.4.0
toolz==0.9.0
urllib3==1.22
watchtower==0.5.3
web3==4.8.1
websockets==6.0
Werkzeug==0.14.1
wrapt==1.10.11
```

### What was wrong?
Encountered three different issues while trying to use websocket provider with Infura ropsten websocket endpoint.

***First error*** is related to gas price where value returnd by eth.gasPrice is either an 'int' or 'list'
Please include any of the following that are applicable:

* `gas_price = int(min(gas_price, self.__config.max_gas_price_wei))`
* `Traceback (most recent call last):
  File "***.py", line 187, in __compute_gas_price
    gas_price = int(min(gas_price, self.__config.max_gas_price_wei))
TypeError: '<' not supported between instances of 'int' and 'list'`

During handling of the above exception, another exception occurred:`
* infura ropsten endpoint

***Second error*** is related to block number where the value returned can be either a valid block number or again an empty list

***Third error*** relates to filter creation where sometimes a filter (using createFilter method) is not created properly again returning an empty list which when passed to infura endpint to get all entries complains about invalid id. This can be fixed by replacing empty array with empty string.

**Comment by pacrob** [comment]
Closing due to age, please open a new issue if you're still having, well, issues.
