### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by serderovsh** [ethereum/web3.py#1142]
File: datatypes.py
Link: https://github.com/ethereum/web3.py/blob/0cbb1e4d3bf5f5fe1e7493f374d824b112d389d8/web3/_utils/datatypes.py#L27

**Assigning to function call which doesn't return**
```python
verify_key_attr = verify_attr(name, key)
```
**No value for argument 'namespace' in function call**
```python
verify_key_attr = verify_attr(name, key)
```

Fix 2:
File: validation.py
Code: 
https://github.com/ethereum/web3.py/blob/0cbb1e4d3bf5f5fe1e7493f374d824b112d389d8/web3/_utils/validation.py#L50

Lambda may not be necessary

**Comment by carver** [comment]
This is going to need more explanation before we can act on it.

**Comment by marcgarreau** [comment]
stale; re-open with more context if appropriate.
