### ISSUE TITLE
eth.getTransaction Get wrong result no matter how many times to retry

### ISSUE THREAD

**Issue by freexspeed** [ethereum/web3.py#1148]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?
Analyze all transaction in all blocks.  No problem at most time. But when the program run for a while. 
eth.getTransaction Get None no matter how many times to retry.

I am sure the transaction hash is right, and if use break point, a few hours later, continue debug, is get the right result (transaction infos).

I am try to reset the session (_session_cache.clear()).  but no useful.

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
Please fully fill out the issue if you'd like support.
