### ISSUE TITLE
Web3 crashes in time-based gas price strategies with empty chain

### ISSUE THREAD

**Issue by fredo** [ethereum/web3.py#1149]
* Version: 4.7.1
* Python: 3.6
* OS: linux

### What was wrong?

Running our test suite web3 crashes when estimating time based gas price. Probably it is caused by not having any transactions in our test chain. However when probabilities are calculated they are empty (empty tuple) which causes then an Index Error in ` '104, in _compute_gas_price\r\n    first = probabilities[0]\r\nIndexError: tuple index out of range\`

It might be the case that there is a problem with our geth client during runtime.

```
File “/home/circleci/raiden/raiden/network/rpc/client.py”, line 346, in gas_price
return int(self.web3.eth.generateGasPrice())
File “/home/circleci/venv-3.7/lib/python3.7/site-packages/web3/eth.py”, line 385, in generateGasPrice
return self.gasPriceStrategy(self.web3, transaction_params)
File “/home/circleci/venv-3.7/lib/python3.7/site-packages/web3/gas_strategies/time_based.py”, line 168, in time_based_gas_price_strategy
gas_price = _compute_gas_price(probabilities, probability / 100)
File “/home/circleci/venv-3.7/lib/python3.7/site-packages/web3/gas_strategies/time_based.py”, line 104, in _compute_gas_price
first = probabilities[0]
IndexError: tuple index out of range
```

### How can it be fixed?

However I would suggest handling the edge case that there is an empty tuple and not unconditionally access `first = probabilities[0] `

I'm happy to give more information when needed

**Comment by palango** [comment]
I'd argue that the best fallback would be to use ` web3.eth.gasPrice`.
