### ISSUE TITLE
is there no web3.close() or w3.TestRPCProvider.close() function?

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/web3.py#1152]
* web3.py 4.7.2 - 4.8.2
* Python 3.5
* eth-testrpc 1.3.5
* OS: linux

### What was wrong?
Does the TestRPCProvider()  stay alive forever?

```
from web3 import Web3
w3 = Web3(Web3.TestRPCProvider()) 
w3 = Web3(Web3.TestRPCProvider()) 
...
OSError: [Errno 98] Address already in use
```

```
w3.close()

w3.TestRPCProvider.close()
...                                                                                                           
AttributeError: type object 'TestRPCProvider' has no attribute 'close'
```

### How can it be fixed?

Dunno.

I am using `w3 = Web3(Web3.TestRPCProvider())` in my unittests, I would like to be able to call it again.

Thanks.

**Comment by carver** [comment]
Try initializing it once during setup, and reusing it. That provider is deprecated, so unlikely to get any new changes: https://web3py.readthedocs.io/en/stable/providers.html#web3.providers.eth_tester.TestRPCProvider

Closing, but feel free to continue the conversation here.
