### ISSUE TITLE
Define support window for v4

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1167]
### What was wrong?

`master` is now formally `v5`.  With the removal of python3.5 which will eventually propagate into removing support for python3.5 from py-evm we need to define how long our `v4` branch will be formally supported since the testing facilities in web3.py rely on py-evm.

### How can it be fixed?

Something like committing to support `v4` for 6 months from the stable release of `v5` which means we cannot drop python3.5 from py-evm until at least very late in that support window.

**Comment by carver** [comment]
> means we cannot drop python3.5 from py-evm until at least very late in that support window.

Or maybe web3 v4 could just be pinned to an old version of `py-evm` that never upgrades. AFAICT, web3's use of py-evm is not a security-sensitive thing where we would have to issue patch releases against the old py-evm.
