### ISSUE TITLE
Convert all `toolz` imports to be from compat module `eth_utils.toolz`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1196]
Depends on https://github.com/ethereum/web3.py/pull/1195 which updates the `eth-utils` dependency to be `>=1.3.0`

### What was wrong?

We currently have `web3._utils.toolz` which handles the `toolz/cytoolz` import logic.  This compat module was added to `eth-utils` making this code redundant.

### How can it be fixed?

Convert all `toolz` imports to be from `eth_utils.toolz`

**Comment by jmcph4** [comment]
Just for reference, as of cba95384, this **should** be the list of affected files:

    web3.py$ grep -r --include "*.py" toolz . | cut -f1 -d :
    ./web3/module.py
    ./web3/gas_strategies/time_based.py
    ./web3/eth.py
    ./web3/middleware/gas_price_strategy.py
    ./web3/middleware/exception_handling.py
    ./web3/middleware/validation.py
    ./web3/middleware/attrdict.py
    ./web3/middleware/geth_poa.py
    ./web3/middleware/signing.py
    ./web3/middleware/formatting.py
    ./web3/middleware/pythonic.py
    ./web3/middleware/pythonic.py
    ./web3/middleware/filter.py
    ./web3/middleware/normalize_errors.py
    ./web3/method.py
    ./web3/providers/eth_tester/middleware.py
    ./web3/providers/eth_tester/defaults.py
    ./web3/providers/eth_tester/defaults.py
    ./web3/providers/eth_tester/defaults.py
    ./web3/_utils/normalizers.py
    ./web3/_utils/formatters.py
    ./web3/_utils/contracts.py
    ./web3/_utils/abi.py
    ./web3/_utils/toolz/curried.py
    ./web3/_utils/toolz/curried.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/toolz/__init__.py
    ./web3/_utils/validation.py
    ./web3/_utils/encoding.py
    ./web3/_utils/filters.py
    ./web3/_utils/events.py
    ./web3/_utils/datatypes.py
    ./web3/_utils/rpc_abi.py
    ./web3/_utils/transactions.py
    ./web3/pm.py
    ./web3/contract.py
    ./web3/parity.py
    ./tests/integration/parity/install_parity.py
    ./tests/integration/parity/install_parity.py
    ./tests/integration/parity/install_parity.py
    ./tests/integration/parity/install_parity.py
    ./tests/integration/generate_fixtures/go_ethereum.py
    ./tests/integration/generate_fixtures/parity.py
    ./tests/conftest.py
    ./tests/generate_go_ethereum_fixture.py
    ./tests/core/method-class/test_method.py
    ./tests/core/middleware/test_transaction_signing.py
    ./tests/core/eth-module/test_accounts.py
    ./tests/core/contracts/test_contract_ambiguous_functions.py
    ./tests/core/contracts/test_contract_buildTransaction.py
    ./tests/core/contracts/test_contract_call_interface.py
    ./tests/core/contracts/test_contract_caller_interface.py
    ./tests/core/core/block-utils/test_select_method_for_block_identifier.py
