### ISSUE TITLE
Remove `web3._utils.formatters` in favor of `eth-utils` versions

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1197]
Depends on https://github.com/ethereum/web3.py/pull/1195 which upgrades the `eth-utils` dependency

### What was wrong?

https://github.com/ethereum/web3.py/blob/864bc1d2a93ba7a6ca2a0629839b0d7a4c944e12/web3/_utils/formatters.py

We currently have a module `web3._utils.formatters` which implements a number of *functional* formatter functions.  These functions were elevated to live in `eth-utils` recently and thus are duplicate code.

### How can it be fixed?

Remove any/all functions from `web3._utils.formatters` in favor of the [`eth-utils` versions](https://eth-utils.readthedocs.io/en/latest/utilities.html#applicators).

**Comment by dylanjw** [comment]
Can I include this change in #1209?  It might be the same amount of work to do as it would to rebase this change from master.

**Comment by pipermerriam** [comment]
If they can be done separately that would be ideal since this change should just be code removal and modification of imports.  Mixing that with functionality changes makes for more difficult review.  Feel free to write them together but to segregate your commits so that when you're done you can split them into two PRs.
