### ISSUE TITLE
Mechanism for auto-generating changelog

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1208]
I wanted to point out an idea that's being floated in the Trinity codebase for auto-generation of the changelog.

See: https://github.com/ethereum/trinity/issues/101#issuecomment-447104976

**Comment by pipermerriam** [comment]
Murr, it's not clear from that link.  

https://docs.gitlab.com/ce/development/changelog.html

This is the proposed mechanism I'm referencing.

**Comment by carver** [comment]
Also see https://github.com/ethereum/trinity/issues/754
