### ISSUE TITLE
Add support for Goerli

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/web3.py#1229]
https://github.com/goerli/testnet

## Motivation
Goerli is the dapp testnet of the future. All PoA testnet chains will bow before it's power (and eventually move their ETH?) Support should be added for the modifications to the consensus data required to support it so that I can interact with the new chain!

**Comment by veox** [comment]
AFAIK it uses Rinkeby's Clique consensus engine; have you tried using a Goerli node with Rinkeby instructions (the one-line middleware addition)?

**Comment by fubuloubu** [comment]
I've had problems getting Rinkeby to work before as well. I can try that though. What's the name of the middleware for that?

**Comment by fubuloubu** [comment]
Yeah, I'm not sure what the difference is but I'm pretty sure there is a difference

**Comment by pipermerriam** [comment]
cc @carver who may know.  I *think* `geth_poa_middleware` just needs to be renamed to `clique_poa_middleware`

**Comment by fubuloubu** [comment]
p.s. Added #1234 after realizing I forgot the middleware for Infura when I did that change.

**Comment by veox** [comment]
I've just tried it locally, with `git master` version of `go-ethereum`, which [added support for `geth --goerli` a day ago](https://github.com/ethereum/go-ethereum/pull/18121).

I've ran a simple block filter script with that as the back-end, and it worked just fine.

I think the only change that'll be required in `web3.py` is to look for the IPC socket in `~/.ethereum/goerli/geth.ipc`, too, when using `web3.auto`. That, and add the middleware, just as in PR #1234.

**Comment by carver** [comment]
> * look for the IPC socket in `~/.ethereum/goerli/geth.ipc`, too, when using `web3.auto`; similar for `parity-ethereum` and any other supported node impln-s;

Yup! Although if I remember correctly we are moving away from dynamically/automatically switching between testnet and mainnet depending on which is available. So maybe it's time for something like:

```py
from web3.auto.geth.goerli import w3
# plus an alias, since I think we should encourage goerli as the "default" testnet:
from web3.auto.geth.testnet import w3
```

> * add the middleware when using Goerli, just as PR #1234 does for Rinkeby;

:+1: 

> * aforementioned rename to `clique_poa_middleware` would be nice ^_^ - don't forget the docs if so.

:+1:
