### ISSUE TITLE
Error :InsufficientDataBytes

### ISSUE THREAD

**Issue by Abhimanyu121** [ethereum/web3.py#1231]
* Version: 0.5.3
* Python: 3.5
* OS: win

### What was wrong?
There is error of "InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes"
Other issues mentioned that it will be fixed in solidity version 5, but it still isn't fixed .

* The full output of the error
`https://del.dog/adodanejoz.sql`
* Smart contract we are using 
`https://del.dog/veqelecuku`

**Comment by pipermerriam** [comment]
It's preferred to inline stack traces and example code using code blocks in the issue.  Please reference the issue template for what constitutes a complete bug report.

**Comment by fselmo** [comment]
stale
