### ISSUE TITLE
getLogs by blockHash

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/web3.py#1236]
* Version: commit c4de4746c89b224bfb212e9ed7971ca70024777f (master)
* Python: 3.6
* OS: linux

### What was wrong?

The JSON-RPC wiki says that `eth_getLogs` can take `blockHash` as a parameter instead of `fromBlock`/`toBlock` but `Event.getLogs` does not take it as a parameter.

### How can it be fixed?

Add `blockHash` as an acceptable parameter to `Event.getLogs`. Although it should be noted that parity does not apparently support this - or if it does, the behavior is undocumented (https://wiki.parity.io/JSONRPC-eth-module.html#eth_getlogs).

**Comment by charles-cooper** [comment]
Just tested on parity v2.2.8 and getLogs accepts blockHash as a parameter to the `getLogs` filter spec.

**Comment by kclowes** [comment]
Looks like this is complete! Thanks @charles-cooper!
