### ISSUE TITLE
Deprecate Infura with no API key

### ISSUE THREAD

**Issue by davesque** [ethereum/web3.py#1246]
### What was wrong?

Currently, the Infura provider is usable without an API key.

### How can it be fixed?

This needs to be deprecated since Infura will soon cut support for interactions without an API key.

**Comment by pipermerriam** [comment]
@kclowes I assigned this to you.  I don't know exact timeline but I think it's less than two months.  Can you see about getting a deprecation warning in for this ASAP.  I think it needs to get backported to v4 as well.
