### ISSUE TITLE
Remove Python `collections` Deprecation warnings

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1266]
* Python: 3.7 and below

### What was wrong?
Python 3.8 is changing the way imports from `collections` are being handled. The following Deprecation warning describes the issue: 
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

### How can it be fixed?
Go through the codebase and swap out any `collections` imports for `collections.abc`

**Comment by stringray55** [comment]
I would like to take this up.

**Comment by kclowes** [comment]
Awesome, thank you!

**Comment by dathbezumniy** [comment]
Is the issue still takeable?
