### ISSUE TITLE
ImportError with web3-5.0.0a7

### ISSUE THREAD

**Issue by Amxx** [ethereum/web3.py#1285]
I tried moving to toward `5.0.0a7`. I made a fresh install with

    sudo pip uninstall web3
    sudo pip install git+https://github.com/ethereum/web3.py.git

Once the install done, I have an error when importing `web3`

    ImportError: cannot import name 'collapse_if_tuple' from 'eth_utils.abi' (/usr/lib/python3.7/site-packages/eth_utils/abi.py)

**Comment by kclowes** [comment]
@Amxx you probably need to update eth-utils. It looks like `collapse_if_tuple` was added in 1.4.0. I should probably update the requirement in `setup.py` though. Thanks!
