### ISSUE TITLE
the rumtime enviroment of web3

### ISSUE THREAD

**Issue by mengquanrun** [ethereum/web3.py#1289]
* Version: x.x.x
* Python: 2.7/
* OS: ubuntu 18.04

### What was wrong?

i want to install web3 on python2.7, because a tool i need to use is python2.7, and it depend on web3,.

So i want to know is there **an old version** of web3 that can support python2.7?

**Comment by kclowes** [comment]
web3 v4 is when we started requiring Python 3 https://web3py.readthedocs.io/en/stable/releases.html. So anything before v4 should work with python 2 but know that v3 is not being actively maintained. Depending on your use case, it's probably a good idea to update to python 3. Here is some info on doing so: https://web3py.readthedocs.io/en/stable/v4_migration.html#python-2-to-python-3. Closing this issue, but feel free to reopen if this doesn't answer your question.

**Comment by evandrix** [comment]
`web3==3.16.1`, but dep:`ERROR: Package 'eth-hash' requires a different Python: 2.7.17 not in '>=3.5, <4'`

**Comment by kclowes** [comment]
@evandrix You may need to downgrade the `eth-hash` package, or it may be that web3 will work okay even with the error. Unfortunately, v3 is no longer supported. Can you upgrade to v4 or better yet, v5?
