### ISSUE TITLE
Add a command to launch with an IPC connection

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#1306]
Some nodes, like geth, would prefer to drop their maintenance of tools like `geth attach` in favor of a web3.py python command line tool. They would do a simple alias, like:

```sh
geth --datadir /home/hacker/.ethereum/ pyconsole
```

to invoke

```sh
pyconsole /home/hacker/.ethereum/geth.ipc
```

(Some alternate names for `pyconsole`: `ethpy`, `pyeth`, `web3py`.)

That gives us a clean geth integration, and a more general all-node console.

We *could* put it in it's own repo, but I think this would be a truly tiny addition to web3.py, and is essentially just another way to launch web3.py.

_Originally posted by @carver in https://github.com/ethereum/go-ethereum/issues/16382#issuecomment-375868054_

**Comment by pacrob** [comment]
Closing as stale. If someone has interest, please open a new issue.
