### ISSUE TITLE
error while installing web3

### ISSUE THREAD

**Issue by warkechetan** [ethereum/web3.py#1313]
* Version: x.x.x
* Python: 3.6.5
* OS: win
I gave command pip install web3 in anaconda it giving me error as follows:
Collecting web3
  Using cached https://files.pythonhosted.org/packages/9d/df/0bfb618ff309ef9f2014e829daf689c13d0652534002d8dff8615b92946b/web3-4.9.1-py3-none-any.whl
Requirement already satisfied: eth-utils<2.0.0,>=1.2.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (1.4.1)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (2.18.4)
Requirement already satisfied: pypiwin32>=223; platform_system == "Windows" in c:\users\chetan\anaconda3\lib\site-packages (from web3) (223)
Requirement already satisfied: eth-abi<2.0.0,>=1.2.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (1.3.0)
Requirement already satisfied: websockets<7.0.0,>=6.0.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (6.0)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (0.2.0)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython" in c:\users\chetan\anaconda3\lib\site-packages (from web3) (0.9.0.1)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (0.1.0)
Requirement already satisfied: eth-account<0.4.0,>=0.2.1 in c:\users\chetan\anaconda3\lib\site-packages (from web3) (0.3.0)
Collecting lru-dict<2.0.0,>=1.1.6 (from web3)
  Using cached https://files.pythonhosted.org/packages/00/a5/32ed6e10246cd341ca8cc205acea5d208e4053f48a4dced2b1b31d45ba3f/lru-dict-1.1.6.tar.gz
Requirement already satisfied: eth-typing<3.0.0,>=1.0.0 in c:\users\chetan\anaconda3\lib\site-packages (from eth-utils<2.0.0,>=1.2.0->web3) (2.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\chetan\anaconda3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\chetan\anaconda3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\chetan\anaconda3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chetan\anaconda3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2018.4.16)
Requirement already satisfied: pywin32>=223 in c:\users\chetan\anaconda3\lib\site-packages (from pypiwin32>=223; platform_system == "Windows"->web3) (223)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\chetan\anaconda3\lib\site-packages (from eth-abi<2.0.0,>=1.2.0->web3) (0.8.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in c:\users\chetan\anaconda3\lib\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.8.1)
Requirement already satisfied: toolz>=0.8.0 in c:\users\chetan\anaconda3\lib\site-packages (from cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython"->web3) (0.9.0)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in c:\users\chetan\anaconda3\lib\site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.5.1)
Requirement already satisfied: eth-keys<0.3.0,>=0.2.0b3 in c:\users\chetan\anaconda3\lib\site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.2.1)
Requirement already satisfied: attrdict<3,>=2.0.0 in c:\users\chetan\anaconda3\lib\site-packages (from eth-account<0.4.0,>=0.2.1->web3) (2.0.1)
Requirement already satisfied: eth-rlp<1,>=0.1.2 in c:\users\chetan\anaconda3\lib\site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.1.2)
Requirement already satisfied: six>=1.9.0 in c:\users\chetan\anaconda3\lib\site-packages (from parsimonious<0.9.0,>=0.8.0->eth-abi<2.0.0,>=1.2.0->web3) (1.11.0)
Requirement already satisfied: rlp<2,>=0.6.0 in c:\users\chetan\anaconda3\lib\site-packages (from eth-rlp<1,>=0.1.2->eth-account<0.4.0,>=0.2.1->web3) (1.1.0)
Building wheels for collected packages: lru-dict
  Building wheel for lru-dict (setup.py) ... error
  Complete output from command c:\users\chetan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chetan\\AppData\\Local\\Temp\\pip-install-yd21sgli\\lru-dict\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Chetan\AppData\Local\Temp\pip-wheel-aao0w8zp --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
Failed to build lru-dict
Installing collected packages: lru-dict, web3
  Running setup.py install for lru-dict ... error
    Complete output from command c:\users\chetan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chetan\\AppData\\Local\\Temp\\pip-install-yd21sgli\\lru-dict\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Chetan\AppData\Local\Temp\pip-record-fy8io6pq\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lru' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "c:\users\chetan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Chetan\\AppData\\Local\\Temp\\pip-install-yd21sgli\\lru-dict\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Chetan\AppData\Local\Temp\pip-record-fy8io6pq\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Chetan\AppData\Local\Temp\pip-install-yd21sgli\lru-dict\

**Comment by kclowes** [comment]
@warkechetan Try installing Microsoft Visual C++ 14.0 like the error says. Do you get another error after that?

**Comment by warkechetan** [comment]
Can u suggest me link i m unable to find Microsoft Visual c++ 14.0

**Comment by kclowes** [comment]
I'm just reading the error message you posted. Looks like it can be downloaded here: 
> Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by warkechetan** [comment]
> 
> 
> I'm just reading the error message you posted. Looks like it can be downloaded here:
> 
> > Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

i Downloaded it giving me error of cl.exe no directory found.
Then i try to install it through MSC++ command prompt now giving error
Installed c:\users\chetan\appdata\local\temp\pip-build-vgpau9\eth-account\.eggs\wheel-0.33.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\chetan\appdata\local\temp\pip-build-vgpau9\eth-account\setup.py", line 71, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 444, in __init__
        k: v for k, v in attrs.items()
      File "c:\python27\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 732, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\chetan\appdata\local\temp\pip-build-vgpau9\eth-account\.eggs\setuptools_markdown-0.2-py2.7.egg\setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "c:\users\chetan\appdata\local\temp\pip-build-vgpau9\eth-account\.eggs\pypandoc-1.4-py2.7.egg\pypandoc\__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\chetan\appdata\local\temp\pip-build-vgpau9\eth-account\

**Comment by kclowes** [comment]
I can't tell what's actually happening, but it looks like your python version is 2.7, which leads me to believe you aren't installing web3 in a clean environment. The most recent stable web3 needs python3.5 or higher, and the latest unstable web3 version needs 3.6+. I'm not sure if you are using one, but we highly recommend using a virtual environment. There are instructions here to set one up: https://web3py.readthedocs.io/en/stable/troubleshooting.html#setup-environment

**Comment by kclowes** [comment]
Closing, but feel free to reopen if you still need support!
