### ISSUE TITLE
AttributeError: type object 'Transfer' has no attribute 'getLogs'

### ISSUE THREAD

**Issue by araa47** [ethereum/web3.py#1318]
* Version: 4.9.1
* Python: 3.7.3
* OS: osx
* `pip freeze` output
```
appdirs==1.4.3
attrdict==2.0.1
attrs==19.1.0
black==19.3b0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cytoolz==0.9.0.1
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.4.1
hexbytes==0.1.0
idna==2.8
lru-dict==1.1.6
parsimonious==0.8.1
pycryptodome==3.8.1
requests==2.21.0
rlp==1.1.0
six==1.12.0
toml==0.10.0
toolz==0.9.0
urllib3==1.24.1
web3==4.9.1
websockets==6.0
```

### What was wrong?

Code
```
web3 = Web3(
 WebsocketProvider("wss://mainnet.infura.io/ws/v3/myappid")
)
token_contract = web3.eth.contract(address=tokenContractAddress, abi=contract_abi)
from_block = max(token_contract.web3.eth.blockNumber - 10, 1)
to_block = token_contract.web3.eth.blockNumber
print(f"From: {from_block} To: {to_block}")
print(token_contract.events.Transfer.getLogs(fromBlock=from_block, toBlock=to_block))
```
Error:
```
From: 7525075 To: 7525085
Traceback (most recent call last):
  File "app.py", line 94, in <module>
    print(token_contract.events.Transfer.getLogs(fromBlock=from_block, toBlock=to_block))
AttributeError: type object 'Transfer' has no attribute 'getLogs'

```
I am currently trying to get a list of all the contract transfers, so I can get the balances for each wallet who owns this erc20 token for each block. Based on instructions in https://github.com/ethereum/web3.py/blob/master/web3/contract.py. 

Is there a better way to approach this problem? Basically I want to track all the balances of the erc20 token since creation date, and have snapshots for each block number, so I can easily search token balances for each wallet for certain dates.

**Comment by araa47** [comment]
I have also tried another method to get all erc20 transactions for the token based on https://web3py.readthedocs.io/en/stable/contracts.html. 

Code: 
```
web3 = Web3(
 WebsocketProvider("wss://mainnet.infura.io/ws/v3/myappid")
)
token_contract = web3.eth.contract(address=tokenContractAddress, abi=contract_abi)
transfer_filter = token_contract.eventFilter('Transfer')
print(transfer_filter.get_all_entries())
```

Output: 
```
[]
```

Still can't seem to pull the transactions for the particular erc20 token in order to calculate balances during different points of time.

**Comment by kclowes** [comment]
If you want to use the contract instance like you have in the first comment:
> `token_contract.events.Transfer.getLogs(fromBlock=from_block, toBlock=to_block)`

You'll need to create the filter first:
`event_filter = token_contract.events.Transfer.createFilter(fromBlock=from_block, toBlock=to_block)`
and then you can get the new entries:
`event_filter.get_new_entries()`

I'm not sure why `transfer_filter = token_contract.eventFilter('Transfer')` isn't working. I'd guess that there are no transfer events on the latest block? If you don't specify otherwise, the default `from` and `toBlock` is `latest`. 

More info can be found [here](https://web3py.readthedocs.io/en/stable/filters.html#module-web3.utils.filters) and eventFilter docs are [here]( https://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.Contract.eventFilter)

**Comment by araa47** [comment]
@kclowes , was able to try it out, here is the exact code snippet used. However I still get an empty list as output. I have checked etherscan to make sure there are transactions available between the blocks for the token I use. 

```
event_filter = token_contract.events.Transfer.createFilter(fromBlock= from_block, toBlock=to_block)
print(event_filter.get_new_entries())
```

**Comment by araa47** [comment]
I seem to have found a web3 js function that works with Infura Http provider. 

```
async function getPastEvents(token, blockStart, blockEnd) {
   return new Promise((resolve, reject) => {
      token.getPastEvents('Transfer', {
         //filter: { _from : account },
         fromBlock: blockStart,
         toBlock: blockEnd
      }, (error, results) => { resolve(results) })
   })
}
```

Is there a python equivalent of this? The node js snippet can be run using infura http provider, while the python code above seems to need infura websocket provider since filters are not available with infura http provider.

**Comment by merc1er** [comment]
> Is there a python equivalent of this?

Yes, `contract.events.Transfer.getLogs(fromBlock=0x0)` should return something similar.

**Comment by fselmo** [comment]
stale
