### ISSUE TITLE
AttributeError: 'list' object has no attribute 'buildTransaction'

### ISSUE THREAD

**Issue by ethdev279** [ethereum/web3.py#1340]
* Version:
* Python: 3.5
* OS: win10
* `pip freeze` output

```
attrdict==2.0.1
beautifulsoup4==4.7.1
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cytoolz==0.9.0.1
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.4.1
Flask==1.0.2
hexbytes==0.1.0
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
lru-dict==1.1.6
MarkupSafe==1.1.1
parsimonious==0.8.1
pycryptodome==3.8.0
pypiwin32==223
pywin32==224
rebound-cli==2.0.0
requests==2.21.0
rlp==1.1.0
six==1.12.0
soupsieve==1.9.1
toolz==0.9.0
urllib3==1.24.1
urwid==2.0.1
web3==4.9.1
websockets==6.0
Werkzeug==0.15.2
windows-curses==1.1
```

### What was wrong?

Please include any of the following that are applicable:

* I'm trying to send a transaction to smartcontract function. below is the error.
```
 tx = contract_instance.greet("Hi devs").buildTransaction({'nonce': web3.eth.getTransactionCount(account_address)})
AttributeError: 'list' object has no attribute 'buildTransaction'
```
*

**Comment by kclowes** [comment]
You need to add `functions` in between `contract_instance` and `greet`. For example: 
`contract_instance.functions.greet("Hi devs").buildTransaction({...})`. You can check out the docs [here](https://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.ContractFunction.buildTransaction). Feel free to reopen if that doesn't solve your problem!

**Comment by ilijapet** [comment]
Same here. I call write functiin 
```
stored_transaction = self.nft_contract.functions.transferFrom(self.owner_address, user_address, int(number_of_nft)).buildTransaction(
                {"from": self.owner_address, "nonce": nonce}
            )
```

and I get 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'transferFrom' object has no attribute 'buildTransaction'
```

But for example when I read from the same contract function works without any problem. 
Example:

`self.nft_contract.functions.symbol().call() `

```
'TPACK'
```

Someone have some idea?

**Comment by fselmo** [comment]
@ilijapet in `v6`, it's snaked cased as `build_transaction()`

**Comment by studentforcode** [comment]
@ethdev279
you tried to send with multisig wallet ..


`if secret_key:
    try:
        wallet = keys.PrivateKey(bytes.fromhex(secret_key))
        from_address = wallet.public_key.to_base58check_address()
        txn = (
            contract.functions.transfer(to_address, amount)
            .with_owner(from_address)
            .fee_limit(50_000_000)
            .build()
            .inspect()
            .permission_id(2)
            .sign(wallet)
            .broadcast()
        )`

can you sen the complet file ?
