### ISSUE TITLE
Add support for a JSON string in eth_signTypedData and personal_signTypedData

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1342]
### What was wrong?

Currently, the `signTypedData` implementations only allow a JSON object. We should add support for a JSON string in `eth_signTypedData` and `personal_signTypedData` too. Inspired by [this comment](https://github.com/ethereum/web3.py/pull/1319/files#r279892669) :)

**Comment by pacrob** [comment]
This is `eth-account`. Closing.
