### ISSUE TITLE
ethers.utils.solidityKeccak256 equivalent in web3 

### ISSUE THREAD

**Issue by araa47** [ethereum/web3.py#1344]
* Version: 4.9.2
* Python: 3.7.3
* OS: osx

### Question 

Is there a web3 equivalent of the ethers.utils.solidityKeccak256 function, 
or how would i go about re-creating a similar hash given a bunch of parameters. 

It helps with computing the keccak256 cryptographic hash using the Solidity non-standard (tightly) packed data for values given the types.

**Comment by kclowes** [comment]
Is this what you're looking for? https://web3py.readthedocs.io/en/stable/overview.html?highlight=soliditySha3#Web3.soliditySha3
