### ISSUE TITLE
Add Testing Best Practices Documentation

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1356]
### What was wrong?
We don't have any documentation around best practices for testing (that I'm aware of) for contributors to reference other than how to run the tests in the README. We should write some up! Some topics might include:
- Integration test setup/hierarchy
- Preferring the `@pytest.mark.xfail` decorator over `pytest.xfail`
- ...Any other best practices

**Comment by pipermerriam** [comment]
These are things that we'd often place in the https://github.com/ethereum/snake-charmers-tactical-manual 

Maybe put them there and cross link from web3.py documentation?

**Comment by kclowes** [comment]
Sounds good to me! Let me know if you have anything else you'd like to see added to this documentation.

**Comment by pacrob** [comment]
Present in Tactical Manual and contributing docs.
