### ISSUE TITLE
ENS: Name normalisation is using `idna.decode` instead of `idna.encode`

### ISSUE THREAD

**Issue by joshuawu** [ethereum/web3.py#1357]
Normalisation function:

https://github.com/ethereum/web3.py/blob/abb3b631fb76eca21f02d420785c32c17ea9e760/ens/utils.py#L74-L91

The line in question:

https://github.com/ethereum/web3.py/blob/abb3b631fb76eca21f02d420785c32c17ea9e760/ens/utils.py#L89

Shouldn't this be `idna.encode(...)`? I don't see how this makes sense trying to decode the original input into Unicode. We want to encode it into ASCII.

**Comment by pipermerriam** [comment]
Do you know if there are any test vectors from the ENS spec that would demonstrate the correct behavior so we can add a test?

**Comment by joshuawu** [comment]
> Do you know if there are any test vectors from the ENS spec that would demonstrate the correct behavior so we can add a test?

There are no test vectors in the EIP #137 spec.

**Comment by kclowes** [comment]
@joshuawu I believe decode is correct here because the purpose is to take any of the ASCII encoded urls `xn--...` and turn them into utf-8. See this testcase: https://github.com/ethereum/web3.py/blob/master/tests/ens/test_nameprep.py#L15
