### ISSUE TITLE
ModuleNotFoundError: No module named'eth_account.local'

### ISSUE THREAD

**Issue by wangyuncong123** [ethereum/web3.py#1362]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

I use the buildozer 

requirements = python3,kivy,web3,eth-account,cytoolz,setuptools,toolz,ethereum,eth-keyfile,pycryptodome,eth-keys,eth-utils,eth-hash,eth-typing,hexbytes,eth-rlp,rlp,attrdict,eth-abi,parsimonious,idna,lru-dict,requests

### What was wrong?

Please include any of the following that are applicable:

05-24 14:11:53.759  9444  9467 I python  :    File "/home/wyc/.buildozer/android/platform/build/build/python-installs/myapp/web3/middleware/signing.py", line 9, in <module>
05-24 14:11:53.761  9444  9467 I python  :  ModuleNotFoundError: No module named 'eth_account.local'
05-24 14:11:53.761  9444  9467 I python  : Python for android ended.

### How can it be fixed?
in signing.py
from eth_account.local import (
    LocalAccount,
)

but there is only eth_account/signer/local.py

I changed signing.py  to from eth_account.signer.local import       but it doesn't work 
how to fix it?

**Comment by kclowes** [comment]
If you're using web3 v4, you'll want to make sure you're using an eth-account version between 0.3.0 and 0.2.1. The `eth_account /signer` change came in v0.4.0. If you make a new virtual environment and do a fresh `pip install`, it should work. Closing this, but feel free to reopen if you still are having issues. If you do reopen, pasting the output from running `pip freeze` would be helpful. Thanks!

**Comment by wangyuncong123** [comment]
solve it！thanks a lot
