### ISSUE TITLE
Mini Typo in "web3.txpool.inspect" API description

### ISSUE THREAD

**Issue by Dominik1999** [ethereum/web3.py#1363]
Hey there, 

just because I saw it: 

`Returns a textual summary of all transactions currently pending for inclusing in the next block(s) as will as ones that are scheduled for future execution.`

must be 

`Returns a textual summary of all transactions currently pending for including in the next block(s) as well as ones that are scheduled for future execution.`

right?

**Comment by kclowes** [comment]
Yes it should! Thanks for finding it. It would be awesome if you wanted to open a PR 😃

**Comment by L-F-Escobar** [comment]
Can I get a link to where this api description is? I cant find it in the docs

**Comment by kclowes** [comment]
https://raw.githubusercontent.com/ethereum/web3.py/master/docs/web3.geth.rst, line 359

**Comment by fselmo** [comment]
closed by #2326
