### ISSUE TITLE
Latest docs incorrectly suggest that sendRawTransaction returns a string, actually HexBytes

### ISSUE THREAD

**Issue by wjmelements** [ethereum/web3.py#1367]
Docs say string:
<img width="662" alt="Screen Shot 2019-06-05 at 6 20 40 PM" src="https://user-images.githubusercontent.com/799573/59000403-33425800-87bf-11e9-90cd-87c9b18d4c20.png">
However:
<img width="556" alt="Screen Shot 2019-06-05 at 6 15 04 PM" src="https://user-images.githubusercontent.com/799573/59000411-363d4880-87bf-11e9-972d-f51a85c19f78.png">

**Comment by kclowes** [comment]
You're right! Thanks for pointing that out!
