### ISSUE TITLE
Docs should show checksummed addresses

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1388]
### What was wrong?
As pointed out [here](https://github.com/ethereum/web3.py/pull/1384#issuecomment-511522479), docs should show the checksummed version of the address so that examples can be used easier.

### How can it be fixed?

Go through the docs and replace any addresses that aren't checksummed with the checksummed version.

**Comment by crawfordleeds** [comment]
I've started this so feel free to assign me. Should have a PR within a few days.
