### ISSUE TITLE
Not Receiving Deprecation Notice for Web3.soliditySha3() method

### ISSUE THREAD

**Issue by crawfordleeds** [ethereum/web3.py#1399]
* Version: 5.0.0b4
* Python: 3.7.4
* OS: osx
* `pip freeze` output

```
attrdict==2.0.1
base58==1.0.3
certifi==2019.6.16
chardet==3.0.4
coverage==4.5.3
cytoolz==0.10.0
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.6.1
ethtoken==0.0.1a4
hexbytes==0.2.0
idna==2.8
ipfshttpclient==0.4.12
jsonschema==2.6.0
lru-dict==1.1.6
multiaddr==0.0.8
netaddr==0.7.19
nose2==0.9.1
parsimonious==0.8.1
protobuf==3.7.1
pycryptodome==3.8.2
requests==2.22.0
rlp==1.1.0
six==1.12.0
toolz==0.10.0
urllib3==1.25.3
varint==1.0.2
virtualenv==16.6.1
web3==5.0.0b4
websockets==7.0
```

### What was wrong?

When I use the soliditySha3 method, per the docs in [overview.rst](https://github.com/ethereum/web3.py/blob/master/docs/overview.rst), I am not receiving a console warning indicating deprecation. The warning appears as expected with the Web3.sha3() method.

Here's what my console looks like in pycharm:
```
>>> Web3.sha3(text='txt')
<input>:1: DeprecationWarning: sha3 is deprecated in favor of keccak
HexBytes('0xd7278090a36507640ea6b7a0034b69b0d240766fa3f98e3722be93c613b29d2e')
>>> Web3.soliditySha3(['bool'], [True])
HexBytes('0x5fe7f977e71dba2ea1a68e21057beebb9be2ac30c6410aa38d4f3fbe41dcffd2')
```

### How can it be fixed?

I'm not sure because there seems to be a decorator in the code so I was hoping someone might have some insight.

https://github.com/ethereum/web3.py/blob/388cd2d259b401fe9fe87aa523c7dc3fb6f2f1a9/web3/main.py#L166-L191

I appreciate the help!

**Comment by kclowes** [comment]
@crawfordleeds see #1140 for the explanation on what's happening. I also just made a PR to have the deprecation warnings show because I think it's more confusing that one warning shows and one does not.

**Comment by crawfordleeds** [comment]
@kclowes thanks and sorry I wasn't aware of issue #1140. Seems it's all been handled there and through your PR.
