### ISSUE TITLE
eth.getTransactionReceipt return a error instead null when transaction not in blockchain

### ISSUE THREAD

**Issue by BlackTurtle123** [ethereum/web3.py#1421]
* Version: 5.0.0
* Python: 3.6
* OS: linux

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

`signed_txn = self._web3_proxy.eth.account.signTransaction(txn_dict, address.privateKey.hex())
                transaction = self._web3_proxy.eth.sendRawTransaction(signed_txn.rawTransaction)
                print(str(signed_txn))
                print(str(transaction))
                tx_receipt = self._web3_proxy.eth.getTransactionReceipt(self._web3_proxy.toHex(transaction))
`

### How can it be fixed?

Document how to handle a receipt which is not in the blockchain yet.
Or make it return null again.
Documentation still says it should return null
https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#gettransactionreceipt

**Comment by pipermerriam** [comment]
The documentation you are linking to is the Javascript library `web3js`  

That said, it appears that our documentation is out of date as it also says that it returns `None`.

https://web3py.readthedocs.io/en/stable/web3.eth.html

**Comment by marcgarreau** [comment]
As of #1663, the documentation is more accurate. Closing this nearly year-old issue; please open a new one if there's still a request beyond this correction.
