### ISSUE TITLE
Add Snake Case Methods for JSON-RPC calls

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1429]
### What was wrong?
We'd like to start using pythonic snake_case names for all JSON-RPC methods. The pattern has been laid out in the Geth admin module. 

### How can it be fixed?
Add deprecation warnings, new snake case methods, and tests for all other modules. Ideally, each module would be its own PR. 

- [x] Eth
- [x] GethShh
- [x] GethPersonal
- [x] GethTxPool
- [x] GethMiner
- [x] Net
- [x] ParityShh
- [x] ParityPersonal
- [x] Parity

**Comment by Patil2099** [comment]
@kclowes Can You Explain it a bit more? I want to work on this issue!

**Comment by pipermerriam** [comment]
@Patil2099 see this PR https://github.com/ethereum/web3.py/pull/1326 which implements this in the geth admin module.  You would follow the same pattern for the listed modules in this issue.

**Comment by Patil2099** [comment]
Thanks 😊

On Aug 22, 2019 10:07 PM, Piper Merriam <notifications@github.com> wrote:

@Patil2099<https://github.com/Patil2099> see this PR #1326<https://github.com/ethereum/web3.py/pull/1326> which implements this in the geth admin module. You would follow the same pattern for the listed modules in this issue.

**Comment by Patil2099** [comment]
@kclowes  I will start working on it.

**Comment by Patil2099** [comment]
@kclowes Do I have to do it like this?

**Comment by kclowes** [comment]
> @kclowes Do I have to do it like this?

I'm not sure what you mean. Can you explain a little more?

We would prefer that you follow the implementation laid out in #1326, but we're open to hearing other ideas!

**Comment by Patil2099** [comment]
@kclowes should I start working on other modules?
Now I have a good example to follow.

**Comment by kclowes** [comment]
That would be great, thank you!

**Comment by smilegodly** [comment]
I'd like to work on the GethPersonal module if that's ok ?

**Comment by kclowes** [comment]
@smilegodly that would be great, thanks! Let me know if you have any questions!

**Comment by smilegodly** [comment]
@kclowes How can I individually run [these tests here](https://github.com/ethereum/web3.py/pull/1326/files#diff-9db648eb49912b137f56e9563f2011f2R7),  so that I can see if the Deprecation Warnings get raised? 

At the moment , I've just been using ```tox``` to test on the whole build structure.. but I would like to be able to run just what I need to be running to see that the deprecation warning tests are working fine .

**Comment by kclowes** [comment]
@smilegodly If you’re running the core tests, those use eth-tester and the skipped methods probably aren’t implemented in eth-tester. You might try running the integration tests. I think some of those are marked xfail, but the test should run and you may be able to check for a deprecation warning in the test anyway with a ‘with pytest.warns(DeprecationWarning, match=...)’. If that’s confusing I can expand more, just let me know!

**Comment by ashish10677** [comment]
Is this issue still open?

**Comment by kclowes** [comment]
@ashish10677 Yes it is! If you're going to work on one of the modules, please share which one here so we don't get two people working on the same thing! Thanks!

**Comment by tmckenzie51** [comment]
I'm working on the ParitySsh module.

**Comment by billbsing** [comment]
If it's OK I would like to start on GethMiner.

**Comment by billbsing** [comment]
I'm working on the Net module

**Comment by tmckenzie51** [comment]
I'm working on the parity personal module

**Comment by billbsing** [comment]
If it's ok I would like to start working on the eth module start soon. 

I assume @Patil2099 your last PR #1465 is not active anymore?

I'm planning to break it into several PRs since it's the bigger module.
+ properties
+ methods
+ Move to ModuleV2 and the _utils/eth.py module ? (maybe a new issue for this?)

**Comment by kclowes** [comment]
Thanks @billbsing, but I've been working on moving the eth module to use ModuleV2, so hold off on that for a bit, otherwise I'll have some nasty merge conflicts! I'll let you know when I'm done if you still want to pick it up!

**Comment by Ifere** [comment]
@kclowes any modules left to be done? I'd like to work on this issue. Also is there a guide I could follow?

**Comment by kclowes** [comment]
@Ifere I've been working my way through the `eth` methods one by one. If you'd like to work on one (or more) of those, that would be awesome! The pattern can be found in pretty much any of the linked PRs, but #1829 or #1828 are probably the best to check out since they're the most recent and in the `eth` module. Be sure to get a PR up at the beginning (even if it's in progress), or list here what method you choose so that we don't have overlapping work! Thanks!

**Comment by marcgarreau** [comment]
pretty sure #1963 was the last of em :tada: closing out.
