### ISSUE TITLE
waitForTransactionReceipt may cause Too Many Requests error

### ISSUE THREAD

**Issue by m3ngyang** [ethereum/web3.py#1435]
* Version: v5.0.0
* Python: 3.6
* OS: linux
* `pip freeze` output

### What was wrong?

The following function to query transaction receipt periodically may cause error `requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for xxx` under certain circumstance.

https://github.com/ethereum/web3.py/blob/53337c3f909084a9082ee9081f677165540f6a75/web3/eth.py#L257-L259

In fact, the depending function `wait_for_transaction_receipt` has a latency parameter,

https://github.com/ethereum/web3.py/blob/53337c3f909084a9082ee9081f677165540f6a75/web3/_utils/transactions.py#L68

### How can it be fixed?

Export `poll_latency` for function `waitForTransactionReceipt`.

**Comment by m3ngyang** [comment]
If you have install web3 and met the same problem, you could find installed `web3.py/web3/_utils/transactions.py` and modify the `poll_latency` to a larger value as a workaround.

**Comment by hunterpack** [comment]
@m3ngyang I am making a request to 500 transactions, and am getting a 429 too many requests still after changing the poll latency ranging from .001 to 1200, I can't get the error to pass. Do you have any suggestions.

**Comment by kclowes** [comment]
@hunterpack do you have a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) I can try out to help you troubleshoot?

**Comment by Pet3ris** [comment]
This should be closed? https://github.com/ethereum/web3.py/pull/1144

**Comment by kclowes** [comment]
Yep, you're right. Thanks @Pet3ris!
