### ISSUE TITLE
Cannot create `newAccount` using new `geth` API

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/web3.py#1442]
* Version: 5.0.2
* Python: 3.6
* OS: osx
* `pip freeze` output

```
appdirs==1.4.3
atomicwrites==1.3.0
attrdict==2.0.1
attrs==19.1.0
base58==1.0.3
black==19.3b0
blessings==1.7
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cytoolz==0.10.0
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.6.4
hexbytes==0.2.0
idna==2.8
importlib-metadata==0.19
inquirer==2.6.3
ipfshttpclient==0.4.12
jsonschema==2.6.0
lru-dict==1.1.6
more-itertools==7.2.0
multiaddr==0.0.8
netaddr==0.7.19
packaging==19.1
parsimonious==0.8.1
pluggy==0.12.0
protobuf==3.9.1
psutil==5.6.3
py==1.8.0
py-solc===3.2.0-fixedstdin
pycryptodome==3.8.2
pyparsing==2.4.2
pytest==5.1.1
python-editor==1.0.4
readchar==2.0.1
requests==2.22.0
rlp==1.1.0
semantic-version==2.6.0
six==1.12.0
tableformatter==0.1.4
toml==0.10.0
toolz==0.10.0
urllib3==1.25.3
varint==1.0.2
vyper==0.1.0b11
wcwidth==0.1.7
web3==5.0.2
websockets==7.0
zipp==0.6.0
```

### What was wrong?

Running `self.web3.geth.personal.newAccount(<passphrase>)` on a new Geth dev instance doesn't work.

Geth launched with:

```bash
geth --dev --rpc --ipcdisable --rpcaddr 0.0.0.0 --rpcapi="db,eth,net,personal,web3" --allow-insecure-unlock'
```

The error:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b3245d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

### How can it be fixed?

I'm looking either for guidance on how I'm applying the new API wrong (because this code used to work with the personal API pre Web3.py v5.

Or alternatively, I'm looking to see if there is a new recommended cross-client approach of creating new accounts!

Thanks a lot.

**Comment by Pet3ris** [comment]
[StackOverflow thread](https://ethereum.stackexchange.com/questions/74567/creating-new-accounts-using-web3).

**Comment by kclowes** [comment]
@Pet3ris if you run `w3.isConnected()` do you get a `True` response? It looks like maybe you're not connected

**Comment by Pet3ris** [comment]
Hi @kclowes, unfortunately it's connected :(. Other transactions (e.g., deploying contracts, making calls to contracts) go through.

The problem was that `geth` dev instance has only one account pre-allocated in `web3.eth.accounts`, so my goal is simply to create a couple more and also replicate this across other evm clients.

**Comment by kclowes** [comment]
> my goal is simply to create a couple more and also replicate this across other evm clients.

Yep, that makes sense to me. 

It doesn't make sense to me that other transactions go through but the personal endpoints aren't working. I started up geth with the command you listed above, and am able to create new accounts via `w3.geth.personal.newAccount()`. I saw the error once, right on startup, but as soon as geth got going, it worked. I assume you're able to consistently replicate even if the geth process has been running for a while?

**Comment by Pet3ris** [comment]
@kclowes it indeed was a timing issue. Thanks a lot for the help.

Any thoughts on how to do the same for `parity`?

**Comment by kclowes** [comment]
You should be able to use the same method: `w3.parity.personal.newAccount(<passphrase>)`, but you do need to enable the personal API on your node: https://wiki.parity.io/JSONRPC.html#enabled-apis-default

**Comment by kclowes** [comment]
Looks like this was resolved way back when. Closing, but feel free to reopen if I'm mistaken!
