### ISSUE TITLE
Websocket timeout isn't working properly

### ISSUE THREAD

**Issue by fab-spring** [ethereum/web3.py#1449]
* Version: 5.0.5b
* Python: 3.7
* OS: osx

### What was wrong?
```
In [19]: w = Web3(Web3.WebsocketProvider('WS_URL_THAT_DOESNT_WORK', websocket_timeout=1, websocket_kwargs={'timeout': 1}))
In [20]: w.isConnected()
```

The commands above hangs. It appears that it doesn't timeout properly.

**Comment by gohuygo** [comment]
@kclowes I addressed this issue in https://github.com/ethereum/web3.py/pull/1452. Please take a look.

**Comment by voith** [comment]
@fab-spring will it be possible for you to provide `WS_URL_THAT_DOESNT_WORK` or at least the format of the URL? refer https://github.com/ethereum/web3.py/pull/1452#issuecomment-532589911

**Comment by kkx** [comment]
hi, i am having the same issues here, when i try to connect to an unreachable endpoint(correct format but unreachable). seems that in the establishing socket connection step we are not using websocket_timeout as a configurable option inside of asyncio.wait_for
i tested to change this [line](https://github.com/ethereum/web3.py/blob/aa30b3bf97d67b8434cb399c659d8b6425a9bec1/web3/providers/websocket.py#L67)
to 
```
self.ws = await asyncio.wait_for(
                    websockets.connect(
                    uri=self.endpoint_uri, loop=self.loop, **self.websocket_kwargs
                  ),
                    timeout=websocket_timeout
                )
```
and worked for me.

**Comment by kclowes** [comment]
Closing, if this is still an issue, please reopen. The WebsocketProvider will become LegacyWebsocketProvider in v7, and there is a new WebsocketProvider that will be released in v7 as well. You can try out the new WebsocketProvider in v6 by importing WebsocketProviderV2. Docs [here](https://web3py.readthedocs.io/en/stable/providers.html#websocketproviderv2-beta).
