### ISSUE TITLE
Docs for web3.geth.personal.unlockAccount are incorrect wrt to duration parameter

### ISSUE THREAD

**Issue by cygnusv** [ethereum/web3.py#1462]
Current docs for `web3.geth.personal.unlockAccount` say: "If duration is None then the account will remain unlocked indefinitely."

However, from the documentation of Geth's `personal_unlockAccount` (see [here](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_unlockaccount)) and confirmation by inspection of go-ethereum code, it seems that in this case the behaviour is to unlock for 300 seconds. 
In order to unlock indefinitely one should use an explicit duration of 0 seconds. 

I suggest changing that line in the docs to something like: 

> If duration is None then the account will remain unlocked for 300 seconds (which is current default by Geth); if duration is set to 0, the account will remain unlocked indefinitely.

**Comment by cygnusv** [comment]
Can this be closed?

**Comment by kclowes** [comment]
Yep!
