### ISSUE TITLE
Web3 gives inconsistent function matching

### ISSUE THREAD

**Issue by CodeForcer** [ethereum/web3.py#1496]
So I have a series of tests where I'm calling a smart contract with specific input, and checking for correct output. I'm using Web3 and Pytest

I'm using Genache deterministic local Blockchain, and Truffle migrations to bring up the Blockchain. This means that every time I run the tests the Blockchain AND input variables are exactly the same.

But about 10-30% of tests fails with a `Could not identify the intended function` error.

The weird thing is that these errors are NOT consistent, Ie: if I get a few errors I can just run the tests over and over and eventually they will all pass

Example input:
```
UUID b'+2\x07q\x90w\xac"|\xc4\rk\x08\xd3\xf4\xf8'
Seller 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
Buyer 0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0
Amount 3644119000000000
Fee 100
Payment Window 2700
Expiry 2572525888
V 28
R 0xd02763b7a598bd16335fcdab694a2e9c719484f8844ad53d131a56b306cc13e
S 0x7fd1690ce03e41e96acf80c5b4c31bdde3f3d4f00416c74eb1622d4762bc3567
```
Example error message:
```
Could not identify the intended function with name `createEscrow`, positional argument(s) of type `(<class 'bytes'>, <class 'str'>, <class 'str'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'str'>, <class 'str'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `createEscrow`: ['createEscrow(bytes16,address,address,uint256,uint16,uint32,uint32,uint8,bytes32,bytes32)']
Function invocation failed due to no matching argument types.
```

However I ran the tests again straight away and the exact same test passes cleanly.

What can I do here to create a more consistent state for testing? This is bugging me no end

**Comment by pipermerriam** [comment]
Can you provide us with the ABI for the contract you are trying to interact with and the exact function parameters that are being passed in when you get this error as well as the code you are using to invoke the function.  Basically a "minimal reproducible example" https://stackoverflow.com/help/minimal-reproducible-example

**Comment by pipermerriam** [comment]
BTW, it would be best if you provided these both as the values you expect to be using but also by adding a `try/except` in your code where this is being raised and then reporting `contract.abi` and the function arguments used for invocation at runtime.

**Comment by CodeForcer** [comment]
I've figured out the issue and fixed it, so I'm writing here incase any other developers stumble across the same problem.

The cause of the issue is the way that the Pytest library invokes functions during runtime, which wasn't playing nicely with the use of the `functools` package in Web3py.

I was generating some tokens for use in my smart contract like this:
```
import secrets
tradeID = secrets.secrets.token_bytes(16)
```

The invocation of the function to assign this variable was happening inconsistently, seemingly because of slight variations in how fast my computer would run the tests.

Sometimes the Web3 matching function would get passed a 16 byte hex value as an argument, but other times it would get passed `secrets.secrets.token_bytes(16)`, and would then fail.

To further complicate debugging of the issue printing this function to terminal would invoke it, giving the appearance that the Web3 matching function was always receiving the same arguments.

Invoking the function to assign the variables before running tests led to consistent results every test run.

**Comment by pipermerriam** [comment]
Thanks for reporting back on this.  Glad you got it worked out.

You might consider using deterministic randomness in your test suite (`pytest-randomly` does this for you).  This can help considerably when diagnosing [heisenbugs](https://en.wikipedia.org/wiki/Heisenbug)
