### ISSUE TITLE
Help!!!.. How to mine with cpu am getting errors

### ISSUE THREAD

**Issue by mallerkmike** [ethereum/web3.py#1509]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by kclowes** [comment]
@mallerkmike please help us help you by filling out the issue template

**Comment by mallerkmike** [comment]
jj

**Comment by pipermerriam** [comment]
@mallerkmike we'll happily reopen this and do what we can to help if you will please fill in the requested information in the issue.
