### ISSUE TITLE
how can I get the account locked information via python web3?

### ISSUE THREAD

**Issue by ayeteng** [ethereum/web3.py#1516]
* Version: 5.2.2
* Python: 3.6
* OS: osx

There is a command personal.listWallets in geth cli to get the account locked/unlocked status such as below:

```
> personal.listWallets[1]
{
  accounts: [{
      address: "0x175ec34c2b545a4e2195bfbfe03a82b67e594390",
      url: "keystore:///var/geth/keystore/UTC--2018-07-16T09-18-23.192773724Z--175ec34c2b545a4e2195bfbfe03a82b67e594390"
  }],
  status: "Locked",
  url: "keystore:///var/geth/keystore/UTC--2018-07-16T09-18-23.192773724Z--175ec34c2b545a4e2195bfbfe03a82b67e594390"
}

```

How can I get the similar account status from python web3 package or send the same command to fetch the information via python web3?

**Comment by kclowes** [comment]
I don't think there is a good way to get the account locked/unlocked status in this library, unfortunately. Probably the closest thing we have in web3py is [unlockAccount](https://web3py.readthedocs.io/en/stable/web3.geth.html#web3.geth.personal.unlockAccount). But you can always add a PR to add listWallets to our personal geth module. I'm happy to guide you through the process, or I'll get to as soon as I have a bit of time!
