### ISSUE TITLE
Transfer records miss when using Eth_filter()

### ISSUE THREAD

**Issue by Lvzhou48** [ethereum/web3.py#1519]
* Version: 5.3.0
* Python: 3.7
* OS: win

### What was wrong?

`from web3.auto.infura import w3`
`filt = w3.eth.filter({'fromBlock': 8959976, 'toBlock': 8959976})`
`w3.eth.getFilterLogs(filt.filter_id)`

As a noob, I try to use filter like "filt = w3.eth.filter({'fromBlock': 8959976, 'toBlock': 8959976})" to get some ETH transactions from block "8959976", using func: "w3.eth.getFilterLogs(filt.filter_id)". However, among the results, I can only find transaction records whose properity of to_address are contract(.value = 0 Ether), ETH transaction records are disappeared...
Program results are as follows:

[{'address': '0xC77b230F31b517F1ef362e59c173C2BE6540B5E8',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000000000000000000000000346c9731260e9e8c0000',
  'logIndex': 0,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000650d1dbea813b58978a208b1135fcff6fcfc7e4e'),
   HexBytes('0x000000000000000000000000cdef4f34e5ceb46c7c55134cda34273349be65b7')],
  'transactionHash': HexBytes('0xc836d78a165fdc0443e2fec8630924b77f85bce17a881cf72d90f45bdc98afad'),
  'transactionIndex': 2},
 {'address': '0xdAC17F958D2ee523a2206206994597C13D831ec7',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000000000000002361701',
  'logIndex': 1,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000cdddc4165b39e921a152e513bd95b900acece302'),
   HexBytes('0x000000000000000000000000bff5092f83bd810e0926068b89633bf66eaa037b')],
  'transactionHash': HexBytes('0xabb88186cb23de63397e301d4ec33ef53a25416fe5063258e87956c4992f134d'),
  'transactionIndex': 3},
 {'address': '0xC77b230F31b517F1ef362e59c173C2BE6540B5E8',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000cb8ae2f2936c41b0000',
  'logIndex': 2,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000001b4d161a0117f778454034e4169d72cdd2e3a9ab'),
   HexBytes('0x000000000000000000000000cdef4f34e5ceb46c7c55134cda34273349be65b7')],
  'transactionHash': HexBytes('0x88d557e0b0d5194506895cf09624394bf3fd7ceeae930dcc6fbfbfd73ce8e915'),
  'transactionIndex': 4},
 {'address': '0x68E54AF74B22aCACCffA04CcaAd13bE16ED14EAC',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000000000000000000000000000000000019f5eafb00',
  'logIndex': 3,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000008babf0ba311aab914c00e8fda7e8558a8b66de5d'),
   HexBytes('0x0000000000000000000000003d6cb662f312a0903df2e7654a820e6715cbf426')],
  'transactionHash': HexBytes('0xdce3f670c8ff882ae19e922a697ed2aef0c266673593d11e227bc0cfc0c89fdd'),
  'transactionIndex': 5},
 {'address': '0x1988A5D9F8732eF08C46E8a8f8E263De4f52A277',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000001fc3842bd1f071c00000',
  'logIndex': 4,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x00000000000000000000000087dff275773934ccb80f37533015212ad0b1ac7b'),
   HexBytes('0x000000000000000000000000cdef4f34e5ceb46c7c55134cda34273349be65b7')],
  'transactionHash': HexBytes('0x419afc26dc5c403b45853e909b18a334df84fc2c24eb6768f01156e80060c42f'),
  'transactionIndex': 6},
 {'address': '0x9e9801BACE260f58407C15E6e515C45918756E0F',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000000000000e3fcde400',
  'logIndex': 5,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000004e7afc9fdad8f1235f43983dafa8bab704664dbd'),
   HexBytes('0x000000000000000000000000ced1a523e996669f59f371b912cd426427fb3437')],
  'transactionHash': HexBytes('0xa2075e5cfc470f0500fc54abf5ddf5e4d01782ad213e467cb6cc464a1a018771'),
  'transactionIndex': 7},
 {'address': '0x9e9801BACE260f58407C15E6e515C45918756E0F',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000000000000e3fcde400',
  'logIndex': 6,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000004e7afc9fdad8f1235f43983dafa8bab704664dbd'),
   HexBytes('0x000000000000000000000000d8cdcea1e619ed1db542e7579710e14ca83f0084')],
  'transactionHash': HexBytes('0xf95439d4f0bbb77a6d4cf4426c6dced032007af8a72378ef8ed1f1e4fdbc7cc1'),
  'transactionIndex': 8},
 {'address': '0x9e9801BACE260f58407C15E6e515C45918756E0F',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000000000000e3fcde400',
  'logIndex': 7,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000004e7afc9fdad8f1235f43983dafa8bab704664dbd'),
   HexBytes('0x000000000000000000000000b3b2be1ff6e9083fe1cdf0a56eaf9f87f1f59278')],
  'transactionHash': HexBytes('0xb2043dfb2b13e66bf062129086271c386a82edd01edc17cee7af9be613bd9bec'),
  'transactionIndex': 9},
 {'address': '0xdAC17F958D2ee523a2206206994597C13D831ec7',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000000000000059682f00',
  'logIndex': 8,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000a956ed40cadd05fc68ad949a5dc19f1ca7af7761'),
   HexBytes('0x0000000000000000000000004c65d791917f9da00b0780019ab269ce52c9f1e9')],
  'transactionHash': HexBytes('0x56306b2c6f14d4d39644766559e53ebf9f30cc5709f09d6f07fe602d68a5439f'),
  'transactionIndex': 11},
 {'address': '0xE09E2F59De8c2596a6D4fC4c3cB673A8275bC397',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000495b6c26706a980000',
  'logIndex': 9,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000215ca4de799520d0922c3dd6d3b56d17e87f3454'),
   HexBytes('0x0000000000000000000000009f3b11d2c71bca7b50617ae041de85db2fc62212')],
  'transactionHash': HexBytes('0x3892ff96d5ab3a1f765762adaee8673401a8555549037750c88efdf0e45e1804'),
  'transactionIndex': 12},
 {'address': '0xC071aF0e952Aa2813C34BA093FAEeE8ebD4A6696',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000000000000000000000000000000000000000368a8',
  'logIndex': 10,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000e40c3a96c2f1e65c58c327af6faac3e8064d06f9'),
   HexBytes('0x000000000000000000000000e9351e334eb160678585f2ec0ba12a5fcdae69ff')],
  'transactionHash': HexBytes('0xcebd24a6df0735bdc83124e0b6fd9708ead96ebaa269b10ed54a25d431e91cb2'),
  'transactionIndex': 13},
 {'address': '0xD1CEeeeee83F8bCF3BEDad437202b6154E9F5405',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000000000000000000000000000004149a976717abf0',
  'logIndex': 11,
  'removed': False,
  'topics': [HexBytes('0xd4f43975feb89f48dd30cabbb32011045be187d1e11c8ea9faa43efc35282519'),
   HexBytes('0x00000000000000000000000076ca811470ae77a88a5d4626a750a3b505fbf1be')],
  'transactionHash': HexBytes('0xe8503f61f9b7a5489a660fe5a556706c3ad666b68a581c87edf6badb81df19ad'),
  'transactionIndex': 15},
 {'address': '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000001b1ae4d6e2ef5000000',
  'logIndex': 12,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x00000000000000000000000039755357759ce0d7f32dc8dc45414cca409ae24e'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0x1b0793ed15d609f9c5c2fa5b66433719179b435702910f39e7c97fa4f04db41c'),
  'transactionIndex': 16},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3dc',
  'logIndex': 13,
  'removed': False,
  'topics': [HexBytes('0xa2c251311b1a7a475913900a2a73dc9789a21b04bc737e050bbc506dd4eb3488')],
  'transactionHash': HexBytes('0x1b0793ed15d609f9c5c2fa5b66433719179b435702910f39e7c97fa4f04db41c'),
  'transactionIndex': 16},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000001b1ae4d6e2ef50000000000000000000000000000000000000000000000000000028d70b23f95c109bf000000000000000000000000000000000000000000000000000000005dd355b6',
  'logIndex': 14,
  'removed': False,
  'topics': [HexBytes('0x9577941d28fff863bfbee4694a6a4a56fb09e169619189d2eaa750b5b4819995'),
   HexBytes('0x000000000000000000000000000000000000000000000000000000000008e3dc'),
   HexBytes('0x10aed75aa327f09ef87e5bdfaedf498ca260499a251ae5e049ddbd5e1633cd9c'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0x1b0793ed15d609f9c5c2fa5b66433719179b435702910f39e7c97fa4f04db41c'),
  'transactionIndex': 16},
 {'address': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000022b1c8c1227a00000',
  'logIndex': 15,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x00000000000000000000000039755357759ce0d7f32dc8dc45414cca409ae24e'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0x2e31cdd3dc01698a7589258f0910ba88f371f08c933a14dbc494a9aa0268ded1'),
  'transactionIndex': 17},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3dd',
  'logIndex': 16,
  'removed': False,
  'topics': [HexBytes('0xa2c251311b1a7a475913900a2a73dc9789a21b04bc737e050bbc506dd4eb3488')],
  'transactionHash': HexBytes('0x2e31cdd3dc01698a7589258f0910ba88f371f08c933a14dbc494a9aa0268ded1'),
  'transactionIndex': 17},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a232603590000000000000000000000000000000000000000000000022b1c8c1227a000000000000000000000000000000000000000000000000001a68411f9c680bc1000000000000000000000000000000000000000000000000000000000005dd355b6',
  'logIndex': 17,
  'removed': False,
  'topics': [HexBytes('0x9577941d28fff863bfbee4694a6a4a56fb09e169619189d2eaa750b5b4819995'),
   HexBytes('0x000000000000000000000000000000000000000000000000000000000008e3dd'),
   HexBytes('0x9dd48110dcc444fdc242510c09bbbbe21a5975cac061d82f7b843bce061ba391'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0x2e31cdd3dc01698a7589258f0910ba88f371f08c933a14dbc494a9aa0268ded1'),
  'transactionIndex': 17},
 {'address': '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000001b1ae4d6e2ef5000000',
  'logIndex': 18,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d'),
   HexBytes('0x00000000000000000000000039755357759ce0d7f32dc8dc45414cca409ae24e')],
  'transactionHash': HexBytes('0xaa726ba70b88f55bf6db30307fc890b03afd905c74e7d7f7c0076ff2a1dede9b'),
  'transactionIndex': 19},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3e0',
  'logIndex': 19,
  'removed': False,
  'topics': [HexBytes('0xa2c251311b1a7a475913900a2a73dc9789a21b04bc737e050bbc506dd4eb3488')],
  'transactionHash': HexBytes('0xaa726ba70b88f55bf6db30307fc890b03afd905c74e7d7f7c0076ff2a1dede9b'),
  'transactionIndex': 19},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000001b1ae4d6e2ef5000000000000000000000000000000000000000000000000000002b51a63d3ea317952000000000000000000000000000000000000000000000000000000005dd355b6',
  'logIndex': 20,
  'removed': False,
  'topics': [HexBytes('0x773ff502687307abfa024ac9f62f9752a0d210dac2ffd9a29e38e12e2ea82c82'),
   HexBytes('0x000000000000000000000000000000000000000000000000000000000008e3e0'),
   HexBytes('0x10aed75aa327f09ef87e5bdfaedf498ca260499a251ae5e049ddbd5e1633cd9c'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0xaa726ba70b88f55bf6db30307fc890b03afd905c74e7d7f7c0076ff2a1dede9b'),
  'transactionIndex': 19},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3e0',
  'logIndex': 21,
  'removed': False,
  'topics': [HexBytes('0x20fb9bad86c18f7e22e8065258790d9416a7d2df8ff05f80f82c46d38b925acd')],
  'transactionHash': HexBytes('0xaa726ba70b88f55bf6db30307fc890b03afd905c74e7d7f7c0076ff2a1dede9b'),
  'transactionIndex': 19},
 {'address': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000022b1c8c1227a00000',
  'logIndex': 22,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d'),
   HexBytes('0x00000000000000000000000039755357759ce0d7f32dc8dc45414cca409ae24e')],
  'transactionHash': HexBytes('0x730c630a433cb32c766008cadd8622213a34c3583a1d4eecb6e058177963c0cc'),
  'transactionIndex': 20},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3e1',
  'logIndex': 23,
  'removed': False,
  'topics': [HexBytes('0xa2c251311b1a7a475913900a2a73dc9789a21b04bc737e050bbc506dd4eb3488')],
  'transactionHash': HexBytes('0x730c630a433cb32c766008cadd8622213a34c3583a1d4eecb6e058177963c0cc'),
  'transactionIndex': 20},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a232603590000000000000000000000000000000000000000000000022b1c8c1227a00000000000000000000000000000000000000000000000000191bd4482545f249800000000000000000000000000000000000000000000000000000000005dd355b6',
  'logIndex': 24,
  'removed': False,
  'topics': [HexBytes('0x773ff502687307abfa024ac9f62f9752a0d210dac2ffd9a29e38e12e2ea82c82'),
   HexBytes('0x000000000000000000000000000000000000000000000000000000000008e3e1'),
   HexBytes('0x9dd48110dcc444fdc242510c09bbbbe21a5975cac061d82f7b843bce061ba391'),
   HexBytes('0x0000000000000000000000002cedf8de3933d71c77bf3c08b8d1af32545d9b0d')],
  'transactionHash': HexBytes('0x730c630a433cb32c766008cadd8622213a34c3583a1d4eecb6e058177963c0cc'),
  'transactionIndex': 20},
 {'address': '0x39755357759cE0d7f32dC8dC45414CCa409AE24e',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000000000000000008e3e1',
  'logIndex': 25,
  'removed': False,
  'topics': [HexBytes('0x20fb9bad86c18f7e22e8065258790d9416a7d2df8ff05f80f82c46d38b925acd')],
  'transactionHash': HexBytes('0x730c630a433cb32c766008cadd8622213a34c3583a1d4eecb6e058177963c0cc'),
  'transactionIndex': 20},
 {'address': '0x1c040C4ab9accE984D0d4C135576598013950e52',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000004563918244f40000',
  'logIndex': 26,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000ecfe1930ffe9f5828a9aba39276a44d18b2e9aa3'),
   HexBytes('0x0000000000000000000000002c67d1b1d78dcb337a38bf31fa0f69fa207ba4ea')],
  'transactionHash': HexBytes('0x5cc3a5ad795b00fe2bfc4b1c41ab4a4e0d7a2463bddcfb3a69f2f0479db6b9cd'),
  'transactionIndex': 22},
 {'address': '0x102406079234CC1Ea88888e58B88c03467FfA5F3',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000056bc75e2d63100000',
  'logIndex': 27,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x000000000000000000000000c0b5660f68662d2659dbbe9b383e539a0e9044e5'),
   HexBytes('0x000000000000000000000000f0a479406ed88f2461ab081b77516b82cbf9431b')],
  'transactionHash': HexBytes('0x6a2d1cc416df5c38f0fb6aa76be22f1e2fde6acd3815d6d7966e144dd844a354'),
  'transactionIndex': 23},
 {'address': '0x72a2f259b6f691D5c1634d8DC8E1D15db7999811',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x0000000000000000000000000000000000000000000000052663ccab1e1c0000',
  'logIndex': 28,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000007b36da6597cc1a6f15b821bc1890abadf3b7c358'),
   HexBytes('0x000000000000000000000000ec502e95124b01b9ba96182c10b941fda6d0afd7')],
  'transactionHash': HexBytes('0xbc0a2f67a2df025b298bdd531b7014fa0e318ba9a10d0440f47a791c9f7ff995'),
  'transactionIndex': 24},
 {'address': '0x62B9f8741Bf53a6986A5411C0557c30F6F11f3af',
  'blockHash': HexBytes('0xf80dca182f77c1f50f1c062b43d6736d08e97d6a3a869010a0b4c1ca7b750d4a'),
  'blockNumber': 8959976,
  'data': '0x000000000000000000000000000000000000000000000061f5299e1a8adc0000',
  'logIndex': 29,
  'removed': False,
  'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
   HexBytes('0x0000000000000000000000003b47affc3ed2b12f1ade76c1cfc6695d343c8059'),
   HexBytes('0x000000000000000000000000c1bf46efeccba53756fa0e3720823a648354b175')],
  'transactionHash': HexBytes('0x9788bf21b0d07485ef25b570830615415781ff409165ba49752a6fbc02f8db26'),
  'transactionIndex': 26}]

Cute Animal Pictures
![u=3149010975,2632274932 fm=26 gp=0](https://user-images.githubusercontent.com/44354747/69243835-cb51c380-0bde-11ea-8144-cc98cc0ca28b.jpg)

**Comment by kclowes** [comment]
@Lvzhou48 it's because transfers outside of contracts don't have events associated with them. An event needs to be written into a contract in order to get logged. Let me know if that doesn't clear up your question!

**Comment by Lvzhou48** [comment]
@kclowes Thank you for your response! Here comes another question, what should I do if I want to get details of transfers outside of contracts? (maybe some other methods?)

**Comment by kclowes** [comment]
You could try the [getTransactionByBlock](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.getTransactionByBlock) method. What sort of data are you trying to see?

**Comment by Lvzhou48** [comment]
@kclowes I want to see some transfer information(such as : From_address, To_address, value, etc.) outside of contracts, getting Eth transfers for certain exchanges and than make some analysis. I think the getTransactionByBlock method and the getBlockTransactionCount method can help me to solve this task, thank you for your answer!
