### ISSUE TITLE
Update docs to reflect methods that raise errors in v5 instead of returning None

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1522]
* Version: 5.x

### What was wrong?
The docs weren't updated when we started returning a `TransactionNotFound` or `BlockNotFound` error instead of `None` for RPC methods that don't find a transaction. 

### How can it be fixed?
Docs need to be checked and updated for the following methods: 
https://web3py.readthedocs.io/en/stable/v5_migration.html#json-rpc-updates

**Comment by ashish10677** [comment]
Hi. I want to try to contribute to this issue. Can you please assign it to me?

**Comment by kclowes** [comment]
Thanks @ashish10677! Let me know if you have questions!

**Comment by ashish10677** [comment]
@kclowes I had a very silly doubt. In the documentation, these methods: https://web3py.readthedocs.io/en/stable/v5_migration.html#json-rpc-updates , only one of them has a return type of `None` mentioned. Do you want me to include the return type of `TransactionNotFound` or `BlockNotFound` in all?

**Comment by kclowes** [comment]
Yep, let's go ahead and include the return type for all of them.

**Comment by ashish10677** [comment]
@kclowes I have raised a pull request. I am very new to open source contributions. Please guide me if there are any mistakes that I can fix. I will be happy to do it.

**Comment by Swixx** [comment]
@kclowes Can this be closed because of #1527?

**Comment by kclowes** [comment]
@Swixx Yes! Thanks!
