### ISSUE TITLE
[Help!!]About Decentralized Optimization with Blockchains

### ISSUE THREAD

**Issue by ushiwak** [ethereum/web3.py#1553]
* Python: 3.7 (Anaconda3)
* OS: windows10
*Blockchain environment: Ganache
* `pip freeze` output

```
<'Web3' object has no attribute 'web3'>
```

### What was wrong?

I am student studying blockchain and energy.

As a tutorial on research in this field,
http://ecomunsing.com/tutorial-controlling-ethereum-with-python
We are verifying.
In the environment at that time
Since connection of p blockchain and python is not done with web3, the compatibility part must be considered newly, but it is troubled because an error comes out even if it tries many times.

The latest error message is as described above. Please let me know how to move this part smoothly.

*The problem part is the In [4] ~ [6] part of the above site.
```
import json
from web3 import Web3

ganache_url = "HTTP://127.0.0.1:7545"
web3 = Web3(Web3.HTTPProvider(ganache_url))

conn = Web3('HTTP://127.0.0.1:7545')

x_addr = conn.web3.eth.accounts[0]
z_addr = conn.web3.eth.accounts[1]
                          ・
                          ・
                          ・
```

Note: The above code is written in python2. I'm currently testing in the python3 environment, so the code has been rewritten a bit, but there wasn't much difference.

**Comment by kclowes** [comment]
You shouldn't need to `conn =` line. You should just be able to say `web3.eth.accounts[0]`. Let me know if that doesn't fix the issue.

**Comment by ushiwak** [comment]
thank you for your comment

Thanks to you, it moved safely! Thank you
