### ISSUE TITLE
Lacklustre performance using Websockets

### ISSUE THREAD

**Issue by ackhia** [ethereum/web3.py#1555]
* Version: 5.4.0
* Python: 3.7
* OS: osx
* `pip freeze` output

```
astroid==2.2.5
atomicwrites==1.3.0
attrdict==2.0.1
attrs==19.1.0
base58==1.0.3
certifi==2019.9.11
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==2.2.0
cytoolz==0.10.1
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-tester==0.2.0b3
eth-typing==2.1.0
eth-utils==1.8.4
Flask==1.1.1
gunicorn==20.0.4
hexbytes==0.2.0
idna==2.8
importlib-metadata==0.23
inflection==0.3.1
ipfshttpclient==0.4.12
isort==4.3.21
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.2.0
lazy-object-proxy==1.4.2
lru-dict==1.1.6
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.2.0
multiaddr==0.0.8
mypy-extensions==0.4.3
netaddr==0.7.19
openapi-spec-validator==0.2.8
packaging==19.2
parsimonious==0.8.1
pip-check-reqs==2.0.3
pluggy==0.13.0
protobuf==3.11.1
py==1.8.0
pycryptodome==3.9.0
pylint==2.3.1
pyparsing==2.4.2
pyrsistent==0.15.4
pytest==5.0.1
python-dateutil==2.6.0
PyYAML==5.1.2
requests==2.22.0
rlp==1.1.0
semantic-version==2.8.2
six==1.12.0
swagger-spec-validator==2.4.3
swagger-ui-bundle==0.0.5
toolz==0.10.0
typed-ast==1.4.0
typing-extensions==3.7.4.1
urllib3==1.25.6
varint==1.0.2
virtualenv==16.7.5
wcwidth==0.1.7
web3==5.4.0
websockets==8.1
Werkzeug==0.16.0
wrapt==1.11.2
zipp==0.6.0
```

### What was wrong?

I wrote an API which utilises Web3.py but found the performance was slower than expected. I created the following two functionally equivalent (I believe) snippets, one using Web3.py and other using the Javascript Web3 library. They both time how long it takes to send 1000 transactions to my PoA blockchain and receive the transaction hash.

#### Python

```

from web3 import Web3, WebsocketProvider
from web3.middleware import geth_poa_middleware

import time

w3 = Web3(WebsocketProvider('ws://localhost:9545'))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
w3.eth.defaultAccount = w3.eth.accounts[0]

start = time.time()
count = 1000
for i in range(count):   
    w3.eth.sendTransaction({'to': '0xd3CdA913deB6f67967B99D67aCDFa1712C293601', 'from': w3.eth.accounts[0], 'value': 0})
end = time.time()
print(f'Time: {end-start} Tx/s: {count/(end-start)}')
```

#### JS
```

const Web3 = require("web3")


const TRANSACTIONS = 1000

const options = {
  transactionBlockTimeout: 50,
  transactionConfirmationBlocks: 1,
  transactionPollingTimeout: 480,
}

const web3 = new Web3(
  new Web3.providers.WebsocketProvider(
    "ws://localhost:9545"
  ), 
  null,
  options
)

txidsGenerated = 0;
endTime = 0;

async function sendTx() {
  let txs = []
  let accounts = await web3.eth.getAccounts()
  let fromAddr = accounts[0]
  let toAddr = '0x000000000000000000000000000000000000dEaD'
  
  for (let i = 0; i < TRANSACTIONS; i++) {
    tx = web3.eth.sendTransaction({from:fromAddr,to:toAddr, value:0})
    tx.on('transactionHash', function(){
        txidsGenerated++;
        if(txidsGenerated == TRANSACTIONS){
            endTime = Math.floor(new Date() / 1000)
        }
    })
    txs.push(tx)
  }
  console.log('TXs sent')
  await Promise.all(txs)
}

async function run() {
  startTime = Math.floor(new Date() / 1000)
  await sendTx()
  let timeTaken = endTime - startTime
  let txSec = TRANSACTIONS / timeTaken
  console.log(`Starting time: ${startTime}`)
  console.log(`Ending time: ${endTime}`)
  console.log(`Time taken: ${timeTaken} secs`)
  console.log(`Transactions sent: ${TRANSACTIONS}`)
  console.log(`Tx/Sec: ${txSec}`) 
  web3.currentProvider.connection.close()
}


run()

```
This is the output:

```
MacBook-Pro-4:python jon$ python txs.py 
Time: 25.330008029937744 Tx/s: 39.47886628453065
MacBook-Pro-4:python jon$ node ../benchmark/txs.js 
TXs sent
Starting time: 1576986065
Ending time: 1576986073
Time taken: 8 secs
Transactions sent: 1000
Tx/Sec: 125
```
So the Javascript version can send 125 tx/sec while the python version only produces 39.

Is there anything I can do to improve performance? I looked at the Websocket provider and it seems to be using asyncio although the performance may suggest the requests are being send in serial?

### How can it be fixed?

There is nothing really to fix, I'm just looking for suggestions as to how I may be able to improve the performance of my API.

Thanks

**Comment by coccoinomane** [comment]
@ackhia Did you eventually discovered why web3.py is so slow with a websocket?

This could be related to https://github.com/ethereum/web3.py/issues/2007

**Comment by ackhia** [comment]
I did yes @coccoinomane , it's because Web3.py's Websocket connector blocked the process until the server (Ethereum Node) responds. You can switch to HTTP for better performance. If you can't do that, another option is to use something like RQ to send the requests from many processes.

**Comment by coccoinomane** [comment]
Thanks @ackhia 🙏

I guess the reason for the block is that websockets are meant to listen to events, while if you need to send transactions you're better off using an HTTP endpoint.

After you switched to HTTP, did you see a performance comparable with Javascript?

Cheers,
Cocco

**Comment by ackhia** [comment]
@coccoinomane  Hello! Yes you should see comparable performance with HTTP. I believe the reason it is slow is because websockets is an async library and web3 is a sync library. If you try to wrap one in another the app will lock every time you try to call your async function and massively slow performance.

**Comment by coccoinomane** [comment]
> @coccoinomane Hello! Yes you should see comparable performance with HTTP. I believe the reason it is slow is because websockets is an async library and web3 is a sync library. If you try to wrap one in another the app will lock every time you try to call your async function and massively slow performance.

I see, thanks @ackhia!

I wonder whether web3.py 6.0.0 fixes this.

Anyhow, I use websockets to do scan the mempool so hopefully I should be fine with web3.py... or at least I think so 🤞

Cheers,
Cocco

**Comment by ackhia** [comment]
> > @coccoinomane 
> I wonder whether web3.py 6.0.0 fixes this.

I'm not sure actually, I haven't used library for many years. Good luck with the project anyway. Sound interesting!

**Comment by kclowes** [comment]
We have a new `WebsocketProvider` (currently available in v6 as `WebsocketProviderV2`), which is more performant. Closing since the current `WebsocketProvider` will soon become  deprecated.
