### ISSUE TITLE
How to transact two variable values?

### ISSUE THREAD

**Issue by ushiwak** [ethereum/web3.py#1561]
* Python: 3.7 (Anaconda 3, Using Jupyter notebook)
* OS: Windows10
* Samrtcontract is deproyed by REMIX
*Blockchain: Ganache

・I want to store x (and i) calculated in python in a smart contract, but I get such an error.
Please tell me how rewriting works
### Smartcontract 
```
　　　　　　　　　　　　　・
　　　　　　　　　　　　　・
　　　　　　　　　　　　　・
unction submitValue (int256 myGuess, uint16 myiteration) public{

    	assert(! problemSolved);
    	assert(iteration == myiteration);

    	if (waiting[msg.sender]){
            // If we are still waiting for this sender, go ahead with the assignment.
            if (msg.sender == whitelist[0]){
                x = myGuess;
            } else if (msg.sender == whitelist[1]){
            	s = rho * A * B * (myGuess - z);
                z = myGuess;
            } else {revert();}
            waiting[msg.sender] = false;
    	} else { revert(); }
　　　　　　　　　　　　・
　　　　　　　　　　　　・
　　　　　　　　　　　　・
```
### python code
```
　　　　　　　　　　　　・
　　　　　　　　　　　　・
　　　　　　　　　　　　・
rho = contract.functions.rho().call()
c   = contract.functions.c().call()

i = 0
resultDf.loc[0,:] = [0,0,0]

for i in range(1, 20):
    ### X LOCAL CALCULATION: need to retrieve z and y
    z =contract.functions.z().call() 
    y = contract.functions.y().call()
    x = int( 1/(2.+rho) * (c*rho - y - rho*z) )
    # Submit the x-update    
    tx_hash = contract.functions.submitValue("x","i").transact()
　　　　　　　　　　　　・
　　　　　　　　　　　　・
　　　　　　　　　　　　・
```
### Error message
```
Could not identify the intended function with name `submitValue`, positional argument(s) of type `(<class 'str'>, <class 'str'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `submitValue`: ['submitValue(int256,uint16)']
Function invocation failed due to no matching argument types.
```

### Supplementary information
This code refers to the following site for the purpose of deepening my understanding of blockchain.
The site uses JSON-RPC to link python and blockchain.
However, JSON-RPC is not currently supported, so I rewrote some of the code.

**Comment by kclowes** [comment]
@ushiwak it looks like the ABI requires calling `contract.functions.submitValue` with an `int256` and a `uint16`. In your code above you are calling the function with two string arguments. It looks like maybe you want to say `contract.functions.submitValue(x, i).transact()`. Closing because this is not a web3 issue, but feel free to reopen if I am mistaken!

**Comment by ushiwak** [comment]
Dear kclowes,

I deeply thank you for your valuable comments and suggestions.
I have tried your methods, but it doesn't work correctly. 
As you mentioned, now I think that my problem is not on web3 but solidity.
I will ask a solidity community the same question. 

Sincerely,
ushiwak
