### ISSUE TITLE
Support Solidity v0.6.x

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1566]
* Version: 5.x

### What was wrong?

Placeholder PR to check web3 support for Solidity v0.6. I'll fill in what needs to be done when I dig in, but if anyone knows something that needs to be changed, feel free to comment on this issue. 

https://solidity.readthedocs.io/en/v0.6.1/060-breaking-changes.html

PR #1565 has already begun to address the new `receive` keyword.

**Comment by mswilkison** [comment]
Do you all have an estimate as to when v0.6 support will land in web3.py? Thanks!

**Comment by kclowes** [comment]
@mswilkison it's not on the immediate docket, but knowing there is interest helps. It looks like supporting `receive()` is the feature you need? Anything else that would be handy?

**Comment by vzotova** [comment]
@kclowes thank you, only `receive()`, other features that we use are already working with latest version of web3.py

**Comment by kclowes** [comment]
@mswilkison (or anyone else) On a quick glance, I think we can close this? Are there other v0.6.x features we still need to support?

**Comment by vzotova** [comment]
I think it can be closed, thank you. We are using 0.7.x for now and everything works good
