### ISSUE TITLE
`eth_getCode` gets initiated after `eth_call` fails

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/web3.py#1567]
* Version: 5.4.0
* Python: 3.7.5
* OS: OS X Catalina
* `pip freeze` output

Relevant libraries:

```
ethereum==2.3.2
eth-abi==2.1.0
web3==5.4.0 # eth-tester version
```

### What was wrong?

I'm using a custom `web3.py` provider and I've noticed that after a failed `eth_call` statement an `eth_getCode` rpc call is made immediately after. In particular the `eth_call` statement failed for a function with a `uint256` return value by returning `0x`. Just for clarification I'm not reporting the failure of the call just asking about why the `eth_getCode` call is issued afterwards.

The error was: `web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?`. The sub-error is decoding the return value `eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes`.

### How can it be fixed?

-

**Comment by kclowes** [comment]
@Pet3ris I think this is the line that's making the call: https://github.com/ethereum/web3.py/blob/master/web3/contract.py#L1450 So behavior is expected after all. I am going to close, but feel free to reopen if you want to continue the conversation!

**Comment by Pet3ris** [comment]
@kclowes - thanks, makes sense now !

**Comment by pipermerriam** [comment]
@kclowes something to keep an eye out for but nothing that needs to be acted on now.  Maybe there's a case where `eth_call` is supported but `eth_getCode` isn't...  In that case it would be ideal to be able to disable this follow up check.  It could be something as simple as an environment variable and/or a toggle-able property on the `eth` module.

**Comment by kclowes** [comment]
@pipermerriam Yeah, I like that. @Pet3ris, is that `getCode` call causing you problems?

**Comment by Pet3ris** [comment]
@kclowes not at all - in fact it actually helped me uncover a bug :).

I was simply wondering to understand whether my provider was triggering this call by accident cause it didn't make sense!
