### ISSUE TITLE
Export type hints

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#1582]
* Version: 5.5.1
* Python: 3.7
* OS: osx

### What was wrong?

It seems like currently the type information is not announced properly and won't be used by `mypy` in packages depending on `web3`.

See https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages for more infos.

### How can it be fixed?

Like described, typing infos need to be announced via PEP561

**Comment by kclowes** [comment]
This has been released with 5.6.0 @palango! Thanks!
