### ISSUE TITLE
Getting timeout when trying to connect using websocket

### ISSUE THREAD

**Issue by rranjan3** [ethereum/web3.py#1584]
* Version: 5.4.0
* Python: 3.6.8
* OS: linux

Getting timeout when `isConnected()` is called over a websocket. The error would also occur on filter is the `isConnected()` call were removed.
Other clients(`wscat`) are able to get a connection over the same socket and receive events.

Here's the code where `isConnected()` is called.

```
import time
import json
from web3 import Web3, HTTPProvider, WebsocketProvider
contract_address = '0x6891c4e1171Fb5ec0B77734E49c62077066FBB4D'
wallet_address = '0x8093d4d4C6eFea785eaeba5430Bb62574C113214'

w3 = Web3(WebsocketProvider('ws://localhost:22002/'))
print("Connection established : ", w3.isConnected())

contractDetails = json.load(open("build/contracts/MyContract.json"))
contract = w3.eth.contract(address = contract_address, abi = contractDetails.get('abi'))

evt_filter = contract.events.BroadcastEvent.createFilter(fromBlock='latest') #-- latest for my event

while True :
evnts = evt_filter.get_new_entries()
if len(evnts) > 0:
print(evnts)
```

Here's the stack trace - 

```
Traceback (most recent call last):
File "./event_listener.py", line 16, in <module>
print("Connection established : ", w3.isConnected())
File "/home/rranjan/.local/lib/python3.6/site-packages/web3/main.py", line 258, in isConnected
return self.provider.isConnected()
File "/home/rranjan/.local/lib/python3.6/site-packages/web3/providers/base.py", line 102, in isConnected
response = self.make_request(RPCEndpoint('web3_clientVersion'), [])
File "/home/rranjan/.local/lib/python3.6/site-packages/web3/providers/websocket.py", line 137, in make_request
return future.result()
File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in getresult
raise self._exception
File "/home/rranjan/.local/lib/python3.6/site-packages/web3/providers/websocket.py", line 125, in coro_make_request
timeout=self.websocket_timeout
File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by kclowes** [comment]
@rranjan3 I am not sure what is going on here. I'm unable to replicate with your code. It's strange that you're able to connect using `wscat`, but not web3 which does indicate that there may be a bug in web3. You might try connecting in new environment or upgrading to the most recent web3 (5.5.1). Let me know if neither of those options work for you and I can keep looking.

**Comment by realjohnward** [comment]
@kclowes @rranjan3 
I was only able to reproduce the error when using localhost:22002 as the websocket. Below is the listening port's output when running the script:
`Client connected`
`{"jsonrpc": "2.0", "method": "web3_clientVersion", "params": [], "id": 0}`
`Disconnected (code: 1000, reason: "")`

I tested WebsocketProvider with an Infura websocket and it works fine.

**Comment by ItayPodhajcer** [comment]
Having the exact same issue when trying to connect to a remote Hyperledger Besu node through the default 8546 port.
`wscat` works without any issues.

**Comment by kclowes** [comment]
Closing - `WebsocketProvider` will become `LegacyWebsocketProvider` in v7 and we will deprecate eventually. Try out the new `WebsocketProviderV2` in v6.
