### ISSUE TITLE
trouble in installing web3 using pip

### ISSUE THREAD

**Issue by hindhanadi** [ethereum/web3.py#1598]
hi guys, I have been trying to install web3 using the command pip install web3 but it doesn't work !!!, I have tried so many solutions but nothing works , here is the error that I have, I hope guys you can help me.
at the bigging, it gives this and then right after it just continues to give me red lines  of errors  
"""Collecting web3
  Using cached web3-5.6.0-py3-none-any.whl (459 kB)
Collecting eth-account<0.5.0,>=0.4.0
  Using cached eth_account-0.4.0-py3-none-any.whl (26 kB)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (0.2.0)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied: ipfshttpclient<1,>=0.4.12 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (0.4.12)
Requirement already satisfied: jsonschema<4.0.0,>=3.0.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (3.2.0)
Requirement already satisfied: protobuf<4,>=3.10.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (3.11.3)
Requirement already satisfied: websockets<9.0.0,>=8.1.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (8.1)
Collecting eth-utils<2.0.0,>=1.8.4
  Using cached eth_utils-1.8.4-py3-none-any.whl (23 kB)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (2.23.0)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (2.2.1)
Requirement already satisfied: pypiwin32>=223; platform_system == "Windows" in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from web3) (223)
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Collecting eth-keys<0.3.0,>=0.2.1
  Using cached eth_keys-0.2.4-py3-none-any.whl (24 kB)
Collecting eth-rlp<1,>=0.1.2
  Using cached eth_rlp-0.1.2-py3-none-any.whl (6.5 kB)
Collecting rlp<2,>=1.0.0
  Using cached rlp-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting attrdict<3,>=2.0.0
  Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.9.7)
Requirement already satisfied: six in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from ipfshttpclient<1,>=0.4.12->web3) (1.13.0)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from ipfshttpclient<1,>=0.4.12->web3) (0.0.9)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (0.15.7)
Requirement already satisfied: attrs>=17.4.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (19.3.0)
Requirement already satisfied: setuptools in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (46.0.0)
Collecting cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"
  Using cached cytoolz-0.10.1.tar.gz (475 kB)
Requirement already satisfied: idna<3,>=2.5 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2019.11.28)
Requirement already satisfied: pywin32>=223 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from pypiwin32>=223; platform_system == "Windows"->web3) (227)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: varint in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (1.0.2)
Requirement already satisfied: netaddr in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (0.7.19)
Requirement already satisfied: base58 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (2.0.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\toshiba\appdata\local\programs\python\python38-32\lib\site-packages (from cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"->eth-utils<2.0.0,>=1.8.4->web3) (0.10.0)
Building wheels for collected packages: lru-dict, cytoolz
  Building wheel for lru-dict (setup.py): started
  Building wheel for lru-dict (setup.py): finished with status 'error'
  Running setup.py clean for lru-dict
  Building wheel for cytoolz (setup.py): started
  Building wheel for cytoolz (setup.py): finished with status 'error'
  Running setup.py clean for cytoolz
Failed to build lru-dict cytoolz
Installing collected packages: cytoolz, eth-utils, eth-keys, rlp, hexbytes, eth-rlp, eth-keyfile, eth-abi, attrdict, eth-account, lru-dict, web3
    Running setup.py install for cytoolz: started
    Running setup.py install for cytoolz: finished with sta""""

**Comment by kclowes** [comment]
@hindhanadi It's hard to tell without the whole stack trace, but it looks a lot like #1578 to me. I'm going to close but feel free to reopen if the solution in #1578 doesn't work for you.
