### ISSUE TITLE
I am new to python! need help with running this. Any body can help?

### ISSUE THREAD

**Issue by MSadriAghdam** [ethereum/web3.py#1599]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by cburgdorf** [comment]
@MSadriAghdam I think you forgot to mention the issue you are seeing. The placeholder in the issue template were meant to be filled out so that people can help you.

**Comment by kclowes** [comment]
Closing, but feel free to reopen or open another issue with some details if you still need help @MSadriAghdam!
