### ISSUE TITLE
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call func return data b'' for output_types ['uint256'] due to `geth` version

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1606]
For clearity I am using two different ubuntu machines as follows, please note that both machines are sync to my private black chain and working on the same smart-contract: 

Contract call was working on `1.9.9` where it starts not to work on `1.9.13`.

=> **ubuntu-a** uses: 
```
- web3==5.7.0`, Python `3.6.8`, OS: `linux` on `venv`
- geth Version: 1.9.9-stable

Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

-------

=> **ubuntu-b** uses: 
```
- On `web3==5.7.0`, Python `3.7.5` on `venv` I have also tried for Python `3.6.8`
- geth Version: 1.9.13-unstable

Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

----

Following function call works using `web3py` on **ubuntu-a** which has (geth Version: 1.9.9-stable): but when I upgrade the geth version to geth Version: 1.9.13-unstable it starts not to work.

```
contract.functions.getReceivedStorageDeposit(b'97fc72c7b24e499b79cb9e2d42300ad1').call()
```

where the function has the following signature:

```solidity
function getReceivedStorageDeposit(bytes32 sourceCodeHash)
    external
    view
    whenProviderRegistered returns (uint256)
```

------

On **ubuntu-b**, I get the following error message:

```
Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 1432, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "koo.py", line 5, in <module>
    eBlocBroker.functions.getReceivedStorageDeposit(b"").call()
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 904, in call
    **self.kwargs
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 1454, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getReceivedStorageDeposit return data b'' for output_types ['uint256']
```

**[Q]** What may cause this error? How can I fix it?

**Comment by kclowes** [comment]
@avatar-lavventura I was looking at Geth [release notes](https://github.com/ethereum/go-ethereum/releases) for 1.9.12, and I don't think this is your issue, but does this apply to you: 

> One small breaking change in the release is that eth_call will not default to your first account any more if you don't explicitly specify a sender.

**Comment by avatar-lavventura** [comment]
I actually use `Geth` only to start my node, and all the other operations is done through `Web3.py`. 

One my `call()`s I didn't used `from` but `msg.sender` is not used within the function I am having issue.

```
    function getReceivedStorageDeposit(address _provider, address requester, bytes32 sourceCodeHash)
        external
	view
        whenProviderRegistered
        returns (uint256)
    {
        return providers[_provider].storageInfo[requester][sourceCodeHash].received;
    }
```

**Comment by avatar-lavventura** [comment]
@kclowes: I feel like you have a good catch. I have asked the same issue on `go-ethereum` and @karalabe told me the same issue you mentioned (https://github.com/ethereum/go-ethereum/issues/20785#issuecomment-601590678). I will debug more and let you know.

**Comment by avatar-lavventura** [comment]
Solved in this issue, it was related to update on `geth` as @kclowes mentioned: (https://github.com/ethereum/go-ethereum/issues/20785#issuecomment-601590678)

@karalabe
> I have a hunch. We've merged in a change to eth_call so that it will not default to your first account if you don't specify any sender (rather to 0x00). This was made to make the operations more predictable in different environments.
