### ISSUE TITLE
Better document how to set up a web3 instance

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1609]
### What was wrong?

There are many different ways to set up a web3 instance. For example:
```
from web3.auto import w3

from web3 import IPCProvider, Web3
w3 = Web3(IPCProvider('path/to/ipc/file.ipc'))

from web3 import WebsocketProvider, Web3
w3 = Web3(WebsocketProvider('ws://localhost:8546'))

from web3 import HTTPProvider, Web3
w3 = Web3(HTTPProvider('http://localhost:8545'))

from web3.auto.infura import w3

from web3.auto.infura.rinkeby import w3

...
```

But with each of these options comes certain configuration that needs to happen. 

For example, `web3.auto` requires either an environment variable set, a local node running on mainnet, or an http provider running on localhost:8545. But you have to go to a different page in the docs to see that.

Similarly, if you are trying to connect to a local geth node over HTTP or Websockets, you need to start geth with the `--rpc` or `--ws` flag, respectively, in order to connect. 

It would be nice if the docs mentioned these nuances.

**Comment by marcgarreau** [comment]
Double-checking that its on your radar: I found the [Providers](https://web3py.readthedocs.io/en/stable/providers.html) docs surprisingly robust. I do think it could stand to be higher up in the table of contents, though, as its the first thing you'll need to configure before being able to use the lib. 

I wouldn't expect newcomers to guess that there's important setup information in the `Providers` link in the middle of a long list of other links, but I think the `Quickstart` and `Overview` sections do a reasonably good job of highlighting the concept.

**Comment by kclowes** [comment]
Yes, I agree, the `Providers` docs are really good! And could stand to be higher up the list. Maybe this stuff really belongs in the troubleshooting docs. If `w3.isConnected() == False`, try these things depending on how you're trying to connect

**Comment by marcgarreau** [comment]
👍 I'll make some tweaks and ping you for feedback.

**Comment by marcgarreau** [comment]
@kclowes up for debate: https://github.com/ethereum/web3.py/pull/1619

Re: `If w3.isConnected() == False, try these things depending on how you're trying to connect`,
I only had a couple thoughts that I dropped into a new Troubleshooting section. Let me know if you had additional ideas in mind.
