### ISSUE TITLE
Document manual contract instantiation vs ethpm

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1611]
@njgheorghita What do you think about adding a section to the docs comparing/contrasting manual contract instantiation and using ethpm? And maybe describing when you'd want to use one over another.

**Comment by njgheorghita** [comment]
@kclowes Sounds like a good idea to me! Has there been any confusion around the difference b/w the two methods? I'm happy to write something up... are you thinking it belongs in the `Contracts` section of the docs?

**Comment by kclowes** [comment]
Awesome! Piper pointed out [this tutorial](https://consensys.net/blog/blockchain-development/how-to-send-money-using-python-a-web3-py-tutorial/), and was thinking about how there are multiple ways to do things in web3py, and how all of them aren't necessarily easy to find, one of which being manual contract instantiation vs using ethpm. So I haven't heard of any specific confusion. I was thinking either `Contracts` or `Examples`, but don't have a strong preference which!
