### ISSUE TITLE
Contract Fallback functions undocumented

### ISSUE THREAD

**Issue by MatthiasLohr** [ethereum/web3.py#1638]
* Version: 5.9.0

According to https://web3py.readthedocs.io/en/stable/contracts.html#fallback-function, there is some support for fallback functions for interacting with a smart contract. Is there any documentaton on how to use this? I'm also not possible to figure this out by reading the code. Some infos would be nice.

Best regards
Matthias

**Comment by marcgarreau** [comment]
Thanks for pointing out the limited documentation here @MatthiasLohr. If there is one in the contract, the fallback function is available directly on the contract instance. For example:

```
# calling contract functions:
example_contract.functions.do_something().transact()

# calling fallback function:
example_contract.fallback.transact()
```

New to solidity 0.6.X, there's also a [`receive` keyword](https://solidity.readthedocs.io/en/latest/060-breaking-changes.html?highlight=receive#semantic-and-syntactic-changes), which is another type of fallback function. This is already supported in web3, but could also use some documentation. I'll get to this Soon™ if someone doesn't beat me to it.

**Comment by MatthiasLohr** [comment]
Thanks for replying so quickly!

How to set the fallback function? Just `example_contract.fallback.transact = mytransact`?

**Comment by marcgarreau** [comment]
Actually, the contract API will figure that out for you. Maybe a more long-winded example will help:
```
import json

# create/compile a contract in Remix, then copy/paste the abi and bytecode it outputs:
abi = json.loads("...")
bytecode = "..."

# deploy the contract via its constructor function:
ExampleContract = w3.eth.contract(abi=abi, bytecode=bytecode)
tx_hash = ExampleContract.constructor().transact()

# when the receipt returns, the contract deployment was successful and is available for use:
tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

# get the instance of the deployed contract:
example_contract = w3.eth.contract(address=tx_receipt.contractAddress, abi=abi)

# web3 will parse the ABI and know which functions (including fallbacks) are available:
example_contract.functions.do_something().transact()
example_contract.fallback.transact()
```

If you're interacting with an existing contract on the network, obviously you don't need to deploy it again, and can just skip to the last couple lines in the example. Etherscan can be a good place to find contract addresses and ABIs. ([The DAI contract](https://etherscan.io/address/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359#code), for example.)

Does that help? Let me know if anything still unclear.

**Comment by MatthiasLohr** [comment]
Sorry, maybe I'm just too stupid for that.

The main reason why I'm asking is the fallback for estimateGas. I'm working on a contract method where estimateGas always fails (no idea why). I thought this fallback option might help to introduce a custom estimateGas method which is able to catch and handle the error, e.g. by setting a default gas limit.

**Comment by marcgarreau** [comment]
Ah, I understand the confusion now. `fallback` in this case is a specific type of function in solidity, so cannot be used to do things like handle estimateGas failures. You _can_ customize the way that gas price is calculated in web3: https://web3py.readthedocs.io/en/stable/gas_price.html.

This issue related to adding more documentation around fallback functions is appropriate, but I'd prefer not to debug gas price issues within the same thread. Please open a new issue with the estimateGas error and related context if you'd like additional help with that.

**Comment by MatthiasLohr** [comment]
Sure, out of scope. Just last comment: My question is not related to gas *price*, but gas estimation.
