### ISSUE TITLE
Feature Request: Expose RPC client until batching is done

### ISSUE THREAD

**Issue by ahonnecke** [ethereum/web3.py#1640]
Until https://github.com/ethereum/web3.py/issues/832 is worked out, it would be nice to have the ability to get the RPC client directly such that one could send batch requests but still leverage web3 for the decoding.

The equivalent of:
`
curl -X POST --data \
'[{"jsonrpc":"2.0","id":"1","method":"eth_getBlockByNumber","params":["0x1b4", true]},{"jsonrpc":"2.0","id":"2","method":"eth_getBlockByNumber","params":["0x1b5", true]}]'
`

**Comment by kclowes** [comment]
Batching is done as of #3370. Closing.
