### ISSUE TITLE
PyPi Document format problem

### ISSUE THREAD

**Issue by 99Kies** [ethereum/web3.py#1643]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

<https://pypi.org/project/web3/1.3.0/>
PyPi Document format problem, Markdown seems to have failed.
![image](https://user-images.githubusercontent.com/45918704/81358591-90e6cf00-9109-11ea-91c8-79deebe7ad0f.png)
### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by marcgarreau** [comment]
Thanks for reporting. 1.3.0 is an old, unsupported version, though. We're up to [v5.9.0](https://pypi.org/project/web3/5.9.0/) and all the latest releases are properly formatted.
