### ISSUE TITLE
Upgrade Sphinx to v3.0+

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1644]
* Version: 5.9+

### What was wrong?
The Sphinx dependency wasn't pinned and when Sphinx 3.0 came out some of our doctests broke. It's currently pinned to  >=2.4.4,<3. 

### How can it be fixed?
Pin Sphinx between 3.0 and 4, and then fix any failing tests.

**Comment by rajeev29five** [comment]
I would like to work on this.

**Comment by dbfreem** [comment]
This issue appears to already be fixed in this [PR](https://github.com/ethereum/web3.py/pull/1977/files). Sphinx was upgraded in the [setup.py](https://github.com/ethereum/web3.py/blob/master/setup.py#L27). This issue can probably be closed.

**Comment by kclowes** [comment]
Yep, you're right @dbfreem. Closing!
