### ISSUE TITLE
ValueError with eth.contract()

### ISSUE THREAD

**Issue by brschkv** [ethereum/web3.py#1662]
* Version: 5.10.0
* Python: 3.8
* OS: ubuntu 20.04
* `pip freeze` output

```
attrs==19.3.0
backcall==0.1.0
base58==2.0.0
bitarray==1.2.2
bleach==3.1.5
certifi==2020.4.5.1
chardet==3.0.4
cycler==0.10.0
cytoolz==0.10.1
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.2
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.1.2
eth-typing==2.2.1
eth-utils==1.9.0
hexbytes==0.2.0
idna==2.9
ipfshttpclient==0.4.13.2
ipykernel==5.3.0
ipython==7.14.0
ipython-genutils==0.2.0
jedi==0.17.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyterlab==2.1.3
jupyterlab-server==1.1.5
kiwisolver==1.2.0
lru-dict==1.1.6
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
multiaddr==0.0.9
nbconvert==5.6.1
nbformat==5.0.6
netaddr==0.7.19
notebook==6.0.3
numpy==1.18.4
packaging==20.4
pandas==1.0.3
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pkg-resources==0.0.0
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pycryptodome==3.9.7
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.1
requests==2.23.0
rlp==1.2.0
Send2Trash==1.5.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
tqdm==4.46.0
traitlets==4.3.3
urllib3==1.25.9
varint==1.0.2
wcwidth==0.1.9
web3==5.10.0
webencodings==0.5.1
websockets==8.1
```

### What was wrong?
Code:
```python
import json
import web3

def get_contract(abi_file: str, address: str):
    with open(abi_file) as f:
      abi = json.load(f)
    address = w3.toChecksumAddress(address)
    contract = w3.eth.contract(address=address, abi=abi)
    return contract

w3 = web3.Web3(web3.WebsocketProvider("wss://ropsten.infura.io/ws/v3/<my_api_key>"))
assert w3.isConnected()

comptroller = get_contract('Comptroller.json', '0xe03718b458a2e912141cf3fc8dab648362ee7463')
```

Json source of the contract can be found here: https://compound.finance/docs/abi/ropsten/Comptroller

Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.virtualenvs/liquidation/lib/python3.8/site-packages/eth_utils/applicators.py in apply_formatters_to_dict(formatters, value)
     83             try:
---> 84                 yield key, formatters[key](item)
     85             except (TypeError, ValueError) as exc:

~/.virtualenvs/liquidation/lib/python3.8/site-packages/web3/_utils/normalizers.py in normalize_abi(abi)
    242         abi = json.loads(abi)
--> 243     validate_abi(cast(ABI, abi))
    244     return cast(ABI, abi)

~/.virtualenvs/liquidation/lib/python3.8/site-packages/web3/_utils/validation.py in validate_abi(abi)
     84     if duplicates:
---> 85         raise ValueError(
     86             'Abi contains functions with colliding selectors. '

ValueError: Abi contains functions with colliding selectors. Functions admin(), admin(), admin() have selector 0xf851a440 and
comptrollerImplementation(), comptrollerImplementation(), comptrollerImplementation() have selector 0xbb82aa5e and
pendingAdmin(), pendingAdmin(), pendingAdmin() have selector 0x26782247 and
pendingComptrollerImplementation(), pendingComptrollerImplementation(), pendingComptrollerImplementation() have selector 0xdcfbc0c7 and
_setCloseFactor(uint256), _setCloseFactor(uint256) have selector 0x317b0b77 and
_setCollateralFactor(address,uint256), _setCollateralFactor(address,uint256) have selector 0xe4028eee and
_setLiquidationIncentive(uint256), _setLiquidationIncentive(uint256) have selector 0x4fd42e17 and
_setMaxAssets(uint256), _setMaxAssets(uint256) have selector 0xd9226ced and
_setPriceOracle(address), _setPriceOracle(address) have selector 0x55ee1fe1 and
_supportMarket(address), _supportMarket(address) have selector 0xa76b3fda and
accountAssets(address,uint256), accountAssets(address,uint256) have selector 0xdce15449 and
borrowAllowed(address,address,uint256), borrowAllowed(address,address,uint256) have selector 0xda3d454c and
borrowVerify(address,address,uint256), borrowVerify(address,address,uint256) have selector 0x5c778605 and
checkMembership(address,address), checkMembership(address,address) have selector 0x929fe9a1 and
closeFactorMantissa(), closeFactorMantissa() have selector 0xe8755446 and
enterMarkets(address[]), enterMarkets(address[]) have selector 0xc2998238 and
exitMarket(address), exitMarket(address) have selector 0xede4edd0 and
getAccountLiquidity(address), getAccountLiquidity(address) have selector 0x5ec88c79 and
getAssetsIn(address), getAssetsIn(address) have selector 0xabfceffc and
isComptroller(), isComptroller() have selector 0x007e3dd2 and
liquidateBorrowAllowed(address,address,address,address,uint256), liquidateBorrowAllowed(address,address,address,address,uint256) have selector 0x5fc7e71e and
liquidateBorrowVerify(address,address,address,address,uint256,uint256), liquidateBorrowVerify(address,address,address,address,uint256,uint256) have selector 0x47ef3b3b and
liquidateCalculateSeizeTokens(address,address,uint256), liquidateCalculateSeizeTokens(address,address,uint256) have selector 0xc488847b and
liquidationIncentiveMantissa(), liquidationIncentiveMantissa() have selector 0x4ada90af and
markets(address), markets(address) have selector 0x8e8f294b and
maxAssets(), maxAssets() have selector 0x94b2294b and
mintAllowed(address,address,uint256), mintAllowed(address,address,uint256) have selector 0x4ef4c3e1 and
mintVerify(address,address,uint256,uint256), mintVerify(address,address,uint256,uint256) have selector 0x41c728b9 and
oracle(), oracle() have selector 0x7dc0d1d0 and
redeemAllowed(address,address,uint256), redeemAllowed(address,address,uint256) have selector 0xeabe7d91 and
redeemVerify(address,address,uint256,uint256), redeemVerify(address,address,uint256,uint256) have selector 0x51dff989 and
repayBorrowAllowed(address,address,address,uint256), repayBorrowAllowed(address,address,address,uint256) have selector 0x24008a62 and
repayBorrowVerify(address,address,address,uint256,uint256), repayBorrowVerify(address,address,address,uint256,uint256) have selector 0x1ededc91 and
seizeAllowed(address,address,address,address,uint256), seizeAllowed(address,address,address,address,uint256) have selector 0xd02f7351 and
seizeVerify(address,address,address,address,uint256), seizeVerify(address,address,address,address,uint256) have selector 0x6d35bf91 and
transferAllowed(address,address,address,uint256), transferAllowed(address,address,address,uint256) have selector 0xbdcdc258 and
transferVerify(address,address,address,uint256), transferVerify(address,address,address,uint256) have selector 0x6a56947e

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-96-0e6ce4457ea2> in <module>
----> 1 comptroller = get_contract('Comptroller.json', '0xe03718b458a2e912141cf3fc8dab648362ee7463')

<ipython-input-95-f583a7448314> in get_contract(abi_file, address)
      6       abi = json.load(f)
      7     address = w3.toChecksumAddress(address)
----> 8     contract = w3.eth.contract(address=address, abi=abi)
      9     return contract

~/.virtualenvs/liquidation/lib/python3.8/site-packages/web3/eth.py in contract(self, address, **kwargs)
    524         ContractFactoryClass = kwargs.pop('ContractFactoryClass', self.defaultContractFactory)
    525 
--> 526         ContractFactory = ContractFactoryClass.factory(self.web3, **kwargs)
    527 
    528         if address:

~/.virtualenvs/liquidation/lib/python3.8/site-packages/web3/contract.py in factory(cls, web3, class_name, **kwargs)
    358         }
    359 
--> 360         contract = cast(Contract, PropertyCheckingFactory(
    361             class_name or cls.__name__,
    362             (cls,),

~/.virtualenvs/liquidation/lib/python3.8/site-packages/web3/_utils/datatypes.py in __new__(mcs, name, bases, namespace, normalizers)
     51 
     52         if normalizers:
---> 53             processed_namespace = apply_formatters_to_dict(
     54                 normalizers,
     55                 namespace,

~/.virtualenvs/liquidation/lib/python3.8/site-packages/eth_utils/functional.py in inner(*args, **kwargs)
     43         @functools.wraps(fn)
     44         def inner(*args, **kwargs) -> T:  # type: ignore
---> 45             return callback(fn(*args, **kwargs))
     46 
     47         return inner

~/.virtualenvs/liquidation/lib/python3.8/site-packages/eth_utils/applicators.py in apply_formatters_to_dict(formatters, value)
     84                 yield key, formatters[key](item)
     85             except (TypeError, ValueError) as exc:
---> 86                 raise type(exc)(
     87                     "Could not format value %r as field %r" % (item, key)
     88                 ) from exc

```

**Comment by pipermerriam** [comment]
If you take a look at the error message (clipped from what you included in your issue)

```
ValueError: Abi contains functions with colliding selectors. Functions admin(), admin(), admin() have selector 0xf851a440 and
comptrollerImplementation(), comptrollerImplementation(), comptrollerImplementation() have selector 0xbb82aa5e and
pendingAdmin(), pendingAdmin(), pendingAdmin() have selector 0x26782247 and
pendingComptrollerImplementation(), pendingComptrollerImplementation(), pendingComptrollerImplementation() have selector 0xdcfbc0c7 and
_setCloseFactor(uint256), _setCloseFactor(uint256) have selector 0x317b0b77 and
_setCollateralFactor(address,uint256), _setCollateralFactor(address,uint256) have selector 0xe4028eee and
_setLiquidationIncentive(uint256), _setLiquidationIncentive(uint256) have selector 0x4fd42e17 and
_setMaxAssets(uint256), _setMaxAssets(uint256) have selector 0xd9226ced and
_setPriceOracle(address), _setPriceOracle(address) have selector 0x55ee1fe1 and
_supportMarket(address), _supportMarket(address) have selector 0xa76b3fda and
accountAssets(address,uint256), accountAssets(address,uint256) have selector 0xdce15449 and
borrowAllowed(address,address,uint256), borrowAllowed(address,address,uint256) have selector 0xda3d454c and
borrowVerify(address,address,uint256), borrowVerify(address,address,uint256) have selector 0x5c778605 and
checkMembership(address,address), checkMembership(address,address) have selector 0x929fe9a1 and
closeFactorMantissa(), closeFactorMantissa() have selector 0xe8755446 and
enterMarkets(address[]), enterMarkets(address[]) have selector 0xc2998238 and
exitMarket(address), exitMarket(address) have selector 0xede4edd0 and
getAccountLiquidity(address), getAccountLiquidity(address) have selector 0x5ec88c79 and
getAssetsIn(address), getAssetsIn(address) have selector 0xabfceffc and
isComptroller(), isComptroller() have selector 0x007e3dd2 and
liquidateBorrowAllowed(address,address,address,address,uint256), liquidateBorrowAllowed(address,address,address,address,uint256) have selector 0x5fc7e71e and
liquidateBorrowVerify(address,address,address,address,uint256,uint256), liquidateBorrowVerify(address,address,address,address,uint256,uint256) have selector 0x47ef3b3b and
liquidateCalculateSeizeTokens(address,address,uint256), liquidateCalculateSeizeTokens(address,address,uint256) have selector 0xc488847b and
liquidationIncentiveMantissa(), liquidationIncentiveMantissa() have selector 0x4ada90af and
markets(address), markets(address) have selector 0x8e8f294b and
maxAssets(), maxAssets() have selector 0x94b2294b and
mintAllowed(address,address,uint256), mintAllowed(address,address,uint256) have selector 0x4ef4c3e1 and
mintVerify(address,address,uint256,uint256), mintVerify(address,address,uint256,uint256) have selector 0x41c728b9 and
oracle(), oracle() have selector 0x7dc0d1d0 and
redeemAllowed(address,address,uint256), redeemAllowed(address,address,uint256) have selector 0xeabe7d91 and
redeemVerify(address,address,uint256,uint256), redeemVerify(address,address,uint256,uint256) have selector 0x51dff989 and
repayBorrowAllowed(address,address,address,uint256), repayBorrowAllowed(address,address,address,uint256) have selector 0x24008a62 and
repayBorrowVerify(address,address,address,uint256,uint256), repayBorrowVerify(address,address,address,uint256,uint256) have selector 0x1ededc91 and
seizeAllowed(address,address,address,address,uint256), seizeAllowed(address,address,address,address,uint256) have selector 0xd02f7351 and
seizeVerify(address,address,address,address,uint256), seizeVerify(address,address,address,address,uint256) have selector 0x6d35bf91 and
transferAllowed(address,address,address,uint256), transferAllowed(address,address,address,uint256) have selector 0xbdcdc258 and
transferVerify(address,address,address,uint256), transferVerify(address,address,address,uint256) have selector 0x6a56947e
```

You'll see that the ABI you are loading includes duplicate definitions of multiple functions which is an invalid ABI.  If you fix your ABI json to remove the duplicates everything is likely to be fine.  Feel free to re-open or continue the conversation here if you are still having trouble.  I'm closing this since it doesn't appear to  be a library bug.

cc @marcgarreau our use of `ValueError` here might be improved by a custom exception with a more descriptive name, or an `eth_utils.ValidationError` since this is really a validation check.

**Comment by pipermerriam** [comment]
Oh, and if we adjust the exception class here, it would be reasonably simple to make the formatting of this error message better with some line breaks and simple markup so that it is easier to pull out the most important information.

**Comment by brschkv** [comment]
> If you take a look at the error message (clipped from what you included in your issue)
> 
> ```
> ValueError: Abi contains functions with colliding selectors. Functions admin(), admin(), admin() have selector 0xf851a440 and
> comptrollerImplementation(), comptrollerImplementation(), comptrollerImplementation() have selector 0xbb82aa5e and
> pendingAdmin(), pendingAdmin(), pendingAdmin() have selector 0x26782247 and
> pendingComptrollerImplementation(), pendingComptrollerImplementation(), pendingComptrollerImplementation() have selector 0xdcfbc0c7 and
> _setCloseFactor(uint256), _setCloseFactor(uint256) have selector 0x317b0b77 and
> _setCollateralFactor(address,uint256), _setCollateralFactor(address,uint256) have selector 0xe4028eee and
> _setLiquidationIncentive(uint256), _setLiquidationIncentive(uint256) have selector 0x4fd42e17 and
> _setMaxAssets(uint256), _setMaxAssets(uint256) have selector 0xd9226ced and
> _setPriceOracle(address), _setPriceOracle(address) have selector 0x55ee1fe1 and
> _supportMarket(address), _supportMarket(address) have selector 0xa76b3fda and
> accountAssets(address,uint256), accountAssets(address,uint256) have selector 0xdce15449 and
> borrowAllowed(address,address,uint256), borrowAllowed(address,address,uint256) have selector 0xda3d454c and
> borrowVerify(address,address,uint256), borrowVerify(address,address,uint256) have selector 0x5c778605 and
> checkMembership(address,address), checkMembership(address,address) have selector 0x929fe9a1 and
> closeFactorMantissa(), closeFactorMantissa() have selector 0xe8755446 and
> enterMarkets(address[]), enterMarkets(address[]) have selector 0xc2998238 and
> exitMarket(address), exitMarket(address) have selector 0xede4edd0 and
> getAccountLiquidity(address), getAccountLiquidity(address) have selector 0x5ec88c79 and
> getAssetsIn(address), getAssetsIn(address) have selector 0xabfceffc and
> isComptroller(), isComptroller() have selector 0x007e3dd2 and
> liquidateBorrowAllowed(address,address,address,address,uint256), liquidateBorrowAllowed(address,address,address,address,uint256) have selector 0x5fc7e71e and
> liquidateBorrowVerify(address,address,address,address,uint256,uint256), liquidateBorrowVerify(address,address,address,address,uint256,uint256) have selector 0x47ef3b3b and
> liquidateCalculateSeizeTokens(address,address,uint256), liquidateCalculateSeizeTokens(address,address,uint256) have selector 0xc488847b and
> liquidationIncentiveMantissa(), liquidationIncentiveMantissa() have selector 0x4ada90af and
> markets(address), markets(address) have selector 0x8e8f294b and
> maxAssets(), maxAssets() have selector 0x94b2294b and
> mintAllowed(address,address,uint256), mintAllowed(address,address,uint256) have selector 0x4ef4c3e1 and
> mintVerify(address,address,uint256,uint256), mintVerify(address,address,uint256,uint256) have selector 0x41c728b9 and
> oracle(), oracle() have selector 0x7dc0d1d0 and
> redeemAllowed(address,address,uint256), redeemAllowed(address,address,uint256) have selector 0xeabe7d91 and
> redeemVerify(address,address,uint256,uint256), redeemVerify(address,address,uint256,uint256) have selector 0x51dff989 and
> repayBorrowAllowed(address,address,address,uint256), repayBorrowAllowed(address,address,address,uint256) have selector 0x24008a62 and
> repayBorrowVerify(address,address,address,uint256,uint256), repayBorrowVerify(address,address,address,uint256,uint256) have selector 0x1ededc91 and
> seizeAllowed(address,address,address,address,uint256), seizeAllowed(address,address,address,address,uint256) have selector 0xd02f7351 and
> seizeVerify(address,address,address,address,uint256), seizeVerify(address,address,address,address,uint256) have selector 0x6d35bf91 and
> transferAllowed(address,address,address,uint256), transferAllowed(address,address,address,uint256) have selector 0xbdcdc258 and
> transferVerify(address,address,address,uint256), transferVerify(address,address,address,uint256) have selector 0x6a56947e
> ```
> 
> You'll see that the ABI you are loading includes duplicate definitions of multiple functions which is an invalid ABI. If you fix your ABI json to remove the duplicates everything is likely to be fine. Feel free to re-open or continue the conversation here if you are still having trouble. I'm closing this since it doesn't appear to be a library bug.
> 
> cc @marcgarreau our use of `ValueError` here might be improved by a custom exception with a more descriptive name, or an `eth_utils.ValidationError` since this is really a validation check.

Hi,
thanks for you quick reply. I clipped part of the error message because it became redundant at a certain point.

However, I am able to load and interact with the exact same ABI from web3.js. So I think the contract is actually valid. Probably should have added that in the original description.

web3.js Code:
```nodejs
Web3 = require('web3')
var prov = new Web3.providers.WebsocketProvider('wss://ropsten.infura.io/ws/v3/<my_api_key>')
web3 = new Web3(prov)
var abi = JSON.parse(fs.readFileSync('Comptroller.json', 'utf8'))
test = new web3.eth.Contract(abi, '0xe03718b458a2e912141cf3fc8dab648362ee7463')
test.methods.closeFactorMantissa().call().then(function(result) {console.log(result)})
```
Output:
```json
> 100000000000000000
```

**Comment by pipermerriam** [comment]
> However, I am able to load and interact with the exact same ABI from web3.js. So I think the contract is actually valid. Probably should have added that in the original description.

Please re-read my reply to you.  It explains why you are getting the exception and what you need to do to fix it.

I suspect web3.js is just not performing the same validation checks that web3.py does.

**Comment by brschkv** [comment]
> I suspect web3.js is just not performing the same validation checks that web3.py does.

Which is my point: The very first line of the web.py Readme says "A Python implementation of web3.js". So I would expect both libraries to have the same opinion of what a valid contract is, with web3.js being the point of reference.

And also, I don't think the official solution to using vendor supplied contracts (this one being from Compound) should be to hack around in it until it validates.

We can agree to disagree, but I still think this is a bug or at least something that should be changed.

I will gladly offer my help, if there is some consensus to change the validation logic.

**Comment by voith** [comment]
I can verify that the ABI that @brschkv was using has some colliding functions. 
More details on [gitter](https://gitter.im/ethereum/web3.py?at=5ed578a9a3a1b13679bf39e1).
