### ISSUE TITLE
Private key signing not possible

### ISSUE THREAD

**Issue by ice09** [ethereum/web3.py#167]
* Version: 3.7.2
* Python: 3.5
* OS: ubuntu 16.04 lts

### What was wrong?

When following instructions on http://web3py.readthedocs.io/en/latest/managers.html for private key signing, if the transaction 

`web3.eth.sendTransaction({'from':web3.eth.accounts[1],'to':web3.eth.accounts[0],'value':1000000000000})`

is sent, the result in the geth node is

`Tx(044891110df9790252c41bd6f1af0b0b7f1cfac8eea3ccc8d8b7f8ccfe0141c7) to: &7361cf89b8ea0a4224a8330df0ade1130f3a2192`

whereas the correct one: 

`Tx(0x45ed38ec7e8b8e6f86f6d1b279736ad4f45dd8336011289a1017d0a0f01b6e37) to: 0x7361cf89b8ea0a4224a8330df0ade1130f3a2192`

is printed if exact the same transaction is called with standard wallet manager.

#### Cute Animal Picture

![Cute animal picture]()

**Comment by carver** [comment]
Should be resolved by #324

**Comment by carver** [comment]
Available in the v4-beta: http://web3py.readthedocs.io/en/latest/web3.eth.account.html
