### ISSUE TITLE
Whisper: Received event's recipientPublicKey does not contain sender's publicKey

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1672]
* Version: 5.11.0
* Python: 3.5
* OS: linux

### What was wrong?

I observe that when a message received sender's public key does not show up instead receiver see itself's public key. Basically I am unable to retreive the public key of the sender from `event`. Could there be any solution for this?

---

What I have [done on ethereum stack](https://ethereum.stackexchange.com/a/58299/4575) pasted below:

## Solution using `Web3.py`:

I have followed following [ssh-mode code](https://github.com/ethereum/web3.py/blob/master/tests/core/shh-module/test_shh_filter.py).

------

`receiver.py` that runs on node-1:

```
from os.path import expanduser
from web3 import HTTPProvider, Web3
import asyncio
import time


def handle_event(event):
    print(f"recipientPublicKey={event['recipientPublicKey'].hex()}")
    print(event["payload"].decode("utf-8"))


async def log_loop(filter_id, poll_interval):
    while True:
        for event in w3.geth.shh.getMessages(filter_id):  # event_filter.get_new_entries():
            handle_event(event)  # TODO: add try catch
        await asyncio.sleep(poll_interval)
        time.sleep(0.1)

if __name__ == "__main__":
    w3 = Web3(HTTPProvider("http://localhost:8545"))
    home = expanduser("~")
    topic = "0x07678231"

    print("Initializing...")
    key_id = w3.geth.shh.newKeyPair()  # generates a new public and private key pair for message decryption and encryption.
    public_key = w3.geth.shh.getPublicKey(key_id)
    filter_id = w3.geth.shh.new_message_filter({"topic": topic, "privateKeyID": key_id, "recipientPublicKey": public_key})
    print(f"my_public_key={public_key}")

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(asyncio.gather(log_loop(filter_id, 2)))
    finally:
        loop.close()
```

Output:

    my_public_key=0x0429824f14966d802e8a12b09c276361cdf13eda4dd5f4f776d0a2a4db61ba4e24683be84df2b521ff8c6290e3851bf9b59a8e9a7e13345fee603de9be862f5ef3

----------

After `Node_1`'s messages are sent; I have copied printed `receiverPublicKey` into `receiver_pub` variable on the following code. I run following code on `Node 2`. `Node 2` sends a message to the network. Later I press enter on the `Node_1` and `Node_1` prints the message

    from web3 import Web3, HTTPProvider
    web3 = Web3(HTTPProvider('http://localhost:8545'))
    
    # obtained from node_1 and assigned here.
    receiver_pub =
    "0x0429824f14966d802e8a12b09c276361cdf13eda4dd5f4f776d0a2a4db61ba4e24683be84df2b521ff8c6290e3851bf9b59a8e9a7e13345fee603de9be862f5ef3"
    
    topic = '0x07678231'
    payloads = [web3.toHex(text="test message :)"), web3.toHex(text="2nd test message")]
    
    web3.geth.shh.post(
        {"powTarget": 2.5, "powTime": 2, "ttl": 60, "payload": payloads[0], "topic": topic, "pubKey": receiver_pub}
    )

 
Output again for the receiver after message is received. receiver's public key is same as its received event's public key so it cannot reply back to sender becuase it cannot get sender's public key.   

```
Initializing...
my_public_key=0x0429824f14966d802e8a12b09c276361cdf13eda4dd5f4f776d0a2a4db61ba4e24683be84df2b521ff8c6290e3851bf9b59a8e9a7e13345fee603de9be862f5ef3
recipientPublicKey=0x0429824f14966d802e8a12b09c276361cdf13eda4dd5f4f776d0a2a4db61ba4e24683be84df2b521ff8c6290e3851bf9b59a8e9a7e13345fee603de9be862f5ef3
test message :)
```

**Comment by marcgarreau** [comment]
Whisper was finally removed from Geth distributions (see: https://github.com/ethereum/go-ethereum/releases/tag/v1.9.21), so I expect that we will soon drop support for it too. I believe Waku, the Status fork of Whisper, continues to be supported. If this is mission critical software, that's where I would be looking. Closing as a `wontfix`, but welcome feedback or additional context.
