### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [ethereum/web3.py#1674]
It would be great if web3.py provided support for deploying and upgrading diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Here is a blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by marcgarreau** [comment]
I see this has been broadcasted to many tools/repos, which is fine, but I don't have the bandwidth in the short-term to deep dive into the EIP and brainstorm APIs and the like. If someone is interested enough in this feature, please feel free to propose something specific and concrete.

Upon quick inspection, though, this seems like it may be better suited for a framework like Brownie, cc/ @iamdefinitelyahuman.

**Comment by marcgarreau** [comment]
My gut is still telling me this is in dapp framework territory and outside the scope of web3.py. Closing the issue, but if someone feels strongly otherwise, you can still state your case.
