### ISSUE TITLE
problem with unlock account method

### ISSUE THREAD

**Issue by manuthema-rodriguez** [ethereum/web3.py#1675]
Versions:
python -->3.6.9
web3.py --> 5.11.1
trinity --> 0.1.0a35

I run trinity with:

trinity --genesis /root/devnet.json --trinity-root-dir /tmp/node1 --data-dir /tmp/node1/devnet --network-id 4711 --disable-tx-pool

i got unexpected error when try to use unlock_account
This is my script,
```

from web3 import Web3

w3 = Web3(Web3.IPCProvider("/tmp/node1/devnet/ipcs-eth1/jsonrpc.ipc"))
w3.isConnected()
# True

account = ''
passphrase = ''

w3.eth.personal.unlockAccount(account, passphrase)
# AttributeError: 'Eth' object has no attribute 'personal'
w3.geth.personal.unlockAccount(account, passphrase)
# ValueError: Module unavailable: 'personal'
w3.personal.unlockAccount(account, passphrase)
#AttributeError: 'Web3' object has no attribute 'personal'

```
I have tried other combinations without success

**Comment by roussafi-omar** [comment]
i have the same probleme

**Comment by manuthema-rodriguez** [comment]
it is a limitation of trinity. I recommend using geth with --dev or some test network like ropsten through infura.io.
These two ways worked for me
