### ISSUE TITLE
call contract from different user account  using web3.py

### ISSUE THREAD

**Issue by esraa95mahmoud** [ethereum/web3.py#1685]
The project is a group of Ethereum users, who want to send their data to the blockchain network to be saved, this data is sent by those users by Python. As I understood that each user has an address that sends his data through this address in order to save the data.
Python will be used to send data. My question is how will I specify the addresses that will send the data in the Python file?
Or how will more than one user (the address) call the job in the smart contract?
I don't want to send Ether from more than one address
I am a beginner in this topic!
If the answer can be explained with a code, and if it is explained by sending a random number to simplify the problem by many users for example in web3.py

**Comment by marcgarreau** [comment]
Hey @esraa95mahmoud, thanks for reaching out, but GitHub issues are best used for pointing out bugs or making feature requests in the library. I'll see if I can quickly point you in a helpful direction, though.

> My question is how will I specify the addresses that will send the data in the Python file?

The `sendTransaction` method or contract functions allow you to specify a `from` value. 

> Or how will more than one user (the address) call the job in the smart contract?

Your smart contract can have whatever permissions you code into it. If you write a public function with no restrictions, anyone can call that function on your smart contract.

If you don't see what you need in the web3.py [examples](https://web3py.readthedocs.io/en/latest/examples.html#making-transactions) and documentation, then potentially [StackExchange](https://ethereum.stackexchange.com/questions/tagged/web3.py) is a good place to ask questions about how to develop your idea. You're more likely to get better answers if you ask one specific question per post, though. Closing this issue as it doesn't represent a TODO item for web3.py.
