### ISSUE TITLE
Client diversity and Web3.py

### ISSUE THREAD

**Issue by wolovim** [ethereum/web3.py#1694]
### What was wrong?

Geth dominates the etherscape, [according to Etherscan](https://etherscan.io/nodetracker#) (~75% at the time of writing). Client diversity has been the subject of multiple recent All Core Devs conversations, so it feels apt to create some space to ask if/how Web3.py can support network health in this capacity.

Q's:
- Geth and Parity are first-class citizens in the library. Should we make it a priority to extend this list? (Are we ready to explore the Trinity integration story?)
- Our documentation gets a fair number of daily eyeballs. Geth and Infura (using mostly Geth, I believe) are our primary examples. Should they be? Should we encourage branching out in some capacity?
- Anything else Web3.py can do to promote client diversity? 

@pipermerriam has [theorized](https://snakecharmers.ethereum.org/applying-the-five-whys-to-the-client-diversity-problem/) that clients are fundamentally too difficult to build and that is ultimately what needs to change to improve client diversity.

Q's:
- Is there something Web3.py could do to encourage or prepare for that version of the future?
- (your question here)

**Comment by dbfreem** [comment]
What things could web3.py do to support client diversity? Make a pluggable system to allow add-ins that would allow the individual clients to implement their client specific logic?

This is an interesting problem for Ethereum as a whole.

**Comment by pacrob** [comment]
This is pretty well ingrained in our thinking. We are slowly updating lists and docs to reflect diversity and/or remove specific client names where possible. Closing.
