### ISSUE TITLE
AttributeError: type object 'Web3' has no attribute 'utils'

### ISSUE THREAD

**Issue by esraa95mahmoud** [ethereum/web3.py#1696]
When I run into a Python file with the smart contract
`contract.functions.set_data (1, i, lis1 [i]). transact ({'from': Web3.utils.toChecksumAddress (0xdc2221d583aef3539547cb041cb58fa3c81f1d92)})`
I'm getting the error
Traceback (most recent call last):
   ```
File "1_accounts.py", line 54, in <module>
     rusalt = contract.functions.set_data (1, i, lis1 [i]). transact ({'from': Web3.utils.toChecksumAddress (0xdc2221d583aef3539547cb041cb58fa3c81f1d92)})
AttributeError: type object 'Web3' has no attribute 'utils'
```

**Comment by pipermerriam** [comment]
I think you can find what you need in the documentation:

https://web3py.readthedocs.io/en/latest/web3.main.html#web3.Web3.toChecksumAddress
