### ISSUE TITLE
Can not pip3 install web3 on raspberry 4

### ISSUE THREAD

**Issue by n3me5is-git** [ethereum/web3.py#1707]
I'm using python 3.7 on raspbian and using `pip3 install web3'. The error I get is
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting web3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/web3/
```
All the other packages I need are installing fine.
Any suggestions?

**Comment by kclowes** [comment]
I am not familiar with piwheels, but following the url (https://www.piwheels.org/simple/web3/), indicates that there isn't a web3 package there. A brief look at the [piwheels FAQ](https://www.piwheels.org/faq.html) leads me to believe that there should be, so will take some troubleshooting with the piwheels team to figure out why it's not there. However, if you run this command: `pip3 wheel <package>` does it work? If not, on that same FAQ page, it looks like you can either install a package from pypi or you can [open an issue](https://www.piwheels.org/faq.html) on the piwheels page for a missing package. I'm going to close this issue, but feel free to reopen if you need further assistance!

**Comment by n3me5is-git** [comment]
`pip3 wheel web3` solved the issue. Thanks. I also opened the issue as suggested so they can add the wheel to the database.
