### ISSUE TITLE
 ModuleNotFoundError: No module named 'eth_account'

### ISSUE THREAD

**Issue by hivemall** [ethereum/web3.py#1710]
git clone + `git checkout tags/v5.12.0 -b v5.12.0_b` + pytest in base dir results in:
```
ImportError while loading conftest 
./conftest.py'.
conftest.py:6: in <module>
    from web3._utils.threads import (
web3/__init__.py:6: in <module>
    from eth_account import (
E   ModuleNotFoundError: No module named 'eth_account'
```

**Comment by marcgarreau** [comment]
Did you install the dependencies? For local development, we use `pip install -e .[dev]`

I'm assuming that'll resolve it, so closing this issue. Please reopen if that's not the case.
