### ISSUE TITLE
mypy can't find methods in `eth-utils.curried `

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1716]
# What was wrong?

Eth-utils had some linting tests failing, and updated the `curried` stub file (`eth-utils/curried/__init__.pyi`) in this PR: https://github.com/ethereum/eth-utils/pull/191/files. This update broke the web3.py mypy runs. Trinity has a similar problem described [here](https://github.com/ethereum/trinity/issues/1982).

### How can it be fixed?
I found these issues: 
https://github.com/python/mypy/issues/7423
https://github.com/python/mypy/issues/7251
https://github.com/python/mypy/issues/7247
Which indicate that should be able to do a `from eth_utils import ... as ...` to fix those or add an `__all__ = ['module', module2, ...]`

**Comment by kclowes** [comment]
update: AIUI, eth-utils 1.9.4 removed the `pyi` file so we'll need to add missing curried methods like so: https://github.com/ethereum/eth-utils/pull/200/files#diff-daeec037a8849e663467fa69ac7d6e6cR155-R173

**Comment by fselmo** [comment]
stale
