### ISSUE TITLE
waitForSeveralTransactionReceipts

### ISSUE THREAD

**Issue by kaleb-keny** [ethereum/web3.py#1718]
* Version: 5.6.0
* Python: 3.7.4
* OS: win
* pip freeze output

I am working on a piece of code that needs to await the receipt of several hashes and returns a result as soon as a result is returned using `asyncio.FIRST_COMPLETED`. This should happen either if a timeout error  is triggered or an actual receipt is received. The issue I am facing is that `waitForSeveralTransactionReceipts` is not an awaitable function. So not sure how to go about it with concurrency, typically I would do an  `await waitForSeveralTransactionReceipts` as it would be almost equivalent `await asyncio.sleep(timeOut)`. 
Below is a working code with 2 hashes, one already on chain and the other always in a pending state. The expected behavior from this is that the task should end right away as one of the hashes is already on chain, but I intend to use it to query few transactions until one of them is on chain or the first one returns a timeout.

```
import asyncio
import nest_asyncio
nest_asyncio.apply()
import web3

infuraKey  = 'XXXXXXXXXXXXXXXXXXXXX'
infuraLink = 'https://kovan.infura.io/v3/'+infuraKey
kovanProvider = web3.HTTPProvider(infuraLink )
w3 = web3.Web3(kovanProvider)

async def awaitSeveralTransactionsMaster(txHashesBytes,
                                         timeout=5):

    tasks = [awaitSeveralTransactionsWorker(txHash,timeout) for txHash in txHashesBytes]
    
    finished, unfinished = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)

    if unfinished:
        for task in unfinished:
            task.cancel()
            await asyncio.wait(unfinished)

    return [task for task in finished]

async def awaitSeveralTransactionsWorker(txHash,
                                         timeout):

    print(f"doing search for hash {txHash.hex()} with worker")

    try:
        result = w3.eth.waitForTransactionReceipt(txHash,timeout)
        return result
    
    except KeyboardInterrupt:
        print("await interrupted")
    
    except TimeoutError:
        #This yields to the other potential hash
        print("time out error")
        await asyncio.sleep(3)

if __name__== '__main__':
    txHashes = ['0x1c121c6bbc75f1b4c086b3d4e27f80d033a696f562669db4d058523c44ca5bc6',
                '0x2c7fc023649927646271b9a4bf00138e7730ac68a716245280228c7b107e2c9f']
    txHashesBytes = [bytes.fromhex(txHash[2:]) for txHash in txHashes]
    
    results = asyncio.run(awaitSeveralTransactionsMaster(txHashesBytes=txHashesBytes,timeout=10))
```

**Comment by kclowes** [comment]
@kaleb-keny I'm not sure what the question is here. Can you clarify?

**Comment by kaleb-keny** [comment]
Yeah sure no issue, so the purpose of this snipped of code is to take in several hashes as an input and should await a response from one of the `waitForTransactionReceipt` asynchronously.  When one of the hashes returns a response (either a receipt or a timeout) then it should terminate all the tasks and return the result. 

I am not able to figure out how to await `w3.eth.waitForTransactionReceipt(txHash,timeout)` so that the cpu can move on to the other hash while the first one is running. As an example, when you are calling a site and there is a delay in a response, you could await the response, same thing here, but we're waiting for a hash to be included in the block. So do you think it is possible do this?

**Comment by kclowes** [comment]
Gotcha. I am not super familiar with async python, but AIUI, I don't think that is possible with how the code base stands. 

@pipermerriam do you have any ideas?

**Comment by kaleb-keny** [comment]
Yeah I understand, async on python is really challenging as the docs are really not that straightforward... So the end objective of this is I send a transaction, it's still pending because of the crazy gas prices, ok I send another one with the same nonce... So  I would need await the new transaction as well as the old one as it could happen that the first one is mined by the time the second is sent. I could alternate between the two hashes, but seems to me there could be a more elegant solution with async processing where you could await n number of transactions at the same time.

**Comment by pipermerriam** [comment]
Web3.py doesn't yet support native awaitable APIs.  If you are using `asyncio` you can use [loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) to push it into a thread but I can't make any guarantees that it will *just work*.

You can see me doing something similar but using the `trio` async framework here: 

https://github.com/ethereum/cthaeh/blob/faec68da2a63d14329c7499e9161350cd2382c04/cthaeh/exfiltration.py#L351-L355

**Comment by kaleb-keny** [comment]
alright thank you for your replies @pipermerriam  @kclowes I'll look into it.
