### ISSUE TITLE
Flaky Geth websocket tests

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1719]
### What was wrong?
[This PR](https://github.com/ethereum/web3.py/pull/1708) introduced flaky tests in the Geth Websocket module. 
Failures look like: https://app.circleci.com/pipelines/github/ethereum/web3.py/331/workflows/b033c86b-528a-47eb-a699-44027cb1e46b/jobs/122605

**Comment by carver** [comment]
Oops, didn't realize that linking it from the PR would auto-close it on the merge (without the "close" tag)... weird.

**Comment by kclowes** [comment]
Yeah, super weird. At first I thought you just figured it out really quickly 😆
