### ISSUE TITLE
Update Flake8

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1720]
* Version: 5.12.0
* Python: 3.8

### What was wrong?
flake8 3.4.1 doesn't run with python 3.8, but upgrading flake8 will fail our linting.

### How can it be fixed?
Upgrade flake8 to the most recent version and fix all the errors. 

...Or maybe this is a good time to pull in black

**Comment by pratik-vii** [comment]
@kclowes I will pick this up. please assign to me.

**Comment by kclowes** [comment]
Closed via #1759.
