### ISSUE TITLE
Get Rid of Hypothesis Deprecation Warnings

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1729]
* Version: 5.12.1

### What was wrong?

At the end of our core tests, we have a Deprecation Warning that looks like: 
`HypothesisDeprecationWarning: tests/core/utilities/test_event_filter_builder.py::test_match_any_bytes_type_properties uses the 'web3' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.  See https://docs.pytest.org/en/latest/fixture.html#sharing-test-data for details on fixture scope.`

Actual output can be found in this [test run](https://app.circleci.com/pipelines/github/ethereum/web3.py/368/workflows/a61f1619-cbb4-4c43-b0f5-a3c49cee62a5/jobs/123892).

### How can it be fixed?

Add the appropriate scope to each fixture. This will need to be done in multiple PRs.

**Comment by tmckenzie51** [comment]
I'm interested in working on this issue.

**Comment by kclowes** [comment]
Yes it does, and we'd love help! You can see the full list of warnings on any of the latest core test runs on CircleCI. The py36-core tests can be found [here](https://app.circleci.com/pipelines/github/ethereum/web3.py/1440/workflows/5b42450d-b9d8-4d5a-bd6e-e82a1641764b/jobs/159645), and you can see the warnings in the `run tox` dropdown. I'd recommend tackling a few at a time so that we can review smaller PRs. Let us know if you need more direction!

**Comment by reyaw** [comment]
Couple of questions: 
1) Is this the correct way to define the scope of a fixture? (top line of the screenshot)

![fixture_scope](https://user-images.githubusercontent.com/82685635/122440542-a8c68e80-cf6a-11eb-84d2-7e85e03190c1.png)

**Comment by kclowes** [comment]
> 1. Is this the correct way to define the scope of a fixture? (top line of the screenshot)

yep!

> 2. How can I determine the correct scope of each fixture?

Since we're not having problems with the scope now, I'd start with the largest scope you can (which I believe is session, but I'm not sure on that) and then make the scope narrower as you run into issues. We've done a few of these before - [this PR](https://github.com/ethereum/web3.py/pull/1780/files) is a good example. We ended up moving all of the functions related to the Emitter fixture to a module scope, and moved it into the file where it was actually used. You'll likely need to do something similar. Let me know if you have more questions!

**Comment by smishy05** [comment]
Hey there @kclowes ! Has this issue been resolved? If no, then I would like to have a go at it?
Many thanks!

**Comment by kclowes** [comment]
@smishy05 It would be great if you wanted to have a go! Let me know if you have questions. Thanks!

**Comment by smishy05** [comment]
Thanks a lot for the reply! Yup, I will let you know if I face any issues.

**Comment by dbfreem** [comment]
@kclowes  this issue can be closed.

**Comment by kclowes** [comment]
Thanks!
