### ISSUE TITLE
Can't install web3 through pip

### ISSUE THREAD

**Issue by Daxxas** [ethereum/web3.py#1730]
* Version: x.x.x
* Python: 3.8.5
* OS: win
* `pip freeze` output

```
appdirs==1.4.4
Cython==0.29.21
distlib==0.3.1
filelock==3.0.12
javaobj-py3==0.4.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycryptodomex==3.9.8
selenium==3.141.0
six==1.15.0
urllib3==1.25.10
virtualenv==20.0.31
```

### What was wrong?

With the command "pip install web3"
I got the error as following : 

```
ERROR: Could not find a version that satisfies the requirement rusty-rlp<0.2,>=0.1.15 (from rlp<=2.0.0.alpha-1,>=1.0.0->eth-account<0.6.0,>=0.5.3->web3) (from versions: none)
ERROR: No matching distribution found for rusty-rlp<0.2,>=0.1.15 (from rlp<=2.0.0.alpha-1,>=1.0.0->eth-account<0.6.0,>=0.5.3->web3)
```
 I did followed this as much as I could : https://web3py.readthedocs.io/en/latest/troubleshooting.html#setup-environment

I'm using JetBrains PyCharm and its console with a virtual environnement

what can I do to be able to install web3 ?

**Comment by r-marques** [comment]
I see this happening in alpine. With fedora or ubuntu it works fine

**Comment by iammortimer** [comment]
i had the same problem with an alpine docker build. Setting web3 <= 5.8.0 let's it run through.
If that works for you depends on if you need any changes from after 5.8.0

**Comment by kclowes** [comment]
Interesting, thanks for raising this and tracking down a version that works. I'll see if I can figure out what changed after 5.8.0 🤔

**Comment by Daxxas** [comment]
Installing Windows SDK fixed the issue for me
https://developer.microsoft.com/fr-fr/windows/downloads/windows-10-sdk/

**Comment by takipsizad** [comment]
bruh

**Comment by takipsizad** [comment]
> 
> 
> Installing Windows SDK fixed the issue for me
> https://developer.microsoft.com/fr-fr/windows/downloads/windows-10-sdk/

yeah but i dont want to spend 13 gb for a thing that i wont use

**Comment by kclowes** [comment]
This might be a dependency resolution issue. Try installing with either `pip install web3 --use-feature=2020-resolver` or with pip version 20.3 or greater.

**Comment by takipsizad** [comment]
> 
> 
> This might be a dependency resolution issue. Try installing with either `pip install web3 --use-feature=2020-resolver` or with pip version 20.3 or greater.

well i can get pass it but lru wont let me after that

**Comment by kclowes** [comment]
@takipsizad Can you post a stack trace?

**Comment by takipsizad** [comment]
> 
> 
> @takipsizad Can you post a stack trace?

i was downloading lru instead of lru-dist

**Comment by pacrob** [comment]
Closing due to non-action, please open a new issue if you're still having problems.
