### ISSUE TITLE
Docs still mention UnhandledRequest but it's been removed

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/web3.py#1737]
### What was wrong?

There are still two mentions of `UnhandledRequest` in the docs even though it appears to have been removed in #1166.

- The [note in the Infura provider section of the quickstart](https://web3py.readthedocs.io/en/stable/quickstart.html#provider-infura)
- [`BaseProvider.isConnected()` section of the Web3 internals](https://web3py.readthedocs.io/en/stable/internals.html#BaseProvider.isConnected) page of the docs

### How can it be fixed?

A quick read of the PR suggests that it may now be `CannotHandleRequest`?  I'm not entirely sure if it's a direct replacement so didn't put in a PR for the doc change.

**Comment by kclowes** [comment]
Yep, you're right. Without doing too much digging it looks to me like we just pass through whatever error comes from the  provider, but docs definitely need to be changed. Thanks for the report!
