### ISSUE TITLE
remove block_number_formatter in favor of to_hex_if_integer

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1745]
* Version: 5.13 (to be released)

### What was wrong?
In `web3/_utils/method_formatters.py` there is a method called `block_number_formatter` that is used for all of the block numbers. However, I also want to use it for a transaction index. I added a method called `to_hex_if_integer` that is the exact same functionality with a different name. 

### How can it be fixed?

This should be a straightforward replacement of `block_number_formatter` for `to_hex_if_integer`.

**Comment by tmckenzie51** [comment]
I can start working on this
