### ISSUE TITLE
RESOLVED: Issue installing Web3 with Pip

### ISSUE THREAD

**Issue by ferhatkochan** [ethereum/web3.py#1750]
* Version: x.x.x
* Python: 3.8.2
* OS: OSXw
* `pip freeze` output

```
eth-typing==2.2.2
toolz==0.10.0
```

Following the step-by-step installation instructions on the [Quickstart page](https://web3py.readthedocs.io/en/latest/troubleshooting.html#setup-environment), i was unable to install web3 via Pip. 

Here is the error generated when running the command: pip install --upgrade web3 (i also tried pip3). I appreciate the help. 

pip install --upgrade web3
Collecting web3
  Using cached web3-5.12.1-py3-none-any.whl (467 kB)
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Collecting ipfshttpclient<1,>=0.4.13
  Using cached ipfshttpclient-0.6.1-py3-none-any.whl (231 kB)
Collecting eth-typing<3.0.0,>=2.0.0
  Using cached eth_typing-2.2.2-py3-none-any.whl (6.2 kB)
Collecting websockets<9.0.0,>=8.1.0
  Using cached websockets-8.1-cp38-cp38-macosx_10_9_x86_64.whl (64 kB)
Collecting requests<3.0.0,>=2.16.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.1-py3-none-any.whl (6.0 kB)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.13.0-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0
  Using cached eth_hash-0.2.0-py3-none-any.whl (7.2 kB)
Collecting eth-account<0.6.0,>=0.5.3
  Using cached eth_account-0.5.3-py3-none-any.whl (94 kB)
Collecting eth-utils<2.0.0,>=1.9.5
  Using cached eth_utils-1.9.5-py3-none-any.whl (23 kB)
Processing /Users/ferhatkochan/Library/Caches/pip/wheels/d8/af/19/fb896f509a437aca2dcf62583e84d7fb2cd5b628c1564a609c/parsimonious-0.8.1-py3-none-any.whl
Collecting multiaddr>=0.0.7
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting six>=1.11.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Processing /Users/ferhatkochan/Library/Caches/pip/wheels/3d/22/08/7042eb6309c650c7b53615d5df5cc61f1ea9680e7edd3a08d2/pyrsistent-0.17.3-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied, skipping upgrade: setuptools in /Users/ferhatkochan/.venv-py3/lib/python3.8/site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (50.3.0)
Collecting pycryptodome<4,>=3.6.6; extra == "pycryptodome"
  Using cached pycryptodome-3.9.8-cp38-cp38-macosx_10_9_x86_64.whl (13.3 MB)
Collecting eth-keys!=0.3.2,<0.4.0,>=0.2.1
  Using cached eth_keys-0.3.3-py3-none-any.whl (20 kB)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Collecting eth-rlp<1,>=0.1.2
  Using cached eth_rlp-0.2.0-py3-none-any.whl (5.0 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting rlp<=2.0.0.alpha-1,>=1.0.0
  Using cached rlp-2.0.0a1-py2.py3-none-any.whl (19 kB)
Collecting cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"
  Using cached cytoolz-0.10.1.tar.gz (475 kB)
Processing /Users/ferhatkochan/Library/Caches/pip/wheels/cc/a8/a4/4d9e9807c27585dc974fc0e86a3e4345649d71f8a35906d1a8/varint-1.0.2-py3-none-any.whl
Collecting netaddr
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting base58
  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)
Collecting rusty-rlp<0.2,>=0.1.15
  Using cached rusty_rlp-0.1.15-cp38-cp38-macosx_10_7_x86_64.whl (117 kB)
Collecting toolz>=0.8.0
  Using cached toolz-0.10.0-py3-none-any.whl (56 kB)
Building wheels for collected packages: lru-dict, bitarray, cytoolz
  Building wheel for lru-dict (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ferhatkochan/.venv-py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/lru-dict/setup.py'"'"'; __file__='"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/lru-dict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-wheel-gchcl3nm
       cwd: /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/lru-dict/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.8
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/ferhatkochan/.venv-py3/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c lru.c -o build/temp.macosx-10.9-x86_64-3.8/lru.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ferhatkochan/.venv-py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/bitarray/setup.py'"'"'; __file__='"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/bitarray/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-wheel-arwryt5u
       cwd: /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/bitarray/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/bitarray
  copying bitarray/util.py -> build/lib.macosx-10.9-x86_64-3.8/bitarray
  copying bitarray/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/bitarray
  copying bitarray/test_bitarray.py -> build/lib.macosx-10.9-x86_64-3.8/bitarray
  copying bitarray/test_util.py -> build/lib.macosx-10.9-x86_64-3.8/bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/bitarray
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/ferhatkochan/.venv-py3/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c bitarray/_bitarray.c -o build/temp.macosx-10.9-x86_64-3.8/bitarray/_bitarray.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ferhatkochan/.venv-py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"'; __file__='"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-wheel-8ttfw72q
       cwd: /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/
  Complete output (54 lines):
  ALERT: Cython not installed.  Building without Cython.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/compatibility.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/utils_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/_version.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/_signatures.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  creating build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
  copying cytoolz/itertoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/functoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/recipes.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/utils.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/utils.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
  creating build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/cytoolz
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/ferhatkochan/.venv-py3/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.macosx-10.9-x86_64-3.8/cytoolz/dicttoolz.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
Failed to build lru-dict bitarray cytoolz
Installing collected packages: eth-typing, toolz, cytoolz, pycryptodome, eth-hash, eth-utils, six, parsimonious, eth-abi, varint, netaddr, base58, multiaddr, urllib3, certifi, idna, chardet, requests, ipfshttpclient, websockets, lru-dict, hexbytes, attrs, pyrsistent, jsonschema, protobuf, eth-keys, bitarray, rusty-rlp, rlp, eth-rlp, eth-keyfile, eth-account, web3
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ferhatkochan/.venv-py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"'; __file__='"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-record-slor93d9/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ferhatkochan/.venv-py3/include/site/python3.8/cytoolz
         cwd: /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/
    Complete output (54 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/compatibility.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/utils_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/_version.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/_signatures.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    creating build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/curried
    copying cytoolz/itertoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/utils.pyx -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/utils.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.macosx-10.9-x86_64-3.8/cytoolz
    creating build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.macosx-10.9-x86_64-3.8/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/cytoolz
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/ferhatkochan/.venv-py3/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.macosx-10.9-x86_64-3.8/cytoolz/dicttoolz.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ferhatkochan/.venv-py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"'; __file__='"'"'/private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-install-c6jweelu/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hw/g2s7r9sd1l77hn1y0c6t2ppm0000gn/T/pip-record-slor93d9/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ferhatkochan/.venv-py3/include/site/python3.8/cytoolz Check the logs for full command output.

**Comment by ferhatkkochan** [comment]
Installing X Code Command Line Tools and `python-dev-tools` has resolved the issue.

**Comment by kclowes** [comment]
Closing, since this is resolved!
