### ISSUE TITLE
Eth 2 Endpoints

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1758]
### What was wrong?
We'll need to add the Eth2 endpoints so that people can access that data. We'll also need good documentation and it would probably be nice to have a tutorial or two.

### How can it be fixed?
For the initial pass, @pipermerriam and I talked about making a new provider to access the endpoints and then putting the provider behind a flag much like the `enable_unstable_package_management_api` flag. The standardized API is found [here](https://github.com/ethereum/eth2.0-apis)

**Comment by marcgarreau** [comment]
MVP merged in. Work remains for input/output validation, documentation, etc., but we're early to the party, so we'll keep iterating. (Only Teku and Lighthouse support the API so far.)
