### ISSUE TITLE
How to catch contract exception in Web3 py?

### ISSUE THREAD

**Issue by bizso09** [ethereum/web3.py#1760]
I'm using infura.io with web3.py and I would like to catch exception thrown by smart contract. Currently, web3.py does not throw any exception even if the contract does, and hence it burns a lot of gas failing.

Since I'm using a public node, I have to sign the raw transactions before submitting

```
trans = contract.functions.addAdmin(address)
built = trans.buildTransaction({"gasPrice":...})
signed_tx = self.wallet.signTransaction(built)
tx_hash = self.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
```
The problem is that addAdmin throws an exception, but web3 py will just send the transaction any way and does not propagate it. How can I detect the error before sending?

**Comment by kclowes** [comment]
This issue is similar (I think) to #1762. From the comments there, you may try using Ganache, but there isn't a way in web3 to detect the error before sending. I am going to close this issue, but feel free to reopen if you have other questions, or if I misunderstood!

**Comment by bizso09** [comment]
in fact, there is a way. Need to call `web3.eth.estimateGas()` on the transaction. This will throw an error if an exception is encountered.
