### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1769]
* Version: 5.x
* Python: 3.9!
* OS: osx/linux/win

### What was wrong?

Now that Python 3.9 is out, we should make sure we can support it.

### How can it be fixed?

Pretty much anywhere that tests against Python 3.7 and 3.8, we should add Python 3.9. Python 3.8 support was added  #1471, so that would be a good template to follow.

**Comment by marcgarreau** [comment]
closed via #1774
