### ISSUE TITLE
use web3.py for other  ethereum-based blockchains

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [ethereum/web3.py#1771]
is this possible to use this library for other ethereum-based blockchains like binance smart chain(bsc) and if yes how?

**Comment by kclowes** [comment]
I don't know much about Binance, but I think that should be possible in theory. You would follow [these instructions](https://web3py.readthedocs.io/en/stable/overview.html#providers) to make your web3 instance with whatever provider and URL makes sense for you. Feel free to open another issue if you have specific questions!
