### ISSUE TITLE
Pip freeze

### ISSUE THREAD

**Issue by FeliciaXmL** [ethereum/web3.py#1772]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by kclowes** [comment]
Closing, since this is blank. Feel free to open another one with the details filled out if you have questions, @FeliciaXmL.
