### ISSUE TITLE
Benchmarking suite

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#1776]
### What was wrong?

We need a baseline for library performance.

### How can it be fixed?

We should create a benchmarking suite.  Here are some high level contraints.

- The code should live under `web3.tools.benchmarking`
- The benchmarking code should be run as part of the test suite.  These runs should be fast, intended to only ensure that the benchmarking suite works well, and thus the benchmarking suite should be parametrizable.
- The benchmarks need to run against our different providers (HTTP, IPC, websockets)

For testing methodology, I think we want to measure the following three things for each thing we benchmark.

1. base performance: making the request manually without using any of the Web3 APIs
1. provider performance by making the request directly from the provider without any of the `Web3` mechanics.
2. user facing performance by making the requests using the `Web3` APIs.

And as for what we benchmark, I suggest we start with

- `eth_blockNumber`
- `eth_getBlockByHash`

To *serve* the JSON-RPC, I think we want a dedicated provider running in a dedicated process that is serving these from memory so that we can minimize the server's impact on our performance numbers.  We could even go as far as logging the actual server time and accounting for this in our benchmarking numbers.

For IPC based JSON-RPC you can copy/pasta from here: https://github.com/ethereum/ddht/blob/9d6bf7d9d218cdad7ecb43f27452e3827456c02a/ddht/rpc.py

I think it would be best to start with testing a single provider type, and then to expand to the others once we've got the base framework in place.

Cues could be taken from the existing Lahja benchmarking suite: https://github.com/ethereum/lahja/tree/master/lahja/tools/benchmark

**Comment by pipermerriam** [comment]
This is marked as "good first issue", and it is, but it's also not going to be small or easy, it just won't require too much intimate knowledge of the library internals.

**Comment by kclowes** [comment]
@pipermerriam - Tiffany and I were talking about how to approach to this issue today, and wanted to make sure we had the API right for the testing methodology you lay out here: 

> For testing methodology, I think we want to measure the following three things for each thing we benchmark.
> 1. base performance: making the request manually without using any of the Web3 APIs
> 1. provider performance by making the request directly from the provider without any of the Web3 mechanics.
> 1. user facing performance by making the requests using the Web3 APIs.

Taking IPC as an example, implement the RPC server like you linked to in `ddht`, and then:

Base performance:
`RPCServer().execute_rpc()`

Provider performance: 
`Web3.IPCProvider('path/to/rpc/server').make_request(...)`

User facing performance: 
```
w3 = Web3(IPCProvider('path/to/rpc/server'))
w3.eth.block_number
```

Is that what you were thinking?

**Comment by pipermerriam** [comment]
Spot on

**Comment by Harmouch101** [comment]
@pipermerriam, I think I can handle this task if it is related to profiling or something like so.

**Comment by marcgarreau** [comment]
While still nascent, benchmarking got off the ground in #2002, so closing out this issue. New issues should be opened if we want to track more specifics.
