### ISSUE TITLE
Revert reason is successfully parsed as int number

### ISSUE THREAD

**Issue by sobolev-igor** [ethereum/web3.py#1781]
* Version: 5.12.3
* Python: 3.8/3.9
* OS: osx

### What was wrong?

I have a function that returns `uint256` value and has a revert with error text in it. The return value of the tx starts with `0x08c379a0` (e.g. `0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000184461692f696e73756666696369656e742d62616c616e63650000000000000000`) which is successfully parsed as `3963877391197344453575983046348115674221700746820753546331534351508065746944` number.

references: 
https://solidity.readthedocs.io/en/latest/control-structures.html#revert
https://web3js.readthedocs.io/en/v1.2.5/web3-eth-contract.html?highlight=revert#handlerevert

### How can it be fixed?

I suppose output length should be checked, and in case it starts with `0x08c379a0` return the following error message in the exception.

**Comment by marcgarreau** [comment]
Should be addressed by https://github.com/ethereum/web3.py/pull/1585 in the next release; please reopen after the release if not the case.
