### ISSUE TITLE
Incorrect docs for Eth.getTransaction: it doesn't throw when TX is not mined yet

### ISSUE THREAD

**Issue by cygnusv** [ethereum/web3.py#1799]
### What was wrong?

Documentation on the `Eth.getTransaction()` method states:

> Returns the transaction specified by `transaction_hash`. If the transaction has not yet been mined throws `web3.exceptions.TransactionNotFound`.

That last sentence is not true: if the TX is pending it still gives you the TX data.

### How can it be fixed?

Specify what are the correct conditions for `eth.getTransaction()` to throw `web3.exceptions.TransactionNotFound`.

**Comment by kclowes** [comment]
Thanks for the report @cygnusv! Sorry for the long response time. I will take a look!

**Comment by fselmo** [comment]
This has since been updated
