### ISSUE TITLE
`getTransactionCount` fails with a block identifier using `web3[tester]`

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/web3.py#1801]
* Version: 5.13.0
* Python: 3.7
* OS: osx

### What was wrong?

```python
import web3
import eth_tester

backend = eth_tester.PyEVMBackend()
w3 = web3.Web3(web3.Web3.EthereumTesterProvider(backend))

w3.eth.getTransactionCount(w3.eth.accounts[0], 0)
```

This code fails when it should succeed. It seems that `web3.py` automatically formats block references to hex numbers but `eth-tester` `get_nonce` expects it to be a number.

### How can it be fixed?

This could possibly be an `eth-tester` issue but I've added it here for coverage.

**Comment by Pet3ris** [comment]
Two possible fixes:

One would be to accept hexadecimal block numbers on the `eth-tester` side https://github.com/ethereum/eth-tester/blob/171dce6074d6ee1b7dd6d97dbd0df397259d421d/eth_tester/backends/pyevm/main.py#L194.

Another would be to fix the formatting for `get_nonce` rpc calls on the `web3.py` side.

**Comment by kclowes** [comment]
Thanks for the report @Pet3ris! I want to double check, but I think we'll want to fix this on the eth-tester side.
