### ISSUE TITLE
Multiple events found

### ISSUE THREAD

**Issue by Activity00** [ethereum/web3.py#1804]
* Version: 5.12.1
* Python: 3.7.0
* OS: linux

### What was wrong?
/usr/local/lib/python3.7/site-packages/web3/_utils/contracts.py in find_matching_event_abi
raise ValueError("Multiple events found")

https://etherscan.io/tx/0x59054d383a9b3dd5289ebd994bc6fb95dd66fee741a33f1da9aa9a0b4a04a086#eventlog
same name event

**Comment by pipermerriam** [comment]
@Activity00 it is helpful for you to supply more context for this.  Can you supply the actual code you are using that triggered this error?


@kclowes here's where we need an API for retrieving an event directly by it's topic which a brief scan of the code suggests that 1) we might have never implemented a way to retrieve events that have duplicate names and 2) That we have inadequate documentation on the different ways there are to access an event.

**Comment by kclowes** [comment]
Yeah, I believe there is a half-baked PR up to allow overloaded events, but it still needs more work. And more documentation is always good! cc @marcgarreau to add to the tutorial/blog post list

**Comment by marcgarreau** [comment]
An attempt was made (https://github.com/ethereum/web3.py/pull/1705), but after digging in a bit, we found that a larger effort was required. Details/suggestions for how to go about it are in the PR. I just added a `help wanted` label, which I should've done before moving on to other priorities.

**Comment by pacrob** [comment]
Dup of #1704. Closing.
