### ISSUE TITLE
Problem with installing web3 on Ubuntu 18.04

### ISSUE THREAD

**Issue by zak100** [ethereum/web3.py#1811]
* Version: x.x.x
* Python: 2.7.17/3.6.9/Pycharm community 2020.3
* OS: ubuntu 18.04
* `pip freeze` output
~$ pip install web3
Collecting web3
  Using cached https://files.pythonhosted.org/packages/85/01/eacb73ae16364295bf26cba4aacc94e513f5feae54dbb5f8121bec697e49/web3-4.8.1.tar.gz
web3 requires Python '>=3.5.3,<4' but the running Python is 2.7.17

```
<put the output from running pip freeze here>
```
~$ `pip freeze` output
anytree==2.8.0: command not found
@lc2530hz:~$ 

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

$ pip install  web3
Collecting web3
  Using cached https://files.pythonhosted.org/packages/85/01/eacb73ae16364295bf26cba4aacc94e513f5feae54dbb5f8121bec697e49/web3-4.8.1.tar.gz
web3 requires Python '>=3.5.3,<4' but the running Python is 2.7.17
@lc2530hz:~$ `pip freeze` output
anytree==2.8.0: command not found
@lc2530hz:~$ 

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.
I have 3 versions of Python installed on my system. This might be the problem.
Somebody please guide me. I would highly appreciate your help.
Zulfi.
zulfi6000@yahoo.com

**Comment by kclowes** [comment]
It looks like you're using python 2.7 which isn't supported by web3. You need to upgrade to python 3.6 or higher. You might try installing something like [pyenv](https://github.com/pyenv/pyenv) to manage your python versions. Closing, but feel free to reopen if that doesn't fix your issue!

**Comment by zak100** [comment]
Hi,

I am still trying to  install web3 on my ubuntu 18.04 system. I am using the following command:

@lc2530hz:~$ sudo npm install -g web3

but I am getting the error:

    sudo: npm: command not found

But when I am typing: @lc2530hz:~$ npm --version 6.14.6

I have node version 10 installed on my system. Kindly guide me how to solve this problem.

Zulfi.

**Comment by kclowes** [comment]
npm is the package manager for JavaScript. So if you want to install web3py, you'll need to do a `pip install web3`. If you're trying to use web3js, you'll have to raise an issue on their repo.

**Comment by zak100** [comment]
Hi,I did "pip install web3"
I got following message at the end:
Successfully built bitarray pyrsistent cytoolz
Installing collected packages: hexbytes, certifi, idna, urllib3, chardet, requests, pycryptodome, eth-hash, toolz, cytoolz, eth-typing, eth-utils, six, parsimonious, eth-abi, bitarray, eth-keys, eth-keyfile, rlp, eth-rlp, eth-account, websockets, base58, zipp, importlib-resources, netaddr, varint, multiaddr, ipfshttpclient, lru-dict, pyrsistent, typing-extensions, importlib-metadata, attrs, setuptools, jsonschema, protobuf, web3
Successfully installed attrs-20.3.0 base58-2.0.1 bitarray-1.2.2 certifi-2020.12.5 chardet-4.0.0 cytoolz-0.11.0 eth-abi-2.1.1 eth-account-0.5.4 eth-hash-0.2.0 eth-keyfile-0.5.1 eth-keys-0.3.3 eth-rlp-0.2.1 eth-typing-2.2.2 eth-utils-1.9.5 hexbytes-0.2.1 idna-2.10 importlib-metadata-3.3.0 importlib-resources-3.3.0 ipfshttpclient-0.7.0a1 jsonschema-3.2.0 lru-dict-1.1.6 multiaddr-0.0.9 netaddr-0.8.0 parsimonious-0.8.1 protobuf-3.14.0 pycryptodome-3.9.9 pyrsistent-0.17.3 requests-2.25.1 rlp-2.0.1 setuptools-51.1.0.post20201221 six-1.15.0 toolz-0.11.1 typing-extensions-3.7.4.3 urllib3-1.26.2 varint-1.0.2 web3-5.13.1 websockets-8.1 zipp-3.4.0
zulfi@lc2530hz:~$ web3

Command 'web3' not found, did you mean:

  command 'deb3' from deb quilt

Try: sudo apt install <deb name>

@lc2530hz:~$ 
What does it mean? 

Does it mean that I installed web3? 

But when I did:
~$ web3

Command 'web3' not found, did you mean:

  command 'deb3' from deb quilt

Try: sudo apt install <deb name>

@lc2530hz:~$ 


Kindly guide me whether I installed web3 or not?
Zulfi.

    On Monday, December 21, 2020, 2:42:08 PM CST, kclowes <notifications@github.com> wrote:  
 
 


npm is the package manager for JavaScript. So if you want to install web3py, you'll need to do a pip install web3. If you're trying to use web3js, you'll have to raise an issue on their repo.

**Comment by kclowes** [comment]
It looks to me like the build succeeded, but we don't have a command line interface which is why you can't run just `web3` from the command line. In a REPL, try `from web3 import Web3`. If it succeeds, then web3 installed successfully.

**Comment by MdSamsuzzohaShayon** [comment]
you may need to install those 
```
sudo apt-get install python-dev 
sudo apt-get install python3-dev 
sudo apt-get install libevent-dev
```

**Comment by akashsenta13** [comment]
@MdSamsuzzohaShayon  : Installing mentioned library works. Allowed me to install web3 after that. Thanks
