### ISSUE TITLE
web3.exceptions.MismatchedABI: The event signature did not match the provided ABI

### ISSUE THREAD

**Issue by yaocg** [ethereum/web3.py#1830]
* Version: 5.14.0
* Python: 3.7.9
* OS: linux
* `pip freeze` output

```
APScheduler==3.6.3
asgiref==3.3.1
attrs==20.3.0
base58==2.0.1
binwalk===2.2.0-ff34b12
bitarray==1.2.2
certifi==2019.3.9
chardet==3.0.4
cytoolz==0.11.0
Django==3.1.4
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.0
idna==2.8
importlib-metadata==3.3.0
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lru-dict==1.1.6
Markdown==3.3.3
multiaddr==0.0.9
netaddr==0.8.0
numpy==1.17.2
pandas==0.25.1
parsimonious==0.8.1
protobuf==3.14.0
pycryptodome==3.9.9
pyrsistent==0.17.3
python-bitcoinlib==0.10.2.dev0
python-dateutil==2.8.0
pytz==2019.2
redis==3.5.3
requests==2.21.0
rlp==2.0.1
six==1.12.0
sqlparse==0.4.1
toolz==0.10.0
typing-extensions==3.7.4.3
tzlocal==2.1
uniswap-v2-asynctomatic @ git+git://github.com/asynctomatic/uniswap-v2-py.git@3bd3d2e5f3b30f2ae5327b42c5a55e5450c3fda7
urllib3==1.24.3
varint==1.0.2
virtualenv==16.7.5
web3==5.14.0
websockets==8.1
zipp==3.4.0
```

### What was wrong?
event_abi_to_log_topic(event_abi) return: b'\x1cA\x1e\x9a\x96\xe0q$\x1c/!\xf7rk\x17\xae\x89\xe3\xca\xb4\xc7\x8b\xe5\x0e\x06+\x03\xa9\xff\xfb\xba\xd1' 
log_entry['topics'][0] return: 0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1

in file:web3/_utils/events.py

    209     # type ignored b/c event_abi_to_log_topic(event_abi: Dict[str, Any])
    210     elif event_abi_to_log_topic(event_abi) != log_entry['topics'][0]:  # type: ignore
    211         raise MismatchedABI("The event signature did not match the provided ABI")

error:
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    print(x.processLog(log))
  File "/home/xxx/.local/lib/python3.7/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/web3/contract.py", line 1172, in processLog
    return get_event_data(self.web3.codec, self.abi, log)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/xxx/.local/lib/python3.7/site-packages/web3/_utils/events.py", line 211, in get_event_data
    raise MismatchedABI("The event signature did not match the provided ABI")
web3.exceptions.MismatchedABI: The event signature did not match the provided ABI

**Comment by kclowes** [comment]
@yaocg That error says that there is a mismatch between the event returned and the ABI that web3 is trying to decode it with, but I can't tell much more without a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). If you provide that I can help you troubleshoot some more.

**Comment by dvdblk** [comment]
@yaocg how did you solve it? I'm having the exact same issue.

When I encode it manually I get the same topics but the `get_event_data` raises `MismatchedABI`.
