### ISSUE TITLE
Upgrade to hypothesis v6.0

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1832]
* Version: 5.14

### What was wrong?
Hypothesis v5 introduced a bunch of deprecation warnings around fixture scoping that need to be addressed before we can upgrade to v6.

### How can it be fixed?
Fix deprecation warnings. This will probably best be done in a few, smaller PRs The warnings can be seen on any of our core test CI runs.

**Comment by pacrob** [comment]
Done!
