### ISSUE TITLE
Support ENS multicoin EIP-2304

### ISSUE THREAD

**Issue by vnavascues** [ethereum/web3.py#1839]
* Version: 5.11.1
* Python: 3.7
* OS: osx/linux/win

[ENS PublicResolver](https://docs.ens.domains/contract-api-reference/publicresolver)
[EIP-2304](https://eips.ethereum.org/EIPS/eip-2304)

`RESOLVER` would require something like this:
```python
  {
      "constant": True,
      "inputs": [
          {
              "name": "node",
              "type": "bytes32"
          },
          {
              "name": "coinType",
              "type": "uint256"
          },
      ],
      "name": "addr",
      "outputs": [
          {
              "name": "ret",
              "type": "bytes"
          }
      ],
      "payable": False,
      "type": "function"
  },
```

[bruno.eth](https://app.ens.domains/name/bruno.eth) is an ENS domain with multiple coins set up.

By calling `addr(bytes32, unit256)` on its public resolver with:
- bytes32: `0x9de0b76f3b87380f0bcb9e41b403c69b88b01fbeaf785e83f38a6879902af71b`
- uint256: `434`

You should expect:
- bytes: `0x0aff6865635ae11013a83835c019d44ec3f865145943f487ae82a8e7bed3a66b`

Thanks

**Comment by kclowes** [comment]
Thanks for raising this issue! I'm for it, but will probably take a bit for us to get to it. If you'd like this feature soon, feel free to open a PR and we'd be happy to review!

**Comment by vnavascues** [comment]
> Thanks for raising this issue! I'm for it, but will probably take a bit for us to get to it. If you'd like this feature soon, feel free to open a PR and we'd be happy to review!

Hi! No rush at least for me. If I find some time definitely I'll try to open a PR.
