### ISSUE TITLE
Update docs for web3.eth API

### ISSUE THREAD

**Issue by NikitosnikN** [ethereum/web3.py#1868]
### What was wrong?

Docs for `eth.getTransactionReceipt`, `eth.waitForTransactionReceipt` is outdated. Response of these methods is different:
It includes `logsBloom`, `status` fields and does not include `root` field.

Also it is impossible to find information about transaction status (if it is successful or it was reverted) in web3.py docs, but this info can be found in simular section [web3.js docs](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#eth-gettransactionreceipt-return).

### How can it be fixed?

Update web3.eth API method responses, add info about returned parameters

**Comment by marcgarreau** [comment]
thanks for the PR!
