### ISSUE TITLE
Getting the block_number asynchronously is hacky

### ISSUE THREAD

**Issue by hoh** [ethereum/web3.py#1875]
* Version: 5.16.0
* Python: 3.8.5

### What was wrong?

PR #1851 `Moving blockNumber -> block_number` replaced a function with a `@property`.

Since that peoperty does RPC under the hood, which blocks on the network, using a property here does not seem intuitive, but more importantly it makes it more difficult to get that information in a non-blocking way.

This is an issue when running this in a Thread, Process or Asyncio eventloop. In an asyncio process for example, one would have to do the following replacement:
```diff
- return await loop.run_in_executor(None, w3.eth.block_number)
+ return await loop.run_in_executor(None, getattr, (w3.eth, 'block_number'))
```

or alternatively to call the underlying method, which the underscore marks as private and best practices recommend against using:
```python
- return await loop.run_in_executor(None, w3.eth.block_number)
- return await loop.run_in_executor(None, w3.eth._block_number)
```

### How can it be fixed?

The underlying methods could be made public instead of private:
```diff
-    _block_number: Method[Callable[[], BlockNumber]] = Method(
+    get_block_number: Method[Callable[[], BlockNumber]] = Method(
        RPC.eth_blockNumber,
        mungers=None,
    )

    @property
    def block_number(self) -> BlockNumber:
-        return self._block_number()
+        return self.get_block_number()
```

Alternatively, an async API on web3 would be great, since parts of it already such as WebsocketProvider use asyncio under the hood.

**Comment by kclowes** [comment]
@hoh thank you for the report! It's historically been a property, and I think it accidentally became a public method, but I don't have any problem moving it back to being a public method as well :thumbsup:
