### ISSUE TITLE
Gas Price Cache Strategy not working

### ISSUE THREAD

**Issue by datgrog** [ethereum/web3.py#1881]
Python 3.8.1
web3.py 5.15.0

Using the doc (https://web3py.readthedocs.io/en/stable/gas_price.html#selecting-the-gas-price-strategy) with Infura's ropsten node

```
from web3 import Web3, middleware
from web3.gas_strategies.time_based import glacial_gas_price_strategy

w3 = Web3(Web3.HTTPProvider('https://ropsten.infura.io/v3/PROJECT_ID'))
w3.eth.setGasPriceStrategy(glacial_gas_price_strategy)

w3.middleware_onion.add(middleware.time_based_cache_middleware)
w3.middleware_onion.add(middleware.latest_block_based_cache_middleware)
w3.middleware_onion.add(middleware.simple_cache_middleware)

>>> glacial_gas_price_strategy(w3, None)
    1000000000 // ~1min30sec
>>> glacial_gas_price_strategy(w3, None)
    1000000000 // ~1min30sec
>>> w3.eth.gasPrice
    1209362578 // instant
```

I expected that the first time I called the glacial_gas_price_strategy it would take time but not the second time I called it because of the cache set but it does not appear to change anything. I am using it wrong ?

**Comment by marcgarreau** [comment]
Hey @datgrog, this part of the world could be better documented. In your case, you're executing the `glacial_gas_price_strategy` outside of the w3 instance and its middleware. Try `w3.eth.generateGasPrice()` instead. Subsequent calls should be quicker.

I did a quick demo with the `medium_gas_price_strategy` and found the first call took ~35 seconds, and subsequent calls were ~8 seconds. That's longer than I'd expect, but I may be bumping up against a different issue there, as the latter calls are producing different gas numbers and not just fetching from cache.

**Comment by datgrog** [comment]
Many thanks for your reply ✌️
