### ISSUE TITLE
Failure Installing 'tester' Extra With Pip

### ISSUE THREAD

**Issue by poisson-aerohead** [ethereum/web3.py#1885]
* Version: 5.16.0
* Python: 3.9.1
* OS: linux
* `pip freeze` output

```
alabaster==0.7.12
appdirs==1.4.4
asn1crypto==1.4.0
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
base58==2.1.0
bitarray==1.2.2
breezy==3.1.0
CacheControl==0.12.6
certifi==2020.6.20
cffi==1.14.5
chardet==3.0.4
colorama==0.4.4
configobj==5.1.0.dev0
contextlib2==0.6.0.post1
cryptography==3.3.1
cvxopt==1.2.6
cycler==0.10.0
cypari2==2.1.2
cysignals==1.10.2
cytoolz==0.11.0
decorator==4.4.2
distlib==0.3.1
distro==1.5.0
docutils==0.16
dulwich==0.20.19
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-tester==0.5.0b3
eth-typing==2.2.2
eth-utils==1.10.0
fastimport==0.9.8
fpylll==0.5.5
future==0.18.2
gmpy2==2.1.0b5
hexbytes==0.2.1
html5lib==1.1
idna==2.10
imagesize==1.2.0
ipfshttpclient==0.7.0a1
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.17.2
Jinja2==2.11.3
jsonschema==3.2.0
kiwisolver==1.3.1
lensfun==0.3.95
lit==0.11.1.dev0
louis==3.16.0
lru-dict==1.1.7
MarkupSafe==1.1.1
matplotlib==3.3.4
mercurial==5.7
mpmath==1.2.1
msgpack==1.0.2
multiaddr==0.0.9
netaddr==0.8.0
networkx==2.5
numpy==1.20.0
ordered-set==4.0.2
packaging==20.9
parsimonious==0.8.1
parso==0.7.1
patiencediff==0.2.1
pep517==0.9.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
ply==3.11
pplpy==0.8.7
progress==1.5
prompt-toolkit==3.0.16
protobuf==3.15.1
psutil==5.8.0
ptyprocess==0.7.0
py-geth==2.4.0
pyasn1==0.4.8
pycparser==2.20
pycryptodome==3.10.1
Pygments==2.8.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
PyQt5==5.15.2
PyQt5-sip==12.8.1
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
resolvelib==0.5.4
retrying==1.3.3
rlp==2.0.1
rpy2==3.4.2
sage==9.2
scipy==1.6.1
semantic-version==2.8.5
six==1.15.0
snowballstemmer==2.1.0
Sphinx==3.5.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sympy==1.7.1
toml==0.10.2
toolz==0.11.1
traitlets==5.0.5
tzlocal==2.1
urllib3==1.26.3
validate==5.1.0.dev0
varint==1.0.2
w3lib==1.22.0
wcwidth==0.2.5
web3==5.16.0
webencodings==0.5.1
websockets==8.1

```

### What was wrong?

I attempted to install the 'testers' extra with

pip install 'web3[tester]'

I received the following error:

  Using cached netaddr-0.7.3.zip (1.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-01qwfzc7/netaddr_1a2b2c61623442e988382d8d91bc40c1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-01qwfzc7/netaddr_1a2b2c61623442e988382d8d91bc40c1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vmfvs8ah
         cwd: /tmp/pip-install-01qwfzc7/netaddr_1a2b2c61623442e988382d8d91bc40c1/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-01qwfzc7/netaddr_1a2b2c61623442e988382d8d91bc40c1/setup.py", line 23
        print "netaddr requires Python version 2.4.x or higher."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("netaddr requires Python version 2.4.x or higher.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I reran with a log file which is attached below.

[web3tester.pip.log](https://github.com/ethereum/web3.py/files/6026401/web3tester.pip.log)

FWIW, I'm not a python expert but I attempted to read the pip files a bit and found the requires extra section of setup.py. I traced through those, attempting installs, and this may be a eth-tester[py-evm] installation problem. Looking at those projects on pypi, it seems most of the maintainers overlap, though.

Please let me know if any more info will help.

EDIT:
I can see that it is having trouble resolving a dependency and is looking at "too many" past versions of netaddr, eventually getting to files written for python2. I just figure that rather than hacking some solution there must be a real reason that this is happening. As you can see, I already have a netaddr.

**Comment by kclowes** [comment]
Sorry for the long response time. Unfortunately, it looks like you're running python 3.9 which we don't support yet. Try downgrading to 3.8. If that doesn't fix your issue feel free to reopen!
