### ISSUE TITLE
Getting: AttributeError: 'Eth' object has no attribute 'xxxx(any)'

### ISSUE THREAD

**Issue by Pol-Lanski** [ethereum/web3.py#1889]
* Version: 
```
>>> w3.api
'5.0.0'
```
* Python: 3.9.1
* OS: osx
* `pip freeze` output:

```
appdirs==1.4.4
appnope==0.1.0
argon2-cffi==20.1.0
async-generator==1.10
atomicwrites==1.4.0
attrdict==2.0.1
attrs==20.3.0
backcall==0.2.0
base58==2.0.1
beautifulsoup4==4.9.3
bleach==3.2.1
cadCAD==0.4.23
certifi==2020.11.8
cffi==1.14.3
chardet==3.0.4
cycler==0.10.0
cytoolz==0.11.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
distlib==0.3.1
dydx-python==0.11.2
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.9.5
filelock==3.0.12
fn==0.4.3
funcy==1.15
hexbytes==0.2.1
idna==2.8
importlib-metadata==0.23
ipfshttpclient==0.6.1
ipykernel==5.3.2
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
json5==0.9.5
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab==2.2.0
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
kiwisolver==1.3.1
lru-dict==1.1.6
lxml==4.6.2
MarkupSafe==1.1.1
matplotlib==3.3.0
mistune==0.8.4
more-itertools==8.6.0
multiaddr==0.0.9
multiprocess==0.70.11.1
multitasking==0.0.9
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.3
netaddr==0.8.0
notebook==6.0.3
numpy==1.19.4
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.3
parsimonious==0.8.1
parso==0.7.1
pathos==0.2.7
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.0.1
plotly==4.11.0
pluggy==0.13.1
pox==0.2.9
ppft==1.6.6.3
prometheus-client==0.8.0
prompt-toolkit==3.0.8
protobuf==3.14.0
ptyprocess==0.6.0
py==1.9.0
pycparser==2.20
pycryptodome==3.9.9
Pygments==2.7.2
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==4.6.11
python-dateutil==2.8.1
pytz==2020.4
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.22.0
requests-mock==1.6.0
retrying==1.3.3
rlp==1.2.0
scipy==1.5.4
seaborn==0.10.1
Send2Trash==1.5.0
six==1.12.0
soupsieve==2.0.1
statsmodels==0.12.0
terminado==0.9.1
testpath==0.4.4
toml==0.10.2
toolz==0.11.1
tornado==6.1
tox==3.13.2
traitlets==5.0.5
urllib3==1.25.11
varint==1.0.2
virtualenv==20.2.1
wcwidth==0.2.5
web3==5.0.0
webencodings==0.5.1
websockets==7.0
widgetsnbextension==3.5.1
yfinance==0.1.55
zipp==3.4.0
```

### What was wrong?

I can't seem to use any of the `web3.eth` methods

Other calls like `web3.api` or `web3.clientVersion` work, so the object is created.

I'm using Jupyter Notebook.

* The code which produced the error
`w3.eth.chain_id`
or
`w3.eth.get_block('latest')`

* The full output of the error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-70b856a4c410> in <module>
----> 1 w3.eth.get_block('latest')

AttributeError: 'Eth' object has no attribute 'get_block'
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-9e974a6bb0e9> in <module>
----> 1 w3.eth.chain_id

AttributeError: 'Eth' object has no attribute 'chain_id'
```

* What type of node you were connecting to.
```
w3.clientVersion
'Nethermind/v1.9.47-0-e99cadc8b-20210224/X64-Linux/Core3.1.10'
```

### How can it be fixed?

Not sure what I'm doing wrong :)

**Comment by marcgarreau** [comment]
Hey @Pol-Lanski, typically this is because you haven't configured a web3 provider. See the docs [here](https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-can-t-i-use-a-particular-function). Closing, but please reopen if that wasn't your issue.

**Comment by Pol-Lanski** [comment]
Hey @marcgarreau , thanks a bunch, I really appreciate the help!
Unless I'm forgetting something super basic, I have configured a web3 provider.

I am connected to my local Nethermind Node, but I also tried with infura to make sure it wasn't my node, with the same result: 
`w3 = Web3(Web3.HTTPProvider('http://fullnode.dappnode:8545'))`
and also
`w3 = Web3(Web3.HTTPProvider("https://mainnet.infura.io/v3/XXX"))`

`w3.isConnected()` returns `True` with both.

**Comment by pipermerriam** [comment]
I think it's because he's using `web3==5.0.0`.  Try `w3.eth.getBlock`.  Those methods were recently migrated to snake case.

**Comment by Pol-Lanski** [comment]
Oh my god. Thanks @pipermerriam , that made it :) I knew it had to be something super stupid and I was starting to go crazy!
Admittedly, I'm also not great at this :)

Thanks a lot!

**Comment by pipermerriam** [comment]
glad we could get it figured out.  Reach back out if you run into any more problems.

**Comment by BarryB-dev** [comment]
I am having a very similar issue but neither get_block nor getBlock work, I am web3 V5.31.1 and infura as a websocketprovider.
The only method that works is w3.eth.chainId

`from web3 import Web3, EthereumTesterProvider, WebsocketProvider
import web3

w3 = Web3(Web3.WebsocketProvider('wss://mainnet.infura.io/ws/v3/myapikey'))

print(w3.eth.chainId)

#w3.clientVersion --#doesnt work
#w3.is_connected()  --#doesnt work

try:
    print(web3.eth.get_block('latest'))
except:
    print(web3.eth.getBlock('latest'))`

any ideas?

**Comment by pacrob** [comment]
In v5.31.1, you need `isConnected`. `clientVersion` should be fine though. In your try/except you want `w3.eth.get_block`, not `web3.eth.get_block`

For further help, please check out our [discord](https://discord.gg/GHryRvPB84)
