### ISSUE TITLE
add package to conda-forge

### ISSUE THREAD

**Issue by spinoch** [ethereum/web3.py#1892]
pip environments are easily broken, (conda)[https://docs.conda.io/] solves most of these issues by tracking package versions and their dependencies to prevent broken environments

All of `web3`'s dependencies are already on `conda` except for `pypiwin32`. Adding `web3` to conda-forge would be trivial if it were not for this dependency. I am not entirely aware what the value is of having `pypiwin32` as a hard requirement for web3, could it be an optional requirement or if it's no longer used, removed altogether?

**Comment by kclowes** [comment]
It's for windows users to allow them to use the package, so we can't delete it. However, it's pretty outdated AFAIK, and there is a PR up to swap it out for `pywin32` that keeps getting deprioritized. I don't use conda, but it looks like pywin32 is on conda-forge, is that right? If so, I can work on spinning up a Windows virtualenv to test/review the PR.

**Comment by spinoch** [comment]
Thanks for clarifying.

> t looks like pywin32 is on conda-forge, is that right?

That's right: https://anaconda.org/conda-forge/pywin32

>  If so, I can work on spinning up a Windows virtualenv to test/review the PR.

That'd be great

**Comment by spinoch** [comment]
I'll close this as the conda-forge recipe already exists
