### ISSUE TITLE
Does not work on M1 Macs

### ISSUE THREAD

**Issue by JoshuaMulliken** [ethereum/web3.py#1894]
* Version: 5.17.0
* Python: 3.9.2
* OS: osx
* `pip freeze` output

```
asttokens==2.0.4
attrs==20.3.0
base58==2.1.0
bitarray==1.2.2
certifi==2020.12.5
chardet==4.0.0
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.15.5
pycryptodome==3.10.1
pyrsistent==0.17.3
requests==2.25.1
rlp==2.0.1
semantic-version==2.8.5
six==1.15.0
toolz==0.11.1
urllib3==1.26.3
varint==1.0.2
vyper==0.2.11
web3==5.17.0
websockets==8.1
```

### What was wrong?

<img width="948" alt="CleanShot 2021-03-06 at 17 13 19@2x" src="https://user-images.githubusercontent.com/36283247/110222306-42c46880-7e9f-11eb-9dc3-f81c610658f5.png">

### How can it be fixed?

I am not sure but I believe some of the dependencies need to be updated to support this.

**Comment by kclowes** [comment]
I can confirm that the library does work on M1 macs, but we don't yet support python 3.9. Try using python 3.8 and feel free to reopen if that doesn't do it!
