### ISSUE TITLE
eth_newPendingTransactionFilter does not exist

### ISSUE THREAD

**Issue by tobiwankenobii** [ethereum/web3.py#1899]
### What was wrong?

```
w3 = Web3(Web3.WebsocketProvider(infura))
w3.eth.filter({'fromBlock': 'latest', 'toBlock': 'pending'})
```
returns:
`ValueError: {'code': -32002, 'message': 'pending logs not supported'}`

```
w3 = Web3(Web3.WebsocketProvider(infura))
w3.eth.filter('pending')
```
returns:
`ValueError: {'code': -32601, 'message': 'The method eth_newPendingTransactionFilter does not exist/is not available'}`

### How can it be fixed?

It's probably related to request param getting changed to `newPendingTransactions`, described [here](https://community.infura.io/t/python-getting-pending-transactions/2124/3).

Contact Infura and change the param.

### BTW

I don't want to be rude but this is the worst written package for Python that i have ever seen. It's impossible to read, it's impossible to check the annotations, it's impossible to overwrite some behaviours because of poor architecture, it's impossible to use some features as mentioned above. This is just terrifyng, i would advice to start it from the begining, cuz it doesnt even look like it's possible to refactor...

**Comment by kclowes** [comment]
It looks like Infura doesn't support the RPC method `eth_newPendingTransactionFilter`, and web3py doesn't support `eth_subscribe` at this point but we plan to in the future (see #1402). One workaround is to use your own local node instead of a hosted one. Closing since the eth_subscribe/unsubscribe feature request is already tracked, and this isn't a bug in web3.

**Comment by tobiwankenobii** [comment]
LOL, so since almost 1.5 year there is completely no implemenation regarding one of the most used endpoints?
Which could be implemented in like 5 lines?
```
async with websockets.connect(infura_wss) as websocket_client:
    request_data = {"jsonrpc": "2.0", "id": 1, "method": "eth_subscribe", "params": ["newPendingTransactions"]}
    await websocket_client.send(json.dumps(request_data))
    result = await websocket_client.recv()
```
Well, obviously `it could`, in some normal project where you can move it in some kind of service and make it available in whole package. But here it's impossible, like many things mentioned above.

I really don't like this kind of "subofficial" awful packages, because they are discouringing normal devs to create normal packages for such purposes. So don't say this isn't a bug in web3, because web3js is handling it properly without doing "workarounds" and it's actually readable (wow, it's possible to write readable package even in js).

Finally, I would like to add that there is a paradox in this package - the more you study the code, the less you know. And let's end our discussions here.

**Comment by pipermerriam** [comment]
@tobiwankenobii this is an open source project.  The way you are engaging with us doesn't work for me.  If you don't like this library you can:

1. Not use it.
2. Improve it with pull requests or contributions
3. Provide constructive feedback that is kind and respectful

The way you are currently interacting with us isn't acceptable and won't be tolerated going forward.
