### ISSUE TITLE
Standardize `apply_formatter_to_array` 

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1902]
* Version: v6

### What was wrong?

The eth-utils and web3 `apply_formatter_to_array` functions are slightly different. We should standardize on one or the other (probably the eth-utils version). The `apply_formatter_to_array` function in web3 converts the return value to an array and the eth-utils version does not.

**Comment by dbfreem** [comment]
if the desire is to standardize on one should we just remove apply_formatter_to_array from web3 and utilize the one from eth-utils?
