### ISSUE TITLE
Clarify snake case migration strategy

### ISSUE THREAD

**Issue by ulope** [ethereum/web3.py#1918]
### What was wrong?

In recent releases a bunch of RPC methods became deprecated and suggest to use the new snake_case alternative.
However only a small handfull of methods so far seem to be converted.

This piecemeal way of converting the namespace is quite confusing and additionally causes ongoing maintenance burden on downstream projects.

Please clarify what the strategy going forward is going to be be. I.e.:
- When will the old methods be removed 
- Will all methods be converted before the first deprecated ones are removed?

**Comment by kclowes** [comment]
Sorry for the confusion and added burden! The goal was to keep PRs small and easy to review so we don't miss anything. 

Here are the answers to your questions:

> When will the old methods be removed

Old methods will be around until v6. We try very hard to not introduce breaking changes in minor version releases. The exception to this rule is if our dependencies (Geth, Parity/OE, Infura, etc.) make breaking changes and we have to incorporate them right away. For example, when Infura started requiring an API key for all requests, or the clients all dropped support for the whisper protocol.

> Will all methods be converted before the first deprecated ones are removed?

Yes, all methods will be deprecated in v5 and will not be removed until the v6 release. 

Feel free to reopen if you have other questions!
