### ISSUE TITLE
BlockNotFound and TransactionNotFound don't fire with TurboGeth

### ISSUE THREAD

**Issue by banteg** [ethereum/web3.py#1931]
* Version: 5.11.1
* Python: 3.8
* OS: linux
* `pip freeze` output

### What was wrong?

There is inconsistent behavior between Geth and TurboGeth when requesting nonexistent blocks and transactions.

Geth returns null, which raises an exception, while TurboGeth returns an RPC error.

```python
# geth
>>> web3.eth.getTransaction(txid)
  File "<console>", line 1, in <module>
  File "web3/eth.py", line 290, in getTransaction
    raise TransactionNotFound(f"Transaction with hash: {transaction_hash} not found.")
TransactionNotFound: Transaction with hash: 0xaa1e8bb8679f89579406598fa789ee6570ed529b4453b43ec81b5a4093e31e9f not found.

>>> web3.eth.getBlock(10**9)
  File "<console>", line 1, in <module>
  File "web3/eth.py", line 222, in getBlock
    raise BlockNotFound(f"Block with id: {block_identifier} not found.")
BlockNotFound: Block with id: 1000000000 not found.

# turbo-geth
>>> web3.eth.getTransaction(txid)
  File "<console>", line 1, in <module>
  File "web3/eth.py", line 285, in getTransaction
    result = self.web3.manager.request_blocking(
  File "web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'transaction 0xaa1e8bb8679f89579406598fa789ee6570ed529b4453b43ec81b5a4093e31e9f not found'}

>>> web3.eth.getBlock(10**9)
  File "<console>", line 1, in <module>
  File "web3/eth.py", line 217, in getBlock
    result = self.web3.manager.request_blocking(
  File "web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'block not found: 1000000000'}
```

### How can it be fixed?

This can be fixed on either web3py or TurboGeth side.

**Comment by pipermerriam** [comment]
I *think* that this is worth considering as an extensible compatibility layer.  When different providers have different behavior, adding special cases to the core library code isn't a very scalable solution.  Ideally, we could do something like registering a turbo-geth specific error handler (or multiple error handlers) that allow shimming this behavior.

Could be something very simple...

```python
from web3.tools.turbo_geth import turbo_geth_error_handler

w3 = Web3(...)
# add a handler
w3.register_error_handler(turbo_geth_handler)
# remove a handler
w3.remove_error_handler(turbo_geth_handler)
```

Just a thought.  The counter-argument is that this adds more complexity to the pipeline, which is already quite complex...

**Comment by alcuadrado** [comment]
Good news! This has been fixed in TurboGeth: https://github.com/ledgerwatch/turbo-geth/issues/1645

**Comment by kclowes** [comment]
Awesome! I'm going to close issue then. I believe the other way you could handle this is through some custom middleware if you wanted to catch the `ValueError` and raise a `Transaction`/`BlockNotFound` error, although I realize that's not ideal.
