### ISSUE TITLE
txpool.content() giving incomplete output and in different format

### ISSUE THREAD

**Issue by luboremo** [ethereum/web3.py#1932]
* Version: 5.17.0
* Python: 3.8.6 64bit
* OS: win10

### What was wrong?

I'm trying to get content of txpool from geth. But it seems that the output is incomplete since it is missing beginning.
Also the format seems to differ from what is shown in the docs and from what I get when I run txpool.content in attached web3 console in the geth node.
The one from web3py ends with ) while the one from geth console ends with }

Is the problem that the output of txpool.content is too long and it gets cut in the beginning for some reason?

Please include any of the following that are applicable:

* The code which produced the error
```
import web3

w3_http = web3.Web3(web3.Web3.HTTPProvider('http://myNodesDNS:8545'))

r = w3_http.geth.txpool.content()
print(r)
```
* The full output:
```
1e9d1ac9fb831529c8bda41f725109'}), '576': AttributeDict({'blockHash': None, 'blockNumber': None, 'from': '0xbc28425f49c8028f6efd047aa940be7029e996a8', 'gas': '0x249f0', 'gasPrice': '0x309d732800', 'hash': '0xb8c11cf24ca03a951b360924d1766f82a7d397aced3a1e1dd345e9860dc0ac02', 'input': 
... A LOT OF DATA ...  
'type': '0x0', 'v': '0x26', 'r': '0x7335e7f03e1f833b91d69b57b5ecb5508c51399143e6e50dbfd55b5a2ffe42d1', 's': '0x6aa2832523ee16da45e125d252f6cc5839c8b5be25a81acb215ee39362c6bd9'})})})})
```

* What type of node you were connecting to.
Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16

**Comment by luboremo** [comment]
ok the problem was between the computer and the chair :D

I am able to get the complete output in correct format when I redirect it to a file
```
curl -H "Content-Type: application/json" -X POST -d '{"jsonrpc":"2.0","method":"txpool_content","params":[],"id":1}' http://myGethNode.com:8545 | json_pp > txpool.out
```

It seems the output is too long and terminal just cut it and shows it from some part to the end of the output, but that is what gets stored in my variables when I use the query through web3py.
In fact I also get incomplete result in my terminal when I use the command directly in geth web3 console.

Can anyone please suggest a way around this using web3py so the output will get stored to a variable completely and in correct data structure?

**Comment by kclowes** [comment]
@luboremo you can turn it into a dict if it makes more sense to work with a plain old dict. AttributeDict is an extension of dict that gives the ability to access attributes with dot notation. For example: 

```
>>> foo = AttributeDict({'a': 1, 'b': {'c': 3}})
>>> foo.a
1
>>> for k, v in foo.items():
>>>    print('key: ', k)
>>>    print('value: ', v)   
key:  a
value:  1
key:  b
value:  {'c': 3}
>>> dict(foo)
{'a': 1, 'b': {'c': 3}}
```

I'm going to close, but feel free to reopen if you need more help!
