### ISSUE TITLE
How to verify eth_signTypedData_v4 in web3 py

### ISSUE THREAD

**Issue by araa47** [ethereum/web3.py#1958]
## Problem 

How to verify signer of the method `eth_signTypedData_v4` using web3 py?

### Js Metamask signature example:
 https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4

## What Ive tried

```
data = msgParams # equivalent to the js object in the example above 
original_message = json.dumps(data)
message = encode_defunct(text=message)
signer = w3.eth.account.recover_message(message, signature=signature)
```

## Current result

Signer shows up as random addresses that does not match with the actual signer of the message. 

The above web3 py code works if `personal_sign` method is used in js

**Comment by beaugunderson** [comment]
this is the difference between v3/v4 in the JavaScript library that does v4 signing if it's helpful to someone:

https://github.com/MetaMask/eth-sig-util/blob/41a62c8255ce061130f85876be178e65e6ae99a2/src/index.ts#L98-L151

**Comment by em1208** [comment]
@araa47 @beaugunderson I had the same issue and I solved it by using the function `encode_structured_data` as follow:
```python
message = encode_structured_data(primitive=data)
recovered = w3.eth.account.recover_message(message, signature=signature)
```
where `encode_structured_data` is defined in the documentation https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.encode_structured_data

I hope this helps!

**Comment by fselmo** [comment]
Closing this as I assume this was resolved by using `encode_structured_data` and since we have tests for this as well. Please feel free to re-open and discuss if that is not the case.

**Comment by oscarsernarosero** [comment]
Trying to do ```message = encode_structured_data(primitive=msg)``` with:

```
msg = {
      "domain": {
        "chainId": 1,
        "name": 'Ether Mail',
        "verifyingContract": '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC',
        "version": '1',
      },
      "message": {
        "contents": 'Hello, Bob!',
        "from": {
          "name": 'Cow',
          "wallets": [
            '0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826',
            '0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF',
          ],
        },
        "to": [
          {
            "name": 'Bob',
            "wallets": [
              '0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB',
              '0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57',
              '0xB0B0b0b0b0b0B000000000000000000000000000',
            ],
          },
        ],
      },
      "primaryType": 'Mail',
      "types": {
        "EIP712Domain": [
          { "name": 'name', "type": 'string' },
          { "name": 'version', "type": 'string' },
          { "name": 'chainId', "type": 'uint256' },
          { "name": 'verifyingContract', "type": 'address' },
        ],
        "Group": [
          { "name": 'name', "type": 'string' },
          { "name": 'members', "type": 'Person[]' },
        ],
        "Mail": [
          { "name": 'from', "type": 'Person' },
          { "name": 'to', "type": 'Person[]' },
          { "name": 'contents', "type": 'string' },
        ],
        "Person": [
          { "name": 'name', "type": 'string' },
          { "name": 'wallets', "type": 'address[]' },
        ],
      },
    }
```

But got 

```
KeyError: 'address'
```

**Comment by voxofox** [comment]
@oscarsernarosero - that's due to https://github.com/ethereum/eth-account/issues/149
