### ISSUE TITLE
[help]  Buy BSC token using web3

### ISSUE THREAD

**Issue by deluxemonitor** [ethereum/web3.py#1966]
i'm trying to buy $TRY token with my code. It's BSC token. The problem is when i send money to the contract i don't receive any token :/ 

The contract i'm trying to buy :
https://bscscan.com/token/0xc12ecee46ed65d970ee5c899fcc7ae133aff9b03

I'm coding in python using Web3 wrapper : https://pypi.org/project/web3/

```
     signed_txn = w3.eth.account.sign_transaction(dict(
            nonce=w3.eth.getTransactionCount(MY_WALLET),
            gasPrice=int(w3.eth.gasPrice*1.5),
            gas=200000,
            to=w3.toChecksumAddress('0xc12ecee46ed65d970ee5c899fcc7ae133aff9b03'),
            value=w3.toWei(amount, 'ether'),
            data=b'',
        ),
            'PRIVATEKEY',
        )

```
I tried with the contract address : 
https://bscscan.com/tx/0xb9652d6f36d22a13a5fc877ade45d7f1c882eec80fd224c87949284793f6fe1a
Payment is OK but i don't receive any token.

I also tried with the pancake routers :
https://bscscan.com/tx/0xc89b620fc08c37dec87f1daa0d79cb1a01f2f0e7b9c200e6fcaf52c66ebe5297
But i got an error "A  status code indicating if the top-level call succeeded or failed (applicable for Post BYZANTIUM blocks only). I don't understand it.

My account detail (only 4 transactions) :
https://bscscan.com/address/0x033f7eea8799696ff46293cf8d84903a6aeeab05

Do you have any idea about how i can buy or sell this token with code ? 
Manually i do it with pancakeswap. There is also an ETH $TRY token with same address but i got same problem ...

**Comment by marcgarreau** [comment]
1) We don't officially support BSC. If Web3.py happens to work with it, great, but we make no commitments there.
2) Are you sure that that sending funds to the contract address is a valid way to purchase tokens? Check with the project. 
3) I don't know anything about Pancake either, but its public methods will be available like any other contract if you configure an [instance of the contract](https://web3py.readthedocs.io/en/stable/examples.html#interacting-with-existing-contracts). 

I'm going to close this issue, but please feel free to reopen if you have an Ethereum-specific question, preferably with the exception text and some reproducible code.
