### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by spindriftur** [ethereum/web3.py#1985]
I installed `web3` using pip and pip3, and when I import it into a py file to use or the interpreter, it returns with `ModuleNotFoundError: No module named 'web3`

python 3.9.0
pip version 21.1.1

**Comment by marcgarreau** [comment]
This is typically an environment, import, or configuration issue on your end. See if [this page](https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-can-t-i-use-a-particular-function) in the docs helps you. If not, please reopen the issue with more details about the commands/code you're running.
