### ISSUE TITLE
`eth_getBlockReceipts` not available via `web3.py`?

### ISSUE THREAD

**Issue by pcko1** [ethereum/web3.py#2004]
Hi, the RPC method `eth_getBlockReceipts` seems not available via `web3.py`, am I mistaken?

**Comment by kclowes** [comment]
Sorry for the delay in response on this. I don't see that rpc method available in Geth. If you want all the transaction receipts from a block, AFAIK, you'll need to do a `w3.eth.get_block(block number)` and then for each transaction, do `w3.eth.get_transaction(tx hash)`. Closing, but feel free to reopen if I misunderstood something.

**Comment by banteg** [comment]
It's a method available in Erigon.
https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md

**Comment by kclowes** [comment]
Ah, thanks for the clarification @banteg. Will reopen!

**Comment by 0xrishabh** [comment]
@kclowes Do you have any suggestions on how to start working on this?

**Comment by kclowes** [comment]
@0xrishabh [here is a PR](https://github.com/ethereum/web3.py/pull/2051) that was merged recently for another RPC method that we just added. That should provide a good starting point.

**Comment by AWendland-CryptoCompare** [comment]
Did this ever get added? I looked at the linked PR but didn't see anything further.

**Comment by kclowes** [comment]
I don't think it ever got added. Feel free to do so, or we now have functionality to add custom methods if you don't want to PR it: https://snakecharmers.ethereum.org/web3-py-patterns-customizations/ . See Section 2.

**Comment by AWendland-CryptoCompare** [comment]
Thanks, if I did want to add it is there some documentation on how to go about that or is it a matter of just looking to work it out?

**Comment by kclowes** [comment]
See three comments up:

> (Here is a PR)[https://github.com/ethereum/web3.py/pull/2051] that was merged recently for another RPC method that we just added. That should provide a good starting point.

**Comment by kclowes** [comment]
Closed via #3247
