### ISSUE TITLE
Web3.WebsocketProvider in web.py can't to listens appear new mined block and to transfer control further only after this

### ISSUE THREAD

**Issue by 4vadim4** [ethereum/web3.py#2007]
* Version: 5.19.0
* Python: 3.8
* OS: Ubuntu 18.04.5 LTS
* `pip freeze` output:

```
attrs==21.2.0
base58==2.1.0
bitarray==1.2.2
certifi==2020.12.5
chardet==4.0.0
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.17.1
pycryptodome==3.10.1
pyrsistent==0.17.3
requests==2.25.1
rlp==2.0.1
six==1.16.0
toolz==0.11.1
urllib3==1.26.5
varint==1.0.2
web3==5.19.0
websockets==8.1

```

### Node

I use own Node at Ubuntu 20.04.2 LTS:

Geth
Version: 1.10.2-stable
Git Commit: 97d11b0187b4695ccf44e3b71b54155fe405a36f
Architecture: amd64
Go Version: go1.16

### What was wrong?

I always thought that:  
- `HTTPProvider` works as endpoint - creates connect, gets some info, closes connect 
but
- `WebsocketProvider` should keeps the connection open after connect and listens new event (block was mined) and after new block was ready something was being happened under hood and i get this block for further works with him. But it's doesn't ? Because i can't search needed method which can do it. So, i have to inspect forcibly my Node every second just to see ready or not a new mined block ? Something like this:  

```
from web3 import Web3
import time


WEB3_WS_URI = 'node_url'
w3 = Web3(Web3.WebsocketProvider(WEB3_WS_URI))


def run():
    while True:
        last_block = w3.eth.block_number
        print(last_block)
        time.sleep(1)
```
Then what the difference between `WebsocketProvider` and `HTTPProvider` with `web3.py` ?
What's the point of websocket in `WebsocketProvider` if it doesn't listen event, i mean ready of new mined block ?
Is there really nothing under hood i mean some method which can to listens appear newly mined block and push next action in `while` block instead using `time.sleep(n)` ?

**Comment by coccoinomane** [comment]
I would love to get an answer to this question: what's the point of a websocket if we cannot use it to listen to events? Thanks!

**Comment by fselmo** [comment]
Please refer to the new `WebSocketProvider` in `v7` beta (`WebsocketProviderV2` in `v6`) for *eth_subscribe* support.
