### ISSUE TITLE
Don't include arbitrary addresses in documentation.

### ISSUE THREAD

**Issue by adam505hq** [ethereum/web3.py#2011]
One example is https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.send_raw_transaction. `0xd3CdA913deB6f67967B99D67aCDFa1712C293601` should be replaced with `public_address_of_receivers_account`.

This is live address that is actually used on mainnet: https://etherscan.io/address/0xd3CdA913deB6f67967B99D67aCDFa1712C293601 . Whether this is accident - I don't know.

**Comment by marcgarreau** [comment]
Fair point; PR welcome or I'll get to it next time I'm in the docs.

**Comment by divyanshugit** [comment]
Hey, @marcgarreau I wanna work on this. Can you please assign this issue to me? It will great If you can provide a little bit more info about this. I think it will be great for me to getting started with ethereum :)

**Comment by fselmo** [comment]
> Can you please assign this issue to me? It will great If you can provide a little bit more info about this. I think it will be great for me to getting started with ethereum :)

Hey @divyanshugit. Thanks for the interest! I went ahead and assigned this to you. For this issue, we would want to replace the address `0xd3CdA913deB6f67967B99D67aCDFa1712C293601`, wherever it appears in the code base, with a variable name that is suited for the context in which it is used. For the particular example mentioned in the description of this issue, `public_address_of_receivers_account` would be suitable. We may, however, need to tweak this variable name a bit depending on the different contexts that you see among the code base.

Hope this helps.

**Comment by gupta437** [comment]
@divyanshugit Are you still working on this issue? If not I would like to work on it. Appreciate your response in advance!

**Comment by kclowes** [comment]
@gupta437 feel free to pick it up since there has been no PR in over a month. I'll remove @divyanshugit from the assignees. Let us know if you have questions!

**Comment by gupta437** [comment]
@kclowes Thankyou! I will pick this up.

**Comment by 0xrishabh** [comment]
@kclowes can't we replace every live address with `address_of_account` or `address`?

**Comment by abdulqgg** [comment]
Hey could i tackle this for my first issue? Thanks

**Comment by fselmo** [comment]
> Hey could i tackle this for my first issue? Thanks

Thanks for the interest, @abdulqgg. Looks like @gupta437 mentioned working on this as of 3 days ago. I would suggest a conversation here with @gupta437 to see how far along they are in order to avoid duplicate work.

**Comment by gupta437** [comment]
@abdulqgg I also picked this up as my first issue.  I am still working on it. I will update you if this would be free to pick up.

**Comment by fselmo** [comment]
@gupta437 I went ahead and officially assigned it to you to avoid confusion 👍

**Comment by bluszcak44** [comment]
@gupta437 If you need I can take this over for you, just let me know!

**Comment by B3nac** [comment]
Is it safe to say this issue is still available since there hasn't been an update since Jul 26, 2021? If this is still being worked on, no worries.

**Comment by Kingteena** [comment]
@fselmo Hi could I please take over this issue if it's still available? There hasn't seemed to be any update for an year so I'm going to assume it is

**Comment by fselmo** [comment]
I would probably default to `account_address` and if there are multiple, maybe `account_address_1`, `account_address_2`, etc... unless the particular example could use a bit more context within the variable name.

**Comment by B3nac** [comment]
Wololo PR submitted! Peanut Dutter Belly! @fselmo

**Comment by fselmo** [comment]
> Wololo PR submitted! Peanut Dutter Belly! @fselmo

Hey thanks for getting this moving again 😅 ... I'm still seeing a few addresses that are actual addresses in the docs:

- `0xd3CdA913deB6f67967B99D67aCDFa1712C293601` is still popping up in `web3.geth.rst`, `web3.main.rst`, and `web3.parity.rst`
- `0x5ce9454909639D2D17A3F753ce7d93fa0b9aB12E` is still present in `web3.eth.account.rst` and is a working address on Ropsten and possibly others
- `0x2a65Aca4D5fC5B5C859090a6c34d164135398226` is also on Ropsten possibly others...

I'm not going to keep looking atm but I think there are still quite a few real addresses in the docs. Ideally we can scramble these by replacing one or two letters or numbers.

**Comment by mahim37** [comment]
Is this issue still persists? If so, @fselmo can I take over?
Else, no worries, 
Cheers!

**Comment by Amitdutta7** [comment]
Hey @fselmo! Looks like this issue is open for quite sometime and the recent commits are failing some checks. Can I work on this if no one is officially assigned to this?

**Comment by kclowes** [comment]
@0xamitdutta Looks like #2594 is up, we just need to review it. We're focused on getting v6 out but will review #2594 when v6 is stable. I'll post back here if we find there is more to do. Thanks for the offer!
