### ISSUE TITLE
Fix AsyncEth module typing

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2013]
### What was wrong?

Because the eth module is called `eth` regardless of whether or not it refers to the `Eth` module or the `AsyncEth` module, the typing is a little bit funky. Once `AsyncEth` is completely switched over to mirror the functionality of the `Eth` module, we can make the `eth` attr [here](https://github.com/ethereum/web3.py/blob/0afdd87d45ca7c4f64d146579e84c7810fac95de/web3/main.py#L160) be `Union[AsyncEth, Eth]`. Then we can go through and remove `type: ignore`s throughout codebase on all `await w3.eth...` lines.

**Comment by fselmo** [comment]
closed by #2819
