### ISSUE TITLE
How do i connect with AWS Managed Block Chain? 

### ISSUE THREAD

**Issue by chivalry123** [ethereum/web3.py#2014]
Currently, I used the following python codes to connect to web3 

    from web3 import Web3
    # Fill in your infura API key here
    infura_url = "https://mainnet.infura.io/v3/djsoiqowejojoajsdooqw"
    web3 = Web3(Web3.HTTPProvider(infura_url))

I am now using AWS managedblockchain, it gives me this credential:

    Node ID
    nd-GFJL!JJDANSANJQWEQNDSA
    Blockchain instance type
    bc.t3.large
    Availability zone
    us-east-1f
    WebSocket EndpointInfo
    nd-ajdsojasdnqkebjb1k2jbj.wss.ethereum.managedblockchain.us-east-1.amazonaws.com
    HTTP EndpointInfo
    nd-zVfjoaisjodbqiwubjud.ethereum.managedblockchain.us-east-1.amazonaws.com
    ARN
    arn:aws:managedblockchain:us-east-1:871628371628:nodes/nd-JASDOIOWQEBJABKJA

How do I used this information to access web3 using web3py?

**Comment by kclowes** [comment]
You should be able to replace the `infura_url` with the HTTP EndpointInfo. Closing, but feel free to reopen if that isn't what you're asking!

**Comment by chivalry123** [comment]
I actually failed if I used:

from web3 import Web3
# Fill in your infura API key here
infura_url = "https://nd-zVfjoaisjodbqiwubjud.ethereum.managedblockchain.us-east-1.amazonaws.com"
web3 = Web3(Web3.HTTPProvider(infura_url))

AWS had provided PRIVATE key and public KEY saying that I need to use it... Is it possible to include such information there?

**Comment by kclowes** [comment]
You'll probably need to include those in the headers. You'll need to figure out which headers Amazon needs, but you can add whatever relevant headers you want to the `request_kwargs` that you pass to your provider. So something like: 
```
headers = {'Authorization':authorization_header, ...}
web3 = Web3(Web3.HTTPProvider(url, request_kwargs=headers))
```
Where it looks like you'll need to calculate the `authorization_header`, but I'm not sure. 

See the docs for the web3 HTTPProvider here for more info on passing the headers: https://web3py.readthedocs.io/en/stable/providers.html#web3.providers.rpc.HTTPProvider. 

I haven't worked with AWS managed blockchain before, but [this](https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/ethereum-json-rpc.html) looks like some relevant documentation on the AWS side.
