### ISSUE TITLE
Sample Contract interaction outdated and erroring

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/web3.py#2020]
* Version: 5.19.0
* Python: 3.9
* OS: macOs big sur 11.4
```
web3==5.19.0
```
The [sample example](https://web3py.readthedocs.io/en/stable/contracts.html#contract-deployment-example) is giving me the following warning and error:

```
UserWarning: Ethereum Tester: No backend was explicitely set, and no *full* backends were available.  Falling back to the `MockBackend` which does not support all EVM functionality.  Please refer to the `eth-tester` documentation for information on what backends are available and how to set them.
File "/Users/patrick/code/web3_py_fund_me/Greeter.py", line 61, in <module>
    tx_hash = Greeter.constructor().transact()
.
.
.
raw_gas_estimate = self.backend.estimate_gas(raw_transaction, raw_block_number)
TypeError: estimate_gas() takes 2 positional arguments but 3 were given
```

### How can it be fixed?

I feel this example should be updated to a working version. It appears we are using an outdated version of something.

**Comment by marcgarreau** [comment]
Thanks for reporting @PatrickAlphaC. Does look like we can use some modernization here. I doubt there are many users compiling their contracts in-line like this, but those that are probably should use the more up-to-date [py-solc-x](https://pypi.org/project/py-solc-x/). PR's welcome to make this example current; otherwise one of us will circle back to it as we're able.

**Comment by divyanshugit** [comment]
Hey, @marcgarreau I would love to work on this. Can you please assign this issue to me? It will great If you can provide a little bit more info about this. I think it will be great for me to getting started with ethereum :)

**Comment by fselmo** [comment]
Hey @divyanshugit. Thanks for the interest on this!

I ended up pulling this issue in my workload at the end of last week and am going to put up a PR this morning. There are some other issues that may be good for getting started in our issues list. I recommend checking out other issues with the "Good First Issue" tag.
