### ISSUE TITLE
Geth Node panics with SIGSEGV when using pending transaction filter

### ISSUE THREAD

**Issue by prashanthvenky** [ethereum/web3.py#2034]
* Version: 5.19.0
* Python: 3.9.5
* OS: linux
* `pip freeze` output

```
# pip freeze
aiohttp==3.7.4.post0
appdirs==1.4.4
apturl==0.5.2
async-timeout==3.0.1
attrs==21.2.0
base58==2.1.0
bcrypt==3.1.7
bitarray==1.2.2
blinker==1.4
Brlapi==0.8.2
certifi==2020.6.20
chardet==4.0.0
click==7.1.2
colorama==0.4.4
command-not-found==0.3
cryptography==3.3.2
cupshelpers==1.0
Cython==0.29.23
cytoolz==0.11.0
dateparser==1.0.0
dbus-python==1.2.16
defer==1.0.6
distlib==0.3.1
distro==1.5.0
distro-info==1.0
duplicity==0.8.17
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
fasteners==0.14.1
filelock==3.0.12
future==0.18.2
hexbytes==0.2.1
httplib2==0.18.1
idna==2.10
importlib-metadata==1.6.0
iotop==0.6
ipfshttpclient==0.7.0
jeepney==0.6.0
jsonschema==3.2.0
keyring==22.2.0
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.5
lockfile==0.12.2
louis==3.16.0
lru-dict==1.1.7
macaroonbakery==1.3.1
Mako==1.1.3
MarkupSafe==1.1.1
monotonic==1.5
more-itertools==4.2.0
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
netifaces==0.10.9
oauthlib==3.1.0
olefile==0.46
paramiko==2.7.2
parsimonious==0.8.1
pexpect==4.8.0
Pillow==8.1.2
protobuf==3.12.4
pycairo==1.16.2
pycryptodome==3.10.1
pycups==2.0.1
PyGObject==3.38.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.4.0
pyRFC3339==1.1
pyrsistent==0.17.3
python-apt==2.1.7+ubuntu2
python-binance==1.0.8
python-dateutil==2.8.1
python-debian==0.1.39
pytz==2021.1
pyxdg==0.27
PyYAML==5.3.1
regex==2021.4.4
reportlab==3.5.66
requests==2.25.1
rlp==2.0.1
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
simplejson==3.17.2
six==1.15.0
ssh-import-id==5.11
systemd-python==234
toolz==0.11.1
typing-extensions==3.10.0.0
tzlocal==2.1
ubuntu-advantage-tools==24.4
ubuntu-drivers-common==0.0.0
ufw==0.36
ujson==4.0.2
unattended-upgrades==0.1
urllib3==1.26.2
usb-creator==0.3.7
varint==1.0.2
virtualenv==20.4.0+ds
wadllib==1.3.5
web3==5.20.0
websockets==8.1
xdg==5
xkit==0.0.0
yarl==1.6.3
zipp==1.0.0
```

### What was wrong?
I run a python script that registers for pending transactions using w3.eth.filter('pending') and continuously polls for new transactions using filter.get_new_entries().
I am using a local geth node and am connected to it over ipc.
I see that atleast once a day, my geth node dies with a segmentation fault with the below output:
=================================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48f167]

goroutine 16672259 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1(0xc501895560, 0xc49d7ebc20, 0xc12fb0cf90, 0xc065879020)
	github.com/ethereum/go-ethereum/eth/filters/api.go:128 +0x1a5
created by github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter
	github.com/ethereum/go-ethereum/eth/filters/api.go:124 +0x1bb
==================================

I feel its got something to do with how web3 registers and calls the filter that could be causing this as my friends using GO are not facing the same issue.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by fselmo** [comment]
@bscqt I haven't yet been able to get to this but it's on my list! I've been updating some things in other libraries but I will try to check this out as soon as I can. For clarification, you can run it over ipc but it will fail at some point throughout the day?

**Comment by bscqt** [comment]
That is correct. Everything seems to run fine over ipc at startup, but it will crash out later. For me this happens 5+ times pr day. For some reason I only see this when connected to BSC nodes.

**Comment by bscqt** [comment]
I am seeing this when running a web3py ipc pending filter towards my own geth bsc fullnode. Again, I do not see it when I run a webp3 ipc pending filter towards my own geth eth fullnode.

**Comment by fselmo** [comment]
@bscqt that is very helpful thanks for the update 👍

**Comment by bscqt** [comment]
Any updates on this? still crashing multiple times pr day..

**Comment by kclowes** [comment]
@bscqt It looks like this is a known issue running BSC, based on [this issue](https://github.com/binance-chain/bsc/issues/388). I'd try updating your node software and see if that fixes the problem. 

I'm going to close this because it looks like the exact same stack trace as the issue linked above, so I don't think this is an issue with web3py.
