### ISSUE TITLE
Add eth_feeHistory RPC endpoint

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2038]
### What was wrong?

Once the London hard fork happens, we'll have access to a new RPC method - `eth_feeHistory`. Some docs can be found [here](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-specs/master/json-rpc/spec.json&uiSchema%5BappBar%5D%5Bui:input%5D=false)

### How can it be fixed?

Add `fee_history` to the eth module and test it. Extra credit to make it available in the Async Eth module as well. It will probably make sense to add this after the 1559 work is merged (#2033) so we'll have access to the geth fixture that includes 1559 for testing.

**Comment by mike6649** [comment]
Hi! 👋 I would like to help work on this. Please assign this task to me and let me know if there are any things I should pay attention to. Thanks!

**Comment by fselmo** [comment]
Closed by merging PR #2094
