### ISSUE TITLE
Add eth_getRawTransactionByHash

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2039]
### What was wrong?

We don't have support for the `eth_getRawTransactionByHash` RPC method. 

### How can it be fixed?

Add it to `BaseEth`, and add it to both `Eth` and `AsyncEth` following established patterns. Tests will need to be added as well.

**Comment by Moras-del** [comment]
Hello! I would like to work on this. Could you assign this task to me? :)

**Comment by kclowes** [comment]
Done! Let me know if you need any guidance! PR-ing early and often is best! Thanks!

**Comment by kclowes** [comment]
Fixed in #2051
