### ISSUE TITLE
ERC20 token burn not working

### ISSUE THREAD

**Issue by rupansh** [ethereum/web3.py#2050]
* Version: 5.20.0
* Python: 3.9
* OS: linux
* `pip freeze` output

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
base58==2.0.1
bitarray==1.2.2
bottle==0.12.19
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.7
cytoolz==0.11.0
erdpy==1.0.15
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
flake8==3.9.2
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0
jsonschema==3.2.0
lru-dict==1.1.7
mccabe==0.6.1
more-itertools==8.8.0
multiaddr==0.0.9
multidict==5.1.0
mypy==0.902
mypy-extensions==0.4.3
netaddr==0.8.0
parsimonious==0.8.1
prettytable==2.1.0
protobuf==3.17.3
py-bip39-bindings==0.1.7
py-ed25519-bindings==0.1.3
py-sr25519-bindings==0.1.3
pycodestyle==2.7.0
pycparser==2.20
pycryptodome==3.10.1
pycryptodomex==3.10.1
pyflakes==2.3.1
PyNaCl==1.4.0
pyrsistent==0.17.3
requests==2.25.1
rlp==2.0.1
scalecodec==0.11.11
six==1.16.0
stdiomask==0.0.6
substrate-interface==0.13.8
toml==0.10.2
toolz==0.11.1
types-requests==0.1.13
typing-extensions==3.10.0.0
urllib3==1.26.5
varint==1.0.2
wcwidth==0.2.5
web3==5.20.0
websocket-client==0.58.0
websockets==8.1
xxhash==2.0.2
yarl==1.6.3
```

### What was wrong?

I have a contract which calls the burn function of an erc20 token.
the following function is called to do so:
`function withdraw(string memory to, uint256 value)`
Upon sending call via web3.py:
```python
destination = "someaddr"
val = 10000000000000000
self.minter.functions.withdraw(destination, val)
```

I am getting
`ValueError: {'code': -32603, 'message': 'Error: VM Exception while processing transaction: revert ERC20: burn amount exceeds balance'}`

However in hardhat console:
`await (await minter.connect(<privatekey>).withdraw("someaddr", '10000000000000000')).wait()`
worked fine.

I suspected some implicit conversion might be messing it so i tried `Wei(val)` instead but that didn't work.

I was connected to a hardhat websocket local node

**Comment by kclowes** [comment]
[Here are the docs](https://web3py.readthedocs.io/en/stable/web3.main.html#currency-conversions) on currency conversions for web3py. I'm going to close this, but feel free to reopen if that doesn't fix your issue!

**Comment by rupansh** [comment]
> [Here are the docs](https://web3py.readthedocs.io/en/stable/web3.main.html#currency-conversions) on currency conversions for web3py. I'm going to close this, but feel free to reopen if that doesn't fix your issue!

Hi.
i tried Web3.toWei(10000000000000000, 'wei'), it didn't work
Web3.fromWei(1000000000000000) -> Decimal, which is incompatible with the function signature

**Comment by rupansh** [comment]
Fixed.
Since the function implicitly depends on the sender of the txn, the gasLimit estimation was causing the transaction to fail.
Using explicit gasLimit.
