### ISSUE TITLE
EIP-1559 gas price / fee history oracles

### ISSUE THREAD

**Issue by wolovim** [ethereum/web3.py#2054]
Pre-London (legacy) transactions rely on a `gasPrice` to be set by the user or determined by Web3.py or the client. Post-London transactions drop `gasPrice` in favor of `maxFeePerGas` and `maxPriorityFeePerGas`. 

Questions:
- Will `eth_gasPrice` continue to be supported for legacy transactions as is?
   - Geth will continue to return total fees paid (tip + base)
- Should Web3.py continue to offer gas price strategies for legacy transactions? Support _both_ legacy and new transactions? Just new txs?
   - TBD
- Should a new oracle fee API return both a `maxFeePerGas` and a `maxPriorityFeePerGas`, or just the latter?
   - New RPC method, `eth_maxPriorityFeePerGas` available after London. Effectively returns `eth_gasPrice - baseFee`. Geth shoots for 60th percentile as the price suggestion to keep downward pressure on the price.
- What are optimal defaults for `maxFeePerGas` and `maxPriorityFeePerGas` if we don't just let the client decide? Or should that be the responsibility of the client?
   - Geth: "If the user doesn't specify `maxFeePerGas`, we default to `maxPriorityFeePerGas + 2*baseFee`"

Resources:
- Peter's description of [Geth's gas oracle behavior](https://github.com/ethereum/pm/issues/328#issuecomment-853234014)
- Freshly merged Geth feeHistory [PR](https://github.com/ethereum/go-ethereum/pull/23033) and [context](https://gist.github.com/zsfelfoldi/473e29106d38525de6b4413e2ebcddf1)
- Newest [ethers.js release](https://github.com/ethers-io/ethers.js/releases/tag/v5.4.0) with 1559 support

Things that may update in Web3.py:
- `generate_gas_price` API
- `gas_strategies`
- `gas_price_strategy` middleware
- `gas_price.rst` docs pages
- new APIs for `maxFeePerGas` and/or `maxPriorityFeePerGas`

**Comment by banteg** [comment]
I added `eth_maxPriorityFeePerGas` in #2100. Tested with `devel` version of Erigon.

**Comment by L-F-Escobar** [comment]
beautiful
