### ISSUE TITLE
Support EIP-1559 params for signTransaction

### ISSUE THREAD

**Issue by fselmo** [ethereum/web3.py#2065]
### What was wrong?
- ~~`geth` does not yet have support for the new 1559 params for the `signTransaction` RPC call~~ [Support added in 1.10.5]
- ~~Waiting on `eth-account` 1559 support~~ - [PR #115](https://github.com/ethereum/eth-account/pull/115)

### How can it be fixed?
- Once geth has support for params `maxFeePerGas` and `maxPriorityFeePerGas` for signing... and eth-account is updated to support the params... we should make sure we support this on our end and update the related tests.

**Comment by kclowes** [comment]
Merged with #2082
