### ISSUE TITLE
Bug with decode_function_input

### ISSUE THREAD

**Issue by Sad-Walrus** [ethereum/web3.py#2076]
* Version: 5.21.0
* Python: 3.8.10
* OS: linux
* `pip freeze` output

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==19.3.0
Automat==0.8.0
base58==2.1.0
bitarray==1.2.2
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==21.2
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
cytoolz==0.11.0
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
ipfshttpclient==0.7.0
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lru-dict==1.1.7
MarkupSafe==1.1.0
more-itertools==4.2.0
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
netifaces==0.10.4
oauthlib==3.1.0
parsimonious==0.8.1
pexpect==4.6.0
protobuf==3.17.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycryptodome==3.10.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.5
python-debian===0.1.36ubuntu1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
rlp==2.0.1
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.1
ssh-import-id==5.10
systemd-python==234
toolz==0.11.1
Twisted==18.9.0
typing-extensions==3.10.0.0
ubuntu-advantage-tools==27.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
varint==1.0.2
wadllib==1.3.3
web3==5.20.1
websockets==9.1
yarl==1.6.3
zipp==1.0.0
zope.interface==4.7.1
```

### What was wrong?

Attempting to use decode_function_input but getting back ValueError: Could not find any function with matching selector despite pulling the exact ABI. Could be an issue with using BSC instead of ETH but it's unlikely. Error is:

Traceback (most recent call last):
  File "scratch.py", line 30, in <module>
    print(contract.decode_function_input(transaction.input).on())
  File "/home/foretoken/.local/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/foretoken/.local/lib/python3.8/site-packages/web3/contract.py", line 466, in decode_function_input
    func = self.get_function_by_selector(selector)
  File "/home/foretoken/.local/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/foretoken/.local/lib/python3.8/site-packages/web3/contract.py", line 459, in get_function_by_selector
    return get_function_by_identifier(fns, 'selector')
  File "/home/foretoken/.local/lib/python3.8/site-packages/web3/contract.py", line 1680, in get_function_by_identifier
    raise ValueError(
ValueError: Could not find any function with matching selector

Code 
`        
        from web3 import Web3
        import json
        import urllib.request, json
        from time import sleep

        provider = Web3.HTTPProvider('https://bsc-dataseed.binance.org/')
        w3 = Web3(provider)
        txid = '0x76cdc42f3ac688cb69b11eb942f6e41db9d5d709dc9aa9d9e402876373ba62b3'
        address = '0x6594A90d41Ae84fc5615D376ec59838744737Bd7'
        requrl = 'https://api.bscscan.com/api?module=contract&action=getabi&address=' + address

        while True:
            with urllib.request.urlopen(requrl) as url:
                if url.code != 200:
                    # TODO: Error handling
                    raise NotImplementedError('I don\'t know how to handle HTTP code {} :('.format(url.code))
                else:
                    result = json.loads(url.read())

                    if result['status'] == '1':
                        abi = json.loads(result['result'])
                        # print(abi)
                        break
                        
                    sleep(1)

        contract = w3.eth.contract(address=address, abi=abi)
        transaction = w3.eth.getTransaction(txid)
        print(contract.decode_function_input(transaction.input))

`

**Comment by Sad-Walrus** [comment]
I take it back, it is a problem with contracts on the Binance Smart Chain, ETH mainnet works fine.

**Comment by fselmo** [comment]
Sounds good. I'm going to close this since this isn't a web3py issue. Feel free to open it if you believe there are outstanding web3py related errors.
