### ISSUE TITLE
Add visual studio requirement for microsoft installs to troubleshooting docs

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2077]
* Version: 5.21+
* OS: win

### What was wrong?
We periodically get an issue like #2075 where a windows user can't install web3 because cytools needs Microsoft Visual C++ 14.0 or greater. 

This results in a stack trace like the one shown in #2075.

### How can it be fixed?

Add a blurb in the `Troubleshooting` section of the docs that shows a genericized stack trace and the link to download Microsoft Visual C++.

**Comment by santoshdvc** [comment]
Hi,
I have created a pull request addressing the changes in the Troubleshooting docs. Please verify them and let me know if some more changes are required.
