### ISSUE TITLE
best practice to query 100 millions of contract function call

### ISSUE THREAD

**Issue by chivalry123** [ethereum/web3.py#2079]
To get the right historical data for analysis, my task actually required me to perform millions of contract function calls on an archive node. What would be the best practice for me to obtain the optimal speed? Shall i do multithreading/ asyncio / bulk query (if such thing exists?) Thanks!

**Comment by kclowes** [comment]
This is a question that would be better asked in the [Python Ethereum Discord](https://discord.gg/GHryRvPB84), or on StackOverflow. We generally use issues for bug reports or for people to get help with specific errors.
