### ISSUE TITLE
use proxy for http request web3py

### ISSUE THREAD

**Issue by chivalry123** [ethereum/web3.py#2081]
I'm currently using this method to connect to web3py 

```
    infura_url = "https://node.node/asdasdasdasdasd/bsc/mainnet/archive/" # fast
    web3 = Web3(Web3.HTTPProvider(infura_url))
```

How do I enable proxy? say i have proxy at '321.123.121.123:8081'

**Comment by kclowes** [comment]
This is a question that would be better asked in the [Python Ethereum Discord](https://discord.gg/GHryRvPB84), or on StackOverflow. We generally use issues for bug reports or for people to get help with specific errors.

**Comment by sinarezaei** [comment]
You can use pass proxies param as request_kwargs in HTTPProvider constructor

You can also use the following library: 
https://github.com/sinarezaei/web3-proxy-providers

I am changing the code a little and creating a pull request for web3py to support socks/http proxies on websocket and http providers
