### ISSUE TITLE
HTTP 503 websocket error web3

### ISSUE THREAD

**Issue by Theagainmen** [ethereum/web3.py#2088]
* Version: 5.21.0
* Python: 3.7
* OS: win

### What was wrong?
After running web3 some time, I get the following error:
```
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 503
```

With the following piece of code:
```
web3 = Web3(Web3.WebsocketProvider("wss://bsc-ws-node.nariox.org:443"))
```
I'm wondering, could it be that I'm exceeding data rate limits or something? It says 10K/5min rate limit, do they mean 10k requests every 5 minutes max?

Also could it be the websocket stays open too long, for like after a day, it just refuses it? It happens every now and then, restarting the program will cause this error over and over, usually the next day it's fixed.

**Comment by fselmo** [comment]
This seems very much related to the node you are connecting to. There seems to be a few different scenarios where the web socket connection may be terminated. Not a direct resource for the node you are connecting to but from the Binance docs [here](https://binance-docs.github.io/apidocs/delivery/en/#basis-market-data):

- A single [websocket] connection is only valid for 24 hours; expect to be disconnected at the 24 hour mark
- The websocket server will send a ping frame every 5 minutes. If the websocket server does not receive a pong frame back from the connection within a 15 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.
- WebSocket connections have a limit of 10 incoming messages per second.

I'm going to close this as this does not seem to be stemming from web3py, nor do we support Binance / BSC directly. If you feel that is wrong and this should be re-opened, please feel free to re-open this. You may also get some more clarification from Binance gitter / discord channels. Good luck!

**Comment by Theagainmen** [comment]
> This seems very much related to the node you are connecting to. There seems to be a few different scenarios where the web socket connection may be terminated (one being longer than 24 hours). But I'm not too sure on the specifics of your node.
> 
> I'm going to close this as this does not seem to be stemming from web3py, nor do we support BSC directly. If you feel that is wrong and this should be re-opened, please feel free to re-open this. You may also get some more clarification from some community BSC-related channels. Good luck!

Thanks and understandable! The node was indeed longer connected than 24 hours, I thought maybe closing and opening the connection manually for when I need it, but I didn't find anything other than `isConnected()`.
