### ISSUE TITLE
Calling contract on past events, or filter get returns [] when using TestRPC

### ISSUE THREAD

**Issue by veqtor** [ethereum/web3.py#209]
* Version: 3.5.0 -> 3.10.0
* Python: 3.5
* OS: osx

Not getting any events, past or currents, when calling get() on either event filters.
I don't really want to post my contract but in any scenario when using testRPC I'm not getting any events at all. I've tried everything, fromBlock,  etc

Also tried downgrading to as low as 3.5.0 and it didn't solve it.
I'm thinking it might be a testrpc related issue...?

**Comment by pipermerriam** [comment]
Yes, this is almost definitely an eth-testrpc issue.

FYI, I'm not planning on focusing on this codebase much longer as I'm in the process of fully replacing it with a new library which can be found here: https://github.com/pipermerriam/ethereum-tester

`eth-tester` isn't ready for use, but it'll present very similar functionality but with a completely re-written codebase that's better tested.  Filters are one of the biggest tech-debt areas being cleaned up.

**Comment by pipermerriam** [comment]
closing this as the filter API has been reworked. Please re-open or re-submit a new issue if you are still having issues.
