### ISSUE TITLE
use web3py to simulate buy token approve sell token to avoid being scammed

### ISSUE THREAD

**Issue by enthusiastics** [ethereum/web3.py#2106]
I have been scammed by some of the web3 contracts, where I can buy it from pancake swap,
but the approve function is written in a way such that it does not take effect. I'm the only one in the world who is scammed by that token, the scammer is 0x608756c184A0723077B0c10F97f4D054c9eE1C0F (in BSC network) he had created a lot of such tokens one of which i accidentally buy. 

So to further avoid being scammed, I would like to test a simulated "buy with wbnb -> approve transfer of token from pancake -> sell that token back into wbnb" cycle. 

What's the best way for me to achieve it? The only way I could think of is writing a new contract and create an un-signed transaction, perform an estimate gas on it, to see if there is any error and confirm i could get back the correct amount of wbnb back to me.... 

However, I haven't written any solidity code before... Is there a better way to approach it? How do I write such a solidity code?

**Comment by fselmo** [comment]
Hey @enthusiastics this is a great question to ask in the [discord](https://discord.gg/9zk7snTfWe). It doesn't seem like an inherent issue with the web3.py library. I or others would be glad to help out if you reach out there. If you feel this is an issue with web3.py and I misunderstood, please feel free to reopen this issue! Cheers.

**Comment by lidd77** [comment]
> 

Hey,  https://stackoverflow.com/questions/69403676/how-to-simulate-buy-trade-transactions-on-local
this link is expired,  any new link to use ? 

thanks.
