### ISSUE TITLE
Support get_logs in AsyncHTTPProvider

### ISSUE THREAD

**Issue by tsudmi** [ethereum/web3.py#2129]
Hi,

Fetching the logs (especially if it's a long list) is one of the most time-consuming operations.  It would be great to add support for executing `get_logs` using `AsyncHTTPProvider`.

Thanks!

**Comment by kclowes** [comment]
Thanks for the request! It's near the top of our priority list!

**Comment by AngeloCa** [comment]
Any update on an async-ification of web3.eth.get_transaction_receipt ?

**Comment by pacrob** [comment]
Thanks for the reminder! Working on it now.

**Comment by pacrob** [comment]
fixed in pr #2310
