### ISSUE TITLE
Support for Consensus Engine Methods

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2130]
### What was wrong?

This isn't ready for work yet, but wanted start tracking. 

There are some new consensus methods coming down the pipe prefixed with `engine_`. Here is a preliminary list: https://hackmd.io/@n0ble/consensus_api_design_space. It will probably make sense to make each method its own issue or group a few methods together for implementation so the PR isn't massive.  

### How can it be fixed?

 Add them!

**Comment by tsudmi** [comment]
@kclowes The validators' withdrawals are about to be supported on Mainnet. It would be great to add them: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md

**Comment by kclowes** [comment]
@tsudmi I don't think these endpoints have anything to do with withdrawals. Withdrawal support is coming in PR #2868. And actually, I'm not sure we need to support the `engine` RPC methods in web3.py since they're just for communicating between the EL and CL. I'm going to leave this open for a bit to see if it garners any more feedback, but at this point, I'm leaning toward not supporting these.

**Comment by kclowes** [comment]
This is just between EL and CL, no support needed.
