### ISSUE TITLE
How to set Gas limit ?

### ISSUE THREAD

**Issue by mapapuche** [ethereum/web3.py#2132]
Hello, i have a little question about gas.

On my code i use it to set the gas gwei
```
def gas_price_strategy():
    return Web3.toWei(5, 'gwei')
```
But i'm paying at fees because of "Gas Limit" i think :
![image](https://user-images.githubusercontent.com/64193148/132136338-926579c8-e58d-4a74-84de-4756f4b70cd8.png)

When i check other people doing exaclty same transaction than me they have 10x less fees than me (same function called)
![image](https://user-images.githubusercontent.com/64193148/132136388-5aff1289-09b8-4562-b495-1353bf928a92.png)

Do you know if there is a way to set a maximum Gas Limit please ? Because he is using 300 000 Gas limit and look like it pays much less lol

**Comment by fselmo** [comment]
@mapapuche This isn't an issue with web3.py. The best avenue for asking usage questions is asking in the [discord server](https://discord.gg/9zk7snTfWe) or [gitter](https://gitter.im/ethereum/web3.py). I'd also suggest getting familiar with BSC transaction setup and sending in particular.

The discord is a great community of people helping people and is a more appropriate method of asking questions. Pop in and say hello and I'd be happy to chat with you about web3.py usage. Cheers.
