### ISSUE TITLE
Issue with buildTranscaction

### ISSUE THREAD

**Issue by jhb10c** [ethereum/web3.py#2134]
* Version: 5.23.1
* Python: 3.8.8
* OS: osx
* `pip freeze` output

```




### What was wrong?

When building the call data for a transaction using buildTransaction, error code -32016 keep occuring. Not sure why it is occuring

Please include any of the following that are applicable:

* The code which produced the error:
rece = router.functions.swapExactTokensForTokens(1,1,Path[:2],web3.toChecksumAddress('0xCA090945dF18fFd93F342Cb1e8B61d3f71e044a7'),1633501982).buildTransaction()



* The full output of the error:

  File "<ipython-input-144-66e457b9cef4>", line 1, in <module>
    rece = router.functions.swapExactTokensForTokens(1,1,Path[:2],web3.toChecksumAddress('0xCA090945dF18fFd93F342Cb1e8B61d3f71e044a7'),1633501982).buildTransaction()

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/contract.py", line 1079, in buildTransaction
    return build_transaction_for_function(

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)

  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/_utils/transactions.py", line 102, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/_utils/transactions.py", line 66, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/eth.py", line 728, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,

  File "/opt/anaconda3/lib/python3.8/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])



* Node:
Infura RPC


### How can it be fixed?

Work around was to build transaction call using the method .encodeABI like below:

    rece = router.encodeABI(fn_name='swapExactTokensForTokens',args=[amountIn,amountOutMin,path,to,deadline])

**Comment by kclowes** [comment]
@jhb10c what's the error message you're seeing with `buildTransaction`?

**Comment by jhb10c** [comment]
This is the error that appears: 

ValueError: {'code': -32016, 'data': 'Reverted', 'message': 'The execution failed due to an exception.'}

**Comment by kclowes** [comment]
I think this is probably an issue with the parameters that you're passing in. `Revert` is a contract error that people use to validate that certain conditions are met in the contract, and it looks like your code is reverting when trying to estimateGas. If you do: `router.functions.swapExactTokensForTokens(1,1,Path[:2],web3.toChecksumAddress('0xCA090945dF18fFd93F342Cb1e8B61d3f71e044a7'),1633501982).estimateGas()`
do you get the same error response from your node? If so, I'd play around with the parameters you're passing in. I'd start with the `deadline` and the `amountOutMin`.

Although I am curious to see the steps you used for the workaround. How did you use `encodeABI` to get it working?

**Comment by jhb10c** [comment]
I tried router.functions.swapExactTokensForTokens(11,5,Path,maddress,1636232904).estimateGas(). The same error appears: {'code': -32016, 'data': 'Reverted', 'message': 'The execution failed due to an exception.'}


For the work around, the transaction is explicitly built using encodeABI. Then it is signed and sent out.
For example, here is the code block that will approve the tokens, build a transaction to swap on routerv2, and then transmit the transaction (this does work for whatever reason):


def swapExactTokensForTokens(amountIn,amountOutMin,path,to,deadline):
    approvePath(web3,IERC20,[web3.toChecksumAddress(path[0])],[amountIn],routerv2)
    rece = router.encodeABI(fn_name='swapExactTokensForTokens',args= 
                [amountIn,amountOutMin,path,to,deadline])
    tx = {'from':maddress,
             'nonce':web3.eth.getTransactionCount(maddress),
              'data':rece,
               'to':routerv2,
               'gas':2100000,
                'gasPrice':web3.toWei(79,'gwei')
             }
    return functiontransaction(web3,privateKey,tx) # signs and transmits the transaction

**Comment by kclowes** [comment]
Interesting. We'll take a look. Thanks for raising this!

**Comment by jhb10c** [comment]
Thanks, if there is a bug, I would not mind fixing it with some directions.

**Comment by Kingsley-Sun** [comment]
hey is it a bug and how long will it be fixed

**Comment by fselmo** [comment]
These errors appear to be coming from the provider you are connected to and when calling `estimateGas`. In your work-around it looks like you define a pretty full transaction and include a `gas` value. I'm confident you can circumvent these `eth_estimateGas` issues if you use this same `gas` value with `build_transaction()` as such:

```py
rece = router.functions.swapExactTokensForTokens(
    1,1,Path[:2],web3.toChecksumAddress('0xCA090945dF18fFd93F342Cb1e8B61d3f71e044a7'),1633501982
).build_transaction({
    'gas': 2100000,  # provide the same gas used in the "encodeABI workaround"
})
```

I'm going to close this as the issue doesn't appear to be with the library but please feel free to reach back out with more information if you believe that it is.
