### ISSUE TITLE
Improving throughput of calls to w3.eth.filter

### ISSUE THREAD

**Issue by helgridly** [ethereum/web3.py#2137]
* Version: 5.23.1
* Python: 3.9.6
* OS: Ubuntu 20.04
* 16 cores (this will become apparent later)

This isn't an issue, it's a discussion :)

## Motivation

I have a list of contracts that I want to get all events for. Here's a rough approximation of my code: it runs a filter and walks through all blocks from the contract creation block to some end block.

```python
async def go():
  # contracts_and_creations = [(contract_addr, contract_creation_block), ...]
  latest_block_num = _w3_inst.eth.get_block(number).number
  job = asyncio.gather(*[walk_events(a, c, latest_block_num) for a, c in contracts_and_creations])

  await asyncio.wait_for(job, 60)
  
stride = 50
async def walk_events(contract_addr, first_block, last_block):
  block_range = last_block - first_block
  for i in range(block_range/stride):
    from_block = first_block + stride*i
    to_block = from_block + stride

    # this is the interesting line we'll talk about
    return await asyncio.to_thread(get_entries, address, from_block, to_block)

def get_entries(address, from_block, to_block):
  # recreate the filter every time as geth loves to drop it
  filter = w3.eth.filter({"address": contract_addr,
                          "fromBlock": from_block,
                          "toBlock": to_block})
  return filter.get_all_entries()
```

(In practice my code is more complicated than this - it adjusts the stride length based on how many results are returned, has error handling, etc. I'm also interested in a specific subset of events so there's some hoop-jumping to add the list of topic hashes to the `filter` call.)

The question is: **How can I increase my overall throughput given hundreds-to-thousands of contracts?**

## Exploration

I've been running the above code a bunch lately and even with ~500 concurrent "walkers" my throughput has been pretty abysmal - well below BSC's 10k/5min ratelimit. This works out to 15 reqs/sec, which shouldn't be hard to achieve! I'm finding that each call to `filter` takes ~2.5s to return, which means 38 parallel walkers should max out the ratelimit. 38 is much less than 500, so I'm clearly bottlenecked somewhere.

The obvious culprit is that HTTPProvider is synchronous. This is initially why I put the call in `asyncio.to_thread`, but I think that just means the thread ends up sitting on the GIL waiting for the request to complete.

So I did some benchmarking. I tried four things, changing the noted "interesting line" in the code sample above:
* `asyncio.to_thread`
* `loop.run_in_executor` with one `ProcessPoolExecutor(max_workers=16)` per walker
* `loop.run_in_executor` with one `ProcessPoolExecutor(max_workers=16)` shared across all walkers
* `loop.run_in_executor` with one `ProcessPoolExecutor(max_workers=64)` shared across all walkers

I ran each test with 15, 30, 60, and 120 concurrent walkers. Here are the results: numbers are average throughput over a 60-second runtime, in requests/second. (bigger numbers are better)
| number of "concurrent" walkers | asyncio.to_thread | per-walker ProcessPoolExecutor | shared ProcessPoolExecutor(16) | shared ProcessPoolExecutor(64) |
|--------------------------------|-------------------|--------------------------------|--------------------------------|--------------------------------|
| 15                             | 4.37              | 4.77                           | 4.75                           | 4.07                           |
| 30                             | 7.30              | 8.42                           | 5.83                           | 9.42                           |
| 60                             | 9.23              | 19.17                          | 7.73                           | 23.87                          |
| 120                            | 14.10             | 39.98                          | 10.82                          | 27.38                          |

I realise that 39.98 is seriously funky, but I tried it a second time and it actually went _up_.

The big surprise to me here is that making a `ProcessPoolExecutor` for _each walker_ seems to be scaling linearly. Presumably that will stop at some point. I also tested a process pool of size 128, which behaved like the per-walker case for 120 walkers. That makes sense.

## Final thoughts

This is pretty good, and I'm close to the ideal case - it should take 38 walkers to hit a throughput of 15 req/sec. That's in the ballpark of what I'm getting, if you squint.

Still: is there anything else you think I could do? The `AsyncHTTPProvider` doesn't support filters yet, so that doesn't help me (though it's not _impossible_ that I make that happen :slightly_smiling_face:). Other than that, any ideas?

(eagle eyes may notice the ending of this has changed; I discovered I wasn't counting right so all my numbers changed!)

**Comment by kclowes** [comment]
Thanks for checking this out and opening such a detailed issue @helgridly! I think your best bet as far as increasing throughput is the AsyncHTTPProvider, like you say. Our preliminary benchmarking looks like a pretty significant performance bump. You can see results on [circle ci](https://app.circleci.com/pipelines/github/ethereum/web3.py/1790/workflows/0cb6d5d0-9fca-453f-a785-b45be5a6fbb5/jobs/172769) under the 'run tox' section of the job if you're curious. You might also try using the [local_filter_middleware](https://web3py.readthedocs.io/en/stable/middleware.html?#locally-managed-log-and-block-filters) - I'm not sure if that would help or hurt.


> though it's not impossible that I make that happen 🙂

If you want to take a swing at async filters, I could definitely help direct/review! It's pretty high on our web3 priority queue, but all of us maintainers are up to our necks in other things right now so it'll be a bit before any of us can get to it.

**Comment by helgridly** [comment]
I tried the local filter middleware and from a quick (not thorough at all) test it seemed way slower, at least for me - I'm typically interested in a small number of addresses, so getting every block and filtering client-side (my understanding of how they work) was quite the yikes.

**Comment by Morgon** [comment]
Just to chime in that using `local_filter_middleware` for block filters has some performance issues, via #1871. I suspect the approach will be more stable once it is resolved.

**Comment by kclowes** [comment]
Closing. `WebSocketProvider` in v7 is async, and we have a new `AsyncIPCProvider` as well. Please re-open if these don't meet your needs.
