### ISSUE TITLE
ModuleNotFoundError: No module named 'web3'

### ISSUE THREAD

**Issue by solkoren** [ethereum/web3.py#2144]
I just started coding in python and I'm trying to do "python deploy.py" and this pops out:

Traceback (most recent call last):
  File "D:\Web3\project\Web3_python\web3_py_simple_storage\deploy.py", line 3, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'

somebody knows what to do?

**Comment by solkoren** [comment]
what i shuld do?

**Comment by rdxpt** [comment]
Have you installed web3 via pip?

**Comment by solkoren** [comment]
i have pip 
and i can not download web3 look...

**Comment by solkoren** [comment]
Collecting web3
  Using cached web3-5.23.1-py3-none-any.whl (486 kB)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (1.10.0)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (2.26.0)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.17.3-cp39-cp39-win_amd64.whl (909 kB)
Collecting websockets<10,>=9.1
  Using cached websockets-9.1-cp39-cp39-win_amd64.whl (90 kB)
Collecting ipfshttpclient==0.8.0a2
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Collecting eth-account<0.6.0,>=0.5.5
  Using cached eth_account-0.5.5-py3-none-any.whl (100 kB)
Collecting aiohttp<4,>=3.7.4.post0
  Using cached aiohttp-3.7.4.post0-cp39-cp39-win_amd64.whl (634 kB)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (2.1.1)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (0.2.2) 
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from 
web3) (0.3.2)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
Collecting pywin32>=223
  Using cached pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (2.2.2)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from ipfshttpclient==0.8.0a2->web3) (0.0.9)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (5.1.0)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (3.10.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.6.3)
Collecting attrs>=17.3.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Requirement already satisfied: chardet<5.0,>=2.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (4.0.0)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: rlp<3,>=1.0.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-account<0.6.0,>=0.5.5->web3) (2.0.1)
Requirement already satisfied: eth-keys!=0.3.2,<0.4.0,>=0.2.1 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-account<0.6.0,>=0.5.5->web3) (0.3.3)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-account<0.6.0,>=0.5.5->web3) (0.5.1)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-account<0.6.0,>=0.5.5->web3) (0.2.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.10.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cytoolz<1.0.0,>=0.9.0->eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.1)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.0)
Requirement already satisfied: setuptools in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (58.0.4)
Requirement already satisfied: six>=1.11.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: base58 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (2.1.0)
Requirement already satisfied: netaddr in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (0.8.0)
Requirement already satisfied: varint in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (1.0.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sol\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.2)
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lru-dict, since package 'wheel' is not installed.
Installing collected packages: bitarray, attrs, async-timeout, websockets, pywin32, protobuf, lru-dict, jsonschema, ipfshttpclient, eth-account, aiohttp, web3
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Sol\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sol\\AppData\\Local\\Temp\\pip-install-zvlv61if\\bitarray_968ecc5c424d41c2a1ac55c2c65887d1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sol\\AppData\\Local\\Temp\\pip-install-zvlv61if\\bitarray_968ecc5c424d41c2a1ac55c2c65887d1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else 
io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sol\AppData\Local\Temp\pip-record-z28cksy2\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Sol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\bitarray'
         cwd: C:\Users\Sol\AppData\Local\Temp\pip-install-zvlv61if\bitarray_968ecc5c424d41c2a1ac55c2c65887d1\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\bitarray
    copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\test_util.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\util.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\__init__.py -> build\lib.win-amd64-3.9\bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Sol\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sol\\AppData\\Local\\Temp\\pip-install-zvlv61if\\bitarray_968ecc5c424d41c2a1ac55c2c65887d1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sol\\AppData\\Local\\Temp\\pip-install-zvlv61if\\bitarray_968ecc5c424d41c2a1ac55c2c65887d1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) 
if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Sol\AppData\Local\Temp\pip-record-z28cksy2\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Sol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\bitarray' Check the logs for full command output.
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\Sol\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

**Comment by kclowes** [comment]
The relevant line in the error message is here: `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`. 

Here is some more info: https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error

**Comment by solkoren** [comment]
ok installed but i have all the time this error

C:\Users\Sol\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'D:\Web3\Solw3\project\Web3_python\deploy.py': [Errno 2] No such file or directory
PS D:\Web3\Solw3\project\Web3_python>

**Comment by Cyber-BlackBird** [comment]
I am facing the same issue @solkoren 
https://github.com/ethereum/web3.py/issues/2147#issue-994967807

@kclowes conda installation is not working. The link to the issue is below - 
https://github.com/conda-forge/web3-feedstock/issues/31#issue-995837337

**Comment by step21** [comment]
> ok installed but i have all the time this error
> 
> C:\Users\Sol\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'D:\Web3\Solw3\project\Web3_python\deploy.py': [Errno 2] No such file or directory
> PS D:\Web3\Solw3\project\Web3_python>

This seems like a problem with your python install, I would suggest using a proper python distribution.
@Cyber-BlackBird yours is likely a different problem, and you should make a different thread for it (as you did on conda-forge/web3-feedstock)

**Comment by Chiemerie1** [comment]
I had this problem but I fixed it by installing Microsoft C++ Build Tools. here is the download link: [https://visualstudio.microsoft.com/visual-cpp-build-tools/]

Run the download setup then check C++ build tools and click install.
Restart you PC and pip install web3 again
