### ISSUE TITLE
Expected ';' but got 'contract'

### ISSUE THREAD

**Issue by solkoren** [ethereum/web3.py#2148]
I'm trying to do this:

pragma solidity ^0.8.0;

import "./ERC721.sol"

contract nft is ERC721.sol {

  constructor() ERC721.sol("name", "NAME") public {
  }
}

and i get this error:

Expected ';' but got 'contract'

what should I do?

**Comment by fselmo** [comment]
@solkoren In general, we refrain from answering questions here and direct users to the [discord](https://discord.gg/GHryRvPB84) as we like to keep this space for issues with the web3.py library. This happens to be a question about writing solidity but I'm sure you'd get some support over there.
