### ISSUE TITLE
Getting 'missing trie node' when call function for a specific block number

### ISSUE THREAD

**Issue by phamhongphuc1999** [ethereum/web3.py#2149]
* Version: web3 5.19.0
* Python: 3.8
* OS: ubuntu
* `pip freeze` output

### What was wrong?
I am using web3 py library to interact with the ethereum based blockchain mainnet. I tried to call a contract method for a specific block number:
```
web3 = Web3(Web3.HTTPProvider(MAINNET_ENDPOINT))
contract = web3.eth.contract(address=contract_address, abi=contract_abi)
data = contract.functions.getReservesList().call(block_identifier=block_number)
```
I am getting the following error(Missing trie node).

![Screenshot from 2021-09-15 00-14-48](https://user-images.githubusercontent.com/56115755/133303867-858e16e6-c1d6-4db9-a71f-383115d9490e.png)

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
@phamhongphuc1999 This is an error being returned by your client. This does not involve an issue with web3.py. It seems like a sync or configuration issue with the client but I would suggest you ask it in the appropriate channel for the client you are using. Best of luck.

**Comment by phamhongphuc1999** [comment]
> @phamhongphuc1999 This is an error being returned by your client. This does not involve an issue with web3.py. It seems like a sync or configuration issue with the client but I would suggest you ask it in the appropriate channel for the client you are using. Best of luck.

thank for your suggestion
