### ISSUE TITLE
How to get metadata of nft token?

### ISSUE THREAD

**Issue by howgoodisdata** [ethereum/web3.py#2156]
I would like to get metadata of nft token through web3.py https://web3py.readthedocs.io/en/stable/examples.html#querying-token-metadata
But when i call this function i'm getting as None, is there any alternative way to get the metadata?
if so please guide me the way to get this done.

**Comment by kclowes** [comment]
What address is it and what is the code you're running? A `None` response sounds like the token hasn't implemented the metadata you're asking for.

**Comment by fselmo** [comment]
Hey @howgoodisdata, we prefer to use issues to track our work. I’m going to close this as this does not seem like it is an issue with web3.py. Please feel free to re-open if you believe it was closed in error.

If you have implementation or usage questions, please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation on [discord](https://discord.gg/GHryRvPB84).
