### ISSUE TITLE
How to sign new modified transaction?

### ISSUE THREAD

**Issue by fahadh4ilyas** [ethereum/web3.py#2163]
* Version: 5.20.0
* Python: 3.9.6
* OS: linux
* `pip freeze` output

```
aiohttp==3.7.4.post0
aioredis==2.0.0
amqp==5.0.6
asn1crypto==1.4.0
asttokens==2.0.4
async-timeout==3.0.1
attrs==21.2.0
base58==2.1.0
billiard==3.6.4.0
bitarray==1.2.2
celery==5.1.2
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
coincurve==15.0.1
colorama==0.4.4
cytoolz==0.11.0
ecdsa==0.17.0
eciespy==0.3.10
eth-abi==2.1.1
eth-account==0.5.5
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
fastapi==0.68.1
fastapi-limiter==0.1.4
gunicorn==20.1.0
h11==0.12.0
hexbytes==0.2.2
idna==3.2
ipfshttpclient==0.7.0
jsonschema==3.2.0
kombu==5.1.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
parsimonious==0.8.1
prompt-toolkit==3.0.20
protobuf==3.17.3
py-solc-x==1.1.0
pyasn1==0.4.8
pycparser==2.20
pycryptodome==3.10.1
pydantic==1.8.2
pymongo==3.12.0
pyrsistent==0.18.0
python-dotenv==0.19.0
python-jose==3.3.0
pytz==2021.1
pywin32==301
PyYAML==5.4.1
redis==3.5.3
requests==2.26.0
rlp==2.0.1
rsa==4.7.2
semantic-version==2.8.5
six==1.16.0
starlette==0.14.2
toolz==0.11.1
tqdm==4.61.1
typing-extensions==3.10.0.2
urllib3==1.26.6
uvicorn==0.13.4
varint==1.0.2
vine==5.0.0
vyper==0.2.12
watchgod==0.7
wcwidth==0.2.5
web3==5.20.0
websockets==8.1
wincertstore==0.2
yarl==1.6.3
```

### What was wrong?

I'm using web3.py to connect to ethereum node using `HTTPProvider`. This is how I connect to the node

```python
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))
```

I also try to send transaction and it's working properly

```python
transaction = {
    "from": w3.eth.accounts[0],
    "to": w3.eth.accounts[1],
    "value": 1000,
    "chainId": w3.eth.chainId,
    "nonce": w3.eth.get_transaction_count(w3.eth.accounts[0]),
    "gasPrice": w3.eth.gas_price
}
transaction["gas"] = w3.eth.estimate_gas(transaction)

account = w3.eth.account.from_key(private_key)
signed_transaction = account.sign_transaction(transaction)
transaction_hash = w3.eth.send_raw_transaction(signed_transaction.rawTransaction)
```

The problem is when I want to try to [`modify_transaction`](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.modify_transaction). This is not working

```python
w3.eth.modify_transaction(transaction_hash, {"value": 2000})
```

I can't just do [`send_transaction`](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.send_transaction) because the accounts in the node are not unlocked due to RPC connection enabled. That's why I believed `modify_transaction` won't be working because basically `modify_transaction` is calling `eth_signTransaction`. Is there any way to `modify_transaction` if the accounts in the node are not unlocked?

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by kclowes** [comment]
You should be able to use the [construct_sign_and_send_raw_middleware](https://web3py.readthedocs.io/en/stable/middleware.html?#web3.middleware.construct_sign_and_send_raw_middleware). Feel free to reopen if that doesn't fix your issue!
