### ISSUE TITLE
Cannot send transactions on arbitrum

### ISSUE THREAD

**Issue by fredo** [ethereum/web3.py#2169]
* Version: 5.24.0
* Python: 3.9
* OS: linux

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

I tried to send a basic transaction (sending eth) on arbitrum with web3.py. 

Configurations: 

`w3 = Web3(HTTPProvider("https://rinkeby.arbitrum.io/rpc"))`
Network: Rinkeby
The address is funded with 0.09999999899 ETH

### Pre EIP-1559 Transaction

code:

```
tx = {
    'nonce': 0,
    'to': "0x31d8E842Be69b43B1caC81215bA4cF5B4ee385D8",
    'from': address,
    'value': 1_000_000_000_000_000,
    'gas': 21000,
    'gasPrice': 1_000_000_000,
    "data": b'',
    "chainId": 421611,
}

signed_tx = w3.eth.account.sign_transaction(tx, private_key)
tx_hash = w3.eth.sendRawTransaction(signed_tx.rawTransaction)
```

output:

```
Traceback (most recent call last):
  File "/home/fred/projects/raisync/tests/arb_comm.py", line 32, in <module>
    tx_hash = w3.eth.sendRawTransaction(signed_tx.rawTransaction)
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/eth.py", line 698, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'not enough funds for gas'}

```

### Post EIP-1559 transaction

code:

```
tx = {
    'nonce': 0,
    'to': "0x31d8E842Be69b43B1caC81215bA4cF5B4ee385D8",
    'from': address,
    'value': 1_000_000_000_000_000,
    'gas': 21000,
    'maxFeePerGas': 10_000_000_000,
    'maxPriorityFeePerGas': 1_000_000_000,
    'data': b'',
    'type': 2,  # (optional) the type is now implicitly set based on appropriate transaction params
    'chainId': 421611,
}

signed_tx = w3.eth.account.sign_transaction(tx, private_key)
tx_hash = w3.eth.sendRawTransaction(signed_tx.rawTransaction)
```

output:

```
Traceback (most recent call last):
  File "/home/fred/projects/raisync/tests/arb_comm.py", line 32, in <module>
    tx_hash = w3.eth.sendRawTransaction(signed_tx.rawTransaction)
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/eth.py", line 698, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/home/fred/projects/raisync/tests/venv/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'rlp: expected List'}

```

I have read that arbitrum is not supported yet, but I wonder if this issue can be fixed easily. Web3.js works out of the box.

It would be nice to get an outlook of when this could be supported.

**Comment by fselmo** [comment]
@jornx This seems to be a known issue with Arbitrum validators I believe. If you are certain that you have enough funds, this is related to the `gas` value being set too low and unfortunately the message here is wrong.

I ran into a similar issue trying to send a transaction and I knew I had enough funds but increasing the `gas` value did the trick. I submitted a support ticket to them but I do believe this is a known issue that will hopefully be fixed soon.

It is important to note here that you still only end up paying the `gas` amount that was requited for the transaction, not what you actually pass in for that value. So I increased the `gas` on a simple transfer transaction to `800000` and it was successful but only used `641,700` Arbitrum gas.

---

With respects to using EIP-1559 style transaction, that is not how Arbitrum works (at least for now). Arbitrum only uses a `gasPrice` value for their transactions. However, Arbitrum uses an EIP-1559-like gas auction system so the `gasPrice` you list in your transaction is a bid, but the actual price may be lower: https://developer.offchainlabs.com/docs/public_testnet#interacting-with-the-chain


Closing this as it is not an issue with the web3.py library.
