### ISSUE TITLE
Pip install error -- Mac

### ISSUE THREAD

**Issue by arjuneth** [ethereum/web3.py#2171]
* Version: x.x.x
* Python: 3.9
* OS: MAC
* `pip freeze` output

```
<put the output from running pip freeze here>
(.venv-py3) arjun@Arjuns-MBP defianalytics % pip freeze
base58==2.1.0
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.6
cytoolz==0.11.0
eth-abi==2.1.1
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.2
idna==3.2
multiaddr==0.0.9
multidict==5.2.0
netaddr==0.8.0
parsimonious==0.8.1
pycryptodome==3.10.4
pyrsistent==0.18.0
requests==2.26.0
rlp==2.0.1
six==1.16.0
toolz==0.11.1
typing-extensions==3.10.0.2
urllib3==1.26.7
varint==1.0.2
yarl==1.6.3

```

### What was wrong?
Trying to install web3 but getting an error when it comes to building wheel for lru-direct and bitarray. I'm trying to run this on a Mac and haven't found a solution yet. Any help would be appreciated. 

Please include any of the following that are applicable:

* The code which produced the error
* pip install --upgrade web3   

* The full output of the error
Collecting web3
  Using cached web3-5.24.0-py3-none-any.whl (487 kB)
Collecting ipfshttpclient==0.8.0a2
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (0.3.2)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
Collecting eth-account<0.6.0,>=0.5.6
  Using cached eth_account-0.5.6-py3-none-any.whl (101 kB)
Collecting aiohttp<4,>=3.7.4.post0
  Using cached aiohttp-3.7.4.post0-cp39-cp39-macosx_10_14_x86_64.whl (649 kB)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (1.10.0)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (2.26.0)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (0.2.2)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.18.1-cp39-cp39-macosx_10_9_x86_64.whl (1.0 MB)
Collecting websockets<10,>=9.1
  Using cached websockets-9.1-cp39-cp39-macosx_10_9_x86_64.whl (88 kB)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (2.1.1)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from web3) (2.2.2)
Requirement already satisfied: multiaddr>=0.0.7 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from ipfshttpclient==0.8.0a2->web3) (0.0.9)
Collecting attrs>=17.3.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from aiohttp<4,>=3.7.4.post0->web3) (3.10.0.2)
Requirement already satisfied: chardet<5.0,>=2.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from aiohttp<4,>=3.7.4.post0->web3) (4.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from aiohttp<4,>=3.7.4.post0->web3) (5.2.0)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: eth-keys!=0.3.2,<0.4.0,>=0.2.1 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.3.3)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.2.1)
Requirement already satisfied: rlp<3,>=1.0.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-account<0.6.0,>=0.5.6->web3) (2.0.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.5.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.10.4)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.6->web3) (0.11.0)
Requirement already satisfied: toolz>=0.8.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from cytoolz<1.0.0,>=0.9.0->eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.6->web3) (0.11.1)
Requirement already satisfied: setuptools in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (58.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.0)
Requirement already satisfied: six>=1.11.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: base58 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (2.1.0)
Requirement already satisfied: varint in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (1.0.2)
Requirement already satisfied: netaddr in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (0.8.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from requests<3.0.0,>=2.16.0->web3) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from requests<3.0.0,>=2.16.0->web3) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/arjun/.venv-py3/lib/python3.9/site-packages (from requests<3.0.0,>=2.16.0->web3) (2.0.6)
Building wheels for collected packages: bitarray, lru-dict
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arjun/.venv-py3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"'; __file__='"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-wheel-t9bjsdjo
       cwd: /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.9
  creating build/lib.macosx-11-x86_64-3.9/bitarray
  copying bitarray/util.py -> build/lib.macosx-11-x86_64-3.9/bitarray
  copying bitarray/__init__.py -> build/lib.macosx-11-x86_64-3.9/bitarray
  copying bitarray/test_bitarray.py -> build/lib.macosx-11-x86_64-3.9/bitarray
  copying bitarray/test_util.py -> build/lib.macosx-11-x86_64-3.9/bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  creating build/temp.macosx-11-x86_64-3.9
  creating build/temp.macosx-11-x86_64-3.9/bitarray
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/arjun/.venv-py3/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c bitarray/_bitarray.c -o build/temp.macosx-11-x86_64-3.9/bitarray/_bitarray.o
  clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
  Building wheel for lru-dict (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arjun/.venv-py3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/lru-dict_7998f91d71c645099167ed038b95a4a1/setup.py'"'"'; __file__='"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/lru-dict_7998f91d71c645099167ed038b95a4a1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-wheel-w8u85rfk
       cwd: /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/lru-dict_7998f91d71c645099167ed038b95a4a1/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build/temp.macosx-11-x86_64-3.9
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/arjun/.venv-py3/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c lru.c -o build/temp.macosx-11-x86_64-3.9/lru.o
  clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
Failed to build bitarray lru-dict
Installing collected packages: bitarray, attrs, async-timeout, websockets, protobuf, lru-dict, jsonschema, ipfshttpclient, eth-account, aiohttp, web3
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/arjun/.venv-py3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"'; __file__='"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-record-9z7w1myw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arjun/.venv-py3/include/site/python3.9/bitarray
         cwd: /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-x86_64-3.9
    creating build/lib.macosx-11-x86_64-3.9/bitarray
    copying bitarray/util.py -> build/lib.macosx-11-x86_64-3.9/bitarray
    copying bitarray/__init__.py -> build/lib.macosx-11-x86_64-3.9/bitarray
    copying bitarray/test_bitarray.py -> build/lib.macosx-11-x86_64-3.9/bitarray
    copying bitarray/test_util.py -> build/lib.macosx-11-x86_64-3.9/bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    creating build/temp.macosx-11-x86_64-3.9
    creating build/temp.macosx-11-x86_64-3.9/bitarray
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/arjun/.venv-py3/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c bitarray/_bitarray.c -o build/temp.macosx-11-x86_64-3.9/bitarray/_bitarray.o
    clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/arjun/.venv-py3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"'; __file__='"'"'/private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-install-d26sbr1t/bitarray_7e42ae51235c40b6bce260fd4be19918/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jp/wpvgxk415w76txzmyq4sg36m0000gn/T/pip-record-9z7w1myw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arjun/.venv-py3/include/site/python3.9/bitarray Check the logs for full command output.

* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Hey @arjuneth this seems like a similar issue we've seen where you don't have xcode command line tools installed (required by some dependencies). Can you try running `xcode-select --install` and see if it is installed or not. If it is not, install it. This will likely solve your issue.

Please report back. Best of luck.

**Comment by ideolog** [comment]
I finally managed to install web3 after many hours of fight! Here is what I did:

1. I've downloaded Python 3.9.7 and reinstalled it https://www.python.org/downloads/release/python-397/
2. I've changed my Python's project interpreter to the new Python 3.9.7. and created a new virtual environment
3. `pip install bitarray` (this step is probably not needed)
4. `pip install web3 `
Everything worked like a charm.

**Comment by fselmo** [comment]
The general bitarray dependency issue is being tracked by https://github.com/ethereum/eth-account/issues/132. I am going to close this in hopes of keeping the conversation in one place.

For now, the most relevant documentation can be found here: https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error

We realize this does not seem to work for everyone and we expect to get to this issue very soon.

**Comment by Cozza50** [comment]
@fselmo Thanks for the tips. I have same problem. I try to running xcode-select --install and it wasn't istalled, after installation it, the pip install web3 was installed without problems.

**Comment by johnngo** [comment]
> I finally managed to install web3 after many hours of fight! Here is what I did:
> 
> 1. I've downloaded Python 3.9.7 and reinstalled it https://www.python.org/downloads/release/python-397/
> 2. I've changed my Python's project interpreter to the new Python 3.9.7. and created a new virtual environment
> 3. `pip install bitarray` (this step is probably not needed)
> 4. `pip install web3 `
>    Everything worked like a charm.

this was magic, thank you very much!
