### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by k128** [ethereum/web3.py#2172]
- Version: 5.x
- Python: 3.10!
- OS: osx/linux/win

What was wrong?
Now that Python 3.10 is out, we should make sure we can support it.

How can it be fixed?
Pretty much anywhere that tests against Python 3.7 - 3.9, we should add Python 3.10. Python 3.9 support was added in [#1774](https://github.com/ethereum/web3.py/pull/1774) so that would be a good template to follow.  Merging will likely have to wait until dependencies support 3.10, but changes can be worked on before then.

**Comment by fselmo** [comment]
This is closed by PR #2175, for reference

**Comment by kclowes** [comment]
3.10 support is in master. Will be released soon:tm: in the first v6.0 beta release.
