### ISSUE TITLE
Trying to duplicate a transaction from GUI to CLI generates a syntax error

### ISSUE THREAD

**Issue by bitcoinmeetups** [ethereum/web3.py#2174]
Hello,

I'm BM. A very nice and polite guy.

I've been trying to duplicate a transaction that I made with a GUI in my Terminal for a while without success.

This is the transaction I'm trying to duplicate:

https://polygonscan.com/tx/0xcaf7358788aed4fd73b4fc26717e44a54750811fc1c62e6997db9bb0ae9f7585

This is what I was trying to do:

txn_data = contract.functions.swapExactETHForTokens(138607273911012674, [0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270, 8f3cf7ad23cd3cadbd9735aff958023239c6a063], e5d77ab5fea649ca621f4f6c8a9b542fef88ab8b, 3260059519).buildTransaction({nonce: nonce, value: 1000000000})

However, the above line always generates a syntax error. I have already asked around on r/ethdev for a number of times but noone there seems to be able to figure this out.

Can you see what's wrong with the input above and why it generates a syntax error?

**Comment by kclowes** [comment]
Stale, closing
