### ISSUE TITLE
Possible speed improvements

### ISSUE THREAD

**Issue by kylemcdonald** [ethereum/web3.py#2176]
After comparing web3.py to web3.js I found web3.js was more performant at most tasks. My particular interest is in the `eth_getBlockByNumber` JSON-RPC method.

Retrieving 1000 blocks over IPC, synchronously:

* web3.py 6.2s
* web3.js 2.5s

Asynchronously:

* web3.py 2.9s
* web3.js 0.3s

I am comparing between Node v12.22.6 and Python 3.7.10 on web3.js 1.6.0 and web3.py 5.24.0, under Ubuntu 18.04, with geth 1.10.9-stable-eae3b194.

By writing raw JSON-RPC calls over IPC and writing/reading in chunks, I was able to achieve 0.5s synchronously from Python. This indicates to me that the difference in speed is not:

- Python
- JSON decoding (though I did my own JSON encoding)

Please check my raw code as well as speed comparison code [here](https://gist.github.com/kylemcdonald/dc3bec51a876c1e6958ab2abc3ba1364).

I noticed that when I submit small chunks, approaching a chunk size of 1, the performance converges on web3.py. This explains why synchronous web3.py is slow: it's about the socket read/write overhead. But it doesn't explain why the async web3.py is slow.

Looking at https://github.com/ethereum/web3.py/blob/master/web3/providers/ipc.py#L247-L266 there might be something in this loop.  Maybe there is a small speedup in looking for newline endings instead of doing a try/catch JSON parse every time a potential ending is found? It might be worth checking how often that except JSONDecodeError code path is triggered in real world use.

Edit: Thanks to cheekybastard on discord for sharing the general form of the async Python test.

**Comment by Harmouch101** [comment]
Given the fact that python `strings/bytes` are immutable. Thus successive bytes concatenation (especially with large bytes) is considerably slow. Presumably, there is room for improvement by switching from `bytes` into `bytearray`(which is mutable).

https://github.com/ethereum/web3.py/blob/16aff7e80a6bc089051c154b5079213317c27da8/web3/providers/ipc.py#L250

**Comment by fselmo** [comment]
We've got an issue open in `eth-account` to track this (https://github.com/ethereum/eth-account/issues/132) and this is a bit older of an issue so I'm closing this in favor of keeping the conversation in one place.

**Comment by fselmo** [comment]
(wrong ticket closed, false alarm... still hoping to take a look at this 👀)

**Comment by sandybradley** [comment]
https://github.com/Narasimha1997/aio-eth

**Comment by kclowes** [comment]
Async providers introduced some significant performance gains. If there are still relevant issues we can reopen.
