### ISSUE TITLE
getTransaction returns transaction without blockHash and blockNumber (both are None)

### ISSUE THREAD

**Issue by BatyaGG** [ethereum/web3.py#2177]
`
from web3 import Web3
from web3.middleware import geth_poa_middleware

w3 = Web3(Web3.HTTPProvider("...."))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

tx = w3.eth.getTransaction('0x09cee22d258425e978a3a1bb4c07a2b5a51196c5a35d5aae813983e69ab25472')
tx_block_num = tx.blockNumber   # None, but other fields are filled
`

**Comment by fselmo** [comment]
@BatyaGG What provider are you connecting to? We need more information. I can't reproduce this on my end. Are you still having issues?

**Comment by fselmo** [comment]
stale
