### ISSUE TITLE
sign_typed_data not reachable through account

### ISSUE THREAD

**Issue by andypavia** [ethereum/web3.py#2180]
* Version: 5.24.0
* Python: 3.6
* OS: linux

### What was wrong?

The sign_typed_data is not available through the Account layer. The web3.eth.Eth.account.sign_transaction is there, however.

`web3.eth.Eth.account.sign_typed_data(initiator_address, transaction)`

### How can it be fixed?

The sign_typed_data should also be exposed through the account layer.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by andypavia** [comment]
Thanks @kclowes! I'll give that a try.

**Comment by cbrzn** [comment]
Any updates on this issue? I am trying to achieve the behavior of `eth_signTypedData` using this library but I can't see a clear path

**Comment by pacrob** [comment]
The `eth_signTypedData` RPC method is not currently supported by any major Execution-Layer Providers (Geth, Erigon, Nethermind, or Besu). It was supported by now-deprecated Parity/Openethereum. I'll update the docs with a note to this effect. If anyone knows of a provider that does support it, let us know!

**Comment by monokh** [comment]
> The `eth_signTypedData` RPC method is not currently supported by any major Execution-Layer Providers (Geth, Erigon, Nethermind, or Besu). It was supported by now-deprecated Parity/Openethereum. I'll update the docs with a note to this effect. If anyone knows of a provider that does support it, let us know!

That's not what the author is suggesting. This is about having the ability for an account loaded through web3py to be able to sign a typed data _locally_, not through a node. There are almost no use cases today that load accounts through node.

See [ethers._signTypedData](https://docs.ethers.org/v5/api/signer/#Signer-signTypedData) for the expected behaviour.

**Comment by pacrob** [comment]
@monokh Thanks for the clarification, I do see what you and @andypavia mean. I'm working on replacement that will be more compatible with what users have come to expect from Ethers and Metamask, and I'll make sure it's exposed via the account in web3.

**Comment by pacrob** [comment]
`sign_typed_data` is now available at `web3.eth.Eth.account.sign_typed_data`.
