### ISSUE TITLE
error to call a contract,return :"rlp: expected List"

### ISSUE THREAD

**Issue by hotbroker** [ethereum/web3.py#2181]
* Version: x.x.x
* Python: 3.7
* OS: win
* `pip freeze` output

```
aiohttp==3.7.4.post0
altgraph==0.16.1
APScheduler==3.6.1
async-timeout==3.0.1
attrs==19.3.0
Babel==2.9.0
backcall==0.1.0
base58==2.1.0
betterproto==1.2.1
bitarray==1.2.2
blackboxprotobuf==1.0.1
bleach==3.1.0
Brotli==1.0.9
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
chart-studio==1.0.0
cheroot==7.0.0
Click==7.0
colorama==0.4.1
colorlover==0.3.0
cryptography==2.8
cufflinks==0.17.0
cycler==0.10.0
cytoolz==0.11.0
dateparser==1.0.0
deap==1.3.1
decorator==4.4.1
defusedxml==0.6.0
Delorean==1.0.0
docopt==0.6.2
entrypoints==0.3
enum34==1.1.6
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
Flask==1.1.1
futu-api==5.2.1408
future==0.18.2
gevent==20.6.2
greenlet==0.4.16
grpclib==0.3.2
h2==4.0.0
hexbytes==0.2.2
hpack==4.0.0
humanize==3.3.0
huobi==0.1.12
huobi-client==1.0.1
hyperframe==6.0.1
ibapi @ https://pip.vnpy.com/colletion/ibapi-9.76.1.tar.gz
idna==2.8
imageio==2.9.0
importlib-metadata==0.23
influxdb==5.3.1
ipfshttpclient==0.8.0a2
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
itchat @ git+https://github.com/luvletter2333/ItChat.git@a546adbb4433c1ea1a887cea4d2e7f1d327091f0
itsdangerous==1.1.0
jaraco.functools==2.0
jedi==0.15.1
Jinja2==2.10.3
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
kiwisolver==1.3.1
lru-dict==1.1.7
lxml==4.6.3
M2CryptoWin64==0.21.1.post3
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.4.1
minidump==0.0.11
mistune==0.8.4
mongoengine==0.23.0
more-itertools==7.2.0
msgpack==1.0.2
multiaddr==0.0.9
multidict==4.5.2
mysql-connector-python==8.0.17
nbconvert==5.6.1
nbformat==4.4.0
netaddr==0.8.0
notebook==6.0.2
numpy==1.17.3
opencv-python==4.0.0.21
pandas==0.25.3
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.5.1
peewee==3.14.4
pefile==2019.4.18
pickleshare==0.7.5
Pillow==7.2.0
plotly==4.2.1
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.10.0
psutil==5.6.5
psycopg2==2.8.6
pyasn1==0.4.2
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.9.9
pyee==8.1.0
pyelliptic==1.5.8
Pygments==2.4.2
PyInstaller==3.5
pykd==0.3.4.10
pymongo==3.11.3
PyMySQL==0.9.3
pyOpenSSL==19.1.0
pyparsing==2.4.7
pypng==0.0.20
PyQRCode==1.2.1
PyQt5==5.14.1
PyQt5-sip==12.8.1
pyqtgraph==0.12.0
pyrsistent==0.15.5
PySocks==1.7.1
pysqlcipher3==1.0.4
python-binance==1.0.12
python-dateutil==2.8.1
python-rapidjson==1.0
pytz==2019.3
pywin32==225
pywin32-ctypes==0.2.0
pywinpty==0.5.5
pyzmq==18.1.0
QDarkStyle==3.0.2
qrcode==6.1
QScintilla==2.11.4
QtPy==1.9.0
quickfix @ https://pip.vnpy.com/colletion/quickfix-1.15.1-cp37-cp37m-win_amd64.whl
redis==3.5.3
regex==2021.4.4
requests==2.22.0
retrying==1.3.3
rlp==2.0.1
rqdatac==2.9.27
rsa==4.0
scipy==1.6.2
seaborn==0.11.1
Send2Trash==1.5.0
simplejson==3.17.0
six==1.13.0
SQLAlchemy==1.4.5
stomp.py==4.1.22
stringcase==1.2.0
TA-Lib @ https://pip.vnpy.com/colletion/TA_Lib-0.4.17-cp37-cp37m-win_amd64.whl
terminado==0.8.2
testpath==0.4.4
tigeropen==1.2.1
toolz==0.11.1
tornado==6.0.3
trading-calendars==2.1.1
traitlets==4.3.3
typing-extensions==3.10.0.2
tzlocal==2.0.0
ujson==4.0.2
urllib3==1.25.6
varint==1.0.2
vnpy @ file:///F:/opensrc/vnpy
wcwidth==0.1.7
web.py==0.40
web3==5.24.0
webencodings==0.5.1
websocket-client==0.56.0
websockets==9.1
wechaty==0.8.11
wechaty-grpc==0.20.19
wechaty-puppet==0.3.dev10
wechaty-puppet-service==0.8.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
winappdbg==1.5
WMI==1.5.1
WSGIserver==1.3
wxpy==0.3.9.8
xlrd==1.2.0
xlwt==1.3.0
yarl==1.3.0
zipp==0.6.0
zope.event==4.4
zope.interface==5.1.0
```

### What was wrong?

Please include any of the following that are applicable:
======
contract source code is here, and it is quite simple

https://ftmscan.com/address/0xf1bf34e46ecf465591b7a7fa9635e4c583174fa3#code

=====

    mytxn = get_rarity_adventure_contract_obj().functions.executeDaycare([int(summonid)]).buildTransaction({
            'nonce': nonce,
            'maxFeePerGas': gasprice,
            'gas':80000,
            'maxPriorityFeePerGas':0,
            'chainId': 250,

        }
    )
    print(mytxn)

    signed_txn = utils._web3obj.eth.account.sign_transaction(mytxn, private_key=account_key)
    print(signed_txn)
    sendres = utils._web3obj.eth.send_raw_transaction(signed_txn.rawTransaction)

* The full output of the error
* 2021-10-12 16:24:05,298 - root - INFO - except Traceback (most recent call last):
  File "daycare_exe_task.py", line 121, in <module>
    make_task()
  File "daycare_exe_task.py", line 114, in make_task
    execute_daycare(account_key, summonid)
  File "daycare_exe_task.py", line 84, in execute_daycare
    sendres = utils._web3obj.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\eth.py", line 698, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\module.py", line 60, in caller
    null_result_formatters)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 190, in request_blocking
    null_result_formatters)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'rlp: expected List'
* What type of node you were connecting to.
* fantom network
* _ep_url='https://rpc.ftm.tools' or 
#_ep_url='https://rpcapi.fantom.network'

### How can it be fixed?
no

**Comment by kclowes** [comment]
That error looks like you are passing the wrong type somewhere along the way (it looks like a `List` is expected). The error is coming back from the node, so I'm going to close because I don't think this is a problem with web3. It's also worth noting that we don't support fantom, so you may run into problems there.
