### ISSUE TITLE
pip install web3 fail: to do with wheels bitarray & lru_dict (got MS C++ and venv)

### ISSUE THREAD

**Issue by irudoramas** [ethereum/web3.py#2187]
Hi, I set up a new virtual environment, I installed Microsoft C++... I tried everything. I tried also installing libpython3.9-dev but didnt work (could not find a version that satisfies the requirement ... no matching distribution found for libpython...).

I also tried downloading bitarray and lru_dict wheels from a link someone provided here, but clicking the downloaded file opens and instantly closes the "cmd-like" window with some red sentence, too fast to be able to read it.

How to proceed?

* Version: x.x.x
* Python: 3.9.7
* OS: Windows
* `pip freeze` output

```
pip freeze
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)
alabaster==0.7.12
appdirs==1.4.4
astor==0.8.1
atomicwrites==1.4.0
attrs==21.2.0
Babel==2.9.1
backports.entry-points-selectable==1.1.0
bandit==1.7.0
base58==2.1.0
certifi==2021.10.8
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.4
coverage==5.5
cytoolz==0.11.0
darglint==1.8.1
distlib==0.3.3
docutils==0.17.1
eradicate==1.0
eth-abi==2.1.1
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
filelock==3.3.1
flake8==3.9.2
flake8-bandit==2.1.2
flake8-broken-line==0.2.1
flake8-bugbear==19.8.0
flake8-commas==2.1.0
flake8-comprehensions==3.7.0
flake8-debugger==3.2.1
flake8-docstrings==1.6.0
flake8-eradicate==0.3.0
flake8-isort==3.0.1
flake8-polyfill==1.0.2
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.12
flake8-string-format==0.2.3
gitdb==4.0.7
GitPython==3.1.24
hexbytes==0.2.2
idna==3.3
imagesize==1.2.0
iniconfig==1.1.1
isort==4.3.21
Jinja2==3.0.2
MarkupSafe==2.0.1
mccabe==0.6.1
multiaddr==0.0.9
multidict==5.2.0
mypy-extensions==0.4.3
netaddr==0.8.0
packaging==21.0
parsimonious==0.8.1
pathspec==0.9.0
pbr==5.6.0
pep8-naming==0.9.1
platformdirs==2.4.0
pluggy==1.0.0
py==1.10.0
pycodestyle==2.7.0
pycryptodome==3.11.0
pydocstyle==5.1.1
pyflakes==2.3.1
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
pytest==6.2.5
pytest-cov==2.12.1
pytz==2021.3
pyupgrade==2.29.0
PyYAML==6.0
regex==2021.10.8
requests==2.26.0
restructuredtext-lint==1.3.2
rlp==2.0.1
six==1.16.0
smmap==4.0.0
snowballstemmer==2.1.0
Sphinx==2.4.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stevedore==3.5.0
testfixtures==6.18.3
tokenize-rt==4.1.0
toml==0.10.2
toolz==0.11.1
tox==3.24.4
tox-travis==0.12
typed-ast==1.4.3
typing-extensions==3.10.0.2
urllib3==1.26.7
varint==1.0.2
virtualenv==20.8.1
wemake-python-styleguide==0.14.1
yarl==1.7.0
```

### What was wrong?
pip install web3
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)
Collecting web3
  Using cached web3-5.24.0-py3-none-any.whl (487 kB)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) (2.2.2)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) (2.1.1)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) (0.3.2)
Collecting aiohttp<4,>=3.7.4.post0
  Using cached aiohttp-3.7.4.post0-cp39-cp39-win_amd64.whl (634 kB)
Collecting ipfshttpclient==0.8.0a2
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) 
(0.2.2)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.18.1-cp39-cp39-win_amd64.whl (912 kB)
Collecting websockets<10,>=9.1
  Using cached websockets-9.1-cp39-cp39-win_amd64.whl (90 kB)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) (2.26.0)
Collecting pywin32>=223
  Using cached pywin32-302-cp39-cp39-win_amd64.whl (9.3 MB)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from web3) (1.10.0)
Collecting eth-account<0.6.0,>=0.5.6
  Using cached eth_account-0.5.6-py3-none-any.whl (101 kB)
Requirement already satisfied: multiaddr>=0.0.7 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from ipfshttpclient==0.8.0a2->web3) (0.0.9)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.7.0)
Requirement already satisfied: attrs>=17.3.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (21.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (5.2.0)
Requirement already satisfied: chardet<5.0,>=2.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (4.0.0)
Requirement already satisfied: typing-extensions>=3.6.5 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (3.10.0.2)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.5.1)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.2.1)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rlp<3,>=1.0.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-account<0.6.0,>=0.5.6->web3) (2.0.1)
Requirement already satisfied: eth-keys!=0.3.2,<0.4.0,>=0.2.1 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-account<0.6.0,>=0.5.6->web3) (0.3.3)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.11.0)
Requirement already satisfied: cytoolz<1.0.0,>=0.10.1 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from eth-utils<2.0.0,>=1.9.5->web3) (0.11.0)
Requirement already satisfied: six>=1.11.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: setuptools in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (58.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.3)
Requirement already satisfied: toolz>=0.8.0 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from cytoolz<1.0.0,>=0.10.1->eth-utils<2.0.0,>=1.9.5->web3) (0.11.1)
Requirement already satisfied: netaddr in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (0.8.0)
Requirement already satisfied: varint in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (1.0.2)
Requirement already satisfied: base58 in e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (2.1.0)
Building wheels for collected packages: lru-dict, bitarray
  Building wheel for lru-dict (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\lru-dict_23fcdc359eb044ed82e7bf139b488f80\\setup.py'"'"'; __file__='"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\lru-dict_23fcdc359eb044ed82e7bf139b488f80\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Iru Lenovo\AppData\Local\Temp\pip-wheel-mwi8nx85'
       cwd: C:\Users\Iru Lenovo\AppData\Local\Temp\pip-install-7lsawmjy\lru-dict_23fcdc359eb044ed82e7bf139b488f80\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tclru.c /Fobuild\temp.win-amd64-3.9\Release\lru.obj
  lru.c
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include\pyconfig.h(59): fatal error C1083: No se puede abrir 
el archivo incluir: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Iru Lenovo\AppData\Local\Temp\pip-wheel-b3rc2xo8'
       cwd: C:\Users\Iru Lenovo\AppData\Local\Temp\pip-install-7lsawmjy\bitarray_512f0d2a874f4d258fdb01337a013d7f\
  Complete output (19 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\bitarray
  copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\test_util.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\util.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\__init__.py -> build\lib.win-amd64-3.9\bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\bitarray
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcbitarray/_bitarray.c /Fobuild\temp.win-amd64-3.9\Release\bitarray/_bitarray.obj
  _bitarray.c
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include\pyconfig.h(59): fatal error C1083: No se puede abrir 
el archivo incluir: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
Failed to build lru-dict bitarray
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)
Installing collected packages: bitarray, async-timeout, websockets, pywin32, protobuf, lru-dict, jsonschema, ipfshttpclient, eth-account, aiohttp, web3
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Iru Lenovo\AppData\Local\Temp\pip-record-8alji9h0\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\include\site\python3.9\bitarray'
         cwd: C:\Users\Iru Lenovo\AppData\Local\Temp\pip-install-7lsawmjy\bitarray_512f0d2a874f4d258fdb01337a013d7f\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\bitarray
    copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\test_util.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\util.py -> build\lib.win-amd64-3.9\bitarray
    copying bitarray\__init__.py -> build\lib.win-amd64-3.9\bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\bitarray
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcbitarray/_bitarray.c /Fobuild\temp.win-amd64-3.9\Release\bitarray/_bitarray.obj        
    _bitarray.c
    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\include\pyconfig.h(59): fatal error C1083: No se puede abrir el archivo incluir: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Iru Lenovo\\AppData\\Local\\Temp\\pip-install-7lsawmjy\\bitarray_512f0d2a874f4d258fdb01337a013d7f\\setup.py'"'"';f = 
getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Iru Lenovo\AppData\Local\Temp\pip-record-8alji9h0\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Iru DATOS\documentos\Coding stuff\Arbitrage bot sBCH-CFlex\venv-py3\include\site\python3.9\bitarray' Check the logs for full command output.
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (e:\iru datos\documentos\coding stuff\arbitrage bot sbch-cflex\venv-py3\lib\site-packages)

**Comment by dbfreem** [comment]
I ran into issues installing web3 on windows so I went the wsl route and everything worked perfectly.

**Comment by fselmo** [comment]
This issue is being tracked by https://github.com/ethereum/eth-account/issues/132. I am going to close this in hopes of keeping the conversation in one place.

For now, the most relevant documentation can be found here: https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error

We realize this does not seem to work for everyone and we expect to get to this issue very soon.
