### ISSUE TITLE
How to check my token balance( shib for example) in BSC?

### ISSUE THREAD

**Issue by FILAgiao** [ethereum/web3.py#2194]
i  don't know how to check one tonken balance in BSC instead of BNB or ETH,if you know ,tell me please.

**Comment by fselmo** [comment]
Hey @FILAgiao. We prefer to use issues to track our work. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation on [discord](https://discord.gg/GHryRvPB84). There's a great community there asking very similar questions every day. Hope this helps.

**Comment by airdropsqb** [comment]
Friends, in case you still need it.
I have created a BSC Balance Validator in Python.
Also for other networks.
https://www.youtube.com/c/AirdropsQb
Playlist: PrivateKey
