### ISSUE TITLE
Something about filter.get_new_entries()

### ISSUE THREAD

**Issue by QinHaoChen97** [ethereum/web3.py#2196]
* Python: 3.6.9
### What was wrong?
I use this example [https://web3py.readthedocs.io/en/latest/filters.html](url)
```python3
from web3.auto import w3
import time

def handle_event(event):
    print(event)

def log_loop(event_filter, poll_interval):
    while True:
        for event in event_filter.get_new_entries():
            handle_event(event)
        time.sleep(poll_interval)

def main():
    block_filter = w3.eth.filter('latest')
    log_loop(block_filter, 2)

if __name__ == '__main__':
    main()
```

when I send a transition in ganache-cli，it return `b'o\\\xd9Z\xc5\x0b\x98\xb1\xe3\nG#\x0c\xfe\x9c\x9a\xe7\x98\tk%\xd3)\x0e|\x16\xf8+l\xad9\xa8'`
I think this is the `blockHash`,But the return value mentioned above is difficult to understand.

### How can it be fixed?

I think a conversion  should be done on the return value，like it
```python3
>>> binascii.hexlify(b'o\\\xd9Z\xc5\x0b\x98\xb1\xe3\nG#\x0c\xfe\x9c\x9a\xe7\x98\tk%\xd3)\x0e|\x16\xf8+l\xad9\xa8')
#This will return an easy-to-understand wording
<<< b'6f5cd95ac50b98b1e30a47230cfe9c9ae798096b25d3290e7c16f82b6cad39a8'
```

Thank you for your development of web3.py, I got a lot of help from it.

**Comment by Daiiszuki** [comment]
Hi, did you manage to solve the messed up output?

**Comment by fselmo** [comment]
Hey @QinHaoChen97, what provider are you using? I'm not seeing the same results on my end.

**Comment by kclowes** [comment]
Closing, stale
