### ISSUE TITLE
AttributeError: 'AsyncEth' object has no attribute 'contract'

### ISSUE THREAD

**Issue by komarp** [ethereum/web3.py#2202]
### What was wrong?

Please include any of the following that are applicable:
```py 
self.contract = await self.node.w3.eth.contract(address=self.addr, abi=self._abi)
```
I use AsyncHttpProvider, when i want to call "contract" function of eth object, python raises the following error:
```py
AttributeError: 'AsyncEth' object has no attribute 'contract'
```

Daclaration of my node class:
```py
class Node:

    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, 'instance'):
            cls.instance = super().__new__(cls)
        return cls.instance  # noqa

    def __init__(self):
        # noinspection PyTypeChecker
        self.w3 = Web3(
            AsyncHTTPProvider(BSC_RPC_URL),
            modules={'eth': (AsyncEth,),  'net': (AsyncNet, )},
            middlewares=[]
        )
```
Help, please!

**Comment by kclowes** [comment]
Async is still a work in progress, and contract isn't natively async yet. Here's [the list](https://web3py.readthedocs.io/en/stable/providers.html#supported-methods) of supported methods/middleware.
