### ISSUE TITLE
how to get all transactions by an address?

### ISSUE THREAD

**Issue by viponedream** [ethereum/web3.py#2204]
how to get all transactions by an address?

i want go get all my transactions. 
how to make it?
thank you all.

**Comment by kratatomi** [comment]
I use the event scanner tool for getting all transactions from smart contracts, like ERC20 tokens: https://web3py.readthedocs.io/en/stable/examples.html

**Comment by fselmo** [comment]
Hey @viponedream. We prefer to use issues to track our work. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join us on [discord](https://discord.gg/GHryRvPB84).

**Comment by viponedream** [comment]
> I use the event scanner tool for getting all transactions from smart contracts, like ERC20 tokens: https://web3py.readthedocs.io/en/stable/examples.html

thanks for your replay. 
how to use this function?

i have run the tool,  it only save nothing in test-state.json
{"last_scanned_block": 4370674, "blocks": {}}
