### ISSUE TITLE
Add support for SmartBCH specific JSON-RPC methods

### ISSUE THREAD

**Issue by kratatomi** [ethereum/web3.py#2206]
SmartBCH has some specific and very useful JSON-RPC methods, described here: https://docs.smartbch.org/smartbch/developers-guide/jsonrpc (under SBCH section).

I wonder if there's possible to add those methods.

**Comment by fselmo** [comment]
Hey @kratatomi, thanks for the interest in expanding the web3 library. We don't plan to support smartBCH in-house but we did recently add the ability to attach external modules. If it is of interest, it would be plausible to create a separate smart BCH library and attach it as a module.

See #2288 which is already merged and #2204 which is coming in the next release for additional details on how that could be accomplished. Best of luck!
