### ISSUE TITLE
Txpool methods not working with ganache or infura

### ISSUE THREAD

**Issue by L-F-Escobar** [ethereum/web3.py#2214]
* Version: 5.24.0
* Python: 3.8.9
* OS: osx
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.1
attrs==21.2.0
base58==2.1.1
bitarray==1.2.2
certifi==2021.10.8
charset-normalizer==2.0.7
crytic-compile==0.2.1
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
frozenlist==1.2.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.2.0
netaddr==0.8.0
parsimonious==0.8.1
prettytable==2.4.0
protobuf==3.19.1
py-solc==3.2.0
pycryptodome==3.11.0
pyrsistent==0.18.0
pysha3==1.0.2
requests==2.26.0
rlp==2.0.1
semantic-version==2.8.5
six @ file:///AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-103/six-1.15.0-py2.py3-none-any.whl
slither-analyzer==0.8.1
toolz==0.11.2
typing-extensions==4.0.0
urllib3==1.26.7
varint==1.0.2
wcwidth==0.2.5
web3==5.25.0
websockets==9.1
yarl==1.7.2
```

### What was wrong?

Connected to local ganache node v2.5.4.

```
w3 = Web3(HTTPProvider("http://127.0.0.1:7545"))
w3.geth.txpool.content() OR w3.geth.txpool.status()
```

yields the following error

```
*** ValueError: {'message': 'Method txpool_content not supported.', 'code': -32000, 'data': {'stack': 'Error: Method txpool_content not supported.\
```

Connected to an infura rospton node yields the following error
```
*** ValueError: {'code': -32601, 'message': 'The method txpool_content does not exist/is not available'}
```

It seems that I cant read from the tx pool with web3.py? I am confused given that I see in the docs examples of web3.py reading from the tx pool
```
https://web3py.readthedocs.io/en/stable/web3.geth.html#web3.geth.txpool.TxPool.content
```

Seems like ganache has not enabled the ability to use `txpool_content` but there is an open mr for it.
https://github.com/trufflesuite/ganache/pull/1539

I have tried the code above with HTTP & WSS providers.

Any clarification would help! Thanks!

**Comment by L-F-Escobar** [comment]
Anyone there? Maybe I should just switch to web3.js, seems a lot more active and zero problems

**Comment by kclowes** [comment]
Infura doesn’t support those methods either. You’ll probably have to run your own geth node if you want access to those methods. Closing since I don’t think this is a bug but feel free to reopen if I misunderstood something.

**Comment by L-F-Escobar** [comment]
Hi @kclowes ! How can I confirm that infura does indeed not support those methods? I dont doubt it, just want to see the docs for myself. 

> You’ll probably have to run your own geth node if you want access to those methods

Apart from running my own node is there any other way I could have access to those methods? 

If I run my own geth node, I should be able to connect web3.py to my nodes `ipc_path` and have access to all geth methods correct? I'm curious if there are instructions for using web3.py with a geth node connected to rospten & main networks

Thanks for all the help!
