### ISSUE TITLE
Using typing-extensions 4 with web3.py and python < 3.8

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/web3.py#2216]
Hey guys,

This is question on typing-extensions package. In setup.py https://github.com/ethereum/web3.py/blob/74fbcd1761407ee37808173b089d8e44e537fb99/setup.py#L88-L89

you require <4 and python <3.8. From what I understand that is since these extensions you use have made it into stdlib's typing module from 3.8 and on.

But from what I see this requirement creates a probem for projects like ours which are still in python 3.7, use web3.py and want to use typing-extensions 4. Is there any reason for the < 4 requirement?

**Comment by kclowes** [comment]
I put up a PR to see what would happen if we bump it, and it looks like we have some dependency resolution errors if we use >=4.0.0 (see [this CI run](https://app.circleci.com/pipelines/github/ethereum/web3.py/1904/workflows/9b2de1e2-86fb-4f38-acfa-5038adb408b0/jobs/176899)), but those aren't insurmountable. On quick glance, it doesn't look like anything would break from our end if we bump to v4+ once we figure out the dependency resolution. Out of curiosity, what feature is in typing-extensions v4 that you'd like to use?

**Comment by LefterisJP** [comment]
> I put up a PR to see what would happen if we bump it, and it looks like we have some dependency resolution errors if we use >=4.0.0 (see [this CI run](https://app.circleci.com/pipelines/github/ethereum/web3.py/1904/workflows/9b2de1e2-86fb-4f38-acfa-5038adb408b0/jobs/176899)), but those aren't insurmountable. On quick glance, it doesn't look like anything would break from our end if we bump to v4+ once we figure out the dependency resolution. Out of curiosity, what feature is in typing-extensions v4 that you'd like to use?

Hey @kclowes thanks for the quick response.

The new additions in v4 are here: https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG#L10-L13

I am most interested to try the TypedDict with certain fields marked as optional and certain as required: https://www.python.org/dev/peps/pep-0655/

**Comment by kclowes** [comment]
> The new additions in v4 are here: https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG#L10-L13

Ah, thanks! I don't see that we're using any of the features that were dropped, so I think we're safe to bump. Will put this in our backlog.

**Comment by LefterisJP** [comment]
Just bumping this one since I saw a new release and it's not yet fixed. Should not be hard to adjust the dependency.

**Comment by LefterisJP** [comment]
Thank you!
