### ISSUE TITLE
Wrong timeout parameter typing in wait_for_transaction_receipt

### ISSUE THREAD

**Issue by maconard** [ethereum/web3.py#2220]
### What was wrong?

The typing for the `timeout` input to the exposed `wait_for_transaction_receipt` is falsely listed as `int`, seeing as the internal function it calls of the same name from `_utils.transactions` accepts float.

Exposed function falsely showing int: https://github.com/ethereum/web3.py/blob/e01e6ca9e765b54430a152ac18f0890dfa8ae69e/web3/eth.py#L670

Internal function accepting float: https://github.com/ethereum/web3.py/blob/e01e6ca9e765b54430a152ac18f0890dfa8ae69e/web3/_utils/transactions.py#L129

### How can it be fixed?

Simply change line 671 of the `eth` module to use `float` instead of `int` for the `timeout` parameter. 

Thanks!

**Comment by kclowes** [comment]
Thanks! Feel free to submit a PR if you have time :) Otherwise it may be a bit until we can get to it!

**Comment by broper2** [comment]
I can scratch up a quick PR to fix this, will be a good first issue to contribute on web3.py

**Comment by fselmo** [comment]
closed by #2221
