### ISSUE TITLE
ModuleNotFoundError: No module named 'web3' 

### ISSUE THREAD

**Issue by maztube** [ethereum/web3.py#2225]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by molecula451** [comment]
<code>web3</code> module is not installed on your python environment, running <code>python3 -m pip install web3</code> should do

**Comment by ComplaintID** [comment]
Message them on Twitter about your complaints. Send them a direct message to get your issues resolved. I also encountered the same problem. 
https://twitter.com/messages/compose?recipient_id=884210741347332100

**Comment by kclowes** [comment]
Closing since there is no info in the issue, and looks like @molecula451 has the right solution to the title.
