### ISSUE TITLE
Can not sign private key ( use 12 word phrase ) when use web3.eth.account.sign_transaction

### ISSUE THREAD

**Issue by anhtuan96a8** [ethereum/web3.py#2236]
* web3 : 5.20.1
* Python: 3.6
* OS: win
I cannot send transaction . It say "binascii.Error: Non-hexadecimal digit found" when i use this function 

pancakeswap2_txn = contract.functions.swapExactETHForTokens(
    0,
    [spend, contract_id],
    sender_address,
    (int(time.time()) + 1000000)
).buildTransaction({
    'from': sender_address,
    'value': web3.toWei(0.001, 'ether'),
    'gas': 250000,
    'gasPrice': web3.toWei('5', 'gwei'),
    'nonce': nonce,
})
"web3.eth.account.sign_transaction(pancakeswap2_txn, privatekey)"
this is link issue
https://stackoverflow.com/questions/70134927/web3-signing-transaction-issue-non-hexadecimal-digit-found-python

**Comment by unparalleled-js** [comment]
You have to use the private key of your account, maybe something from `eth-account` python package, like this:

```python
from eth_account.hdaccount import HDPath, seed_from_mnemonic

hd_path = HDPath(hd_path_format.format(i))  # Pass in your HD Path format here
private_key = HexBytes(hd_path.derive(seed)).hex()  # Pass in your seed-phrase here
```

**Comment by kclowes** [comment]
Looks like this is resolved. Thanks @unparalleled-js!
