### ISSUE TITLE
Update to Quickstart

### ISSUE THREAD

**Issue by ddocs** [ethereum/web3.py#2256]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
non-applicable
```
### What was wrong?

In the current Quickstart, it states the following:
"Provider: Infura
The quickest way to interact with the Ethereum blockchain is to use a remote node provider, like Infura. You can connect to a remote node by specifying the endpoint, just like the previous local node example:"

However, this requires setting up an account with Infura. This is not as quick as it can be. 

### How can it be fixed?

There are free, open access RPC nodes that can be accessed without setting up an account. For example: Ankr provides public RPC nodes for Arbitrum, Avalanche, Celo, Ethereum, Fantom, Near, Polygon and Solana currently. It is not necessary to set up an account. Anyone can use the URL. The format is: https://rpc.ankr.com/arbitrum, https://rpc.ankr.com/avalanche, https://rpc.ankr.com/eth etc. 

I believe the Quickstart should be updated. 

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Thanks for the suggestion, @ddocs. I think we can mark this closed by #2287 and more can be updated if / when we officially support the layer 2 providers. Cheers.
