### ISSUE TITLE
Possible to call estimateGas() without sufficient balance

### ISSUE THREAD

**Issue by rickbeeloo** [ethereum/web3.py#2257]
A rather short question, when calling `estimateGas()` (or `call()` for that matter) on a transfer function, the `from` account needs the specified amount of tokens. Is it possible to execute the gas estimation without checking if the `from` address has the token? I think to recall that I saw a "fake" balance being created with web3.js through `extend` although I'm not sure.

**Comment by kclowes** [comment]
We do not have that functionality AFAIK. Can you link me to the docs in web3js that they have it? I'd be curious to see their implementation.

**Comment by rickbeeloo** [comment]
@kclowes here is an[ issue](https://github.com/ethers-io/ethers.js/discussions/2379) and [here](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#extend) a "desc" in the docs. I don't know if, using this, I can do what I want but in the github issue for example I see that there is something called "balance"

**Comment by kclowes** [comment]
I _think_ the github issue is referencing the `state_override` argument that Geth implements. So when doing a `call` with a geth node you can override certain things. If that suits your needs, we do have that functionality, but only for `call`. Docs [here](https://web3py.readthedocs.io/en/stable/web3.eth.html?highlight=eth_call#web3.eth.Eth.call). Is that what you were looking for?

**Comment by rickbeeloo** [comment]
@kclowes Thank you so much for the quick replies and looking with me!
The main thing is I want to test if a swap is possible regardless of the `from` having insufficient balance of the token. I quickly wrote a reproducible script:

```
from web3 import Web3

PCSABI = [{"inputs":[{"internalType":"uint256","name":"amountIn","type":"uint256"},{"internalType":"uint256","name":"amountOutMin","type":"uint256"},{"internalType":"address[]","name":"path","type":"address[]"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"}],"name":"swapExactTokensForETH","outputs":[{"internalType":"uint256[]","name":"amounts","type":"uint256[]"}],"stateMutability":"nonpayable","type":"function"}]

web3 = Web3(Web3.HTTPProvider('https://bsc-dataseed.binance.org/'))
pcs_router_add = Web3.toChecksumAddress(0x10ED43C718714eb63d5aA57B78B54704E256024E )
pcs_router = web3.eth.contract(address=pcs_router_add, abi=PCSABI)

wadd = Web3.toChecksumAddress('0xb40ED5445aA62b3adF032D89F9183bB907C7f929')
nonce = web3.eth.get_transaction_count(wadd)

tx = pcs_router.functions.swapExactTokensForETH(
    amountIn = 1,
    amountOutMin=0,
    path=[Web3.toChecksumAddress(0xba2ae424d960c26247dd6c32edc70b295c744c43), Web3.toChecksumAddress(0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c) ],
    to=wadd,
    deadline=9999999999).buildTransaction({
    'nonce': nonce,
    'gas': 260000,
    'gasPrice': 28000000000
})

print(web3.eth.call({
     "from"      : wadd,
     "nonce"     : nonce,
     "to"        : pcs_router_add,
     "data"      : tx['data']
}))
```

Since the `from` (i.e. 0xb40ED5445aA62b3adF032D89F9183bB907C7f929) does not hold the token this will throw an `execution reverted: TransferHelper: TRANSFER_FROM_FAILED`, however I'm interesting in errors further down the line so I wondered whether I can tell it just assume it has enough balance or can I use state_override to do so? Not familiar with it

**Comment by rickbeeloo** [comment]
[This](https://www.programcreek.com/python/?code=ethereum%2Feth-tester%2Feth-tester-master%2Ftests%2Fbackends%2Ftest_pyevm.py) looks related, although it looks it's only possible to change the eth balance not that of something else

**Comment by fselmo** [comment]
This isn't a bug with the library so I'm going to close this for housekeeping. If you think there's a bug here, please feel free to re-open. For usage questions I'd like to point you to the [discord](https://discord.gg/GHryRvPB84) where there is a great community of users all helping each other out. Cheers.
