### ISSUE TITLE
Cannot use w3.eth.filter with httpProvider with custom headers

### ISSUE THREAD

**Issue by AngeloCa** [ethereum/web3.py#2262]
### What was wrong?

In order to connect to my HTTP provider, I need to pass an 'X-Auth-Token' containing the credentials in the header. I do the following:

```
from web3 import Web3
from os import environ

TIMEOUT = 5

NODE_ENDPOINT = environ.get('NODE_ENDPOINT')

OPTIONS = {
    'headers':
        {
            'X-Auth-Token': environ.get('AUTH_TOKEN'),
            'Content-Type': 'application/JSON'
        },
    "timeout": TIMEOUT
}

w3 = Web3(Web3.HTTPProvider(NODE_ENDPOINT, request_kwargs=OPTIONS))
```

This works, well when trying to get a block with ```w3.eth.get_block('latest')```. However when I try to use filter methods like ```w3.eth.filter('latest')```, I get an ```HTTPError: 403 Client Error: Forbidden for URL. xxx```

### How can it be fixed?

Verify if the request_kwargs are passed to filtering methods.

**Comment by dbfreem** [comment]
I debugged both of the methods you mentioned and it seems that the kwargs are passing through on both request. 


![image](https://user-images.githubusercontent.com/9778569/146480333-f534b485-5dcd-4155-82b8-7877e12b5c61.png)

1. `w3.eth.get_block('latest')`  kwargs passed to the requests library in request.py `{'headers': {'X-Auth-Token': 'hey', 'Content-Type': 'application/JSON'}, 'timeout': 5}`
2. `w3.eth.fileter('latest')` kwargs passed to the requests library in request.py `{'headers': {'X-Auth-Token': 'hey', 'Content-Type': 'application/JSON'}, 'timeout': 5}`

**Comment by AngeloCa** [comment]
Thank you very much for your help and time. 

1 is working also fine for me. But 2 is receiving an HTTPError: 403 Client Error... 

Do you have any idea why this is the case?

**Comment by AngeloCa** [comment]
The node I am using also supports WebSocket connections. So I have tried using a WebsocketProvider with the same setup. 

I have a similar behavior where 1 works but 2 doesn't. However the error message is different, I have:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "PATH_TO_TEST_FILE/test.py", line 18, in <module>
    w3.eth.filter('latest')
  File "/home/.local/share/virtualenvs/test-8l1nVNaj/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/.local/share/virtualenvs/test-8l1nVNaj/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/.local/share/virtualenvs/test-8l1nVNaj/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32003, 'message': 'Request method filtered'}
```

Any clues about how to understand this error code?
