### ISSUE TITLE
web3 + pyinstaller

### ISSUE THREAD

**Issue by MrCanan** [ethereum/web3.py#2268]
Hi,

```
from web3 import Web3

web3_provider = Web3.HTTPProvider('https://bsc-dataseed.binance.org/')
web3 = Web3(web3_provider)
web3_status = web3.isConnected()

print(web3_status)
```

`pyinstaller --clean --strip --onefile test_web3.py`

Without pyinstaller, web3_status is true every time, so it is normal.
But with pyinstaller, it is ALWAYS false, so there is a problem.

It is for sure a setting of pyinstaller.
Any ideas?

Best regards.

**Comment by MrCanan** [comment]
Hi,

I am on a fresh VM on VirtualBox, so I have already a clean install.
OS: Ubuntu 18.04
Python: 3.6.9
PyInstaller: lastest

Best regards.

**Comment by niko207** [comment]
Hi. I am having the same issue! How did you fix it?

**Comment by marktohark** [comment]
@MrCanan 
I have the same issue.
i found you post issue to pyinstaller issue list.
but you don't give solve, do you solve it!?
