### ISSUE TITLE
Add async support for eth.contract and contract function calls

### ISSUE THREAD

**Issue by AngeloCa** [ethereum/web3.py#2270]
### What was wrong?

Support for async eth.contract and async contract calls would be useful

### How can it be fixed?

Asyncify eth.contracts and contact calls.

**Comment by fselmo** [comment]
closed by #2484

**Comment by IlluvatarEru** [comment]
How can I check in which version was this change released?

**Comment by fselmo** [comment]
> @AngeloCa How can I check in which version was this change released?

You can find this information in the release notes. In this case, this was added into the `v6` [beta.3 release](https://web3py.readthedocs.io/en/latest/releases.html#v6-0-0-beta-3-2022-06-01).
