### ISSUE TITLE
Upgrade websockets to 10.1 ?

### ISSUE THREAD

**Issue by broper2** [ethereum/web3.py#2272]
* Version: 5.25.0
* Python: 3.8
* OS: osx
* `pip freeze` output

```
solana==0.19.0 (problem)
```

### What was wrong?

Currently in dependency hell trying to use solana-py and web3 in same service. solana-py requires websockets 10.1, web3 seems to not support that. Below is the changelog for 10.1 release of websockets, there are no incompatible changes. Any chance I could bother the team to consider upgrading support to 10.1?

Also, from my logs it seems web3 needs "websockets<10" but i think changes were made to support 10.0 (#2175) . May need to update requirements:

remote:        The conflict is caused by:
remote:            solana 0.19.0 depends on websockets<11.0 and >=10.1
remote:            web3 5.25.0 depends on websockets<10 and >=9.1

https://websockets.readthedocs.io/en/latest/project/changelog.html#id3

Thanks!

### How can it be fixed?

Upgrade websockets support to 10.1

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by tudoanh** [comment]
Yes please upgrade the requirement for `websocket` lib to support >= v10.0

Thank you.

**Comment by AgentCosmic** [comment]
+1 for this. Python 3.10 needs v10 `websocket` library.

**Comment by kdowney-cloudwallcapital** [comment]
+1 Also in dependency hell due to this one. If it's not easy to upgrade, is it possible to make in an optional dependency, e.g. web3[websockets] or web3[all] includes this dependency but otherwise excluded?

**Comment by kclowes** [comment]
:eyes: Thanks for chiming in, everyone. It's on our list but it will be a little bit until we can get to it. If anyone has bandwidth to raise a PR in the meantime, we'd be happy to review. That's likely the fastest course of action. It looks like bumping to v10 results in a bunch of deprecation warnings around the `loop` parameter, but I haven't had time to dig into what the fix is for that.

**Comment by kdowney-cloudwallcapital** [comment]
No bandwidth right now unfortunately, but we can push back our web3 integration to give you more time; may be more urgent for others. For reference: the relevant conflicts for us are the latest `uvicorn` ASGI server and the `cryptofeed` package. Both bumped to 10.x in recent versions and are critical to our stack.

**Comment by dbfreem** [comment]
@kclowes  just out of curiosity is the plan to go ahead and remove the ability to pass in the event loop to the [websocket provider](https://github.com/ethereum/web3.py/blob/master/web3/providers/websocket.py#L67) or deprecate it for now. Here is the associated documentation about the ability to pass in an event loop being deprecated in [websockets docs,](https://websockets.readthedocs.io/en/stable/project/changelog.html#backwards-incompatible-changes). The websockets docs say to look at the python 3.10 release notes [python release notes](https://docs.python.org/3/whatsnew/3.10.html), at the bottom it talks about changes to `get_event_loop`

**Comment by kclowes** [comment]
I don't know yet. I think we'll probably deprecate in v5 and remove in v6, but I haven't really looked at it too hard.

**Comment by dino-rodriguez** [comment]
Hey guys, this still seems to be an issue. Can't use solana with web3.

**Comment by kclowes** [comment]
@dino-rodriguez Try web3 v6.0.0-beta.1.
