### ISSUE TITLE
Issue from web3 import Web3 got error: ImportError: cannot import name 'encode_abi' from 'eth_abi' refer to #1698

### ISSUE THREAD

**Issue by ZTreeson** [ethereum/web3.py#2278]
* Version: 5.12.2
* Python: 3.7
* OS: Mac
* `pip freeze` output
```
aiohttp==3.8.1
aiosignal==1.2.0
APScheduler==3.8.1
async-timeout==4.0.1
asynctest==0.13.0
attrs==21.2.0
backports.zoneinfo==0.2.1
base58==2.1.1
bitarray==1.2.2
bscscan-python==2.0.0
certifi==2021.10.8
charset-normalizer==2.0.8
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
ethereum-abi-utils==0.4.7
frozenlist==1.2.0
hexbytes==0.2.2
idna==3.3
importlib-metadata==4.8.2
ipfshttpclient==0.6.1
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.2.0
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.19.1
pycryptodome==3.12.0
pylru==1.2.0
pyrsistent==0.18.0
pysha3==1.0.2
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
requests==2.26.0
rlp==2.0.1
six==1.16.0
toolz==0.11.2
typing-extensions==3.10.0.2
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.7
varint==1.0.2
web3==5.12.2
web3utils==0.1.3
websockets==8.1
yarl==1.7.2
zipp==3.6.0
```
<put the output from running pip freeze here>

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
I try to create contract instance with below simple codes:
```
from web3 import Web3
import json

BSC_PRC='https://bsc-dataseed.binance.org/'
w3=Web3(Web3.HTTPProvider(BSC_PRC))
#pancakeswap router
panRouterContractAddress = '0x10ED43C718714eb63d5aA57B78B54704E256024E'
#pancakeswap router abi
panabi = json.loads('[{"i..]')
contract2=w3.eth.contract(address=panRouterContractAddress,abi=panabi)
```
got error:
```
Traceback (most recent call last):
  File "/Users/treeson/PycharmProjects/bsc_monitor/bsc_mon/web3/web3_test1.py", line 1, in <module>
    from web3 import Web3
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/account.py", line 59, in <module>
    from eth_account.messages import (
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_abi/__init__.py", line 2, in <module>
    "This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` "
DeprecationWarning: This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` package will no longer recieve updates.  Please update your dependencies accordingly.
```
* What type of node you were connecting to.
BSC_PRC='https://bsc-dataseed.binance.org/'

### How can it be fixed?
I refer to #1698, and upgrade my web3 as suggested, but it doesn't work.
No solution yet
Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by ZTreeson** [comment]
I tried to uninstall ethereum-abi-utils and upgrade eth-abi, but another error: ImportError: cannot import name 'encode_abi' from 'eth_abi'.
Not resolved yet.

**Comment by dbfreem** [comment]
maybe try this with a clean virtual environment and see if that fixes the issue.

**Comment by ZTreeson** [comment]
> maybe try this with a clean virtual environment and see if that fixes the issue.

Thank you, tried with ur suggestion and solved the issue.

**Comment by ASISBusiness** [comment]
> * Version: 5.12.2
> 
> * Python: 3.7
> 
> * OS: Mac
> 
> * `pip freeze` output
> 
> ```
> 
> aiohttp==3.8.1
> 
> aiosignal==1.2.0
> 
> APScheduler==3.8.1
> 
> async-timeout==4.0.1
> 
> asynctest==0.13.0
> 
> attrs==21.2.0
> 
> backports.zoneinfo==0.2.1
> 
> base58==2.1.1
> 
> bitarray==1.2.2
> 
> bscscan-python==2.0.0
> 
> certifi==2021.10.8
> 
> charset-normalizer==2.0.8
> 
> cytoolz==0.11.2
> 
> eth-abi==2.1.1
> 
> eth-account==0.5.6
> 
> eth-hash==0.3.2
> 
> eth-keyfile==0.5.1
> 
> eth-keys==0.3.3
> 
> eth-rlp==0.2.1
> 
> eth-typing==2.2.2
> 
> eth-utils==1.10.0
> 
> ethereum-abi-utils==0.4.7
> 
> frozenlist==1.2.0
> 
> hexbytes==0.2.2
> 
> idna==3.3
> 
> importlib-metadata==4.8.2
> 
> ipfshttpclient==0.6.1
> 
> jsonschema==3.2.0
> 
> lru-dict==1.1.7
> 
> multiaddr==0.0.9
> 
> multidict==5.2.0
> 
> netaddr==0.8.0
> 
> parsimonious==0.8.1
> 
> protobuf==3.19.1
> 
> pycryptodome==3.12.0
> 
> pylru==1.2.0
> 
> pyrsistent==0.18.0
> 
> pysha3==1.0.2
> 
> pytz==2021.3
> 
> pytz-deprecation-shim==0.1.0.post0
> 
> requests==2.26.0
> 
> rlp==2.0.1
> 
> six==1.16.0
> 
> toolz==0.11.2
> 
> typing-extensions==3.10.0.2
> 
> tzdata==2021.5
> 
> tzlocal==4.1
> 
> urllib3==1.26.7
> 
> varint==1.0.2
> 
> web3==5.12.2
> 
> web3utils==0.1.3
> 
> websockets==8.1
> 
> yarl==1.7.2
> 
> zipp==3.6.0
> 
> ```
> 
> <put the output from running pip freeze here>
> 
> 
> 
> 
> 
> ### What was wrong?
> 
> 
> 
> Please include any of the following that are applicable:
> 
> 
> 
> * The code which produced the error
> 
> I try to create contract instance with below simple codes:
> 
> ```
> 
> from web3 import Web3
> 
> import json
> 
> 
> 
> BSC_PRC='https://bsc-dataseed.binance.org/'
> 
> w3=Web3(Web3.HTTPProvider(BSC_PRC))
> 
> #pancakeswap router
> 
> panRouterContractAddress = '0x10ED43C718714eb63d5aA57B78B54704E256024E'
> 
> #pancakeswap router abi
> 
> panabi = json.loads('[{"i..]')
> 
> contract2=w3.eth.contract(address=panRouterContractAddress,abi=panabi)
> 
> ```
> 
> got error:
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/Users/treeson/PycharmProjects/bsc_monitor/bsc_mon/web3/web3_test1.py", line 1, in <module>
> 
>     from web3 import Web3
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/web3/__init__.py", line 6, in <module>
> 
>     from eth_account import (
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/__init__.py", line 1, in <module>
> 
>     from eth_account.account import (
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/account.py", line 59, in <module>
> 
>     from eth_account.messages import (
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/messages.py", line 26, in <module>
> 
>     from eth_account._utils.structured_data.hashing import (
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
> 
>     from eth_abi import (
> 
>   File "/Users/treeson/bsc_monitor/lib/python3.7/site-packages/eth_abi/__init__.py", line 2, in <module>
> 
>     "This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` "
> 
> DeprecationWarning: This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` package will no longer recieve updates.  Please update your dependencies accordingly.
> 
> ```
> 
> * What type of node you were connecting to.
> 
> BSC_PRC='https://bsc-dataseed.binance.org/'
> 
> 
> 
> ### How can it be fixed?
> 
> I refer to #1698, and upgrade my web3 as suggested, but it doesn't work.
> 
> No solution yet
> 
> Fill this section in if you know how this could or should be fixed.
> 
> 
> 
> ---
> 
> **Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
> 
> have a feature request, you're in the right place. If you have implementation or usage questions, 
> 
> please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
> 
> on [discord](https://discord.gg/GHryRvPB84).
> 
>
