### ISSUE TITLE
UniswapV3 router exchange method exactInputSingle

### ISSUE THREAD

**Issue by syaringan357** [ethereum/web3.py#2281]
* Version: 5.25.0
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?

When I call
```
router_contract.functions.exactInputSingle({
        "tokenIn": address,
        "tokenOut": ETH_ADDRESS,
        "fee": 3000,
        "recipient": ACCOUNT_ADDRESS2,
        "deadline": round(time.time()) + 60 * 20,
        "amountIn": 0.01 * 10 ** 18,
        "amountOutMinimum": 0,
        "sqrtPriceLimitX96": 0
    }).buildTransaction()
```
It throws an exception: Could not identify the intended function with name `exactInputSingle`, positional argument(s) of type `(<class 'dict'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `exactInputSingle`: ['exactInputSingle(tuple)']
How do i generate tuple type?

**Comment by dbfreem** [comment]
Just trying to make sure I understand the issue, what part of this are you expecting is a web3.py issue? Can you provide some context around this where you are using web3.py

**Comment by syaringan357** [comment]
@dbfreem 
The documentation is here. https://docs.uniswap.org/protocol/guides/swaps/single-swaps
When I wanted to implement it with web3.py, the above problem occurred, and I could not create a tuple type parameter as input.

**Comment by syaringan357** [comment]
@dbfreem 
The uniswap v3 router contract is 0xE592427A0AEce92De3Edee1F18E0157C05861564 .
The ABI is 
[{"inputs":[{"internalType":"address","name":"_factory","type":"address"},{"internalType":"address","name":"_WETH9","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"WETH9","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"components":[{"internalType":"bytes","name":"path","type":"bytes"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"amountIn","type":"uint256"},{"internalType":"uint256","name":"amountOutMinimum","type":"uint256"}],"internalType":"struct ISwapRouter.ExactInputParams","name":"params","type":"tuple"}],"name":"exactInput","outputs":[{"internalType":"uint256","name":"amountOut","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[{"components":[{"internalType":"address","name":"tokenIn","type":"address"},{"internalType":"address","name":"tokenOut","type":"address"},{"internalType":"uint24","name":"fee","type":"uint24"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"amountIn","type":"uint256"},{"internalType":"uint256","name":"amountOutMinimum","type":"uint256"},{"internalType":"uint160","name":"sqrtPriceLimitX96","type":"uint160"}],"internalType":"struct ISwapRouter.ExactInputSingleParams","name":"params","type":"tuple"}],"name":"exactInputSingle","outputs":[{"internalType":"uint256","name":"amountOut","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[{"components":[{"internalType":"bytes","name":"path","type":"bytes"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"amountOut","type":"uint256"},{"internalType":"uint256","name":"amountInMaximum","type":"uint256"}],"internalType":"struct ISwapRouter.ExactOutputParams","name":"params","type":"tuple"}],"name":"exactOutput","outputs":[{"internalType":"uint256","name":"amountIn","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[{"components":[{"internalType":"address","name":"tokenIn","type":"address"},{"internalType":"address","name":"tokenOut","type":"address"},{"internalType":"uint24","name":"fee","type":"uint24"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"amountOut","type":"uint256"},{"internalType":"uint256","name":"amountInMaximum","type":"uint256"},{"internalType":"uint160","name":"sqrtPriceLimitX96","type":"uint160"}],"internalType":"struct ISwapRouter.ExactOutputSingleParams","name":"params","type":"tuple"}],"name":"exactOutputSingle","outputs":[{"internalType":"uint256","name":"amountIn","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"factory","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes[]","name":"data","type":"bytes[]"}],"name":"multicall","outputs":[{"internalType":"bytes[]","name":"results","type":"bytes[]"}],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"refundETH","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint8","name":"v","type":"uint8"},{"internalType":"bytes32","name":"r","type":"bytes32"},{"internalType":"bytes32","name":"s","type":"bytes32"}],"name":"selfPermit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint256","name":"expiry","type":"uint256"},{"internalType":"uint8","name":"v","type":"uint8"},{"internalType":"bytes32","name":"r","type":"bytes32"},{"internalType":"bytes32","name":"s","type":"bytes32"}],"name":"selfPermitAllowed","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint256","name":"expiry","type":"uint256"},{"internalType":"uint8","name":"v","type":"uint8"},{"internalType":"bytes32","name":"r","type":"bytes32"},{"internalType":"bytes32","name":"s","type":"bytes32"}],"name":"selfPermitAllowedIfNecessary","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint8","name":"v","type":"uint8"},{"internalType":"bytes32","name":"r","type":"bytes32"},{"internalType":"bytes32","name":"s","type":"bytes32"}],"name":"selfPermitIfNecessary","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amountMinimum","type":"uint256"},{"internalType":"address","name":"recipient","type":"address"}],"name":"sweepToken","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amountMinimum","type":"uint256"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"feeBips","type":"uint256"},{"internalType":"address","name":"feeRecipient","type":"address"}],"name":"sweepTokenWithFee","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"int256","name":"amount0Delta","type":"int256"},{"internalType":"int256","name":"amount1Delta","type":"int256"},{"internalType":"bytes","name":"_data","type":"bytes"}],"name":"uniswapV3SwapCallback","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"amountMinimum","type":"uint256"},{"internalType":"address","name":"recipient","type":"address"}],"name":"unwrapWETH9","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"uint256","name":"amountMinimum","type":"uint256"},{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"feeBips","type":"uint256"},{"internalType":"address","name":"feeRecipient","type":"address"}],"name":"unwrapWETH9WithFee","outputs":[],"stateMutability":"payable","type":"function"},{"stateMutability":"payable","type":"receive"}]

When I call the exactInputSingle function, the type of parameter that needs to be input is tuple.

**Comment by fselmo** [comment]
@syaringan357 The message is asking for a `tuple` type as the param and you are passing in a `dict`. This is the first issue that I see. However, using your current values, this still errors out as one of your values is not valid. Unfortunately the error message isn't the best there... I'm going to make a note to look into the messaging here as this was a bit tricky to catch.

It looks like your value for `amountIn` is too high. This is the exact amount of `tokenIn` to be swapped for `tokenOut`. Decreasing that value and passing the values in as a tuple seems to work at least for building the transaction on my end. This works for me, using the example of DAI and WETH9 from your link above:

``` python
>>> router_contract = w3.eth.contract(
...    address=UNI_V3_ROUTER_ADDRESS,
...    abi=UNI_V3_ROUTER_ABI
...)

>>> DAI = '0x6B175474E89094C44Da98b954EedeAC495271d0F'
>>> WETH9 = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'

>>> payload = (
...    DAI,  # tokenIn
...    WETH9,  # tokenOut
...    3000,  # fee
...    ACCOUNT_ADDRESS2,  # recipient
...    round(time.time()) + 60 * 20,  # deadline
...    10 ** 9,  # amountIn (exact amount of DAI to be swapped for WETH9)
...    0,  # amountOutMinimum
...    0,  # sqrtPriceLimitX96
...)

>>> type(payload)
tuple

>>> tx = router_contract.functions.exactInputSingle(payload).buildTransaction()
>>> tx
{'value': 0,
 'gas': 22916,
 'maxFeePerGas': 122398613,
 'maxPriorityFeePerGas': 1,
 'chainId': 1337,
 'to': '0xE592427A0AEce92De3Edee1F18E0157C05861564',
 'data': '0x414bf3890000000000000000000000006b175474e89094c44da98b95..........'}
```

Best of luck. Please update here / close this issue if this resolves it for you. Cheers.

**Comment by syaringan357** [comment]
@dbfreem @fselmo Thank you very much.

**Comment by AlexField26** [comment]
Hello, i tried this solution, but still got the error. @syaringan357 : did this work for you?

**Comment by syaringan357** [comment]
@AlexField26 I have solved the above problems, but there are other problems that have not been solved. https://github.com/Uniswap/docs/issues/315#issuecomment -1008764737

**Comment by AlexField26** [comment]
@syaringan357 i have the same issue now

**Comment by 0xflim** [comment]
I am having the same issue now as well. I'm passing in a tuple and it's throwing the same argument type match failed error

```Could not identify the intended function with name `exactInputSingle`, positional argument(s) of type `(<class 'tuple'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `exactInputSingle`: ['exactInputSingle(tuple)']
Function invocation failed due to no matching argument types.```

**Comment by BaiShaojie123123** [comment]
`    # 交易参数 根据精确输出进行交换
    payload = (
        #token_in 被兑换的币
        eth_address,
        #token_out 兑换出的币
        usdc_address,
        #fee
        3000,
        #recipient
        recipient,
        #deadline
        round(time.time())+60*20,
        #amountOut 精确输出,指定要兑换成 token_out 的数量
        # w3.toWei(20,'ether'),
        2*10**6,
        #amountInMaximum 最大输入，指定最多可以花费多少 token_in
        0,
        #sqrt_price_limit_x96
        0
    )
I get error?
    tx = router_contract.functions.exactOutputSingle(payload).buildTransaction()`
web3.exceptions.ContractLogicError: execution reverted

**Comment by shaochila** [comment]
>
我也遇到了类似的问题，如果Status是Fail with error 'STF'，那么你需要授权你的代币给合约地址

**Comment by nikky78** [comment]
Anyone got the answer? I am having the same issue

**Comment by judaniubi** [comment]
Anyone got the answer? I am having the same issue  +1

**Comment by judaniubi** [comment]
transaction =lbpair_contract.functions.addLiquidity(
"0x3C808152e7E2098C0dD8D74CF8d6703e53a5d2c4",
"0xd00ae08403B9bbb9124bB305C09058E32C39A48c",
50,
web3.to_wei(1,'ether'),
web3.to_wei(1,'ether'),
0,
0,
8383990,
5,
[8383990,],
[0,],
[0,],
account.address,
account.address,
int(time.time()) + 3600,
).build_transaction({
'from': account.address,
'gas': 300000,
'gasPrice': web3.to_wei('50', 'gwei'),
'nonce': web3.eth.get_transaction_count(account.address)
})

# 签名交易
signed = web3.eth.account.sign_transaction(transaction, private_key)

# 发送交易
tx_hash = web3.eth.send_raw_transaction(signed.rawTransaction)

print(web3.to_hex(tx_hash))



--------------------------------------------------------------------------
Web3ValidationError: 
Could not identify the intended function with name `addLiquidity`, positional arguments with type(s) `address,address,int,int,int,int,int,int,int,(int),(int),(int),address,address,int` and keyword arguments with type(s) `{}`.
Found 1 function(s) with the name `addLiquidity`: ['addLiquidity((address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,int256[],uint256[],uint256[],address,address,uint256))']
Function invocation failed due to improper number of arguments.

**Comment by kclowes** [comment]
All of these comments look like issues with how the arguments are being passed in, not a problem with the library. I'm going to lock this thread because I don't think it's productive to keep adding to it. If you have usage questions, please post in the [Python Discord](https://discord.gg/GHryRvPB84) and someone may be able to help troubleshoot.
