### ISSUE TITLE
Gas limit parameter as integer in TxParams

### ISSUE THREAD

**Issue by coccoinomane** [ethereum/web3.py#2285]
* Version: 5.25.0
* Python: 3.9
* OS: osx

### What was wrong?

Hi there!
Shouldn't the `gas` parameter type in `TxParams` be an integer instead of `Wei`?
[Here's the line](https://github.com/ethereum/web3.py/blob/master/web3/types.py#L207).

### How can it be fixed?

I am happy to do a pull request if you can confirm it is the case :-)

**Comment by stolpa4** [comment]
@coccoinomane Wei is just an alias for int, so it's not a problem, I think. Just use

```python
from typing import cast

from web3.types import Wei

gas_limit: int = 1000

print(cast(Wei, gas_limit))
```

**Comment by coccoinomane** [comment]
Hi @stolpa4 , thank you for your reply 🙂
I see how casting to `Wei` would do it... but would it not be simpler to just set `gas_limit`'s type to `int` in `TxParams`?
It would be more natural, given that gas limit is a pure number. It is the gas price that carries the dimensionality (Wei).
Cheers,
Guido

**Comment by fselmo** [comment]
@coccoinomane This is definitely a good change. This would technically be a breaking change so we will likely wait to include it in the next major version release. Thanks for submitting!

**Comment by kclowes** [comment]
The fix has been merged! Thanks for the report @coccoinomane!
