### ISSUE TITLE
Bitarray (setup.py) error **pip install web3**

### ISSUE THREAD

**Issue by kubesqrt** [ethereum/web3.py#2290]
Hi :) 

I have been trying to pip install web3 into visual code basics but I am getting some errors. I have been using python 3.10 but tried it with python3.9.9 and 3.9.7 and had no luck. I tried manually downloading bitarray from **"https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray"** and it work in cmd but when I run pip install it still gives me an error. I have made sure I have added the supplementary packages into my visual studio builder.

I'm getting errors of:
**Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:**

and

  **Running setup.py clean for bitarray
Failed to build bitarray
Installing collected packages: bitarray, websockets, protobuf, ipfshttpclient, eth-account, web3
  Attempting uninstall: bitarray
    Found existing installation: bitarray 2.3.4
    Uninstalling bitarray-2.3.4:
      Successfully uninstalled bitarray-2.3.4
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:**

I have reinstalled Microsoft studio with the latest version and got rid of all my old versions. I really am unsure where to go from here because I feel like I have read every single blog post about this issue.  Any help would be much appreciated :)  Thank you!

**Comment by dbfreem** [comment]
The eth-account dependency is dependent on bitarray < 1.3.0 >= 1.2.1 so if you are looking for a precompiled version you need one that fits those requirements. In the above post it looks like you tried to install bitarray 2.3.4.

**Comment by kubesqrt** [comment]
Thanks for that, I found out its not supported on 3.10 after digging through lots of posts. do you know where I could find the .whl file for bitarray < 1.3.0 >= 1.2.1 ? The file is in https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray but only for python versions 3.5 and older. Is that the only python versions that Web3.py is compatible on ? If not would you mind providing me with the .whl file ?

**Comment by dbfreem** [comment]
Web3.py is compatitble with more versions of python. I don't know where you can get a precompiled version of bitarray. I personally would go the WSL route to install web3.py instead of trying to find a precompiled version of bitarray.

WSL didn't have any issues installing web3.py in my experience.

**Comment by kubesqrt** [comment]
Yeah, its not exactly a smooth experience on windows.  thanks for your help. I really appreciate it :)

**Comment by fselmo** [comment]
This issue is being tracked by https://github.com/ethereum/eth-account/issues/132. I am going to close this in hopes of keeping the conversation in one place.

For now, the most relevant documentation can be found here: https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error

We realize this does not seem to work for everyone and we expect to get to this issue very soon.

**Comment by WontknoW** [comment]
Having this same issue. I guess the only way would be to downgrade Python. As for the precompiled versions of bitarray and many others: [https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray]

**Comment by mebedel** [comment]
hey I found the solution
SIMPLE WAY TO INSTALL WEB3
Install irudict , cytools from [https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbjY2QmU2WW9XZDZiMFFwc29BRGo3S0FyblVKd3xBQ3Jtc0tuNDF5WnVZTUh2RWdRT09FNGZtVDR3Z1hNSHNiZm9KMXVfTUtNanh1cVJzLUtXeHpEcXlTcElITjRSSnlZYmlRVE8xUVpoUmp6eW5hVVNaVjc0ZGg2dDZubFNZN3dFU1hENERiSWMyYmRydl9BUW81RQ&q=https%3A%2F%2Fwww.lfd.uci.edu%2F%7Egohlke%2Fpythonlibs%2F&stzid=UgwcMt1C-s_d8ZRRi8V4AaABAg)
watch this video [https://youtu.be/zbNczZLP1tA?t=348](https://www.youtube.com/watch?v=zbNczZLP1tA&t=348s)
if you don't know how to install from the wheels

Then paste: pip install bitarray==1.2.2 to cmd
after that pip install web3

It should work without needing to install visual c build tools
