### ISSUE TITLE
Improve docs for adding external modules

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/web3.py#2291]
### What?

External module support was introduced via #2288. Basic example for `attach_modules` is included, but we can use some more documentation on what modules are and can be composed of.

**Comment by AvinashKasukurthi** [comment]
Hello @marcgarreau I am a beginner in open source contributions.

I am interested to be part in developing web3. 
Can you please guide me through the work so that I can make more reliable contributions another day.

**Comment by marcgarreau** [comment]
This is was closed in #2304.

@AvinashKasukurthi thanks for your interest in contributing! I'll tag you in the next "good first issue" I find. :)

**Comment by AvinashKasukurthi** [comment]
Thank you for making me as a part of web3.
