### ISSUE TITLE
RLP leading zero bytes error for signatures

### ISSUE THREAD

**Issue by amany9000** [ethereum/web3.py#2297]
* Version: 5.23.0
* Python: 3.9
* OS: linux

### RLP leading zero bytes error for signatures occurs once every 10-15 transactions.

```self = <web3.manager.RequestManager object at 0x7f50b6762fd0>
response = {'error': {'code': -32000, 'message': 'rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.LegacyTx).S'}, 'id': 1, 'jsonrpc': '2.0'}
params = ('0xf9012c218477359400830f4240946dda855dd152f7700cb9f2cffa4ea83fbd0c46e080b8c42e8f276200000000000000000000000000000000...7a8366025bce57415452e3df3f360750ad448252f5a06ce728a000774301355072f0d5dd0782ff3be7d0c5729d1e067788ece453720f5fa4d634',)
error_formatters = <cyfunction identity at 0x7f50bb5485f0>
null_result_formatters = <cyfunction identity at 0x7f50bb5485f0>

    def formatted_response(
        self,
        response: RPCResponse,
        params: Any,
        error_formatters: Optional[Callable[..., Any]] = None,
        null_result_formatters: Optional[Callable[..., Any]] = None,
    ) -> Any:
        if "error" in response:
            apply_error_formatters(error_formatters, response)
>           raise ValueError(response["error"])
E           ValueError: {'code': -32000, 'message': 'rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.LegacyTx).S'}

usr/local/lib/python3.9/site-packages/web3/manager.py:168: ValueError```

**Comment by amany9000** [comment]
@dbfreem ?

**Comment by fselmo** [comment]
@amany9000 This message is coming from your provider and it points out that the `s` in the signed transaction starts with zero bytes and this is not acceptable.

This doesn't seem to be an issue with the web3.py library. I want to direct you to the [discord](https://discord.gg/GHryRvPB84) for usage questions. There's a great community there always willing to help. We like to keep this space for tracking issues specific to our library. I'm going to close this for now. If you believe this was closed in error and there is a relevant issue at hand with the web3.py library, please feel free to re-open this. Best of luck.
