### ISSUE TITLE
Contract pastEvents() not working

### ISSUE THREAD

**Issue by mattvick** [ethereum/web3.py#230]
* Version: 3.11.1
* Python: 3.5.3
* OS: macOS 10.12.6

I'm connecting to the **Kovan** network using **Parity 1.7.0** on **localhost**

### Querying a contract for past events returns an empty array

The code that produces the bug:
```py
import json
import logging
from web3 import Web3, HTTPProvider

web3 = Web3(HTTPProvider('http://localhost:8545'))
token_address = '0x3C088443D8a9d63bF427aC7466c9EB8a8409b612'
token_abi = json.loads('[{"constant":true,"inputs":[],"name":"name" ... }]') # shortened the token ABI in this post for clarity
token_contract = web3.eth.contract(address=token_address, abi=token_abi)

transfer_filter = token_contract.pastEvents('Transfer')
# passing {'fromBlock': 'earliest', 'toBlock': 'latest'} doesn't help
# transfer_filter = token_contract.pastEvents('Transfer', {'fromBlock': 'earliest', 'toBlock': 'latest'})
log_entries = transfer_filter.get()
logger.warning(log_entries)

# logs:
[]
```

### Dropping into the lower level `web3.eth.filter` works

Code that works:
```py
import logging
from web3 import Web3, HTTPProvider

web3 = Web3(HTTPProvider('http://localhost:8545'))
token_address = '0x3C088443D8a9d63bF427aC7466c9EB8a8409b612'

filter = web3.eth.filter({
    "fromBlock": "earliest",
    "toBlock": "latest",
    "address": token_address,
    "topics": [
        # The Transfer event signature:
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
    ]
})
log_entries = filter.get(False)
logger.warning(log_entries)

# logs:
[AttributeDict({'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', ... 'transactionIndex': 0})] # shortened the logs in this post for clarity
```

This is not particularly helpful as I would now need to duplicate Contract functionality for decoding event data and topics such as `get_event_data(event_abi, log_entry)`

**Comment by iamkidjoe** [comment]
@mattvick, it seems that I've found some solution. 
Try to call `get` method with False as the first argument. It will return all your past events.
More details you can find [here](https://github.com/pipermerriam/web3.py/blob/cf3f4889f8c072d7fd6704cfc053d8e312532121/docs/filters.rst#event-log-filters).

**Comment by pipermerriam** [comment]
@iamkidjoe 

cc @djrtwo 

Thanks for reporting this.  There's work underway to revamp filters and improve the documentation around them.  See #294

**Comment by pipermerriam** [comment]
closing this as the filter API has been reworked. Please re-open or re-submit a new issue if you are still having issues.
