### ISSUE TITLE
How to make delay some blocks for send transaction.

### ISSUE THREAD

**Issue by Cinderella941217** [ethereum/web3.py#2309]
Hello. I need to wait Transaction until reach proper confirmation number by using web3.py.
For web3.js, there is waitForTransaction() function for this option. But i didn't find any way in web3.py.
How can i treat it? Exactly need to wait some number's block.

**Comment by pacrob** [comment]
Would `wait_for_transaction_receipt` meet your needs?

https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=wait_for_transaction_receipt#web3.eth.Eth.wait_for_transaction_receipt

**Comment by fselmo** [comment]
I'm with @pacrob on this one 👍 

We prefer to use issues to track issues with the library. Please see the [documentation](https://web3py.readthedocs.io/en/latest/) for information on methods or feel free to ask usage questions on the [discord](https://discord.gg/GHryRvPB84).
