### ISSUE TITLE
ERROR: Could not find a version that matches eth-utils<2,<2.0.0,<3,>=1.0.0-beta.1,>=1.0.2,>=1.2.0,>=1.3.0,>=1.9.5,>=2.0.0 from web3==5.26.0-

### ISSUE THREAD

**Issue by giovanni-caiazzo** [ethereum/web3.py#2314]
* Version: 5.26.0
* Python: 3.9
* OS: linux Ubuntu 21.10
* `pipenv lock` output

```
ERROR: Could not find a version that matches eth-utils<2,<2.0.0,<3,>=1.0.0-beta.1,>=1.0.2,>=1.2.0,>=1.3.0,>=1.9.5,>=2.0.0 (from web3==5.26.0->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 7))
Tried: 0.7.0, 0.7.0, 0.7.1, 0.7.1, 0.7.2, 0.7.2, 0.7.3, 0.7.3, 0.7.4, 0.7.4, 0.8.0, 0.8.0, 0.8.1, 0.8.1, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.5.0, 1.5.0, 1.5.1, 1.5.1, 1.5.2, 1.5.2, 1.6.0, 1.6.0, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.6.3, 1.6.3, 1.6.4, 1.6.4, 1.7.0, 1.7.0, 1.8.0, 1.8.0, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.8.3, 1.8.3, 1.8.4, 1.8.4, 1.9.0, 1.9.0, 1.9.2, 1.9.2, 1.9.3, 1.9.3, 1.9.4, 1.9.4, 1.9.5, 1.9.5, 1.10.0, 1.10.0, 2.0.0, 2.0.0
Tried pre-versions: 1.0.0b1, 1.0.0b1, 1.0.0b2, 1.0.0b2, 1.3.0b0, 2.0.0a0, 2.0.0a0
There are incompatible versions in the resolved dependencies:
  eth-utils<2,>=1.0.2 (from rlp==2.0.1->eth-account==0.5.6->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 8))
  eth-utils<2,>=1.3.0 (from eth-account==0.5.6->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 8))
  eth-utils<2.0.0,>=1.0.0-beta.1 (from eth-keyfile==0.5.1->eth-account==0.5.6->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 8))
  eth-utils<2.0.0,>=1.2.0 (from eth-abi==2.1.1->web3==5.26.0->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 7))
  eth-utils<2.0.0,>=1.3.0 (from eth-keys==0.3.3->eth-account==0.5.6->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 8))
  eth-utils<2.0.0,>=1.9.5 (from web3==5.26.0->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 7))
  eth-utils<3,>=2.0.0 (from eth-rlp==0.3.0->eth-account==0.5.6->-r /tmp/pipenvwj559235requirements/pipenv-5nwo02j0-constraints.txt (line 8))

```

* `pipfile` content

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[pipenv]
allow_prereleases = true

[dev-packages]
mock = "*"
boto3-stubs = "*"
"boto3-stubs[essential]" = "*"
pytest = "*"
pytest-sugar = "*"
pytest-xdist = "*"
pytest-mock = "*"
pytest-cov = "*"
hypothesis = "*"
moto = "*"
requests-mock = "*"
black = "*"
colorama = "*"

[packages]
boto3 = "*"
botocore = "*"
requests = "*"
graphql-core="*"
lambda-decorators = "==0.6.0"
aws-lambda-logging = "==0.1.1"
more-itertools = "==8.8.0"
pyjwt="*"
web3="*"
eth_account="*"

[requires]
python_version = "3.9"
```

### What was wrong?

I'm trying to install web3.py in my project using pipenv, but it is throwing this error while installing
Edit: trying to install web3.py version 3.16.0 works without problems when `eth_account` is not present, but I need them both
Edit2: Trying to do pipenv install works and installs the latest version of web3.py, but then locking fails

### How can it be fixed?

It seems like it's asking for conflicting versions of the same package

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by giovanni-caiazzo** [comment]
The problem was that pipfile locking was selecting the wrong versions of the eth-* dependencies. If someone else has my problem just do this:
```
web3 = "*"
eth-account = "==0.5.6"
eth-utils = "==1.10.0"
eth-rlp = "==0.2.1"
```

**Comment by pacrob** [comment]
Thanks for coming back with a solution! Closing this issue.

**Comment by Barabazs** [comment]
Will this be addressed in a coming release?

**Comment by kclowes** [comment]
@Barabazs try using web3.py v5.28+, and if that doesn't work, please raise a new issue with the steps to reproduce. Thanks!

**Comment by dillu24** [comment]
I have the following inside my Pipfile, and when doing `pipenv install` it is raising similar errors again:

![image](https://user-images.githubusercontent.com/23262259/154988908-989b9670-359c-4021-9a8b-facbbf5f4c1b.png)

**Comment by giovanni-caiazzo** [comment]
At the current version I just need this for it to work:
```
web3 = "*"
eth-rlp = "==0.2.1"
```

**Comment by juliangeissler** [comment]
I get this error when I just run `pipenv install web3`, without any other packages installed. I use python 3.10 on W10. The latest version of Web3.py is 5.28.0

**Comment by kclowes** [comment]
If you're using Python 3.10, you'll need to switch to v6.0.0-beta.1. If you want the stable web3 (currently 5.28.0) you'll need to downgrade to Python 3.9.

**Comment by shanexavier313** [comment]
getting this error with python 3.9.12 and web3 5.29.0

**Comment by kclowes** [comment]
@shanexavier313 is that in a fresh virtualenv?
