### ISSUE TITLE
bug ens contract function called twice

### ISSUE THREAD

**Issue by dbfreem** [ethereum/web3.py#2318]
I was looking at what it would take to async resolver in ENS so that it could be used in the name_to_address_middleware when I noticed the below. Feel free to close this issue if I am overlooking something but I am putting in a PR to remove the second call.

In the [main.py](https://github.com/ethereum/web3.py/blob/master/ens/main.py#L245-L248) module for ens the contract function is called twice. Once on line 245 and again on line 248.

**Comment by fselmo** [comment]
closed by #2319
