### ISSUE TITLE
Support for gzip compression?

### ISSUE THREAD

**Issue by quickchase** [ethereum/web3.py#2332]
I've been searching the documentation and the source code, can't find a solid answer.

Does `web3py` support gzip compression? This means:

* Sending gzip encoded requests with `"Content-Encoding: gzip"` header
* Requesting gzip encoded responses with `"Accept-encoding: gzip, deflate"`
* deflating gzip encoded responses (I think this part would be automatically handed by requests)

QuickNode supports this and it often results in far less bandwidth usage on both sides and faster requests/responses.

I know `ethers` supports this with an `allowGzip` bool, but I can't find anything for web3py

**Comment by dbfreem** [comment]
You can pass in the `request_kwargs` parameter to the constructor of the `AsyncHTTPProvider` and those args will flow through to the underlying aiohttp request that goes out. You can see how that works [here](https://github.com/ethereum/web3.py/blob/master/web3/providers/async_rpc.py#L76). So something like this might work for you.

I didn't fully test this out below but it should be generally correct. Try it out and let me know if it works for you. 

`w3 = Web3(AsyncHTTPProvider(url_to_connect_to, request_kwargs={'headers': your_headers}))`

**Comment by kclowes** [comment]
Thanks for the response, @dbfreem! You're right on. Docs are [here](https://web3py.readthedocs.io/en/stable/providers.html#web3.providers.rpc.HTTPProvider). Closing since I believe this is already supported, but @quickchase feel free to reopen if that doesn't work.

**Comment by dbfreem** [comment]
just for note if people run into this issue. As of this writing when you pass in your own headers object web3.py removes the Content-Type: application/json and the web3 useragent. I found this out the hard way until I realized the application/json header was gone.
