### ISSUE TITLE
Is there any appropriate solution regarding the pip insatll web3 issue (version C++ 14.0 required) - I am using visual studio code (shall I download visual studio as well)?

### ISSUE THREAD

**Issue by Ngiannakoylis** [ethereum/web3.py#2339]
* Version: x.x.x
* Python: 3.8.8
win
* `pip freeze` output
Microsoft Windows [Version 10.0.19042.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ngian>pip install web3
Defaulting to user installation because normal site-packages is not writeable
Collecting web3
  Using cached web3-5.27.0-py3-none-any.whl (495 kB)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (0.3.2)
Collecting eth-utils<2.0.0,>=1.9.5
  Using cached eth_utils-1.10.0-py3-none-any.whl (24 kB)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.19.4-cp38-cp38-win_amd64.whl (895 kB)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (0.8.0a2)
Requirement already satisfied: pywin32>=223; platform_system == "Windows" in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (303)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (2.3.0)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
Requirement already satisfied: websockets<10,>=9.1 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (9.1)
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (0.2.2)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (2.27.1)
Requirement already satisfied: aiohttp<4,>=3.7.4.post0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (3.8.1)
Collecting eth-account<0.6.0,>=0.5.7
  Using cached eth_account-0.5.7-py3-none-any.whl (101 kB)
Requirement already satisfied: jsonschema<4.0.0,>=3.2.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from web3) (3.2.0)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in c:\users\ngian\appdata\roaming\python\python38\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.14.1)
Collecting cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"
  Using cached cytoolz-0.11.2.tar.gz (481 kB)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from ipfshttpclient==0.8.0a2->web3) (0.0.9)
Collecting parsimonious<0.9.0,>=0.8.0
  Using cached parsimonious-0.8.1.tar.gz (45 kB)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in c:\users\ngian\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.16.0->web3) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in c:\users\ngian\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.8)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.3.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (21.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (1.7.2)
Collecting rlp<3,>=1.0.0
  Using cached rlp-2.0.1-py2.py3-none-any.whl (20 kB)
Collecting eth-rlp<2,>=0.1.2
  Using cached eth_rlp-0.3.0-py3-none-any.whl (5.0 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting eth-keys<0.4.0,>=0.3.4
  Using cached eth_keys-0.3.4-py3-none-any.whl (21 kB)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Requirement already satisfied: six>=1.11.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.1)
Requirement already satisfied: setuptools in c:\program files\python38\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (49.2.1)
Requirement already satisfied: toolz>=0.8.0 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"->eth-utils<2.0.0,>=1.9.5->web3) (0.11.2)
Requirement already satisfied: netaddr in c:\users\ngian\appdata\roaming\python\python38\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (0.8.0)
Requirement already satisfied: varint in c:\users\ngian\appdata\roaming\python\python38\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (1.0.2)
Requirement already satisfied: base58 in c:\users\ngian\appdata\roaming\python\python38\site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3) (2.1.1)
Using legacy 'setup.py install' for lru-dict, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cytoolz, since package 'wheel' is not installed.
Using legacy 'setup.py install' for parsimonious, since package 'wheel' is not installed.
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Installing collected packages: cytoolz, eth-utils, protobuf, lru-dict, parsimonious, eth-abi, rlp, eth-rlp, eth-keys, eth-keyfile, bitarray, eth-account, web3
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ngian\\AppData\\Local\\Temp\\pip-install-7mfycow6\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\ngian\\AppData\\Local\\Temp\\pip-install-7mfycow6\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ngian\AppData\Local\Temp\pip-record-0o8fz6c7\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\ngian\AppData\Roaming\Python\Python38\Include\cytoolz'
         cwd: C:\Users\ngian\AppData\Local\Temp\pip-install-7mfycow6\cytoolz\
    Complete output (53 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ngian\\AppData\\Local\\Temp\\pip-install-7mfycow6\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\ngian\\AppData\\Local\\Temp\\pip-install-7mfycow6\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ngian\AppData\Local\Temp\pip-record-0o8fz6c7\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\ngian\AppData\Roaming\Python\Python38\Include\cytoolz' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 22.0.3 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

**Comment by pacrob** [comment]
I'm not super familiar with Windows installation, but from your output, I'd say you need Visual C++ 14.0. Quick search shows a similar issue here:

https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-140/6f0726e2-6c32-4719-9fe5-aa68b5ad8e6d

It looks like maybe you can just install the build tools without fully installing Visual Studio?

**Comment by pacrob** [comment]
Closing for now. Please open a new issue or check out our Discord community if you're still having problems.

**Comment by mebedel** [comment]
hey I found the solution
SIMPLE WAY TO INSTALL WEB3
Install irudict , cytools from [https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbjY2QmU2WW9XZDZiMFFwc29BRGo3S0FyblVKd3xBQ3Jtc0tuNDF5WnVZTUh2RWdRT09FNGZtVDR3Z1hNSHNiZm9KMXVfTUtNanh1cVJzLUtXeHpEcXlTcElITjRSSnlZYmlRVE8xUVpoUmp6eW5hVVNaVjc0ZGg2dDZubFNZN3dFU1hENERiSWMyYmRydl9BUW81RQ&q=https%3A%2F%2Fwww.lfd.uci.edu%2F%7Egohlke%2Fpythonlibs%2F&stzid=UgwcMt1C-s_d8ZRRi8V4AaABAg)
watch this video [https://youtu.be/zbNczZLP1tA?t=348](https://www.youtube.com/watch?v=zbNczZLP1tA&t=348s)
if you don't know how to install from the wheels

Then paste: pip install bitarray==1.2.2 to cmd
after that pip install web3

It should work without needing to install visual c build tools
