### ISSUE TITLE
intrinsic gas too low for `eth_call`

### ISSUE THREAD

**Issue by feizerl** [ethereum/web3.py#2341]
Hello,

Occasionally I am getting `err: intrinsic gas too low: have 0, want 21064 (supplied gas 0)` error while calling https://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.ContractFunction.call 

My understanding is that `eth_call` (the underlying call that is made when someone calls `call` on the contract) doesn't actually require gas. 

```
from ... import init_web3, load_abi

import asyncio


def main():
    w3 = init_web3("polygon")

    chainlink = "0xF9680D99D6C9589e2a93a78A04A279e509205945"
    feed_abi = load_abi("PriceFeed")
    feed = w3.eth.contract(address=chainlink, abi=feed_abi)
    new_block_filter = w3.eth.filter("latest")

    def handle_new_block():
        token0_price = feed.functions.latestRoundData().call()[1] / 1e8.  # <--- this fails occasionally 
        print(token0_price)

    async def work():
        while True:
            for _ in new_block_filter.get_new_entries():
                handle_new_block()
        await asyncio.sleep(1)

    asyncio.run(work())


main()
```

Reading alchemy docs from here:
https://docs.alchemy.com/alchemy/apis/ethereum/eth_call

> gas: QUANTITY - (optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions. NOTE: this parameter has a cap of 350 Million gas per request. Reach out to us at support@alchemy.com if you want to increase this limit!

This isn't strictly a `web3py` issue, but was wondering if anyone has seen this before.

**Comment by yenicelik** [comment]
same question. the price of a transaction is dependent on the data it processes, but it's also mentioned that read-only transactions are free. not sure what is true (and to what extent)

**Comment by NickDeLu** [comment]
any update on this?

**Comment by fselmo** [comment]
This does not seem to be a *web3.py* issue. We don't issue that message anywhere and our `Contract` classes correctly use the `eth_call` method so this is likely coming from the node that you are connected to. I am going to close this as stale for now but if this is still happening and there is a reproducible example somewhere that points to the library we can open it back up.
