### ISSUE TITLE
[proposal] add support for poetry.

### ISSUE THREAD

**Issue by wiseaidev** [ethereum/web3.py#2351]
IMHO, using requirements.txt along with setup.py is quite outdated, and it is arguably insecure. What you can do instead is to use [Poetry](https://github.com/python-poetry/poetry) for a proper and modern way of package management. Apparently, Poetry is well maintained and has a good performance. However, I guess that web3 is not currently compatible with the poetry architecture.

What do you think about the project's likelihood of adopting this architecture? Do you think that this project could support pyproject.toml and the [tool.poetry.dependencies] section as used by poetry?

Are you guys down for using poetry as a dependency manager? If so, I would like to give it a shot and start working on it.

Fun fact: "Writing poetry is very powerful for maintaining your well-being, and your mental health." - TrustMeBro.

Consider RTFM of [poetry](https://python-poetry.org/docs/).

**Comment by kclowes** [comment]
We are not going to use Poetry in the near future.
