### ISSUE TITLE
ModuleNotFoundError: No module named 'web3'

### ISSUE THREAD

**Issue by Yazus** [ethereum/web3.py#2356]
* Version: 3.10.2
* Python: 2.7/3.4/3.5
* OS: Windows 10
* `pip freeze` output: web3==5.28.0

**### What was wrong?**

While trying to test my connection, the system is not recognizing the web3 library. 

from web3 import Web3
ganach_url = "HTTP://127.0.0.1:7545"
web3 = Web3(Web3.HTTPProvide(ganach_url))
Print(web3.isConnected())

I received this error message

File "c:\Users\Yaz\Desktop\PYTHON Notes\PYTHON\Ganach-Test.py", line 
1, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'

I tried following what was in this thread  https://github.com/ethereum/web3.py/issues/626  as it's a similar issue but I had a different output when running python repl and trying to import web3:

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'web3'

**Comment by miohtama** [comment]
`pip` and `python` on your system likely point to different installations. 

[Here is a generic Python package installation manual](https://packaging.python.org/en/latest/tutorials/installing-packages/).

**Comment by YisKudo** [comment]
had this same issue. reinstalled the latest version of python with all features in custom installation + all files and "disable path length limit" fixed it for me

**Comment by kclowes** [comment]
Thanks for the answers @miohtama and @YisKudo!
