### ISSUE TITLE
Upgrade jsonschema to the latest 4.4

### ISSUE THREAD

**Issue by kai-alpha** [ethereum/web3.py#2358]
### What was wrong?

https://github.com/ethereum/web3.py/blob/16aff7e80a6bc089051c154b5079213317c27da8/setup.py#L86

I cannot combine `web3.py` with the latest `jsonschema` in a single app (without relying on ugly hacks)

### How can it be fixed?

Maybe just expand the range to `jsonschema>=3.2.0,<4.5` and let users test compatibility?

https://github.com/ethereum/web3.py/blob/16aff7e80a6bc089051c154b5079213317c27da8/docs/web3.pm.rst#L12

so the web3.py dev team shouldn't have to worry too much about maintaining compatibility

**Comment by fselmo** [comment]
closed by #2360 and #2361 for `v5` and `v6`, respectively
