### ISSUE TITLE
RPC error message "already known"

### ISSUE THREAD

**Issue by feizerl** [ethereum/web3.py#2364]
Hello,

This issue is explored [here](https://github.com/ethereum/go-ethereum/issues/22093) as well, but I wanted to verify if there is a possibility that the issue might be due to some interaction of web3py with the remote node. 

I got an "already known" error message when sending a transaction to **polygon mainnet.** 

<img width="849" alt="Screenshot 2022-02-25 at 3 55 02 PM" src="https://user-images.githubusercontent.com/88751631/155801548-03cc7c45-351e-468c-a36b-97907a60ce5e.png">

The web3py usage is pretty straightforward:

```py
            txhash = contract.get_function_by_name(method)(*args).transact(
                txparams
            )

            logger.info(f"Waiting for {txhash.hex()} to be mined...")
            receipt = self.w3.eth.wait_for_transaction_receipt(
                txhash, timeout=None
            )
```

I don't think this is a web3py issue, but wanted to confirm if there is any possibility in which two transactions were sent accidentally? (due to some race condition)

**Comment by 0xburn** [comment]
I am also experiencing this on the Polygon network. I am certain I am sending the transaction only once - yet this error happens intermittently.

**Comment by laoma6** [comment]
mee tooooooooooooooooo!!!!!!!!!
the polygon is bullshit

**Comment by kclowes** [comment]
This looks to me like a problem unique to Polygon, which makes me think it's not web3py. And there's nothing that I can think of off the top of my head that would cause a transaction to be sent twice. I'm going to close, but feel free to reopen if you find something that points to a bug in web3py.
