### ISSUE TITLE
Update dependencies to eth-account >= 0.6.0

### ISSUE THREAD

**Issue by ncocchiaro** [ethereum/web3.py#2366]
* Version: 5.28.0
* Python: 3.8.2
* OS: osx

### What was wrong?

Web3 depends on `eth-account>=0.5.7,<0.6.0` in setup.py, which in turn implies a dependency on `eth-keyfile>=0.5.0,<0.6.0`, which is vulnerable to the timing attack vector on HMAC comparison mitigated in eth-keyfile 0.6.0. This is also detected by [Safety](https://github.com/pyupio/safety).

### How can it be fixed?

The dependency in setup.py can be updated to `eth-account>=0.6.0,<0.7.0`. Are there known issues preventing this?

**Comment by fselmo** [comment]
This is closed by #2342 which should be merged soon. Thanks @ncocchiaro

**Comment by ncocchiaro** [comment]
Ahh thanks @fselmo. I had missed that.

**Comment by kclowes** [comment]
This is merged, and will be pulled into web3 v6.0.0-beta.2. Thanks for the report!
