### ISSUE TITLE
Please help me regarding this ----Error while 'pipenv install web3' Bitarray , cytoolz, lru-dict packages are not installed

### ISSUE THREAD

**Issue by chikkugadu** [ethereum/web3.py#2396]
* Version 5.26
* Python: 3.8
* OS: linux
* `pip freeze` output

```
<put the output from running pip freeze here>
```
aiohttp==3.8.1
aiosignal==1.2.0
aniso8601==7.0.0
asgiref==3.5.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
backports.zoneinfo==0.2.1
base58==2.1.1
bitarray==1.2.2
black==22.1.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.0.3
cytoolz==0.11.2
dataclassy==0.11.1
Django==4.0.3
django-filter==21.1
eip712==0.1.0
eth-abi==2.1.1
eth-account==0.5.7
eth-event==1.2.3
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
execnet==1.9.0
frozenlist==1.3.0
graphene==2.1.9
graphene-django==2.15.0
graphql-core==2.3.2
graphql-relay==2.0.1
gunicorn==20.1.0
hexbytes==0.2.2
hypothesis==6.27.3
idna==3.3
inflection==0.5.0
iniconfig==1.1.1
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lazy-object-proxy==1.7.1
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
mypy-extensions==0.4.3
mythx-models==1.9.1
netaddr==0.8.0
packaging==21.3
parsimonious==0.8.1
pathspec==0.9.0
platformdirs==2.4.1
pluggy==1.0.0
promise==2.3
prompt-toolkit==3.0.26
protobuf==3.19.4
psutil==5.9.0
psycopg2-binary==2.9.3
py==1.11.0
py-solc-ast==1.2.9
py-solc-x==1.1.1
pycryptodome==3.14.1
Pygments==2.11.2
pygments-lexer-solidity==0.7.0
PyJWT==1.7.1
pyparsing==3.0.7
pyrsistent==0.18.1
pytest==6.2.5
pytest-forked==1.4.0
pytest-xdist==1.34.0
python-dateutil==2.8.1
python-dotenv==0.16.0
pythx==1.6.1
pytz==2021.3
PyYAML==5.4.1
requests==2.27.1
rlp==2.0.1
Rx==1.6.1
semantic-version==2.8.5
singledispatch==3.7.0
six==1.16.0
sortedcontainers==2.4.0
sqlparse==0.4.2
text-unidecode==1.3
toml==0.10.2
tomli==2.0.0
toolz==0.11.2
tqdm==4.62.3
typing_extensions==4.0.1
urllib3==1.26.9
varint==1.0.2
vvm==0.1.0
vyper==0.3.1
wcwidth==0.2.5
web3==5.28.0
websockets==9.1
wrapt==1.13.3
yarl==1.7.2

### What was wrong?

An error occurred while installing bitarray==1.2.2 --hash=sha256:! Will try again.
An error occurred while installing cytoolz==0.11.2; python_version >= '3.5' --hash=sha256:! Will try again.
An error occurred while installing lru-dict==1.1.7 --hash=sha256:! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting bitarray==1.2.2
[pipenv.exceptions.InstallError]:   Using cached bitarray-1.2.2.tar.gz (48 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Building wheels for collected packages: bitarray
[pipenv.exceptions.InstallError]:   Building wheel for bitarray (setup.py): started
[pipenv.exceptions.InstallError]:   Building wheel for bitarray (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]:   Running setup.py clean for bitarray
[pipenv.exceptions.InstallError]: Failed to build bitarray
[pipenv.exceptions.InstallError]: Installing collected packages: bitarray
[pipenv.exceptions.InstallError]:   Running setup.py install for bitarray: started
[pipenv.exceptions.InstallError]:   Running setup.py install for bitarray: finished with status 'error'
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × python setup.py bdist_wheel did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [18 lines of output]
[pipenv.exceptions.InstallError]:       running bdist_wheel
[pipenv.exceptions.InstallError]:       running build
[pipenv.exceptions.InstallError]:       running build_py
[pipenv.exceptions.InstallError]:       creating build
[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/test_util.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/util.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/__init__.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       running build_ext
[pipenv.exceptions.InstallError]:       building 'bitarray._bitarray' extension
[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/root/.local/share/virtualenvs/code-_Py8Si6I/include -I/usr/local/include/python3.8 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.8/bitarray/_bitarray.o
[pipenv.exceptions.InstallError]:       error: command 'gcc' failed: No such file or directory
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for bitarray
[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Running setup.py install for bitarray did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [20 lines of output]
[pipenv.exceptions.InstallError]:       running install
[pipenv.exceptions.InstallError]:       /root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
[pipenv.exceptions.InstallError]:         warnings.warn(
[pipenv.exceptions.InstallError]:       running build
[pipenv.exceptions.InstallError]:       running build_py
[pipenv.exceptions.InstallError]:       creating build
[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/test_util.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/util.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       copying bitarray/__init__.py -> build/lib.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       running build_ext
[pipenv.exceptions.InstallError]:       building 'bitarray._bitarray' extension
[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-3.8/bitarray
[pipenv.exceptions.InstallError]:       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/root/.local/share/virtualenvs/code-_Py8Si6I/include -I/usr/local/include/python3.8 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.8/bitarray/_bitarray.o
[pipenv.exceptions.InstallError]:       error: command 'gcc' failed: No such file or directory
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: legacy-install-failure
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Encountered error while trying to install package.
[pipenv.exceptions.InstallError]: ╰─> bitarray
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
[pipenv.exceptions.InstallError]: hint: See above for output from the failure.
ERROR: Couldn't install package: bitarray
 Package installation failed...
/usr/local/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 342 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=6 mode='rb' closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb' closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 341 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by pacrob** [comment]
Some first things to check: Are you using a virtual environment, like `virtualenv`? Have you upgraded your pip, like `pip install --upgrade pip`, before installing web3?

**Comment by AnotherIdea** [comment]
You are missing gcc

See this line:
`error: command 'gcc' failed: No such file or directory`

**Comment by chikkugadu** [comment]
@AnotherIdea what should I do for that ...please suggest

**Comment by chikkugadu** [comment]
@pacrob pip is upgraded and I am using pipenv shell

**Comment by AnotherIdea** [comment]
> @AnotherIdea what should I do for that ...please suggest

Depending on your distro:

apt install gcc
or
dnf install gcc

You might need others packages like python development libs
Check the error log or post it

**Comment by chikkugadu** [comment]
@AnotherIdea im running in docker ... how should i move forward

**Comment by AnotherIdea** [comment]
Give me your Dockerfile

**Comment by kclowes** [comment]
Bitarray added wheels for all platform types in v2.4.0 (see https://github.com/ethereum/eth-account/pull/154), and we relaxed our dependency requirements in eth-account to allow for that version to be installed. Try installing web3 with bitarray>=2.4.0 and please report back if that doesn't work. Closing for now, but feel free to reopen if you're still running into the same issue.
