### ISSUE TITLE
not able to install web3

### ISSUE THREAD

**Issue by sadath-12** [ethereum/web3.py#2429]
i did pip install web3 and its throwing me some erros

   ERROR: Command errored out with exit status 1:
     command: 'C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SYED SADATH ULLA\\AppData\\Local\\Temp\\pip-install-l8nqoybd\\cytoolz_f20de4d624a1428d92b6446bb682cba8\\setup.py'"'"'; __file__='"'"'C:\\Users\\SYED SADATH ULLA\\AppData\\Local\\Temp\\pip-install-l8nqoybd\\cytoolz_f20de4d624a1428d92b6446bb682cba8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\SYED SADATH ULLA\AppData\Local\Temp\pip-record-v3p7ctoh\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\Include\cytoolz'
         cwd: C:\Users\SYED SADATH ULLA\AppData\Local\Temp\pip-install-l8nqoybd\cytoolz_f20de4d624a1428d92b6446bb682cba8\
    Complete output (53 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.10\cytoolz
    creating build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.10\cytoolz
    creating build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.10\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SYED SADATH ULLA\\AppData\\Local\\Temp\\pip-install-l8nqoybd\\cytoolz_f20de4d624a1428d92b6446bb682cba8\\setup.py'"'"'; __file__='"'"'C:\\Users\\SYED SADATH ULLA\\AppData\\Local\\Temp\\pip-install-l8nqoybd\\cytoolz_f20de4d624a1428d92b6446bb682cba8\\setup.py'"'"';f = 
getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\SYED SADATH ULLA\AppData\Local\Tersion 22.0.4 is available.
You should consider upgrading via the 'C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by fselmo** [comment]
Hey @sadath-12, have you tried the suggestion from the error here?

`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Relevant docs can be found [here](https://web3py.readthedocs.io/en/stable/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error).

**Comment by danielsbarros** [comment]
I was having this issue today.
Only solution was open the Visual Studio Installer (if you have Visual Studio installed), and check the option "Desktop C++ Development" (something like that)... it was a large download, but resolved the issue.

**Comment by fselmo** [comment]
@sadath-12 If you are still having issues please feel free to post more information here and ask yo reopen. Installing the C++ Build Tools should ideally get you past this issue as described above. Best of luck.
