### ISSUE TITLE
Dependency requirement of eth-keyfile <0.6.0 has a security issue

### ISSUE THREAD

**Issue by DrUpir** [ethereum/web3.py#2431]
- web3 5.29.0 is the newest one so far,
- web3 5.29.0 required eth-account = ">=0.5.7,<0.6.0",
- eth-account 0.5.7 required eth-keyfile = ">=0.5.0,<0.6.0",
- eth-keyfile <0.6.0 has a securiry issue "Eth-keyfile 0.6.0 mitigates a timing attack vector affecting the hmac comparation when decoding keyfiles." https://github.com/ethereum/eth-keyfile/issues/12

**Comment by kclowes** [comment]
Unfortunately we couldn't upgrade without a breaking change. This change is merged into master and will be released in web3py v6.0.0-beta.2.
