### ISSUE TITLE
the error  {'code': -32000, 'message': 'transaction underpriced'}

### ISSUE THREAD

**Issue by lijixy** [ethereum/web3.py#2437]
when I send the BEP20, the error was  {'code': -32000, 'message': 'transaction underpriced'} back to the rpc

**Comment by fselmo** [comment]
@lijixy this message is coming from your client, not `web3.py` and so is not an issue with the library. If you have questions about usage I would highly suggest checking out the [Discord](https://discord.gg/GHryRvPB84) server.
