### ISSUE TITLE
ModuleNotFoundError: No module named 'eth_tester'

### ISSUE THREAD

**Issue by moltenmuffins** [ethereum/web3.py#2440]
* Version: 5.29.0
* Python: 3.10.4
* OS: linux (Ubuntu 18.04 on WSL2)
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==1.2.2
certifi==2021.10.8
charset-normalizer==2.0.12
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.7
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==4.4.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.20.1
pycryptodome==3.14.1
pyrsistent==0.18.1
requests==2.27.1
rlp==2.0.1
six==1.16.0
toolz==0.11.2
urllib3==1.26.9
varint==1.0.2
web3==5.29.0
websockets==9.1
yarl==1.7.2
```

### What was wrong?

When trying to run the following code:
```python3
from web3 import Web3, EthereumTesterProvider

prov = EthereumTesterProvider()
w3 = Web3(prov)
print(w3.isConnected)
```

The following error is thrown
```
Traceback (most recent call last):
  File "/home/evan/repositories/dev/web3_bot/main.py", line 3, in <module>
    prov = EthereumTesterProvider()
  File "/home/evan/.virtualenvs/web3_bot_env/lib/python3.10/site-packages/web3/providers/eth_tester/main.py", line 69, in __init__
    from eth_tester import EthereumTester  # noqa: F811
ModuleNotFoundError: No module named 'eth_tester'
```

**Comment by fselmo** [comment]
Hey @moltenmuffins. `eth-tester` doesn't come with the `web3` install by default. Try installing the tester dependencies via `pip install "web3[tester]"` and give the example another shot.

**Comment by moltenmuffins** [comment]
I see, I was of the assumption that it was already included as the [quickstart](https://web3py.readthedocs.io/en/stable/quickstart.html#test-provider) didn't explicitly mention to install it.

Will close this issue. Thanks for the quick response!

**Comment by fselmo** [comment]
> I was of the assumption that it was already included as the [quickstart](https://web3py.readthedocs.io/en/stable/quickstart.html#test-provider) didn't explicitly mention to install it.

We could probably use a note on that doc... thanks for bringing attention to it. Glad you got it working.

**Comment by filosofoeduardo** [comment]
I wish that had worked for me. After doing pip install web3tester I got this:

$ from web3 import Web3, EthereumTesterProvider
from: can't read /var/mail/web3
edwin@edwin-Veriton-X680G:~/demos2/brownie_fund_me2$ from web3 import Web3, EthereumTesterProvider
from: can't read /var/mail/web3

**Comment by filosofoeduardo** [comment]
the install was initially followed by this statement (plus masses of further detail):

$ pip install "web3[tester]"
Requirement already satisfied: web3[tester] in /home/edwin/.local/lib/python3.8/site-packages (5.31.1)
