### ISSUE TITLE
Q: How can I pass HTTP header to HTTP provider?

### ISSUE THREAD

**Issue by RickCastle2018** [ethereum/web3.py#2461]
* Version: lastest
* Python: 3.5
* OS: linux

### What was wrong?

To access Ethereum nodes I have to pass an Authorization header for connecting (Authorization: Bearer TOKEN). But I couldn't find how to do this in documentation or anywhere else on the internet.

### How can it be fixed?

Can you please tell me if it's currently possible? If it's not, it shout probably be added to TODO. I think, it can be very useful for many people.

**Comment by kclowes** [comment]
Yes, you can do this. You'll need to use the `request_kwargs` keyword argument as shown [in the docs here](https://web3py.readthedocs.io/en/stable/providers.html#web3.providers.rpc.HTTPProvider). You'll probably need to do something like 

```python
headers = { 'Authorization': 'Bearer token' }
w3 = Web3(HTTPProvider(url, request_kwargs={'headers': headers}))
```

`request_kwargs` gets passed through to the `requests` library so you can check out their documentation to see what they will accept and what format it needs to be in.

**Comment by RickCastle2018** [comment]
@kclowes, thank you very much! I don't know how I didn't notice this thing in docs
