### ISSUE TITLE
Missing v5.29.0 release notes

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/web3.py#2463]
Hey it seems there is no changelog for 5.29. Why is that? 

https://github.com/ethereum/web3.py/blob/master/docs/releases.rst

**Comment by kclowes** [comment]
That's because master and v5 have diverged. They live on the v5 branch here: https://github.com/ethereum/web3.py/blob/v5/docs/releases.rst. There's some tinkering I need to do on Read The Docs to get it to show up there. Sorry about that!

**Comment by kclowes** [comment]
I changed the ReadTheDocs settings to build the v5 branch and master now, so you should be able to see them on our official docs now too. Thanks for the report!
