### ISSUE TITLE
When using eth_call for reading contract functions results, please cache chain_id

### ISSUE THREAD

**Issue by ytrezq** [ethereum/web3.py#2493]
In the latest web3py version, caching the result of `web3.eth.contract` for performing contract_function_name.`call()` still results in `eth_chainid` being sent for each `.call()` even if the function is the same.

This is important for services like Quicknode since it means the quota is divided by 2.

**Comment by fselmo** [comment]
@ytrezq this isn't cached by default. Have you added the `simple_cache_middleware` to your web3 instance and it's still not caching? See the note and example in this section:

https://web3py.readthedocs.io/en/latest/web3.eth.html#web3.eth.Eth.chain_id

**Comment by ytrezq** [comment]
@fselmo : the problem is `web3.eth.contract` related functions are high‑level functions such as someone can’t control what web3 does under the hood.

This prevent doing things like inserting the said middleware or using proxies.

**Comment by ytrezq** [comment]
@fselmo : doing :

    from web3.auto.infura import w3
    from web3.middleware import simple_cache_middleware
    w3.middleware_onion.add(simple_cache_middleware)
    functions=w3.eth.contract(address=Web3.toChecksumAddress(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2), abi=ERC20_ABI).functions
doesn’t works in the way that `eth_chainid` is still called multiple times.

**Comment by fselmo** [comment]
@ytrezq hmm yep I see the issue... thanks for submitting this! I should have a PR for a suggested change out today.

For some context, we are thread locking to prevent read/writes to the cache even if a particular method isn't on the whitelist for caching. So when `eth_call` (from the contract call) gets called, it locks the thread even though it's not in the whitelist to be cached. If the transaction doesn't include the `chainId` then we make a `eth_chainId` call before the `eth_call` has unlocked the thread which doesn't allow us to read from the cache. I think the solution here is to only lock the thread if the method is whitelisted which still prevents any whitelisted method from accessing the cache. I did test this and this does seem to be the issue but we'll have a conversation about the best way to handle this and hopefully get a fix out in the next release.

Thanks again for shedding some light on that.

**Comment by fselmo** [comment]
hey @ytrezq ... this should be fixed in the latest web3.py version `5.29.2`. Thanks again for submitting and let us know here if you are still experiencing any issues.
