### ISSUE TITLE
How to get all transactions of address?

### ISSUE THREAD

**Issue by kevgithub** [ethereum/web3.py#2528]
I found lots of similar questions here and the latest one was asked 4 yrs before, so , its been 2022, is there any easier way to do this job?
thanx

**Comment by pacrob** [comment]
There's still no easy way to do it with just web3.py, just by virtue of how information is organized on the chain. You'd have to step through block-by-block looking for the address. Fortunately other services, etherscan for example, index the chain in various useful ways. An example from their API docs:

https://docs.etherscan.io/v/etherscan/api-endpoints/accounts#get-a-list-of-normal-transactions-by-address

Also, for future reference, usage questions are better directed to our public [Discord](https://discord.gg/GHryRvPB84)
