### ISSUE TITLE
Transaction decoding not properly working

### ISSUE THREAD

**Issue by astrid-net** [ethereum/web3.py#2529]
I'm trying to analyze the transactions of this contract(https://polygonscan.com/address/0x95f57249e6dd394318025068a8bfc841ac6ec0dd), but sometimes when I try to convert from wei to ether value of tokens I got comma in different position than expected. This is the code I'm running:
```
import requests
import web3
import json
from web3 import Web3
 
def fetch_tx(address, chain, node_url, explorer_url, API_KEY, tx_hash):
 
    MORALIS_API_KEY=""
    headers = {'X-API-Key':f"{MORALIS_API_KEY}"}
    tx_details = requests.get(f"https://deep-index.moralis.io/api/v2/transaction/{tx_hash}?chain={chain}", headers=headers).json()
 
    #PRINT TRANSACTION DETAILS
    print(tx_details)
 
    #EXTRACT PARAMETERS AND OBJECT OF THE FUNCTION CALLED
    web3 = Web3(Web3.HTTPProvider(node_url))
    abi_endpoint = f"{explorer_url}?module=contract&action=getabi&address={address}&apikey={API_KEY}"
    abi = json.loads(requests.get(abi_endpoint).text)
 
    contract = web3.eth.contract(address=Web3.toChecksumAddress(tx_details["to_address"]), abi=abi['result'])
    func_obj, func_params = contract.decode_function_input(tx_details["input"])
    #PRINT OBJECT AND PARAMETERS
    print(func_params)
 
    #CONVERT WEI VALUE TO ETHER VALUE---->THIS IS THE PROBLEM!!!
    print(float(Web3.fromWei(func_params['amountsInOutMaxFee'][0], 'ether')))
 
    return func_params
 
 
chain = 'polygon'
node_url = 'https://polygon-rpc.com/'
explorer_url = "https://api.polygonscan.com/api"
API_KEY = 'YOUR_POLYGONSCAN-APIKEY'
tx_hash = '0xa2d59655b42f947dc619f456553476f7b5929ef1ec6da229409dde9d6fb9629d'
fetch_tx(address, chain, node_url, explorer_url, API_KEY, tx_hash)
```

For example take a look at the transaction above on the blockchain explorer (https://polygonscan.com/tx/0xa2d59655b42f947dc619f456553476f7b5929ef1ec6da229409dde9d6fb9629d) you can see that the input decoded data are the same. The problem is that when I convert the amount from wei to ether I got 13.04 while  the blockchain explorer shows 1.304. What's wrong here? thanks for reading.

**Comment by fselmo** [comment]
Answered on ethereum stackexchange [here](https://ethereum.stackexchange.com/questions/130382/conversion-from-wei-to-ether-gives-different-results/130950#130950)... could not reproduce. Please provide more information if this is still an issue.
