### ISSUE TITLE
Deprecate web3.iban module

### ISSUE THREAD

**Issue by pacrob** [ethereum/web3.py#2537]
### What was wrong?

Ethereum IBAN is a dead standard and can be removed.

### How can it be fixed?

Add deprecation notices to the module so it can be removed in a future version of web3.py.

**Comment by dbfreem** [comment]
could this be deprecated in the v5 branch and removed in v6?

**Comment by fselmo** [comment]
> could this be deprecated in the v5 branch and removed in v6?

That would be ideal 👌

**Comment by dbfreem** [comment]
I couldn't find any documentation saying that IBAN is deprecated. Was thinking about picking this issue up but wanted to make sure I got the correct wording in the deprecation warning. Can you point me to anything that says what replaced IBAN  or is it just  a complete deprecation without a replacement.

**Comment by fselmo** [comment]
> I couldn't find any documentation saying that IBAN is deprecated. Was thinking about picking this issue up but wanted to make sure I got the correct wording in the deprecation warning. Can you point me to anything that says what replaced IBAN or is it just a complete deprecation without a replacement.

I haven't looked much into this. Deferring to @pacrob here... 👀

**Comment by pacrob** [comment]
I think it is a feature that was created but never caught on. It is per @pipermerriam  that it is a "a dead standard that is largely if not entirely unused". I spent a while combing through github and couldn't find any recent code using it or similar features in web3.js, ethers, etc.

It will be complete deprecation without replacement, but I think that it would be better to add deprecation notices in v6 and completely remove later. That will give any folks who might still be using it time to change and/or make noise about it.

**Comment by fselmo** [comment]
> That will give any folks who might still be using it time to change and/or make noise about it.

I lean towards adding deprecation in `v5` and removing in `v6` since we're getting breaking changes in now. I think the buffer between `v5` and `v6` should be enough. We are porting all major changes that aren't breaking over to `v5`... I think that gives users enough time to hang out in `v5` until all warnings are addressed.

**Comment by pacrob** [comment]
I defer to your leanings, deprecate in 5 & eliminate in 6 it is!

**Comment by fselmo** [comment]
closed by #2563 (`v5`) and #2565 (`v6`)... thanks once again @dbfreem 👌
