### ISSUE TITLE
Use the `rpc_modules` API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#254]
### What was wrong?

The Management APIs for the go-ethereum RPC expose a method `rpc_modules`.

https://github.com/ethereum/go-ethereum/wiki/Management-APIs#enabling-the-management-apis

It returns data that looks like this:

```javascript
{  
   "id":1,
   "jsonrpc":"2.0",
   "result":{  
      "admin":"1.0",
      "db":"1.0",
      "debug":"1.0",
      "eth":"1.0",
      "miner":"1.0",
      "net":"1.0",
      "personal":"1.0",
      "shh":"1.0",
      "txpool":"1.0",
      "web3":"1.0"
   }
}
```

### How can we use it?

We should use this (when it is available) to determine which APIS are enabled on the `web3` object.  

This needs to account for the following:

* Mutli-provider
* Cases where this method isn't available.  
* Cases where the user still wants access even if the API isn't marked as enabled.

**Comment by carver** [comment]
This is undocumented, but also works in parity.

Perhaps step one is to detect if there's a response from the node saying "Method not found" then check the `rpc_modules` and tweak the error message to make clear that the module is turned off in the given provider.

**Comment by fselmo** [comment]
Closing as not planned. If anyone would find this useful, we would consider re-opening / implementing.
