### ISSUE TITLE
web3.py + pyinstaller

### ISSUE THREAD

**Issue by niko207** [ethereum/web3.py#2540]
from web3 import Web3

web3_provider = Web3.HTTPProvider('https://bsc-dataseed.binance.org/')
web3 = Web3(web3_provider)
web3_status = web3.isConnected()

print(web3_status)

With Pycharm, everything is fine. 

When I convert the script with pyinstaller, status is always False.

Please help, thank you!

**Comment by kclowes** [comment]
I'm not sure how pyinstaller works, but this is more of a usage question and would be better asked in the python [discord](https://discord.gg/GHryRvPB84) channel. It's more likely that you'll come across someone who has used pyinstaller.
