### ISSUE TITLE
Question about interacting dapp - Wallet Connect

### ISSUE THREAD

**Issue by DiMiTriFrog** [ethereum/web3.py#2543]
I'm  trying to simulate a wallet like metamask but with python through wallet connect, but I can't find a way to connect through wallet connect to the dapp and verify the wallet.

To do this I should first set up a wallet with private key and configured to the chain I want to connect, then use that private key to sign the messages, correct?

But I can't find how with the messages that the walletconnect returns I can verify the message.

Does anyone know of an example on which I can base?

I would like  something like a Metamask in python scripting.

**Comment by fselmo** [comment]
Closing, as we prefer to keep our `issues` as issues and not usage questions.

Usage questions are better asked on https://ethereum.stackexchange.com/questions/tagged/web3.py or on the web3 python [discord](https://discord.gg/GHryRvPB84). Best of luck.
