### ISSUE TITLE
Wrong txhash from web3,eth.send_raw_transaction()

### ISSUE THREAD

**Issue by SerK0** [ethereum/web3.py#2548]
* Version: 5.28.0
* Python: 3.10
* OS: linux

### What was wrong?

When I call web3,eth.send_raw_transaction() I receive wrong txhash which is not in pending, not queued, not mined, even after some time.
I use quicknode to connect to BinanceSmartChain.

Is it possible, that node dtops my sended transaction? Any ideas why request give wrong txhash?

**Comment by fselmo** [comment]
Hey @SerK0 👋. We prefer to keep our issues section to talk about issues with the library. Seeing as this doesn't seem like an issue with our library I'm going to close this and suggest we move the conversation somewhere else. For usage questions I recommend the [Ethereum Python Community Discord](https://discord.gg/GHryRvPB84).

If you feel like there _is_ an issue with the library, please feel free to add more details and we can open this back up. Best of luck.
