### ISSUE TITLE
Invalid Sender  

### ISSUE THREAD

**Issue by zaneran9** [ethereum/web3.py#2549]
* Version: 5.29.2
* Python: 3.8
* OS: osx
* `pip freeze` output

```
web3                                              5.29.2  
eth-abi                                           2.1.1      
eth-account                                       0.5.8      
eth-bloom                                         1.0.4      
eth-hash                                          0.3.2      
eth-keyfile                                       0.5.1      
eth-keys                                          0.3.4      
eth-rlp                                           0.3.0      
eth-typing                                        2.3.0      
eth-utils                                         1.10.0     

```

### What was wrong?
I cant's send transaction with ropsten but rinkeby is OK with same codes.

* The code which produced the error
```
w3 = Web3(Web3.HTTPProvider('https://speedy-nodes-nyc.moralis.io/id/eth/ropsten'))
tx_params = {'chainId': 3, 'data': b'', 'gas': 21000, 'maxFeePerGas': '0x47868c00',
             'maxPriorityFeePerGas': '0x47868c00', 'nonce': 4, 'to': 'to_address',
             'type': 2, 'value': 1000000000000000, 'accessList': []}
account = Account.from_key('private_key')
signed_txn = account.sign_transaction(tx_params)
tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
```
* The full output of the error
```
Traceback (most recent call last):
  File "/Users/zane/Work/Projects/test0/eip1559_test/eth_transfer_test.py", line 87, in send_transaction
    tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "/Users/zane/Work/envs/eip1559/lib/python3.9/site-packages/web3/eth.py", line 831, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/Users/zane/Work/envs/eip1559/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/zane/Work/envs/eip1559/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/Users/zane/Work/envs/eip1559/lib/python3.9/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'invalid sender'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zane/Work/Projects/test0/eip1559_test/eth_transfer_test.py", line 146, in <module>
    tx_hash = e.send_transaction(eip1559=False, tx_params=tx_legacy)
  File "/Users/zane/Work/Projects/test0/eip1559_test/eth_transfer_test.py", line 90, in send_transaction
    raise Exception(e)
Exception: {'code': -32000, 'message': 'invalid sender'}

```
* What type of node you were connecting to.
third-party node `moralis.io`,  clientVersion is `{"jsonrpc":"2.0","id":1,"result":"Geth/v1.10.19-stable-23bee162/linux-amd64/go1.18.1"}`

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Hey @zaneran9 👋. This error (`ValueError: {'code': -32000, 'message': 'invalid sender'}`) is coming from the node not the library. I'm going to close this and refer to the note at the bottom of the issue template... 

If you have usage questions the best place to get a quicker answer is the [Ethereum Python Developers Discord](https://discord.gg/GHryRvPB84), otherwise asking or looking around the [Ethereum Stack Exchange](https://ethereum.stackexchange.com) can help as well.

Best of luck.

**Comment by zaneran9** [comment]
> Hey @zaneran9 👋. This error (`ValueError: {'code': -32000, 'message': 'invalid sender'}`) is coming from the node not the library. I'm going to close this and refer to the note at the bottom of the issue template.
> 
> If you have usage questions the best place to get a quicker answer is the [Ethereum Python Developers Discord](https://discord.gg/GHryRvPB84), otherwise asking or looking around the [Ethereum Stack Exchange](https://ethereum.stackexchange.com) can help as well.
> 
> If you feel like this originates from the library somewhere and can provide more details, feel free to post back here and we can open this back up.
> 
> Best of luck.

Hi @fselmo , thanks for your reply quickly. I think that I can't send transaction by Web3.py if the chain has upgraded `The Merge` or  just this node don't support?  Is it related to the transition from pow to pos? If ethereum mainnet is upgraded to The Merge, will I be able to transact via web3.py? Best wishes.

**Comment by zc520yzy** [comment]
@zaneran9 Have you solved it

**Comment by zaneran9** [comment]
> @zaneran9 Have you solved it

yes,  it's wrong client node for me,  check your node.

**Comment by zc520yzy** [comment]
> > @zaneran9你解决了吗
> 
> 是的，这对我来说是错误的客户端节点，请检查您的节点。

https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.send_raw_transaction


![image](https://user-images.githubusercontent.com/19699252/185095776-9b8fc244-0752-40ab-b60e-5b691904d2d5.png)
