### ISSUE TITLE
Why can't import web3 library in python

### ISSUE THREAD

**Issue by devlancer412** [ethereum/web3.py#2557]
* Version: 5.29.2
* Python: 3.10.5
* OS: win
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==1.2.2
certifi==2022.6.15
charset-normalizer==2.1.0
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.8
eth-hash==0.3.3
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==4.6.1
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.20.1
pycryptodome==3.15.0
pyrsistent==0.18.1
pywin32==304
requests==2.28.1
rlp==2.0.1
six==1.16.0
toolz==0.11.2
urllib3==1.26.9
varint==1.0.2
web3==5.29.2
websockets==9.1
yarl==1.7.2
```

### What was wrong?

I tried  to use  web3 library in my project.
but such error occurred.

```
[File "F:\projects\modern-game-backend\.\src\utils\auth.py", line 9, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'](url)
```

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Some other forum or resource (such as [this](https://pytutorial.com/how-to-solve-modulenotfounderror-no-module-named-in-python)) might be best in this scenario as this doesn't seem to have to do with the library. Make sure nothing is named `web3` or `web3.py` in your project as that might conflict as well.
