### ISSUE TITLE
ERROR: Failed building wheel for lru-dict

### ISSUE THREAD

**Issue by m-root** [ethereum/web3.py#2561]
I am trying to install web3 and below is the error that I am getting. 
```
   
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lru-dict


```

**Comment by WyseNynja** [comment]
The relevant part of the error is missing. The part you included pretty much just says "there was an error"

If you look higher up in the log, there is probably more relevant information.

**Comment by m-root** [comment]
I sorted it out by installing the package from the git before installing web3.py. 

`pip install git+https://github.com/amitdev/lru-dict`
