### ISSUE TITLE
Unable to open wiki link

### ISSUE THREAD

**Issue by yongchand** [ethereum/web3.py#2575]
### What was wrong?

Unable to open wiki link in https://github.com/ethereum/web3.py/blob/master/web3/parity.py, including L60 and L75

### How can it be fixed?

Change to other link..maybe https://openethereum.github.io ?

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by pacrob** [comment]
Parity/OpenEthereum fully [deprecated](https://twitter.com/openethereumorg). All related code is due to be removed in v6, so leaving links as they are.
