### ISSUE TITLE
cannot import name 'pipe' from 'eth_utils.toolz'

### ISSUE THREAD

**Issue by lewbei** [ethereum/web3.py#2577]
* Version:5.30.0
* Python:3.5
* OS: win
* `pip freeze` output

```
ImportError                               Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 import web3

File ~\anaconda3\lib\site-packages\web3\__init__.py:6, in <module>
      2 import warnings
      4 import pkg_resources
----> 6 from eth_account import (
      7     Account  # noqa: E402,
      8 )
      9 from web3.main import (
     10     Web3  # noqa: E402,
     11 )
     12 from web3.providers.eth_tester import (  # noqa: E402
     13     EthereumTesterProvider,
     14 )

File ~\anaconda3\lib\site-packages\eth_account\__init__.py:1, in <module>
----> 1 from eth_account.account import (
      2     Account,
      3 )
      5 __all__ = ["Account"]

File ~\anaconda3\lib\site-packages\eth_account\account.py:35, in <module>
     22 from eth_utils.curried import (
     23     combomethod,
     24     hexstr_if_str,
   (...)
     29     to_int,
     30 )
     31 from hexbytes import (
     32     HexBytes,
     33 )
---> 35 from eth_account._utils.legacy_transactions import (
     36     Transaction,
     37     vrs_from,
     38 )
     39 from eth_account._utils.signing import (
     40     hash_of_signed_transaction,
     41     sign_message_hash,
   (...)
     44     to_standard_v,
     45 )
     46 from eth_account._utils.typed_transactions import (
     47     TypedTransaction,
     48 )

File ~\anaconda3\lib\site-packages\eth_account\_utils\legacy_transactions.py:13, in <module>
      2 from typing import (
      3     Dict,
      4 )
      6 from cytoolz import (
      7     curry,
      8     dissoc,
   (...)
     11     pipe,
     12 )
---> 13 from eth_rlp import (
     14     HashableRLP,
     15 )
     16 from eth_utils.curried import (
     17     apply_formatters_to_dict,
     18 )
     19 import rlp

File ~\anaconda3\lib\site-packages\eth_rlp\__init__.py:1, in <module>
----> 1 from .main import (  # noqa: F401
      2     HashableRLP,
      3 )

File ~\anaconda3\lib\site-packages\eth_rlp\main.py:4, in <module>
      1 from eth_utils import (
      2     keccak,
      3 )
----> 4 from eth_utils.toolz import (
      5     pipe,
      6 )
      7 from hexbytes import (
      8     HexBytes,
      9 )
     10 import rlp

ImportError: cannot import name 'pipe' from 'eth_utils.toolz' (C:\Users\anaconda3\lib\site-packages\eth_utils\toolz.py)
```

### What was wrong?

Import Error, cannot import name 'pipe'

### How can it be fixed?

How can i fix this? I could not find any source about this

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Hey @lewbei. Starting off, I would like to point out that python 3.5 is not supported. I don't necessarily think this issue stems from that but my first tip would be to use python 3.7 and above, the later the better. Without your actual code that caused the issue it's also pretty hard to tell what's going on.

Have you tried running your code in a fresh virtual environment with a fresh `web3` pip install? I would try dumbing it down and getting more complex from there to see where the issue emerges.

**Comment by lewbei** [comment]
Hello, my python version is 3.9.12. Sorry for the wrong information. 

I only did "from web3 import Web3" and "import web3". Then, I get this error just by this 2 lines. I have not write my code due to this error. 

I will try it with  a fresh virtual environment.

**Comment by reedsa** [comment]
Closing this out, please file a new issue if you still experience issues.
