### ISSUE TITLE
Please restore chain_id setter (#2376)

### ISSUE THREAD

**Issue by DefiDebauchery** [ethereum/web3.py#2578]
In #2376, `chain_id` was added as a setter. This was a cheap but effective cache to avoid constant lookups during txn building, as `simple_cache` is not currently async.

There was a discussion about adding some validation, but it may have been an accident that @dbfreem removed it in his subsequent commits in #2432 (as I didn't see any comments about it in that PR). To me, it seems better to have this, even if temporary in a v6.0 branch, and improve upon it later (or become obsoleted by an async version of simple_cache)

**Comment by dbfreem** [comment]
After looking into this for a little while, looks like @kclowes removed this [here](https://github.com/ethereum/web3.py/commit/3e8f07c14f10f97071de2f93180e0be07a575ffa).

**Comment by fselmo** [comment]
The simple cache middleware has been asynced, via #2579, and will be out in next release.
