### ISSUE TITLE
Add 'account' to AsyncEth?

### ISSUE THREAD

**Issue by ChristianCoenen** [ethereum/web3.py#2580]
Hey 👋 Is there a reason `account` is not available in `AsyncEth`?

So far, I had to create a non-async w3 object to sign transactions. However, I just found out that when I subclass AsyncEth like this
```python
class CustomAsyncEth(AsyncEth):
    account = Account()
```
signing transactions works just fine.

**Comment by kclowes** [comment]
No reason other than we haven't gotten there yet :) I'll leave this open to track `account` specifically. Feel free to PR the change if you have the time, otherwise know that it's in our queue!

**Comment by dbfreem** [comment]
I went ahead and added this since it was an easy fix. It's in PR #2582

**Comment by fselmo** [comment]
closed by #2582 (`v6`) and #2590 (`v5`)
