### ISSUE TITLE
Mypy error: "TxReceipt" has no attribute "status"

### ISSUE THREAD

**Issue by mdantonio** [ethereum/web3.py#2595]
* Version: 6.0.0b4
* Python: 3.10
* OS: osx
* `pip freeze` output

```
eth-abi==3.0.0
eth-account==0.6.0
eth-hash==0.3.2
eth-keyfile==0.6.0
eth-keys==0.4.0
eth-rlp==0.3.0
eth-tester==0.6.0b6
eth-typing==3.0.0
eth-utils==2.0.0
web3==6.0.0b4
```

### What was wrong?

Mypy is raising a: `"TxReceipt" has no attribute "status"` error

Here a minimal snippet to reproduce the error:

```
from eth_typing import HexStr
from web3 import Web3

rpc_uri = "..."
w3 = Web3(Web3.HTTPProvider(rpc_uri))

tx_receipt = w3.eth.wait_for_transaction_receipt(HexStr("0x..."))

print(tx_receipt.status)
```

->

```
$ mypy test_tx_receipt.py

test_tx_receipt.py:9: error: "TxReceipt" has no attribute "status"
Found 1 error in 1 file (checked 1 source file)
```

The same is for any other properties of TxReceipt (https://github.com/ethereum/web3.py/blob/cdc69f0636524d355af3e489a82129e28c400848/web3/types.py#L264)

**Comment by fselmo** [comment]
Hey @mdantonio... it looks like although attributes do work here, `mypy` reads `TypedDict` as a `dict` with keys and not attributes. `tx_receipt["status"]` should not give any issues with `mypy`.

**Comment by fselmo** [comment]
I'm going to close this but feel free to reopen or ask any questions if you believe there's still something here that we should explore. Best of luck.

**Comment by mdantonio** [comment]
Ok, thank you
