### ISSUE TITLE
Async request session caching incompatible with Flask

### ISSUE THREAD

**Issue by GadzeMike** [ethereum/web3.py#2597]
Flask is not natively async, so it creates a new thread loop for every async request.

When async web3py does an aiohttp call, it caches the session. So the next time you make a request it pulls the stale session out of the cache and throws an "Event loop is closed" exception.

To fix the issue we made the following code changes in request.py as a hack.

```
async def get_async_session(endpoint_uri: URI) -> ClientSession:
    cache_key = generate_cache_key(endpoint_uri)
    ########### TEMP CODE ###########
    if True:# cache_key not in _async_session_cache: # no caching for you!
    ########### TEMP CODE ###########
        await cache_async_session(endpoint_uri, ClientSession(raise_for_status=True))
    return _async_session_cache.get_cache_entry(cache_key)


async def async_get_response_from_get_request(
    endpoint_uri: URI, *args: Any, **kwargs: Any
) -> ClientResponse:
    kwargs.setdefault("timeout", ClientTimeout(10))
    session = await get_async_session(endpoint_uri)
    response = await session.get(endpoint_uri, *args, **kwargs)
    ########### TEMP CODE ###########
    await session.close()
    ########### TEMP CODE ###########
    return response


async def async_get_response_from_post_request(
    endpoint_uri: URI, *args: Any, **kwargs: Any
) -> ClientResponse:
    kwargs.setdefault("timeout", ClientTimeout(10))
    session = await get_async_session(endpoint_uri)
    response = await session.post(endpoint_uri, *args, **kwargs)
    ########### TEMP CODE ###########
    await session.close()
    ########### TEMP CODE ###########
    return response
```

Would be nice to have a setting to disable session caching.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
Hey @GadzeMike, thanks for submitting. Yeah, I think I'm good with making caching optional. Anything that steers the repo towards more customisability is a plus in my book if it makes sense. I think another way you could get around it is to clear the cache after each call on your end for now. We are working on revamping async cache atm as there are some race conditions when multythreading... check the PR [here](https://github.com/ethereum/web3.py/pull/2409) and make sure that the problem still exists on your end. I believe if Flask works the way you described it that the PR I linked won't fix that but if you want to give it a shot then I figured I'd like that for now.

**Comment by fselmo** [comment]
@GadzeMike any luck with that PR? All those changes are currently in the `master` branch, along with some other updates to the caching. If you can try the current `master` branch and update that would be great. We should also have a new version with these recent changes out soon.

If this is still an obstacle, I think caching sessions being optional would take a bit more priority than just a nice-to-have. Update here whenever you can. Thanks!
