### ISSUE TITLE
Snake case remaining main API methods and properties

### ISSUE THREAD

**Issue by wolovim** [ethereum/web3.py#2598]
### What was wrong?

In `web3/main.py` there are a few properties and methods that have managed to avoid snake casing so far.

### How can it be fixed?

- [x] encoding/decoding: `toBytes`, etc.
- [x] currency utilities: `toWei`, `fromWei`
- [x] address utilities: `isAddress`, etc.
- [x] `clientVersion`
- [x] `solidityKeccak`
- [x] `isConnected`
- [x] ENS `fromWeb3`
- [x] contract.py: 
   - [x] `BaseContractEvent`: `processReceipt`, `processLog`, `createFilter` + kwargs in `createFilter`
   - [x] `ContractEvent` + `AsyncContractEvent`: `getLogs`

**Comment by linda-le1** [comment]
I can get going on snake casing `clientVersion`.

**Comment by linda-le1** [comment]
Will get going on `solidityKeccak` next.

**Comment by linda-le1** [comment]
Working on `fromWeb3` next

**Comment by linda-le1** [comment]
Working on snakecasing the encoding/decoding helpers (toBytes, toHex, toInt, toJSON, and toText)

**Comment by linda-le1** [comment]
Working on snakecasing address helpers (`isAddress`, `isChecksumAddress`,  and`toChecksumAddress`) next

**Comment by linda-le1** [comment]
Working on snakecasing the `contract.py` methods listed

**Comment by kclowes** [comment]
I believe this has been completed! 🎉 Thanks @linda-le1!
