### ISSUE TITLE
Speeding up transactions sent via send_raw_transaction()

### ISSUE THREAD

**Issue by MatthewBautista** [ethereum/web3.py#2601]
I use my app with multiple wallets and keys in a csv file and for each I have sent a transaction using send_raw_transaction(), sometimes these transactions have max gas fee and priority values too low to be included in blocks. Are there any known ways to speed up these raw transactions? Based on the docs, I have learned that modify_transaction and replace_transaction only works when you use send_transaction(). Is there a corresponding method to replace transactions so I can continue to use send_raw_transaction() for the wallets/keys I have in my csv file?

**Comment by fselmo** [comment]
Hey @MatthewBautista. We prefer to use issues to track bugs or improvements to the library. This is stated in the issue template. If you have questions please feel free to ask in the [Discord,](https://discord.gg/GHryRvPB84) or [Ethereum StackExchange](https://ethereum.stackexchange.com/questions/tagged/web3.py).
