### ISSUE TITLE
Add authorization header to Infura IPFS calls

### ISSUE THREAD

**Issue by fselmo** [ethereum/web3.py#2604]
### What was wrong?

Infura IPFS calls started requiring proper authentication as of 8/10/2022. We silenced these errors in order to have the tests passing but we need to add a proper authorization header to Infura IPFS calls.

`v6` changes: #2603 
`v5` changes: #2605

### How can it be fixed?

- Add proper authorization header with Infura project id and secret to Infura IPFS calls.
- See these commits for what to turn back on when proper authorization headers are added to these calls:
     - `v6`: [5aad062](https://github.com/ethereum/web3.py/commit/5aad0625285510cde698a02f538018c529a6260e) and [f75d604](https://github.com/ethereum/web3.py/commit/f75d604fc3ba3a58413d4b6b9a77c2fa1ad44082)
     - `v5`: [5ab9c04](https://github.com/ethereum/web3.py/commit/5ab9c04b7a9157f82f466efda5bfdc0ca1a63b70)

**Comment by pacrob** [comment]
EthPM is deprecated and is the only thing that needs IPFS. Closing wontfix
