### ISSUE TITLE
Bump eth-account to 0.5.9+

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2606]
v5+

### What was wrong?

eth-account 0.5.9 was released. It has a fix for a DOS-able regex pattern. See https://github.com/ethereum/eth-account/pull/178

### How can it be fixed?

Change the requirement in setup.py to be `eth-account>=0.5.9,<0.6.0`, and make sure web3.py can still be installed in a fresh env.

**Comment by fselmo** [comment]
closed by #2607

**Comment by fselmo** [comment]
oops... still needs `v6` PR 👀  -- re-opening

**Comment by fselmo** [comment]
closed by #2607 and #2623
