### ISSUE TITLE
TypeError from `validate_abi_type(abi_type)` with `decimal.Decimal`

### ISSUE THREAD

**Issue by Akkarine** [ethereum/web3.py#2620]
* Version: 5.30.0
* Python: 3.9
* OS: docker desktop on WSL2

### What was wrong?

I'm passing to `w3.solidityKeccak(abi_types, values)` `uint256` values as `decimal.Decimal`, supposing, that `web3.py` aware of this type, like it does in docs [here](https://web3py.readthedocs.io/en/stable/examples.html#converting-currency-denominations).

But I get `TypeError: The following abi value is not a 'uint256': 1000000000000000000000000000000000000`:
```log
File /usr/local/lib/python3.9/site-packages/eth_utils/decorators.py:18, in combomethod.__get__.<locals>._wrapper(*args, **kwargs)
     15 @functools.wraps(self.method)
     16 def _wrapper(*args: Any, **kwargs: Any) -> Any:
     17     if obj is not None:
---> 18         return self.method(obj, *args, **kwargs)
     19     else:
     20         return self.method(objtype, *args, **kwargs)

File /usr/local/lib/python3.9/site-packages/web3/main.py:327, in Web3.solidityKeccak(cls, abi_types, values)
    324     w3 = cls
    325 normalized_values = map_abi_data([abi_ens_resolver(w3)], abi_types, values)
--> 327 hex_string = add_0x_prefix(HexStr(''.join(
    328     remove_0x_prefix(hex_encode_abi_type(abi_type, value))
    329     for abi_type, value
    330     in zip(abi_types, normalized_values)
    331 )))
    332 return cls.keccak(hexstr=hex_string)

File /usr/local/lib/python3.9/site-packages/web3/main.py:328, in <genexpr>(.0)
    324     w3 = cls
    325 normalized_values = map_abi_data([abi_ens_resolver(w3)], abi_types, values)
    327 hex_string = add_0x_prefix(HexStr(''.join(
--> 328     remove_0x_prefix(hex_encode_abi_type(abi_type, value))
    329     for abi_type, value
    330     in zip(abi_types, normalized_values)
    331 )))
    332 return cls.keccak(hexstr=hex_string)

File /usr/local/lib/python3.9/site-packages/web3/_utils/encoding.py:66, in hex_encode_abi_type(abi_type, value, force_size)
     62 """
     63 Encodes value into a hex string in format of abi_type
     64 """
     65 validate_abi_type(abi_type)
---> 66 validate_abi_value(abi_type, value)
     68 data_size = force_size or size_of_type(abi_type)
     69 if is_array_type(abi_type):

File /usr/local/lib/python3.9/site-packages/web3/_utils/validation.py:152, in validate_abi_value(abi_type, value)
    149 elif is_string_type(abi_type) and is_string(value):
    150     return
--> 152 raise TypeError(
    153     "The following abi value is not a '{abi_type}': {value}"
    154     .format(abi_type=abi_type, value=value)
    155 )
```

### How can it be fixed?

Probably, function `validate_abi_type(abi_type)` at `validation.py:149` should be a little more complicated, considering, that python Decimal could be represented also as string.

**Comment by ryo-ma** [comment]
Should Decimal type be supported?
if you need me I can help.

eth_utils also needs fixing. 
https://github.com/ethereum/eth-utils/blob/bbdaf5e3b317871c3772c7d34c12d59943e6ea7e/eth_utils/conversions.py#L20

**Comment by pacrob** [comment]
Sorry for the delay in responding. I think we specifically wouldn't want to accept a Decimal here, as we're looking for a `uint` value. If we accept Decimal, then we end up needing check for decimal points and doing implicit conversion. The `toWei` function you mention would be great to use in your process to make that conversion explicit before using the value.
