### ISSUE TITLE
ipfshttpclient is unmaintained

### ISSUE THREAD

**Issue by RaitoBezarius** [ethereum/web3.py#2629]
* Version: not-relevant
* Python: not-relevant
* OS: not-relevant
* `pip freeze` output

```
not-relevant
```

### What was wrong?

According to https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/316 and https://github.com/NixOS/nixpkgs/issues/185294 ; we surmise that `ipfshttpclient` is currently unmaintained or has some breakages unresolved at the moment.

I wanted to understand if you had plans to migrate away to another library or mark the IPFS backend as an extra module or deprecated for now?

### How can it be fixed?

- Drop the IPFS backend (deprecation)
- Move it as an extra module (with appropriate documentation)
- Offer up help to maintain the Python IPFS HTTP client
- Move to another library (homegrown or whatever.)

**Comment by pinnaculum** [comment]
I maintain [this library](https://github.com/pinnaculum/aioipfs) which is now compliant with kubo 0.15, but it's only usable with asyncio.

ipfshttpclient currenly supports the RPC API of go-ipfs between version 0.5.0 and 0.9.0 (i often patched ipfshttpclient.client.assert_version to make it work with later versions). There's a little bit of work involved to make it compliant with kubo but it's doable, would be happy to help.

**Comment by Polsaker** [comment]
> Move it as an extra module (with appropriate documentation)

Another option: Making the IPFS backend opt-in. I bet most people using this library won't be using this and those that want to use this can just install `web3[ipfs]`

**Comment by step21** [comment]
On that note, as packager of the web3.py package for conda-forge, where do you get your ipfshttpclient from? currently setup.py wants 0.8.2 something, but according to pypi and github the latest version is 0.7.0.

**Comment by fselmo** [comment]
> On that note, as packager of the web3.py package for conda-forge, where do you get your ipfshttpclient from? currently setup.py wants 0.8.2 something, but according to pypi and github the latest version is 0.7.0. 

We use [0.8.0a2](https://pypi.org/project/ipfshttpclient/0.8.0a2). PR #2110 for context.

**Comment by fselmo** [comment]
Thanks for raising this @RaitoBezarius. We don't currently have IPFS on the immediate roadmap so this fell by the wayside for a bit. I would be supportive of re-organizing the backend as opt-in. PRs are welcome otherwise we will try to get to this soon, ideally before `v6` moves to stable.
