### ISSUE TITLE
web3.py returning wrong values

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/web3.py#2640]
![image](https://user-images.githubusercontent.com/30082863/189483709-1f7831fe-6667-415d-8b48-9afc60b4d789.png)

As can be seen in the image, every web3.py call i am making to geth returns nothing but 0 

even though the answer is not 0

i am running geth with lighthouse beacon client, please help me out here

**Comment by fselmo** [comment]
@SyedMuhamadYasir this doesn't seem like an issue with the web3.py library, but rather your client configurations. If you believe it's an issue with the library please feel free to reopen with more specifics. Best of luck.
