### ISSUE TITLE
Example contract deployment in the documentation does not work, here's the fix

### ISSUE THREAD

**Issue by mathstream** [ethereum/web3.py#2646]
* Version: 5.30.0
* Python: 3.9.10
* OS: OSX 12.0

### What was wrong?
I copy / pasted the example on https://web3py.readthedocs.io/en/stable/examples.html#deploying-new-contracts
(Exactly the steps under Contract Deployment Example)

The Solidity compiler gets a return code 0 and prints "solcx.exceptions.SolcError: An error occurred during execution"
and then a list of command line options.

***************
Now, if I change change the line:
    return compile_source(source)
to:
    return compile_source(source, output_values=['abi', 'bin'])

then it will compile and run OK.

***************
Found this kinda by accident, I was trying to connect and deploy on Polygon Edge (no success so far) and started pulling things apart to examine each step.

**Comment by kclowes** [comment]
Thank you! If you have the time to make a PR, we'd be very grateful!

**Comment by Kaushik-Iyer** [comment]
Can I work on this? I just have to change that particular line in the docs right?
