### ISSUE TITLE
ethers.utils.verifyTypedData equivalent?

### ISSUE THREAD

**Issue by pedrohba1** [ethereum/web3.py#2661]
* Version: 5.30.0
* Python: 3.9
* OS: linux
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### equivalent of verifyTypedData on web3.py doesn't seem to work properly

Using `ethers` there is a simple way to recover the address of a  message signed with EIP-712:

```
    const signature = await signer?._signTypedData(
      msg.domain,
      msg.types,
      msg.value
    );

    // then get the address of the signer
    const verified = ethers.utils.verifyTypedData(
      msg.domain,
      msg.types,
      msg.value,
      signature
    );
    
```

The closest there is to this approach in web3.py is the following:

```
    message = encode_defunct(text=data)
    signerAddress = w3.eth.account.recover_message(message, signature=HexBytes(signature))
```

However, it doesn't seem to work. The `signerAddress` it gets is different from the one that signed it.

When using the `ethers` method I can make the following signature from the following data and verifiy it using the 
`ethers.utils.verifyTypedData` method:

```
//signature
0x24975d961398ef1270e3cf321b09efc153df89f2ce2df194b2d5e887d6d0dd0f383d0c33be5d9fe1c3883e9f2ea81d63d0d8b31604ffa2076f57da1fe988b6be1b
//data

{"domain":{"chainId":80001,"name":"UMC Field","version":"0.0.1"},"value":{"timestamp":1664197717,"dataId":"16"},"types":{"HealthData":[{"name":"timestamp","type":"uint256"},{"name":"dataId","type":"uint256"}]}}

// it can then retrieve the address: 0x3C886715f7C1CF03F91cD3Cf455Bee361eAF76Ea
```

How can I replicate the `ethers.utils.verifyTypedData` in python then?

**Comment by pacrob** [comment]
We do need to update the docs - `encode_defunct` should be avoided if possible.

Because you're using structured data, rather than just bytes, hexstring, etc., you'll want to use `encode_structured_data` from `eth-account`

```python
import eth_account
from eth_account import Account
from eth_account.messages import encode_structured_data

data = {
    "domain": {
        "chainId": 80001,
        "name": "UMC Field",
        "version": "0.0.1",
        },
    "message": {"timestamp": 1664197717, "dataId": 16},
    "primaryType": "HealthData",
    "types": {
	"EIP712Domain": [
		{"name": "name", "type": "string"},
		{"name": "version", "type": "string"},
		{"name": "chainId", "type": "uint256"},
	],
        "HealthData": [
            {"name": "timestamp", "type": "uint256"},
            {"name": "dataId", "type": "uint256"},
        ]
    },
}

account = Account.from_key(my_private_key)
structured_msg = encode_structured_data(data)
signed = Account.sign_message(structured_msg, account.key)
recovered_address = Account.recover_message(structured_msg, signature=signed.signature)
assert recovered_address == account.address
```

**Comment by pedrohba1** [comment]
> We do need to update the docs - `encode_defunct` should be avoided if possible.
> 
> Because you're using structured data, rather than just bytes, hexstring, etc., you'll want to use `encode_structured_data` from `eth-account`
> 
> ```python
> import eth_account
> from eth_account import Account
> from eth_account.messages import encode_structured_data
> 
> data = {
>     "domain": {
>         "chainId": 80001,
>         "name": "UMC Field",
>         "version": "0.0.1",
>         },
>     "message": {"timestamp": 1664197717, "dataId": 16},
>     "primaryType": "HealthData",
>     "types": {
> 	"EIP712Domain": [
> 		{"name": "name", "type": "string"},
> 		{"name": "version", "type": "string"},
> 		{"name": "chainId", "type": "uint256"},
> 	],
>         "HealthData": [
>             {"name": "timestamp", "type": "uint256"},
>             {"name": "dataId", "type": "uint256"},
>         ]
>     },
> }
> 
> account = Account.from_key(my_private_key)
> structured_msg = encode_structured_data(data)
> signed = Account.sign_message(structured_msg, account.key)
> recovered_address = Account.recover_message(structured_msg, signature=signed.signature)
> assert recovered_address == account.address
> ```

I will try that and tell you if it works

**Comment by pedrohba1** [comment]
It worked, however, there are some differences that it might be useful to point out if someone else tries to handle this using ethers.

In ethers, signing it would be the following:

```
const signature = await signer?._signTypedData(
      msg.domain,
      msg.types,
      msg.value
    );
```

It builds the typedData object from a very different format which might be misleading.

After signing using the function above, if you want to verify the signed message in web3.py, you remake the message in the correct format, specifying the `primaryType`, `types.EIP712Domain`  such as:

```js
const chainId = 80001;

    const dataSignature = {
      domain: { chainId, name: "Application", version: "0.0.1" },
      message: { timestamp, dataId },
      primaryType: "CustomData",
      types: {
        EIP712Domain: [
          { name: "name", type: "string" },
          { name: "version", type: "string" },
          { name: "chainId", type: "uint256" },
        ],
        CustomData: [
          { name: "timestamp", type: "uint256" },
          { name: "dataId", type: "string" },
        ],
      },
    };

```

I did this step and it worked

**Comment by DvScripts** [comment]
`clientMessage = "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"OrderComponents\":[{\"name\":\"offerer\",\"type\":\"address\"},{\"name\":\"zone\",\"type\":\"address\"},{\"name\":\"offer\",\"type\":\"OfferItem[]\"},{\"name\":\"consideration\",\"type\":\"ConsiderationItem[]\"},{\"name\":\"orderType\",\"type\":\"uint8\"},{\"name\":\"startTime\",\"type\":\"uint256\"},{\"name\":\"endTime\",\"type\":\"uint256\"},{\"name\":\"zoneHash\",\"type\":\"bytes32\"},{\"name\":\"salt\",\"type\":\"uint256\"},{\"name\":\"conduitKey\",\"type\":\"bytes32\"},{\"name\":\"counter\",\"type\":\"uint256\"}],\"OfferItem\":[{\"name\":\"itemType\",\"type\":\"uint8\"},{\"name\":\"token\",\"type\":\"address\"},{\"name\":\"identifierOrCriteria\",\"type\":\"uint256\"},{\"name\":\"startAmount\",\"type\":\"uint256\"},{\"name\":\"endAmount\",\"type\":\"uint256\"}],\"ConsiderationItem\":[{\"name\":\"itemType\",\"type\":\"uint8\"},{\"name\":\"token\",\"type\":\"address\"},{\"name\":\"identifierOrCriteria\",\"type\":\"uint256\"},{\"name\":\"startAmount\",\"type\":\"uint256\"},{\"name\":\"endAmount\",\"type\":\"uint256\"},{\"name\":\"recipient\",\"type\":\"address\"}]},\"primaryType\":\"OrderComponents\",\"domain\":{\"name\":\"Seaport\",\"version\":\"1.1\",\"chainId\":\"1\",\"verifyingContract\":\"0x00000000006c3852cbEf3e08E8dF289169EdE581\"},\"message\":{\"offerer\":\"0x51663AE5742164944D1bb6cb2785Fdf839666Ed4\",\"offer\":[{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"5000000000000000\",\"endAmount\":\"5000000000000000\"}],\"consideration\":[{\"itemType\":\"4\",\"token\":\"0x458aed4f6f2Af40De88856e414Cf5b49514cbD78\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"1\",\"endAmount\":\"1\",\"recipient\":\"0x51663AE5742164944D1bb6cb2785Fdf839666Ed4\"},{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"125000000000000\",\"endAmount\":\"125000000000000\",\"recipient\":\"0x0000a26b00c1F0DF003000390027140000fAa719\"},{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"500000000000000\",\"endAmount\":\"500000000000000\",\"recipient\":\"0x769c11a5a8Eb2032F149D3B70798a4eEA59C79aA\"}],\"startTime\":\"1665431940\",\"endTime\":\"1665433736\",\"orderType\":\"2\",\"zone\":\"0x004C00500000aD104D7DBd00e3ae0A5C00560C00\",\"zoneHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"salt\":\"24446860302761739304752683030156737591518664810215442929817238635507136356392\",\"conduitKey\":\"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000\",\"totalOriginalConsiderationItems\":\"3\",\"counter\":\"0\"}}";
`

Can anyone tell me how to Sign Message like this ??? tried this from up but not working
