### ISSUE TITLE
PyChain banner on web3py.readthedocs.io

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.py#2665]
### What was wrong?

Python, though a popular programming language, is still underrepresented in blockchain software development. To lift the profile of Python programming in blockchain and introduce blockchain to more Python developers, we are organizing the [PyChain 2022 virtual conference](https://www.pychain.org/). 

We still need to get people to come to the event and spread awareness of the conference. 

### How can it be fixed?

Web3.py is the most popular Python blockchain library. Thus, Web3.py documentation gets a lot of drive-by traffic from developers that are dipping their toes in blockchain development. 

I would like to ask to get a temporary banner on https://web3py.readthedocs.io/ to advertise PyChain 2022 virtual conference. The event is on November 15th and the banner can be removed after this.

The event itself is non-profit. 

If you are open to the idea and find it aligned with the web3.py community and Ethereum Foundation community conduct, I can make a pull request on Sphinx docs, as I have managed several Sphinx docs sites over the years.

**Comment by kclowes** [comment]
Sure, we can put a banner up. A PR would be great, thanks!

**Comment by wolovim** [comment]
documenting context discussed: in this case, we're happy to support a regular contributor by promoting a very related non-profit event. hopefully an appropriately cautious precedent :)

**Comment by miohtama** [comment]
Thank you sers 🙏 - will get the PR and banner for you tomorrow for review

**Comment by miohtama** [comment]
@kclowes @wolovim Made a PR , but looks like CircleCI is complaining about something which is highly likely to be unrelated.

**Comment by fselmo** [comment]
closed via #2670
