### ISSUE TITLE
Allow passing a custom aiohttp.ClientSession for AsyncHTTPProvider

### ISSUE THREAD

**Issue by DefiDebauchery** [ethereum/web3.py#2674]
Traditionally, we use the `request_args=` kwarg for `HTTPProvider` to apply additional setup arguments to the synchronous requests library. 

In AsyncHTTPProvider, those arguments are collected for aiohttp's get and post methods, however, options to ClientSession are [hardcoded](https://github.com/ethereum/web3.py/blob/3d1fd7a8619bb5d64d4fe5a3f32f58f87e148f0b/web3/_utils/request.py#L162) and there's currently no way to inject a custom ClientSession instance (and pardon my lack of knowledge, but in the scope of #2446, if a single ClientSession was defined, would it need to be duplicated in some form?)

For context of my request, Python 3.11 is set to fix a longstanding issue with using TLS-based proxies, which will instantly fix usage with asyncio/aiohttp. While it appears setting the `proxy` key in `request_kwargs` does allow use within each connection request, instantiating a ClientSession with the `trust_env=True` flag would simplify this process for those who want to utilize the proxy connection throughout an entire application. I would not recommend hardcoding it into line referenced above.

We're sorta halfway there with [async_rpc.py#L58](https://github.com/ethereum/web3.py/blob/master/web3/providers/async_rpc.py#L58), just need an external way of passing our own Client in.

cc: @dbfreem @fselmo

**Comment by DefiDebauchery** [comment]
Hello! I've crawled out from under my rock >.> Apologies for the delay.

So can you think of any downsides to simply allowing a `ClientSession` to be passed into `AsyncHTTPProvider`? It _seems_ straightforward enough, but don't have enough context of `_utils.request.async_cache_and_return_session()` on whether that would pose a problem.

**Comment by kovalevvlad** [comment]
This would be great. I also have a suspicion that there is some level of connection leaking going on. I would like to be able to manage the connections myself.

**Comment by fselmo** [comment]
I'm trying to remember the context here since one of the links for the "we're sort of halfway there" comment is broken. This is effectively [implemented here](https://github.com/ethereum/web3.py/blob/main/web3/providers/rpc/async_rpc.py#L71), right @DefiDebauchery? Or are we still missing a desired configuration option? Can this be closed?
