### ISSUE TITLE
encode_structured_data + signTypedData Python

### ISSUE THREAD

**Issue by DvScripts** [ethereum/web3.py#2679]
Hello
i was trying to sign my message with copying code from there :

https://github.com/ethereum/web3.py/issues/2661

and i can't its not working

`clientMessage = "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"OrderComponents\":[{\"name\":\"offerer\",\"type\":\"address\"},{\"name\":\"zone\",\"type\":\"address\"},{\"name\":\"offer\",\"type\":\"OfferItem[]\"},{\"name\":\"consideration\",\"type\":\"ConsiderationItem[]\"},{\"name\":\"orderType\",\"type\":\"uint8\"},{\"name\":\"startTime\",\"type\":\"uint256\"},{\"name\":\"endTime\",\"type\":\"uint256\"},{\"name\":\"zoneHash\",\"type\":\"bytes32\"},{\"name\":\"salt\",\"type\":\"uint256\"},{\"name\":\"conduitKey\",\"type\":\"bytes32\"},{\"name\":\"counter\",\"type\":\"uint256\"}],\"OfferItem\":[{\"name\":\"itemType\",\"type\":\"uint8\"},{\"name\":\"token\",\"type\":\"address\"},{\"name\":\"identifierOrCriteria\",\"type\":\"uint256\"},{\"name\":\"startAmount\",\"type\":\"uint256\"},{\"name\":\"endAmount\",\"type\":\"uint256\"}],\"ConsiderationItem\":[{\"name\":\"itemType\",\"type\":\"uint8\"},{\"name\":\"token\",\"type\":\"address\"},{\"name\":\"identifierOrCriteria\",\"type\":\"uint256\"},{\"name\":\"startAmount\",\"type\":\"uint256\"},{\"name\":\"endAmount\",\"type\":\"uint256\"},{\"name\":\"recipient\",\"type\":\"address\"}]},\"primaryType\":\"OrderComponents\",\"domain\":{\"name\":\"Seaport\",\"version\":\"1.1\",\"chainId\":\"1\",\"verifyingContract\":\"0x00000000006c3852cbEf3e08E8dF289169EdE581\"},\"message\":{\"offerer\":\"0x51663AE5742164944D1bb6cb2785Fdf839666Ed4\",\"offer\":[{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"5000000000000000\",\"endAmount\":\"5000000000000000\"}],\"consideration\":[{\"itemType\":\"4\",\"token\":\"0x458aed4f6f2Af40De88856e414Cf5b49514cbD78\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"1\",\"endAmount\":\"1\",\"recipient\":\"0x51663AE5742164944D1bb6cb2785Fdf839666Ed4\"},{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"125000000000000\",\"endAmount\":\"125000000000000\",\"recipient\":\"0x0000a26b00c1F0DF003000390027140000fAa719\"},{\"itemType\":\"1\",\"token\":\"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"500000000000000\",\"endAmount\":\"500000000000000\",\"recipient\":\"0x769c11a5a8Eb2032F149D3B70798a4eEA59C79aA\"}],\"startTime\":\"1665431940\",\"endTime\":\"1665433736\",\"orderType\":\"2\",\"zone\":\"0x004C00500000aD104D7DBd00e3ae0A5C00560C00\",\"zoneHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"salt\":\"24446860302761739304752683030156737591518664810215442929817238635507136356392\",\"conduitKey\":\"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000\",\"totalOriginalConsiderationItems\":\"3\",\"counter\":\"0\"}}";
`

JSON FORMAT:

```
{
    'types': {
        'EIP712Domain': [{
                'name': 'name',
                'type': 'string'
            }, {
                'name': 'version',
                'type': 'string'
            }, {
                'name': 'chainId',
                'type': 'uint256'
            }, {
                'name': 'verifyingContract',
                'type': 'address'
            }
        ],
        'OrderComponents': [{
                'name': 'offerer',
                'type': 'address'
            }, {
                'name': 'zone',
                'type': 'address'
            }, {
                'name': 'offer',
                'type': 'OfferItem[]'
            }, {
                'name': 'consideration',
                'type': 'ConsiderationItem[]'
            }, {
                'name': 'orderType',
                'type': 'uint8'
            }, {
                'name': 'startTime',
                'type': 'uint256'
            }, {
                'name': 'endTime',
                'type': 'uint256'
            }, {
                'name': 'zoneHash',
                'type': 'bytes32'
            }, {
                'name': 'salt',
                'type': 'uint256'
            }, {
                'name': 'conduitKey',
                'type': 'bytes32'
            }, {
                'name': 'counter',
                'type': 'uint256'
            }
        ],
        'OfferItem': [{
                'name': 'itemType',
                'type': 'uint8'
            }, {
                'name': 'token',
                'type': 'address'
            }, {
                'name': 'identifierOrCriteria',
                'type': 'uint256'
            }, {
                'name': 'startAmount',
                'type': 'uint256'
            }, {
                'name': 'endAmount',
                'type': 'uint256'
            }
        ],
        'ConsiderationItem': [{
                'name': 'itemType',
                'type': 'uint8'
            }, {
                'name': 'token',
                'type': 'address'
            }, {
                'name': 'identifierOrCriteria',
                'type': 'uint256'
            }, {
                'name': 'startAmount',
                'type': 'uint256'
            }, {
                'name': 'endAmount',
                'type': 'uint256'
            }, {
                'name': 'recipient',
                'type': 'address'
            }
        ]
    },
    'primaryType': 'OrderComponents',
    'domain': {
        'name': 'Seaport',
        'version': '1.1',
        'chainId': '1',
        'verifyingContract': '0x00000000006c3852cbEf3e08E8dF289169EdE581'
    },
    'message': {
        'offerer': '0x51663AE5742164944D1bb6cb2785Fdf839666Ed4',
        'offer': [{
                'itemType': '1',
                'token': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
                'identifierOrCriteria': '0',
                'startAmount': '5000000000000000',
                'endAmount': '5000000000000000'
            }
        ],
        'consideration': [{
                'itemType': '4',
                'token': '0x458aed4f6f2Af40De88856e414Cf5b49514cbD78',
                'identifierOrCriteria': '0',
                'startAmount': '1',
                'endAmount': '1',
                'recipient': '0x51663AE5742164944D1bb6cb2785Fdf839666Ed4'
            }, {
                'itemType': '1',
                'token': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
                'identifierOrCriteria': '0',
                'startAmount': '125000000000000',
                'endAmount': '125000000000000',
                'recipient': '0x0000a26b00c1F0DF003000390027140000fAa719'
            }, {
                'itemType': '1',
                'token': '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
                'identifierOrCriteria': '0',
                'startAmount': '500000000000000',
                'endAmount': '500000000000000',
                'recipient': '0x769c11a5a8Eb2032F149D3B70798a4eEA59C79aA'
            }
        ],
        'startTime': '1665431940',
        'endTime': '1665433736',
        'orderType': '2',
        'zone': '0x004C00500000aD104D7DBd00e3ae0A5C00560C00',
        'zoneHash': '0x0000000000000000000000000000000000000000000000000000000000000000',
        'salt': '24446860302761739304752683030156737591518664810215442929817238635507136356392',
        'conduitKey': '0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000',
        'totalOriginalConsiderationItems': '3',
        'counter': '0'
    }
}
```

```
Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    structured_msg = encode_structured_data(json.loads(clientMessage))
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\messages.py", line 152, in encode_structured_data
    hash_domain(structured_data),
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 281, in hash_domain
    encode_data(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 267, in encode_data
    data_types_and_hashes = _encode_data(primaryType, types, data)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 254, in _encode_data
    raise TypeError(
TypeError: Value of `chainId` (1) in the struct `EIP712Domain` is of the type `<class 'str'>`, but expected uint256 value
```

Can anyone tell me how to Sign Message like this ??? tried this from up but not working, i need it in Python

**Comment by fselmo** [comment]
This is the error you are getting: 

```py
TypeError: Value of `chainId` (1) in the struct `EIP712Domain` is of the type `<class 'str'>`, but expected uint256 value
```

Please use the integer `1` instead of the string `"1"` for the `chainId` value.

**Comment by DvScripts** [comment]
Ok when i changed this now i have ->

```
Traceback (most recent call last):
  File "<pyshell#49>", line 1, in <module>
    structured_msg = encode_structured_data(data)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\messages.py", line 156, in encode_structured_data
    hash_eip712_message(structured_data),
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 260, in hash_message
    encode_data(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 230, in encode_data
    type, value = encode_field(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 196, in encode_field
    field_type_value_pairs = [
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 197, in <listcomp>
    encode_field(types, name, field_type_of_inside_array, item)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 157, in encode_field
    return ('bytes32', keccak(encode_data(field_type, types, value)))
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 230, in encode_data
    type, value = encode_field(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 218, in encode_field
    raise TypeError(
TypeError: Value of `itemType` (1) is not encodable as type `uint8`. If the base type is correct, verify that the value does not exceed the specified size for the type.
```

**Comment by fselmo** [comment]
All of your error messages are telling you what the errors are. Your `itemType` values are strings and need to be integers as well.

<img width="524" alt="Screen Shot 2022-10-12 at 18 05 47" src="https://user-images.githubusercontent.com/3532824/195463810-b37f9667-9133-4c07-b641-17f7088ea0a0.png">

I'm going to close this ticket as I don't see a bug with the library but I encourage you to join the [Discord](https://discord.gg/GHryRvPB84) for any usage questions. There's a great community there that are always willing to help. Best of luck!

**Comment by DvScripts** [comment]
> All of your error messages are telling you what the errors are. Your `itemType` values are strings and need to be integers as well.
> 
> <img alt="Screen Shot 2022-10-12 at 18 05 47" width="524" src="https://user-images.githubusercontent.com/3532824/195463810-b37f9667-9133-4c07-b641-17f7088ea0a0.png">
> 
> I'm going to close this ticket as I don't see a bug with the library but I encourage you to join the [Discord](https://discord.gg/GHryRvPB84) for any usage questions. There's a great community there that are always willing to help. Best of luck!

Hey, i changed then into int, it won't help anyway, can You try to SIGN this code and check Yourself??
