### ISSUE TITLE
how to print the privatekey?

### ISSUE THREAD

**Issue by viponedream** [ethereum/web3.py#2698]
Account.enable_unaudited_hdwallet_features()
    acct, mnemonic = Account.create_with_mnemonic()
    addr = acct.address  
    privatekey = acct.key
    print(acct, addr, privatekey, mnemonic)

the privatekey is not str? how to  convert to str?
please, tks.

i want import the acct.key into metamask.

**Comment by kclowes** [comment]
This is a usage question and better suited for our [Discord channel](https://discord.gg/GHryRvPB84), but you can use `acct.key.hex()` or `bytes(acct.key)`, depending on the format you need.
