### ISSUE TITLE
Tuple always gives error

### ISSUE THREAD

**Issue by laozhang713** [ethereum/web3.py#2701]
I need to construct an openPosition like this

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/63301201/199087435-6277b605-cabe-40a8-bde1-173e083f09ce.png">

Part of my code (sorry for newbies):

`params_baseToken='0x8C835DFaA34e2AE61775e80EE29E2c724c6AE2BB'
	params_amount=100000000000000000000 #100usdc
	params_oppositeAmountBound=account_value
	params_deadline=115792089237316195423570985008687907853269984665640564039457584007913129639935
	params_sqrtPriceLimitX96=0
	params_referralCode='0x0000000000000000000000000000000000000000000000000000000000000000'
	params_tijiao = [params_baseToken,0,1,params_amount,params_oppositeAmountBound,params_deadline,params_sqrtPriceLimitX96,params_referralCode]
	params_tijiao_1=[]
	params_tijiao_1.append(params_tijiao)
	params_tijiao=tuple(params_tijiao_1)
	#params_tijiao=(['0x8C835DFaA34e2AE61775e80EE29E2c724c6AE2BB', 100000000000000000000, 0, 0, 62980813401241784, 115792089237316195423570985008687907853269984665640564039457584007913129639935, 0, '0x0000000000000000000000000000000000000000000000000000000000000000'])
	print(params_tijiao)
        token_contract = web3.eth.contract(address=Web3.toChecksumAddress(contract_address), abi=json.loads(contract_abi))
	func = token_contract.functions.openPosition(params_tijiao)
.............
`

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63301201/199087851-2ef1c8a1-62d3-4d1b-87b6-dac0f667f37f.png">

But I can submit it like this in the browser.
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/63301201/199087946-aabf80b3-1ea9-4736-8c30-6b069c67ce06.png">

Sorry again, I really don't know how to submit this tuple

**Comment by fselmo** [comment]
We like to use issues to track our work. Please refer to the [discord](https://discord.gg/GHryRvPB84) for usage questions. I'd be glad to help you out over there and if we find a bug I will re-open this issue. Best of luck.
