### ISSUE TITLE
estimate_gas(transaction) give error "caller is not the owner"

### ISSUE THREAD

**Issue by Shinwari536** [ethereum/web3.py#2710]
* Version: latest
* Python: 3.7
* OS: Linux

I am trying to run the estimate_gas() function, by following official docs, the link is following:
https://web3py.readthedocs.io/en/v5/contracts.html?highlight=estimategas#web3.contract.ContractFunction.estimateGas:~:text=ContractFunction.estimate_gas

But there is one thing to **note**, the function in my contract is onlyOwner. It means only the owner can execute this function.

So, can anyone suggest to me, how to estimate the gas amount required to execute an onlyOwner method of the contract?
Thanks in advance.

**Comment by reedsa** [comment]
Hello @Shinwari536 , apologies for the lack of response here! Hopefully you were able to find a solution for estimating gas with legacy transactions. As I understand it, estimate gas would only work as the owner of the contract.
