### ISSUE TITLE
'xdc' prefixed addresses are not supported in web3.eth API methods

### ISSUE THREAD

**Issue by shirsom** [ethereum/web3.py#2717]
* Version: 5.22.0
* Python: 3.8
* OS: linux

### What was wrong?

Calling web3.eth API methods for XDC transactions fail as the addresses are prefixed with 'xdc' rather than '0x'.
For example, web3.eth.getTransaction({hash}) returns
ValueError: Could not format invalid value '{xdc_prefixed_address}' as field 'from'

### How can it be fixed?

Support for 'xdc' prefixes

**Comment by kclowes** [comment]
It looks like XDC is another blockchain, and we really only support Ethereum. I haven't checked this, but you may be able to bypass some validation with some custom middleware and/or by using raw call/send_transaction calls. Closing as won't fix.
