### ISSUE TITLE
To get a public variable from a contract?

### ISSUE THREAD

**Issue by Clayfigure** [ethereum/web3.py#2741]
I know that there is a way to call public functions in smart contracts from web3.py.
I wonder if there's a way to call public variable？

For example, here's my contract, how can i get the variable number?
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;
contract FunctionTypes{
    uint256 public number = 5;
    
    constructor() payable {}
}

**Comment by pacrob** [comment]
We use github issues for problems with the library itself. For usage questions, please check out our [discord](https://discord.gg/GHryRvPB84).
