### ISSUE TITLE
having issues installing this on a new windows 11 computer

### ISSUE THREAD

**Issue by mattjaf** [ethereum/web3.py#2742]
* Version: latest
* Python: 3.11
* OS: windows 11
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

PS C:\Users\mattj> pip install web3 --user
Collecting web3
  Downloading web3-5.31.2-py3-none-any.whl (501 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 501.8/501.8 kB 1.9 MB/s eta 0:00:00
Collecting aiohttp<4,>=3.7.4.post0
  Downloading aiohttp-3.8.3-cp311-cp311-win_amd64.whl (317 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 kB 1.5 MB/s eta 0:00:00
Collecting eth-abi<3.0.0,>=2.0.0b6
  Downloading eth_abi-2.2.0-py3-none-any.whl (28 kB)
Collecting eth-account<0.6.0,>=0.5.9
  Downloading eth_account-0.5.9-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 5.7 MB/s eta 0:00:00
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0
  Downloading eth_hash-0.5.1-py3-none-any.whl (9.0 kB)
Collecting eth-rlp<0.3
  Downloading eth_rlp-0.2.1-py3-none-any.whl (5.0 kB)
Collecting eth-typing<3.0.0,>=2.0.0
  Downloading eth_typing-2.3.0-py3-none-any.whl (6.2 kB)
Collecting eth-utils<2.0.0,>=1.9.5
  Downloading eth_utils-1.10.0-py3-none-any.whl (24 kB)
Collecting hexbytes<1.0.0,>=0.1.0
  Downloading hexbytes-0.3.0-py3-none-any.whl (6.4 kB)
Collecting ipfshttpclient==0.8.0a2
  Downloading ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.6/82.6 kB 4.8 MB/s eta 0:00:00
Collecting jsonschema<5,>=3.2.0
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB ? eta 0:00:00
Collecting lru-dict<2.0.0,>=1.1.6
  Downloading lru-dict-1.1.8.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting protobuf==3.19.5
  Downloading protobuf-3.19.5-py2.py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.7/162.7 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\mattj\appdata\roaming\python\python311\site-packages (from web3) (2.28.1)
Collecting websockets<10,>=9.1
  Downloading websockets-9.1.tar.gz (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pywin32>=223
  Downloading pywin32-305-cp311-cp311-win_amd64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 2.7 MB/s eta 0:00:00
Collecting multiaddr>=0.0.7
  Downloading multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Collecting attrs>=17.3.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\mattj\appdata\roaming\python\python311\site-packages (from aiohttp<4,>=3.7.4.post0->web3) (2.1.1)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 2.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.1.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp311-cp311-win_amd64.whl (32 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting parsimonious<0.9.0,>=0.8.0
  Downloading parsimonious-0.8.1.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting bitarray<3,>=1.2.1
  Downloading bitarray-2.6.0.tar.gz (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.8/102.8 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting eth-keyfile<0.6.0,>=0.5.0
  Downloading eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting eth-keys<0.4.0,>=0.3.4
  Downloading eth_keys-0.3.4-py3-none-any.whl (21 kB)
Collecting rlp<3,>=1.0.0
  Downloading rlp-2.0.1-py2.py3-none-any.whl (20 kB)
Collecting pycryptodome<4,>=3.6.6
  Downloading pycryptodome-3.16.0-cp35-abi3-win_amd64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.1 MB/s eta 0:00:00
Collecting eth-utils<2.0.0,>=1.9.5
  Downloading eth_utils-1.9.5-py3-none-any.whl (23 kB)
Collecting cytoolz<1.0.0,>=0.10.1
  Downloading cytoolz-0.12.0.tar.gz (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.8/502.8 kB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.19.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in c:\users\mattj\appdata\roaming\python\python311\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mattj\appdata\roaming\python\python311\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mattj\appdata\roaming\python\python311\site-packages (from requests<3.0.0,>=2.16.0->web3) (2022.9.24)
Collecting toolz>=0.8.0
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 2.8 MB/s eta 0:00:00
Collecting varint
  Downloading varint-1.0.2.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting base58
  Downloading base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting netaddr
  Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.4 MB/s eta 0:00:00
Building wheels for collected packages: cytoolz, multidict, yarl
  Building wheel for cytoolz (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cytoolz (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      [1/5] Cythonizing cytoolz/utils.pyx
      [2/5] Cythonizing cytoolz/dicttoolz.pyx
      [3/5] Cythonizing cytoolz/functoolz.pyx
      [4/5] Cythonizing cytoolz/itertoolz.pyx
      [5/5] Cythonizing cytoolz/recipes.pyx
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\compatibility.py -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\_signatures.py -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\_version.py -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\__init__.py -> build\lib.win-amd64-cpython-311\cytoolz
      creating build\lib.win-amd64-cpython-311\cytoolz\curried
      copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-cpython-311\cytoolz\curried   
      copying cytoolz\curried\operator.py -> build\lib.win-amd64-cpython-311\cytoolz\curried     
      copying cytoolz\curried\__init__.py -> build\lib.win-amd64-cpython-311\cytoolz\curried     
      copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\functoolz.pyx -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\recipes.pyx -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\utils.pyx -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\cpython.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\functoolz.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\recipes.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\utils.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      copying cytoolz\__init__.pxd -> build\lib.win-amd64-cpython-311\cytoolz
      creating build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-cpython-311\cytoolz\tests    
      copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-cpython-311\cytoolz\tests     
      copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-cpython-311\cytoolz\tests   
      copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-cpython-311\cytoolz\tests  
      copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-cpython-311\cytoolz\tests    
      copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-cpython-311\cytoolz\tests   
      copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-cpython-311\cytoolz\tests   
      copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-cpython-311\cytoolz\tests   
      copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-cpython-311\cytoolz\tests     
      copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-cpython-311\cytoolz\tests  
      copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-cpython-311\cytoolz\tests
      copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-cpython-311\cytoolz\tests       
      UPDATING build\lib.win-amd64-cpython-311\cytoolz/_version.py
      set build\lib.win-amd64-cpython-311\cytoolz/_version.py to '0.12.0'
      running build_ext
      building 'cytoolz.dicttoolz' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cytoolz
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-311\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution      
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\mattj\AppData\Local\Temp\pip-build-env-6izup6yf\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'multidict._multilib' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'multidict._multilib' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'multidict._multilib' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'multidict._multilib' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-311\multidict
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
  Building wheel for yarl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      C:\Users\mattj\AppData\Local\Temp\pip-build-env-gpbl69yw\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_py.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_url.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\__init__.py -> build\lib.win-amd64-cpython-311\yarl
      running egg_info
      writing yarl.egg-info\PKG-INFO
      writing dependency_links to yarl.egg-info\dependency_links.txt
      writing requirements to yarl.egg-info\requires.txt
      writing top-level names to yarl.egg-info\top_level.txt
      reading manifest file 'yarl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution      
      warning: no previously-included files matching '*.cache' found anywhere in distribution    
      warning: no previously-included files found matching 'yarl\*.html'
      warning: no previously-included files found matching 'yarl\*.so'
      warning: no previously-included files found matching 'yarl\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info\SOURCES.txt'
      copying yarl\__init__.pyi -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_c.pyi -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_c.pyx -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\py.typed -> build\lib.win-amd64-cpython-311\yarl
      running build_ext
      building 'yarl._quoting_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
colorama           0.4.6
idna               3.4
mypy-extensions    0.4.3pathspec           0.10.2
pip                22.3.1
platformdirs       2.5.4
py-solc-x          1.1.1
requests           2.28.1
semantic-version   2.10.0
setuptools         65.5.0
urllib3            1.26.13
PS C:\Users\mattj>

### How can it be fixed?

working on a solution,

i just realized the output said I need "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

I thought that was included in node.js

![image](https://user-images.githubusercontent.com/5776918/205197704-2bc8a211-d343-4feb-b2f1-9ac7e063fa23.png)

---

**Comment by mattjaf** [comment]
If you get an error with something like:

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"

You’ll have to do the following:

Download and install the [Build Tools for Visual Studio](https://visualstudio.microsoft.com/visual-cpp-build-tools/), and then install the `C++ build tools`. Once installed, run the following command in your terminal. [Here is a video tutorial showing you how to install the build tools.](https://www.youtube.com/watch?v=rcI1_e38BWs)

pip install --upgrade setuptools

**Comment by fselmo** [comment]
@mattjaf correct. Glad you were able to get around it. We have [a section](https://web3py.readthedocs.io/en/latest/troubleshooting.html#why-am-i-getting-visual-c-or-cython-not-installed-error) in our docs dedicated to this error as well.
