### ISSUE TITLE
How can web3.py add socks dynamic proxy

### ISSUE THREAD

**Issue by JLX120** [ethereum/web3.py#2750]
Hello, when I use web3.py, the IP address is blocked. How can I add socks dynamic proxy
from web3 import Web3
w3 = Web3(Web3.HTTPProvider("https://bsc-dataseed.binance.org/"))
print(w3.isConnected())
![image](https://user-images.githubusercontent.com/65143776/206191781-25f7a763-fada-4dbd-8f72-086e3c87b028.png)

**Comment by fselmo** [comment]
We use issues to track issues with out library. I see you already found the Discord. That's a good place to ask usage questions.

**Comment by sinarezaei** [comment]
You can use my library untill it is merged into web3py

https://github.com/sinarezaei/web3-proxy-providers

While it does not support dynamic/rotating proxies yet, it supports proxies socks and http proxies for both websocket and http json-rpc connections, You can do some minor changes to add a rotating/dynamic proxy settings in the code
