### ISSUE TITLE
python3.11    setup.py install for lru-dict ... error

### ISSUE THREAD

**Issue by viponedream** [ethereum/web3.py#2776]
Running setup.py install for lru-dict ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lru-dict did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lru-dict

**Comment by kclowes** [comment]
>  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Looks like you need to install Microsoft Visual C++ 14.0 or greater. See the [troubleshooting section](https://web3py.readthedocs.io/en/v5/troubleshooting.html?#why-am-i-getting-visual-c-or-cython-not-installed-error) here.
