### ISSUE TITLE
How can I do `abi.encode()` in Web3.py similar to the encoding in solidity

### ISSUE THREAD

**Issue by FaizanNehal** [ethereum/web3.py#2782]
Currently I am using the `encode` function from `eth_abi` but I somehow my value is not working when I am passing it into my test. I have tested it directly, the solidity function is working fine but it does seem to accept the encoded value that I am passing from python using `encode` from `eth_abi`. I am relatively new to Web3.py and brownie and I can't seem to figure out a way, there wasn't anything in the documentation also. That's why I am asking it here.

So I am encoding my address using web3.py and the output that I getting is:
```
00000000000000000000000033a4622b82d4c04a53e170c638b944ce27cffce3
```

But encoding the same address in solidity is giving me:
```
0x00000000000000000000000033a4622b82d4c04a53e170c638b944ce27cffce3
```

I know there is a difference of `0x`, but I think maybe because of this it is throwing an error. Whenever I am using the Web3.py encoding I can't seem to make it work and I am not able to find any resource on how to mitigate the issue or make it work. It would be very helpful if you can help me.

**Comment by fselmo** [comment]
@FaizanNehal We use the github issues to track issues with the library, please check out the [Discord](https://discord.gg/GHryRvPB84) for usage questions. I, or someone else, would be happy to answer there.
