### ISSUE TITLE
function get_block tranactions is not in the current block

### ISSUE THREAD

**Issue by zilongliang** [ethereum/web3.py#2800]
I want to synchronize all transactions with the database, so I use get_ Block method. The code is as follows：

    cur_block_num = web3.eth.get_block_number()
    if cur_block_num <= last_block_num:
        return
    res = web3.eth.get_block(cur_block_num, full_transactions=True)
    block_info = json.loads(web3.toJSON(res))
    block_info = convert_numeric_to_str(block_info)
    transactions = block_info.pop('transactions')
    db["block_info"].insert_one(block_info)

but When I get all the transactions in block 16498524, I eventually include the transactions in other blocks. Why is this, and sometimes it is normal? Is my method wrong? Have I got the transactions to be processed? Or is the node alchemy I use now returning the wrong value?

**Comment by fselmo** [comment]
Hey @zilongliang, our issues are used to track our work and bugs within `web3.py`. This doesn't look like a bug with the library - but if you believe that it is, please add more detail and we should re-open this. For usage questions I will link to the [Ethereum Python Community Discord](https://discord.gg/GHryRvPB84). There's a growing community there that is always willing to help out. Best of luck.
