### ISSUE TITLE
web3 can't install  No module named 'setuptools'

### ISSUE THREAD

**Issue by viponedream** [ethereum/web3.py#2801]
ubuntu20.01   python3.11

apt-get install -y python3-setuptools
pip uninstall web3
pip install git+https://github.com/ethereum/web3.py.git

No module named 'setuptools'

i have try the python 3.10 can install well, 
anyone can use python3.11 with web3?

**Comment by MT-Cash** [comment]
Have you tried `pip install --upgrade pip setuptools wheel`?

**Comment by viponedream** [comment]
> 

after use this command  pip install --upgrade pip setuptools wheel
same issue
