### ISSUE TITLE
Building a transaction to be signed elsewhere

### ISSUE THREAD

**Issue by lowercase00** [ethereum/web3.py#2812]
Docs mention the `send_raw_transaction` method should be used when you want to sign the transaction elsewhere, so at this point, one wouldn't have the private key just yet.

However, when going through the method docs, this delegates to `eth_sendRawTransaction` RPC method, which has the description:

> Sends a signed and serialized transaction. Returns the transaction hash as a HexBytes object.

Also, the example of usage includes the `private_key` meaning at this stage one would have all information necessary to sign it.

I wonder if there's a way to build the transaction and then have someone else to sign it.
I would imagine this would just convert an existing (unsigned) transaction object to a `RLP` object or something.

Ideas?

**Comment by kclowes** [comment]
You can use the `build_transaction` method. See the docs [here](https://web3py.readthedocs.io/en/v5/web3.eth.account.html?#sign-a-contract-transaction). We prefer to use issues to track bugs and feature requests. This question is better suited to the discord channel. You can join via [this link](https://discord.gg/GHryRvPB84).
