### ISSUE TITLE
I am wondering if there is an option to run tests on CI with `4` field elements e.g. by overriding the parameter while use minimal presets for test vectors generation?

### ISSUE THREAD

**Issue by KuliHaHa** [ethereum/web3.py#2818]
I am wondering if there is an option to run tests on CI with `4` field elements e.g. by overriding the parameter while use minimal presets for test vectors generation?

_Originally posted by @mkalinin in https://github.com/ethereum/consensus-specs/issues/3255#issuecomment-1433445555_

**Comment by kclowes** [comment]
Spam
