### ISSUE TITLE
Add async eth.modify_transaction

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2825]
### What was wrong?

Some methods are still unavailable on the `AsyncEth` class.

### How can it be fixed?

Following the pattern already established, add `modify_transaction` to the AsyncEth class, and add corresponding tests. The `AsyncHTTPProvider` docs in `docs/provider.rst` will also need to be updated.

**Comment by ketan3108** [comment]
Hey @kclowes ,I am interested in contributing. Can you guide me by providing some references ?

**Comment by esing1201** [comment]
Hi @kclowes I am happy to claim this issue!

**Comment by kclowes** [comment]
Thanks @esing1201! Here is the most recent example of a new async function that's been merged: #2848. The `replace_transaction` PR might also be helpful: #2847.
