### ISSUE TITLE
Add async eth.sign

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2826]
### What was wrong?

Some methods are still unavailable on the `AsyncEth` class.

### How can it be fixed?

Following the pattern already established, add the `sign` method to the `AsyncEth` class, and add corresponding tests. The `AsyncHTTPProvider` docs in `docs/provider.rst` will also need to be updated.

**Comment by e3243eric** [comment]
I would like to work on this issue. I will make a PR for it this week.

**Comment by sujantkumarkv** [comment]
I guess the changes were merged. I then suggest closing this issue. Thanks :)
@kclowes

**Comment by fselmo** [comment]
closed by #2833
