### ISSUE TITLE
Add async eth.sign_typed_data

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2828]
### What was wrong?

Some methods are still unavailable on the `AsyncEth` class.

### How can it be fixed?

Following the pattern already established, add `sign_typed_data` to the `AsyncEth` class, and add corresponding tests. The `AsyncHTTPProvider` docs in `docs/provider.rst` will also need to be updated.

**Comment by abishekdharshan** [comment]
Completed, let me know if this suffices!

**Comment by panganchaoren** [comment]
wow

**Comment by sujantkumarkv** [comment]
Hey! there.
I request update on this. Is it done? Or it needs help?

@kclowes @abishekdharshan @panganchaoren

**Comment by ayamba-coder** [comment]
Is this issues resolved already?
