### ISSUE TITLE
Parity tracing should be renamed and not removed

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#2830]
* Version: 6alpha
* Python: 3.10
* OS: linux

### What was wrong?

On commit ff3e0238970358ea089dbde3e1b34e9581498b36 Parity related tracing was removed, and even if **Parity** does not exist anymore **Nethermind** and **Erigon** continue to support **Parity** style traces (even  `ParityFilterParams` for `trace_filter`), this API is still used and critical for example for the Safe wallet operations.

### How can it be fixed?

- Rename `web3.parity` to `web3.trace`
- Parity types renamed, `ParityFilterParams` -> `TraceFilterParams`, `ParityFilterTrace` -> `TraceFilterTrace`, `ParityBlockTrace` -> `TraceBlockTrace`...

**Comment by kclowes** [comment]
Thanks for the report @Uxio0. We'll put it in our backlog!

**Comment by Uxio0** [comment]
Thank you very much @kclowes , if you need a PR I can also contribute

**Comment by kclowes** [comment]
That would be awesome! And probably be the fastest way to get something in :) We'd be happy to review.

**Comment by Uxio0** [comment]
Hi @kclowes , just added back the methods and renamed them: https://github.com/ethereum/web3.py/pull/2851
