### ISSUE TITLE
Pure Python Implementation Of Raw Transaction Signing

### ISSUE THREAD

**Issue by detherminal** [ethereum/web3.py#2852]
Hi! I want to use ethereum's raw transaction signing function in [my project](https://github.com/detherminal/seruro) but this library becomes too complicated for a Raspberry Pi Pico, I just want the raw transaction signing function. So can anybody show me a way to just sign a transaction as in the example:
```
tx = {
        "nonce": nonce,
        "to": recipient,
        "value": web3.toWei(amount, "ether"),
        'gas': 2000000,
        'gasPrice': web3.toWei('50', 'gwei')
}
signed = rawsigntransaction(tx)
```
In here I just need a pure implementation of rawsigntransaction. Can you show me a way to how to do it?

**Comment by fselmo** [comment]
Hey @detherminal, this is a good question for the [Discord](https://discord.gg/GHryRvPB84). We like to use our issues to track issues with the library.
