### ISSUE TITLE
Deprecate `miner` namespace support and tests

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#2856]
### What was wrong?

Geth removed support for their `miner` API since it's no longer needed after The Merge ™️ . See: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-miner

### How can it be fixed?

Add deprecation warnings to the methods within the miner namespace, and change the tests to check for the deprecation warnings. We can then either remove the methods as Geth stops supporting these, or wait until v7 to remove.

**Comment by fselmo** [comment]
closed by #3236 (`v7`) and #3238 (`v6`)

**Comment by molecula451** [comment]
what about chains that do still support "miner"
