### ISSUE TITLE
Bump pytest version

### ISSUE THREAD

**Issue by pacrob** [ethereum/web3.py#2859]
Running pytest using python3.10, I see:

`DeprecationWarning: You're using an outdated version of pytest. Newer releases of pytest-asyncio will not be compatible with this pytest version. Please update pytest to version 7 or later.`

`pytest --version` yields `pytest 6.2.5`. It looks like pytest 7 still supports python 3.7.

**Comment by kclowes** [comment]
Closed via #2863
