### ISSUE TITLE
Alias camelCase toHex, toChecksumAddress, etc. to make Web3 6.0 migration less painful

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.py#2862]
* Version:6.0

### What was wrong?

Currently there is no migration period for snake casing some of the functions

* toChecksumAddress
* solidityKeccak
* processRecept
* etc.

This will make Web3 5.0 -> 6.0 upgrade unnecessary painful, because it breaks the existing code without allowing gracefully to migrate to  new function naming.

### How can it be fixed?

Add a stub wrapper functions that just 

- Call the snake case function
- Emit deprecation warning

**Comment by kclowes** [comment]
Thanks @miohtama! I think we got them all.
