### ISSUE TITLE
future transaction tries to replace pending

### ISSUE THREAD

**Issue by SongChao160609** [ethereum/web3.py#2903]
* Version: 5.31.4
* Python: 3.8
* OS: osx
* `pip freeze` output
error: {-32000, future transaction tries to replace pending}
我同时向 eth 发送了 2 个带有 nonce 0 和 1 的 tx，节点返回了这个错误，为什么？

**Comment by fselmo** [comment]
This needs more information. This message is also coming from the node not the library. Please add more information if you think this is a bug and I'd be happy to re-open. On a hunch, make sure your `nonce` is not the same for both transactions.

If you'd like help debugging, places like the [Python Ethereum Community Discord](https://discord.gg/GHryRvPB84) would be a good start. Best of luck.

**Comment by SongChao160609** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
