### ISSUE TITLE
How can I put comments(Remark) into a transaction?

### ISSUE THREAD

**Issue by yingshaoxo** [ethereum/web3.py#2906]
Because I think when we do a money transaction, it is a good habit to leave a message.

I couldn't find it in `sign_transaction()` and `send_transaction()` function.

The most similar thing I see is `input_data`. But it seems to be wired since I use utf-8 to encode it, but can't get it back in the same way.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/17190829/230583978-88707c0c-34c4-4174-a3a4-23a3eca7c5e4.png">

Is there a way to decode that message without using `scaner exploer` like this one? https://testnet.bscscan.com/tx/0x8f17b4586a0713bfc19d930ee971ba7373a33398b2c077f1ef8b71eef15c1ec9

**Comment by fselmo** [comment]
Hey @yingshaoxo, we try to use the issues here to keep track of issues with the library. For usage questions, please refer to documentation and there's a great community over on the [Ethereum Python Community Discord](https://discord.gg/GHryRvPB84) that is also a great place to ask usage questions. Best of luck.
