### ISSUE TITLE
web3.datastructures.AttributeDict.__hash__ fails if event logs contain list objects

### ISSUE THREAD

**Issue by JustCallMeDavid** [ethereum/web3.py#2908]
* Version: 5.31.1
* Python: 3.8
* OS: linux
* pip freeze output omitted since not a package specific issue

### What was wrong?

Note: Not exactly an issue but something I had to circumvent myself when using the library and thinking it may be helpful if `web3.py` handled it instead directly.

I was trying to use functions requiring `__hash__` on event logs and the code failed saying lists are not hashable [here](https://github.com/ethereum/web3.py/blob/402d001b4f0a19720d859efe3c9e0ece39168224/web3/datastructures.py#L117). This happens if the event logs contain `list` objects nested inside them (which some smart contracts seem to return), as lists by default are mutable and thus not hashable in Python.

### How can it be fixed?

Would it make sense to (possibly recursively) cast any present lists to tuples inside the hash function to avoid crashes? Would some detection mechanism inside these pseudo-immutable classes be helpful to make sure they are indeed hashable (e.g., raising an error if a list is added)?

Any thoughts?

**Comment by pacrob** [comment]
I think that since it's already casting it to a tuple, recursively tupelizing  the whole thing would be fine. We'd also need to preserve the sorting.

If you have the time to put in a PR, that would be great! Otherwise I'll take further look later.

**Comment by JustCallMeDavid** [comment]
Thank you @pacrob, I agree.

Was thinking of adding an additional class simulating immutable lists similar to the already present `AttributeDict` logic, but I believe that would bring unneeded complexity and little practical benefit. I think the simplest approach would be to leave the lists as is, but only convert them recursively to tuples inside the hash checks, with preserved sorting, so that those will not crash anymore.
If you have any thoughts feel free to let me know, otherwise I would proceed with implementation.

Give me some time (~2 weeks), I will put in a small PR.

**Comment by JustCallMeDavid** [comment]
Hi @pacrob, created the PR ![here](https://github.com/ethereum/web3.py/pull/2939).  Please feel free to have a look.
