### ISSUE TITLE
Show failure reason for `BaseProvider.is_connected()`

### ISSUE THREAD

**Issue by antazoey** [ethereum/web3.py#2910]
* Version: 6.0.0
* Python: 3.10
* OS: macky whacky
* `pip freeze`

```
ill provide if needed
```

### What was wrong?

This line right here officer: https://github.com/ethereum/web3.py/blob/master/web3/providers/base.py#L115
It failed on me, but it didn't tell me why.

**Also, note that `assert` statements in production python code get swept-out when global `__debug__` is set to `False`.**

This whole `assert` line should be a raised exception imo.

### How can it be fixed?

Raise an exception with `error` in the message.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by pacrob** [comment]
I put up an approach in #2912. Adding the flag will allow us to preserve backwards compatibility. Would something like that meet your needs?

**Comment by unparalleled-js** [comment]
re: backwards compat, those `assert` statements would raise exceptions in most dev environments.

but ya, this is definitely helpful; I could at least pass in the flag when I was debugging something to explore the failure
