### ISSUE TITLE
`web3.providers.ipc.get_default_ipc_path()` returned `None` instead of `str`

### ISSUE THREAD

**Issue by antazoey** [ethereum/web3.py#2911]
* Version: 6.0.0
* Python: 3.10
* OS: macky whacky
* `pip freeze` output

```
will provide if needed
```

### What was wrong?

The method `get_deafult_ipc_path()` located in `web3.providers.ipc` returned `None` even though its return type is documented as `str`.

I am not sure why it returned `None` in my case, probably forgot some flag in `geth`.

Edit: it returned None in my case because i was checking it before starting geth, so it didnt exist yet.

### How can it be fixed?

Either change type to `Optional[str]` or raise an error instead of returning `None` ?

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by unparalleled-js** [comment]
For us, it is most useful to have this path even if it does not currently exist yet, since it may not exist at config time but may exist before starting geth

**Comment by kclowes** [comment]
> OS: macky whacky

This is cracking me up 😆 

It would be a small breaking change to return the path  even if it doesn't exist, but I changed the type and made the `return None` explicit in #2917. I don't see a problem with returning the path whether or not it exists, so I'll add this issue to our [v7 megathread](https://github.com/ethereum/web3.py/issues/2854)
