### ISSUE TITLE
Unable to add packages w/ poetry 1.1.14 due to branch name change

### ISSUE THREAD

**Issue by pifantastic** [ethereum/web3.py#2943]
### What was wrong?

I have a project of which web3 is a dependency. Recently, I cannot add new packages to my project (using poetry v `1.1.14` (to my deep dismay, I _must_ use this old version because it is what Render supports)). I encounter the following error:

```
Updating dependencies
Resolving dependencies... (42.2s)

  CalledProcessError

  Command '['git', '--git-dir', '/var/folders/2f/2d9sr74d7t78qqlh6h0j30540000gn/T/pypoetry-git-web3.py9eedyt9s/.git', '--work-tree', '/var/folders/2f/2d9sr74d7t78qqlh6h0j30540000gn/T/pypoetry-git-web3.py9eedyt9s', 'checkout', 'master']' returned non-zero exit status 1.
```

### How can it be fixed?

This seems to be because the `web3` project changed it's default branch from `master` to `main`. I've verified that by just hacking the `poetry` code to hardcode `main` as the branch name when resolving the `web3` dependency, lol.

I think a plausible fix for this is to have a `master` branch which mirrors `main`.

**Comment by fselmo** [comment]
If `Render` doesn't support this, it seems like that's where the issue is. Are you talking about [render-python](https://pypi.org/project/render-python/)? If so, it doesn't look like they have made any changes since 2019. That seems like a bigger problem than our band-aid solution in web3.py could hope to fix.

I'm open to ideas but indefinitely maintaining another copy of `main` as `master` just doesn't seem like the way to go here.

**Comment by pifantastic** [comment]
> I'm open to ideas but indefinitely maintaining another copy of main as master just doesn't seem like the way to go here.

That's fair, this is a silly situation. I am referring to https://render.com/. Feel free to close this issue. I assume this is a `poetry` bug at its heart, somehow. But I don't expect them to fix such an old version.

For posterity, anyone finding this via Google, here is the bonkers way I fixed this.

Make the following change to the poetry source code:

```diff
diff --git a/poetry/puzzle/provider.py b/poetry/puzzle/provider.py
index c05efbd6..a485a2b9 100755
--- a/poetry/puzzle/provider.py
+++ b/poetry/puzzle/provider.py
@@ -166,7 +166,7 @@ class Provider:
             branch=dependency.branch,
             tag=dependency.tag,
             rev=dependency.rev,
-            name=dependency.name,
+            name=dependency.name if dependency.name != 'web3' else 'main',
         )
         package.develop = dependency.develop
```

This should allow you to add your package. After that, you can revert this change.

**Comment by fselmo** [comment]
> I am referring to https://render.com/. 

Ah, I see 👍🏼 

> I assume this is a `poetry` bug at its heart, somehow. But I don't expect them to fix such an old version.

Yeah, that's where I'm leaning too. Not a bug at the time, but being that it is older, it is outdated. I hope you can somehow get Render to use an updated version soon enough.

> Feel free to close this issue.

I will for now as this seems to be a pretty niche and unfortunate situation but if it makes sense to revisit this we can always discuss here. I'm glad you at least have a "workaround" for it, as annoying as it may be 😔
