### ISSUE TITLE
tôi không thể cài thư viện web3, mỗi khi cài nó đều hiện như vậy

### ISSUE THREAD

**Issue by Liber72** [ethereum/web3.py#2946]
PS D:\code> pip install web3
Collecting web3
  Using cached web3-6.3.0-py3-none-any.whl (574 kB)
Collecting aiohttp>=3.7.4.post0 (from web3)
  Using cached aiohttp-3.8.4-cp311-cp311-win_amd64.whl (317 kB)
Requirement already satisfied: eth-abi>=4.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (4.0.0)
Collecting eth-account>=0.8.0 (from web3)
  Using cached eth_account-0.8.0-py3-none-any.whl (102 kB)
Requirement already satisfied: eth-hash[pycryptodome]>=0.5.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (0.5.1)
Requirement already satisfied: eth-typing>=3.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (3.3.0)
Requirement already satisfied: eth-utils>=2.1.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (2.1.0)
Requirement already satisfied: hexbytes>=0.1.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (0.3.0)
Requirement already satisfied: jsonschema>=4.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (4.17.3)
Collecting lru-dict>=1.1.6 (from web3)
  Using cached lru-dict-1.1.8.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf>=4.21.6 (from web3)
  Using cached protobuf-4.22.3-cp310-abi3-win_amd64.whl (420 kB)
Requirement already satisfied: requests>=2.16.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (2.28.2)
Collecting websockets>=10.0.0 (from web3)
  Using cached websockets-11.0.2-cp311-cp311-win_amd64.whl (124 kB)
Requirement already satisfied: pywin32>=223 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from web3) (306)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (3.1.0)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.7.4.post0->web3)
  Using cached multidict-6.0.4-cp311-cp311-win_amd64.whl (28 kB)
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp>=3.7.4.post0->web3)
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp>=3.7.4.post0->web3)
  Using cached yarl-1.9.2-cp311-cp311-win_amd64.whl (60 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.7.4.post0->web3)
  Using cached frozenlist-1.3.3-cp311-cp311-win_amd64.whl (32 kB)
Collecting aiosignal>=1.1.2 (from aiohttp>=3.7.4.post0->web3)
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: parsimonious<0.10.0,>=0.9.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from eth-abi>=4.0.0->web3) (0.9.0)
Collecting bitarray<3,>=2.4.0 (from eth-account>=0.8.0->web3)
  Using cached bitarray-2.7.3-cp311-cp311-win_amd64.whl (118 kB)
Collecting eth-keyfile<0.7.0,>=0.6.0 (from eth-account>=0.8.0->web3)
  Using cached eth_keyfile-0.6.1-py3-none-any.whl (6.5 kB)
Collecting eth-keys<0.5,>=0.4.0 (from eth-account>=0.8.0->web3)
  Using cached eth_keys-0.4.0-py3-none-any.whl (21 kB)
Collecting eth-rlp<1,>=0.3.0 (from eth-account>=0.8.0->web3)
  Using cached eth_rlp-0.3.0-py3-none-any.whl (5.0 kB)
Collecting rlp<4,>=1.0.0 (from eth-account>=0.8.0->web3)
  Using cached rlp-3.0.0-py2.py3-none-any.whl (20 kB)
Collecting pycryptodome<4,>=3.6.6 (from eth-hash[pycryptodome]>=0.5.1->web3)
  Using cached pycryptodome-3.17-cp35-abi3-win_amd64.whl (1.7 MB)
Requirement already satisfied: cytoolz>=0.10.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from eth-utils>=2.1.0->web3) (0.12.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=4.0.0->web3) (0.19.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (2022.12.7)
Requirement already satisfied: toolz>=0.8.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from cytoolz>=0.10.1->eth-utils>=2.1.0->web3) (0.12.0)
Requirement already satisfied: regex>=2022.3.15 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from parsimonious<0.10.0,>=0.9.0->eth-abi>=4.0.0->web3) (2023.5.5)
Building wheels for collected packages: lru-dict
  Building wheel for lru-dict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lru-dict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lru-dict
Failed to build lru-dict
ERROR: Could not build wheels for lru-dict, which is required to install pyproject.toml-based projects

**Comment by kclowes** [comment]
Relevant line from the error message here:
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Liber72** [comment]
> Relevant line from the error message here:
> 
> > error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

i downloaded and installed it, but it doesn't improve
