### ISSUE TITLE
tôi không thể tải tải được thư viện web 3. Lỗi như sau

### ISSUE THREAD

**Issue by Liber72** [ethereum/web3.py#2947]
Requirement already satisfied: regex>=2022.3.15 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from parsimonious<0.10.0,>=0.9.0->eth-abi>=4.0.0->web3) (2023.5.5)
Building wheels for collected packages: lru-dict
  Building wheel for lru-dict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lru-dict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lru-dict
Failed to build lru-dict
ERROR: Could not build wheels for lru-dict, which is required to install pyproject.toml-based projects

**Comment by fselmo** [comment]
Repeat issue with no information; answered here #2946. Please provide more information rather than opening a copy of the same issue.
