### ISSUE TITLE
ERROR: Could not build wheels for lru-dict, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by TG-GOD** [ethereum/web3.py#2954]
* Version: latest
* Python: 3.11.1
* OS: win
* `pip freeze` output

```
aiodns==3.0.0
aiohttp==3.8.3
aiosignal==1.3.1
asgiref==3.6.0
async-timeout==4.0.2
attrs==22.2.0
ccxt==2.6.8
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.6
crispy-bootstrap4==2022.1
cryptography==39.0.0
distlib==0.3.6
dj-database-url==1.3.0
Django==4.2
django-crispy-forms==2.0
django-environ==0.10.0
django-etc==1.4.0
django-heroku==0.3.1
django-hitcount==1.3.5
django-resized==1.0.2
django-taggit==3.1.0
django-tinymce==3.6.1
filelock==3.11.0
frozenlist==1.3.3
gunicorn==20.1.0
idna==3.4
multidict==6.0.4
Pillow==9.5.0
platformdirs==3.2.0
psycopg2==2.9.6
pycares==4.3.0
pycparser==2.21
requests==2.28.2
sqlparse==0.4.3
termcolor==2.2.0
termcolors==0.1.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.14
virtualenv==20.21.0
whitenoise==6.4.0
yarl==1.8.2
```

### What was wrong?

when  i use pip install web3.py， I got “ERROR: Failed building wheel for lru-dict”

PS C:\Users\qqqqew\Documents\Django-Community-Forum-Website-main> pip install --upgrade pip setuptools
Requirement already satisfied: pip in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (23.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (65.5.0)
Collecting setuptools
  Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
ERROR: To modify pip, please run the following command:
C:\Users\qqqqew\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip setuptools

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\qqqqew\Documents\Django-Community-Forum-Website-main> pip install --upgrade web3
Collecting web3
  Using cached web3-6.3.0-py3-none-any.whl (574 kB)
Requirement already satisfied: aiohttp>=3.7.4.post0 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from web3) (3.8.3)
Collecting eth-abi>=4.0.0 (from web3)
  Using cached eth_abi-4.0.0-py3-none-any.whl (28 kB)
Collecting eth-account>=0.8.0 (from web3)
  Using cached eth_account-0.8.0-py3-none-any.whl (102 kB)
Collecting eth-hash[pycryptodome]>=0.5.1 (from web3)
  Using cached eth_hash-0.5.1-py3-none-any.whl (9.0 kB)
Collecting eth-typing>=3.0.0 (from web3)
  Using cached eth_typing-3.3.0-py3-none-any.whl (6.3 kB)
Collecting eth-utils>=2.1.0 (from web3)
  Using cached eth_utils-2.1.0-py3-none-any.whl (24 kB)
Collecting hexbytes>=0.1.0 (from web3)
  Using cached hexbytes-0.3.0-py3-none-any.whl (6.4 kB)
Collecting jsonschema>=4.0.0 (from web3)
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting lru-dict>=1.1.6 (from web3)
  Using cached lru-dict-1.1.8.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf>=4.21.6 (from web3)
  Using cached protobuf-4.23.0-cp310-abi3-win_amd64.whl (422 kB)
Requirement already satisfied: requests>=2.16.0 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from web3) (2.28.2)
Collecting websockets>=10.0.0 (from web3)
  Using cached websockets-11.0.3-cp311-cp311-win_amd64.whl (124 kB)
Collecting pywin32>=223 (from web3)
  Using cached pywin32-306-cp311-cp311-win_amd64.whl (9.2 MB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (22.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from aiohttp>=3.7.4.post0->web3) (1.3.1)
Collecting parsimonious<0.10.0,>=0.9.0 (from eth-abi>=4.0.0->web3)
  Using cached parsimonious-0.9.0-py3-none-any.whl
Collecting bitarray<3,>=2.4.0 (from eth-account>=0.8.0->web3)
  Using cached bitarray-2.7.3-cp311-cp311-win_amd64.whl (118 kB)
Collecting eth-keyfile<0.7.0,>=0.6.0 (from eth-account>=0.8.0->web3)
  Using cached eth_keyfile-0.6.1-py3-none-any.whl (6.5 kB)
Collecting eth-keys<0.5,>=0.4.0 (from eth-account>=0.8.0->web3)
  Using cached eth_keys-0.4.0-py3-none-any.whl (21 kB)
Collecting eth-rlp<1,>=0.3.0 (from eth-account>=0.8.0->web3)
  Using cached eth_rlp-0.3.0-py3-none-any.whl (5.0 kB)
Collecting rlp<4,>=1.0.0 (from eth-account>=0.8.0->web3)
  Using cached rlp-3.0.0-py2.py3-none-any.whl (20 kB)
Collecting pycryptodome<4,>=3.6.6 (from eth-hash[pycryptodome]>=0.5.1->web3)
  Using cached pycryptodome-3.17-cp35-abi3-win_amd64.whl (1.7 MB)
Collecting cytoolz>=0.10.1 (from eth-utils>=2.1.0->web3)
  Using cached cytoolz-0.12.1-cp311-cp311-win_amd64.whl (315 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema>=4.0.0->web3)
  Using cached pyrsistent-0.19.3-cp311-cp311-win_amd64.whl (62 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (3.4)      
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\qqqqew\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.16.0->web3) (2022.12.7)
Collecting toolz>=0.8.0 (from cytoolz>=0.10.1->eth-utils>=2.1.0->web3)
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting regex>=2022.3.15 (from parsimonious<0.10.0,>=0.9.0->eth-abi>=4.0.0->web3)
  Using cached regex-2023.5.5-cp311-cp311-win_amd64.whl (267 kB)
Building wheels for collected packages: lru-dict
  Building wheel for lru-dict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lru-dict (pyproject.toml) did not run successfully.       
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lru-dict
Failed to build lru-dict
ERROR: Could not build wheels for lru-dict, which is required to install pyproject.toml-based projects

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by pacrob** [comment]
The solution is there in your error output: 

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

If you're still having usage problems after installing the Build Tools, please check out our [discord](https://discord.gg/GHryRvPB84), or open a new issue if you think there's a problem with the library.
