### ISSUE TITLE
Add ConnectionCheck middleware

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#297]
### What was wrong?

`JSONDecodeError` is a confusing way to learn that you are not connected to the service.  See this [stackexchange question](https://ethereum.stackexchange.com/questions/26225/issues-connecting-to-the-etherscan-ropsten-api-via-web3-py).

### How can it be fixed?

Maybe a middleware similar to stalecheck that tests if you are connected and raises a specific ConnectionFailure exception if not.

**Comment by pipermerriam** [comment]
I'd also be interested in changing how the `isConnected` is done for both the `HTTP` and `IPC` middlewares to actually check whether an http connection can be made to the host or whether the socket is open respectively.

**Comment by carver** [comment]
Connecting to a missing HTTP and IPC location both give reasonable failures when the endpoint is missing. The problem in the linked example is that they tried to use an endpoint that wasn't an ethereum node. `JSONDecodeError` may not have helped them a ton, but it's a somewhat reasonable response. Closing for now.
