### ISSUE TITLE
object function can't be used in 'await' expression

### ISSUE THREAD

**Issue by bryaan** [ethereum/web3.py#2980]
* Version: 6.4.0

There seems to be a problem with this line:  https://github.com/ethereum/web3.py/blame/c99135587614c4f95275ea27dd3227f45ac23c73/web3/middleware/__init__.py#L130

```
 Python: TypeError: object function can't be used in 'await' expression
│    Python stacktrace:
│     [1] construct_middleware
│       @ web3.middleware ~/Library/Caches/pypoetry/virtualenvs/cryptopy-5siZoxZ4-py3.10/lib/python3.10/site-packages/web3/middleware/__init__.py:130
```

Please excuse the error message as I am calling from julia with PythonCall. jl

It points to the line linked above.  I don't know if its an error with this library or that one. 
Can someone look at this lib closer and confirm it has been done right?

**Comment by pacrob** [comment]
It looks like you've passed a regular function in somewhere it was expecting an async function. The function you point to is working correctly.

For help using the library, check out our [Discord](https://discord.gg/GHryRvPB84)
