### ISSUE TITLE
Add `eth_chainId` to retry middleware whitelist

### ISSUE THREAD

**Issue by dino-rodriguez** [ethereum/web3.py#2993]
### What was wrong?

I enabled the `http_retry_request_middleware`, but an idempotent method that is called frequently (`eth_chainId`) is missing from the retry whitelist

### How can it be fixed?

Add this method to the retry method whitelist in the code

**Comment by dino-rodriguez** [comment]
Also probably worth adding `eth_maxPriorityFeePerGas` to the white list too

**Comment by pacrob** [comment]
It looks like `eth_chainId` was added in #2892, but I think `eth_maxPriorityFeePerGas` should be fine to add. Looking into it.
