### ISSUE TITLE
Deprecation warning for Py2

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#300]
* Version: 3.*
* Python: 2.7
* OS: osx/linux/win

### What was wrong?

Many functions would greatly benefit from being able to differentiate `bytes` and `str`. Hacks and workarounds are all around the system. We should start warning users now so they can prepare their Py3 stacks.

### How can it be fixed?

Add a `DeprecationWarning` if `sys.version_info.major < 3`.

**Comment by djrtwo** [comment]
Excellent.
