### ISSUE TITLE
async_http_retry_request_middleware

### ISSUE THREAD

**Issue by LaoGunz** [ethereum/web3.py#3003]
* Version: 6.4.0
* Python: 3.10
* OS: linux

how to use http_retry_request_middleware for AsyncWeb3? Is there a ready-made method? or should I write my own middleware?

**Comment by kclowes** [comment]
We don't have an equivalent `http_retry_request_middleware` yet for AsyncWeb3 so you'll have to create your own. If you end up going that route and want to PR it, we'd be happy to review! I'll leave this open as a feature request.
