### ISSUE TITLE
Is there staticCall in web3py?

### ISSUE THREAD

**Issue by lurengeng** [ethereum/web3.py#3018]
* Python: 3.8
* OS: win

I have used Multicall(https://github.com/mds1/multicall) in ethers.js.  In that case, it could use "staticCall" to avoid paying gas.

I want to know,   how to use staticCall in web3py
Thx.

**Comment by fselmo** [comment]
For usage questions please refer to the documentation or ask in the Ethereum Community Python [Discord](https://discord.gg/GHryRvPB84).
