### ISSUE TITLE
Drop Python 3.7

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#3032]
* Version: v7

### What was wrong?

As of 6/2023, Python 3.7 is no longer supported, so we shouldn't support either.

### How can it be fixed?

Remove it from CI, and search the code base to update anywhere we're checking for a Python version of <3.8

**Comment by akash-kumar-saw** [comment]
I would love to contribute... 
/assign me please 🙏

**Comment by kclowes** [comment]
Thanks for your willingness to contribute! It'll be a while before we're ready to start the v7 branch, but we'll let you know when we are.

**Comment by DanielFrantes** [comment]
@kclowes can I contribu on this.

**Comment by DanielFrantes** [comment]
Also on what version we want to update it

**Comment by fselmo** [comment]
closed by #3198
