### ISSUE TITLE
Import error in latest version of web3.py pip package

### ISSUE THREAD

**Issue by ehtec** [ethereum/web3.py#3038]
* Version: 6.6.0
* Python: 3.9
* OS: Debian 11

The latest version 6.6.0 that was released about an hour ago of the web3 pip package is broken, it cannot be imported without raising an error. I noticed this because it broke our CI pipelines.

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elias/.local/lib/python3.9/site-packages/web3/__init__.py", line 4, in <module>
    from web3.main import (
  File "/home/elias/.local/lib/python3.9/site-packages/web3/main.py", line 4, in <module>
    from ens import (
  File "/home/elias/.local/lib/python3.9/site-packages/ens/__init__.py", line 3, in <module>
    from .async_ens import (
  File "/home/elias/.local/lib/python3.9/site-packages/ens/async_ens.py", line 35, in <module>
    from ens.base_ens import (
  File "/home/elias/.local/lib/python3.9/site-packages/ens/base_ens.py", line 18, in <module>
    from .utils import (
  File "/home/elias/.local/lib/python3.9/site-packages/ens/utils.py", line 39, in <module>
    from ._normalization import (
  File "/home/elias/.local/lib/python3.9/site-packages/ens/_normalization.py", line 57, in <module>
    with open(os.path.join(specs_dir_path, "normalization_spec.json")) as spec:
FileNotFoundError: [Errno 2] No such file or directory: '/home/elias/.local/lib/python3.9/site-packages/ens/specs/normalization_spec.json'
```

**Comment by Rogalek** [comment]
I have the same issue!

**Comment by kclowes** [comment]
I am not able to replicate. I wonder if there is a caching issue in your CI? Can you clear your cache in CI and let me know?

**Comment by ehtec** [comment]
> I am not able to replicate. I wonder if there is a caching issue in your CI? Can you clear your cache in CI and let me know?

I don't believe this is a caching issue, as other people have the same issue as well, it happened right after the release of the latest verison of web3py, I could replicate it on my laptop (the screenshot above is actually from my laptop, where I upgraded web3py to test), and the `locate` command is telling the that the `normalization_spec.json` file indeed does not exist on my system.

**Comment by kclowes** [comment]
@ehtec How are you installing?

**Comment by ehtec** [comment]
> @ehtec How are you installing?

```
python3 -m pip install --upgrade web3
```

I believe that these `.json` files, which seem to be new according to the commit history, are not included in the pip package by default and need to be manually specified in the `setup.py` configuration which is currently not the case, as far as I have seen.

**Comment by kclowes** [comment]
Yeah, I don't see it in the `tar` file. Thanks for raising and troubleshooting. Will put a patch up shortly.

**Comment by fselmo** [comment]
@ehtec @Rogalek Patch release `v6.6.1` is out now with that change in there... please let us know if that solves your issue. Thanks again for reporting!

**Comment by B2f4** [comment]
Hi. i have the same issue using pyinstaller.
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEICqEE2v/ens/specs/normalization_spec.json'
using 6.6.0, 6.6.1 and the latest version too 6.8.0

**Comment by fselmo** [comment]
@B2f4 *pyinstaller* needs a manual addition utilizing the `--add-data` flag.

https://stackoverflow.com/questions/62017384/adding-json-files-to-an-exe-file-using-pyinstaller
