### ISSUE TITLE
Update test suite for geth 1.7.0

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#304]
### What was wrong?

The latest release of go-ethereum `v1.7.0` uses a database format that is incompatable with the `1.6.x` line.

https://blog.ethereum.org/2017/09/14/geth-1-7-megara/

This will break CI if we try to run the integration tests against the current geth datadir fixture

### How can it be fixed?

Re-generate a new geth fixture for `1.7.x`

TODO: write up the requirements for this fixture as well as a script for generating it.

**Comment by carver** [comment]
We're testing against geth 1.7.x, so this seems to be done.
