### ISSUE TITLE
Formatter Functions ETH<->Wei

### ISSUE THREAD

**Issue by sebastiandine** [ethereum/web3.py#3040]
I am looking for a feature to easily convert values in ETH to wei and vice versa, similar to these [formatters that are provided by ethers.js](https://docs.ethers.org/v5/api/utils/display-logic/#display-logic--functions).
```[tasklist]
### Tasks
```

**Comment by fselmo** [comment]
I'm not sure I understand how this differs from `Web3.to_wei()` and `Web3.from_wei()`

```py
>>> from web3 import Web3

>>> Web3.from_wei(110000222200000000, "ether")
Decimal('0.1100002222')

>>> Web3.to_wei(1.0, "ether")
1000000000000000000
```

I'm going to close this as this has been implemented for some time. Please ask to re-open if you feel that your request is not covered by these methods.
