### ISSUE TITLE
Send all ETH balance in Arbitrum

### ISSUE THREAD

**Issue by MU12351235** [ethereum/web3.py#3047]
Hello, I hope you are well
I am going to empty all ETH from my address using web3.py on Arbitrum network.
I do this by considering the transaction fee and deducting it from the transaction amount, but the amount of $0.02 always remains in my address and is not completely drained.
Please help how to transfer all ETH?

**Comment by fselmo** [comment]
@MU12351235 this is not an issue with the library. Check out the Ethereum Python Community [Discord](https://discord.gg/GHryRvPB84) and ask questions there please.
