### ISSUE TITLE
gas_price on Optimism

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [ethereum/web3.py#3055]
<img width="514" alt="image" src="https://github.com/ethereum/web3.py/assets/26211339/83714043-7081-4732-b5b7-8679a3d0a583">

**Comment by pacrob** [comment]
Closing for lack of information. If you have a usage question, check out our [Discord](https://discord.gg/GHryRvPB84). If you think there's a bug in the library, please provide more detail.
