### ISSUE TITLE
Refactored lightweight web3 library

### ISSUE THREAD

**Issue by Fooyao** [ethereum/web3.py#3059]
web3py is just too bloated for users. Most people just need simple functionality.
We need a completely refactored lightweight web3 library, like ether and viem on JavaScript.

**Comment by wolovim** [comment]
what is your actual pain point? is it difficult to understand certain components of the library? is it difficult to navigate the docs for something in particular? are you trying to alter the lib to serve another purpose/chain? is the raw package size a problem for a use case you have?

**Comment by wolovim** [comment]
closing, but here 4 u frend
