### ISSUE TITLE
type hints isn't working on pycharm

### ISSUE THREAD

**Issue by shifenhutu** [ethereum/web3.py#3068]
* Version: 6.7.0
* Python: 3.11
* OS: osx 
* pycharm: 2023.2 (Professional Edition)
* `pip freeze` output

```
addict==2.4.0
aiohttp==3.8.5
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
bitarray==2.8.0
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
cytoolz==0.12.2
eth-abi==4.1.0
eth-account==0.9.0
eth-hash==0.5.2
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.4.0
eth-utils==2.2.0
frozenlist==1.4.0
hexbytes==0.3.1
idna==3.4
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
lru-dict==1.2.0
many-abis==0.1.7
multidict==6.0.4
parsimonious==0.9.0
protobuf==4.23.4
pycryptodome==3.18.0
python-dotenv==1.0.0
pyunormalize==15.0.0
referencing==0.30.0
regex==2023.6.3
requests==2.31.0
rlp==3.0.0
rpds-py==0.9.2
toolz==0.12.0
typing_extensions==4.7.1
uniswap-python==0.7.0
urllib3==2.0.4
web3==6.7.0
websockets==11.0.3
yarl==1.9.2
```

### What was wrong?

type `BlockData` property isn't on the list 

my code:
```python
from web3 import Web3


alchemy_https_url = f"https://eth-mainnet.g.alchemy.com/v2/{ALCHEMY_ETH_MAINNET_KEY}"

w3 = Web3(Web3.HTTPProvider(alchemy_https_url))

# Get the latest block number
latest_block = w3.eth.get_block('latest')
```

![image](https://github.com/ethereum/web3.py/assets/104620424/ed4eeae3-6097-4a95-878c-6cf66216b672)

![image](https://github.com/ethereum/web3.py/assets/104620424/6e28bdf9-c333-4f7e-af8b-fee9e382f9ea)

### How can it be fixed?

i have no idea

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
@shifenhutu `BlockData` is a `TypedDict` so you'll have to access fields via key + value. Unfortunately, when returning the `AttributeDict` breaks typing. I'm not sure there is a good alternative at the moment to build an "attribute dict" while preserving type hints. If you'd like to get rid of the `AttributeDict` altogether, which wraps all dicts as the `AttributeDict` class via a default middleware, you may remove it:

```py
w3.middleware_onion.remove("attrdict")
```
