### ISSUE TITLE
Variables in code should follow standard conventions

### ISSUE THREAD

**Issue by reedsa** [ethereum/web3.py#3085]
### What was wrong?

Most of the python codebase is using the standard [pep8 variable naming convention](https://peps.python.org/pep-0008/#method-names-and-instance-variables) with a few exceptions. We'll need to look at and decide whether it makes sense to conform to this for all variables throughout the codebase.

In this recent [PR](https://github.com/ethereum/web3.py/pull/3078/files), a couple variables used in filtering (`fromBlock` and `toBlock`) were considered for refactoring into snake_case names. As the request is constructed, the filter arguments can be adapted to the appropriate naming convention so that the code itself has no concern with how the requests look.

### How can it be fixed?

As a result of this thread, we will agree on the conventions we would like to proceed with. Refactoring can proceed as necessary for the v7 release.

**Comment by rarjun7777** [comment]
I would like to work on this .

**Comment by reedsa** [comment]
@rarjun7777 this thread started as one possible approach. Another suggestion is to handle both cases as mentioned in https://github.com/ethereum/web3.py/issues/2787

Not sure which the team is going to decide but will be something to address for v7.
