### ISSUE TITLE
Passing tuple as a function's argument

### ISSUE THREAD

**Issue by Pavel-Polyanskiy** [ethereum/web3.py#3150]
i tried to execute function where the argument type is tuple. I passed it and it returns me an error. The argument has to be a tuple of integers. 

`lp_contract.functions.increaseLiquidity((9948, 3194772954415, 600000000000, 12000))
`
the error:

``Could not identify the intended function with name `increaseLiquidity`, positional argument(s) of type `(<class 'tuple'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `increaseLiquidity`: ['increaseLiquidity(tuple)']
Function invocation failed due to no matching argument types.``

How can i fix it?

Thank you in advance!

**Comment by fselmo** [comment]
We prefer to use issues to track our work. If you have implementation or usage questions, please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation on [discord](https://discord.gg/GHryRvPB84).
