### ISSUE TITLE
AsyncWeb3 persistent_websocket connection gets often closed

### ISSUE THREAD

**Issue by tajelp** [ethereum/web3.py#3151]
* Version: 6.11.3
* Python: 3.10.12
* OS: linux Ubuntu 22.04.3 LTS
* `pip freeze` output

```
aeidon==1.10.1
aiohttp==3.9.0
aiosignal==1.3.1
apt-xapian-index==0.49
argcomplete==3.1.6
async-timeout==4.0.3
attrs==23.1.0
Automat==20.2.0
Babel==2.8.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
bitarray==2.8.3
blinker==1.4
boltons==23.1.1
build==1.0.3
CacheControl==0.13.1
cachy==0.3.0
cclib==1.6.2
certifi==2020.6.20
cffi==1.16.0
chardet==4.0.0
charset-normalizer==3.3.2
cleo==2.1.0
click==8.0.3
clikit==0.6.2
colorama==0.4.4
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
crashtest==0.4.1
cryptography==41.0.5
cupshelpers==1.0
cytoolz==0.12.2
dbus-python==1.2.18
diff-match-patch==20200713
distlib==0.3.7
distro==1.7.0
distro-info==1.1+ubuntu0.1
docopt==0.6.2
dulwich==0.21.6
environs==9.5.0
eth-abi==4.2.1
eth-account==0.10.0
eth-hash==0.5.2
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.5.2
eth-utils==2.3.1
fail2ban==0.11.2
fastjsonschema==2.19.0
filelock==3.13.1
frozenlist==1.4.0
fuse-python==1.0.2
gpg==1.16.0
hexbytes==0.3.1
html5lib==1.1
httplib2==0.20.2
hyperlink==21.0.0
idna==3.4
importlib-metadata==6.8.0
incremental==21.3.0
iniparse==0.4
installer==0.7.0
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.0.3
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
keyring==24.3.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
livereload==2.6.3
lockfile==0.12.2
lru-dict==1.2.0
lxml==4.8.0
Markdown==3.3.6
MarkupSafe==2.0.1
marshmallow==3.20.1
mkdocs==1.1.2
more-itertools==10.1.0
msgpack==1.0.7
multidict==6.0.4
netifaces==0.11.0
numpy==1.21.5
oauthlib==3.2.0
packaging==23.2
parsimonious==0.9.0
pastel==0.2.1
pexpect==4.8.0
phply==1.2.5
pipx==1.2.1
pkginfo==1.9.6
platformdirs==3.11.0
ply==3.11
poetry==1.7.1
poetry-core==1.8.1
poetry-plugin-export==1.6.0
protobuf==4.25.1
psutil==5.9.0
ptyprocess==0.7.0
py==1.10.0
pyaes==1.6.1
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycairo==1.20.1
pycountry==20.7.3
pycparser==2.21
pycryptodome==3.19.0
pycups==2.0.1
pyenchant==3.2.0
Pygments==2.11.2
PyGObject==3.42.1
PyHamcrest==2.0.2
pyinotify==0.9.6
PyJWT==2.3.0
pylev==1.2.0
pylibacl==0.6.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyproject_hooks==1.0.0
PyQt5==5.15.6
PyQt5-sip==12.9.1
pyserial==3.5
PySocks==1.7.1
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.1
python-debian==0.1.43+ubuntu1.1
python-dotenv==1.0.0
python-Levenshtein==0.12.2
python-magic==0.4.24
pytz==2022.1
pyunormalize==15.1.0
pyxattr==0.7.2
PyYAML==5.4.1
pyzmq==22.3.0
rapidfuzz==3.5.2
referencing==0.31.0
regex==2023.10.3
requests==2.31.0
requests-toolbelt==1.0.0
rlp==3.0.0
rpds-py==0.13.0
rsa==4.9
ruamel.yaml==0.17.16
ruamel.yaml.clib==0.2.6
SecretStorage==3.3.3
service-identity==18.1.0
shellingham==1.5.4
simplejson==3.17.6
six==1.16.0
sos==4.5.6
soupsieve==2.3.1
sourcedefender==11.0.4
ssh-import-id==5.11
systemd-python==234
Telethon==1.32.1
TgCrypto==1.2.5
tomli==2.0.1
tomlkit==0.12.3
toolz==0.12.0
tornado==6.1
translate-toolkit==3.6.0
trove-classifiers==2023.11.14
Twisted==22.1.0
typing_extensions==4.8.0
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==2.1.0
userpath==1.8.0
virtualenv==20.24.6
vobject==0.9.6.1
wadllib==1.3.6
web3==6.11.3
webencodings==0.5.1
websockets==12.0
xkit==0.0.0
yarl==1.9.2
zipp==1.0.0
zope.interface==5.4.0
```

I have a code like this:

```
import asyncio
import datetime
from web3 import AsyncWeb3
from web3.providers import WebsocketProviderV2

import asyncio
import datetime
from web3 import AsyncWeb3
from web3.providers import WebsocketProviderV2

async def connect_to_websocket(wss_endpoint):
    while True:
        persistent_tries = 0
        
        async for w3_wss in AsyncWeb3.persistent_websocket(WebsocketProviderV2(wss_endpoint)):
            persistent_tries += 1
                
            if persistent_tries > 10:
                break
            
            try:
                print(f'[{datetime.datetime.utcnow()}] subscribing...')
                subscription_id = await w3_wss.eth.subscribe("newPendingTransactions", True)
                print(f'[{datetime.datetime.utcnow()}] subscribed')

                while True:
                            async for tx in w3_wss.ws.listen_to_websocket():
                                print(tx)
            except websockets.ConnectionClosed:
                print(f'[{datetime.datetime.utcnow()}] connection closed. Opening a new one...')
                await asyncio.sleep(1)
                continue


async def main():
	await connect_to_websocket('ws://127.0.0.1:8546')


async def main():
	await connect_to_websocket('ws://127.0.0.1:8546')
```

The connection gets opened successfully but after a few minutes it gets closed. When trying to automatically reconnect, it can't (no "subscribed" print) but after it tries a lot of times, it will successfully reconnect again. Then it lasts another few minutes and it's the same story all over again. Here's the log:

> [2023-11-20 15:53:54.565898] subscribing...
> [2023-11-20 15:53:54.566937] subscribed
> [2023-11-20 15:59:44.567155] connection closed. Opening a new one...
> [2023-11-20 15:59:45.568193] subscribing...
> [2023-11-20 15:59:45.568571] connection closed. Opening a new one...
> [2023-11-20 15:59:46.569988] subscribing...
> [2023-11-20 15:59:46.570333] connection closed. Opening a new one...
> [2023-11-20 15:59:47.571411] subscribing...
> [2023-11-20 15:59:47.571842] connection closed. Opening a new one...
> [2023-11-20 15:59:48.573255] subscribing...
> [2023-11-20 15:59:48.573609] connection closed. Opening a new one...
> [2023-11-20 15:59:49.574666] subscribing...
> [2023-11-20 15:59:49.575020] connection closed. Opening a new one...
> [2023-11-20 15:59:50.576164] subscribing...
> [2023-11-20 15:59:50.576920] connection closed. Opening a new one...
> [2023-11-20 15:59:51.578126] subscribing...
> [2023-11-20 15:59:51.578555] connection closed. Opening a new one...
> [2023-11-20 15:59:52.579252] subscribing...
> [2023-11-20 15:59:52.579632] connection closed. Opening a new one...
> [2023-11-20 15:59:53.580147] subscribing...
> [2023-11-20 15:59:53.580492] connection closed. Opening a new one...
> [2023-11-20 15:59:54.582360] subscribing...
> [2023-11-20 15:59:54.853080] subscribed
> [2023-11-20 16:05:44.821639] connection closed. Opening a new one...
> [2023-11-20 16:05:45.822672] subscribing...
> [2023-11-20 16:05:45.823035] connection closed. Opening a new one...
> [2023-11-20 16:05:46.824358] subscribing...
> [2023-11-20 16:05:46.824775] connection closed. Opening a new one...
> [2023-11-20 16:05:47.826231] subscribing...
> [2023-11-20 16:05:47.826765] connection closed. Opening a new one...
> [2023-11-20 16:05:48.827471] subscribing...
> [2023-11-20 16:05:48.827828] connection closed. Opening a new one...
> [2023-11-20 16:05:49.828530] subscribing...
> [2023-11-20 16:05:49.828937] connection closed. Opening a new one...
> [2023-11-20 16:05:50.830296] subscribing...
> [2023-11-20 16:05:50.830661] connection closed. Opening a new one...
> [2023-11-20 16:05:51.831986] subscribing...
> [2023-11-20 16:05:51.832441] connection closed. Opening a new one...
> [2023-11-20 16:05:52.833090] subscribing...
> [2023-11-20 16:05:52.833535] connection closed. Opening a new one...
> [2023-11-20 16:05:53.834685] subscribing...
> [2023-11-20 16:05:53.835123] connection closed. Opening a new one...
> [2023-11-20 16:05:54.836982] subscribing...
> [2023-11-20 16:05:54.855761] subscribed
> [2023-11-20 16:11:45.172098] connection closed. Opening a new one...
> [2023-11-20 16:11:46.173358] subscribing...
> [2023-11-20 16:11:46.173757] connection closed. Opening a new one...
> [2023-11-20 16:11:47.175270] subscribing...
> [2023-11-20 16:11:47.175644] connection closed. Opening a new one...
> [2023-11-20 16:11:48.175937] subscribing...
> [2023-11-20 16:11:48.176352] connection closed. Opening a new one...
> [2023-11-20 16:11:49.177940] subscribing...
> [2023-11-20 16:11:49.178266] connection closed. Opening a new one...
> [2023-11-20 16:11:50.179826] subscribing...
> [2023-11-20 16:11:50.180169] connection closed. Opening a new one...
> [2023-11-20 16:11:51.181824] subscribing...
> [2023-11-20 16:11:51.182165] connection closed. Opening a new one...
> [2023-11-20 16:11:52.183824] subscribing...
> [2023-11-20 16:11:52.184159] connection closed. Opening a new one...
> [2023-11-20 16:11:53.185833] subscribing...
> [2023-11-20 16:11:53.186247] connection closed. Opening a new one...
> [2023-11-20 16:11:54.187911] subscribing...
> [2023-11-20 16:11:54.188256] connection closed. Opening a new one...
> [2023-11-20 16:11:55.191071] subscribing...
> [2023-11-20 16:11:55.616656] subscribed
> [2023-11-20 16:17:45.192521] connection closed. Opening a new one...
> [2023-11-20 16:17:46.193992] subscribing...
> [2023-11-20 16:17:46.194389] connection closed. Opening a new one...
> [2023-11-20 16:17:47.195400] subscribing...
> [2023-11-20 16:17:47.195763] connection closed. Opening a new one...
> [2023-11-20 16:17:48.197199] subscribing...
> [2023-11-20 16:17:48.197547] connection closed. Opening a new one...
> [2023-11-20 16:17:49.198676] subscribing...
> [2023-11-20 16:17:49.199032] connection closed. Opening a new one...
> [2023-11-20 16:17:50.199881] subscribing...
> [2023-11-20 16:17:50.200383] connection closed. Opening a new one...
> [2023-11-20 16:17:51.200966] subscribing...
> [2023-11-20 16:17:51.201290] connection closed. Opening a new one...
> [2023-11-20 16:17:52.201889] subscribing...
> [2023-11-20 16:17:52.202273] connection closed. Opening a new one...
> [2023-11-20 16:17:53.202666] subscribing...
> [2023-11-20 16:17:53.203034] connection closed. Opening a new one...
> [2023-11-20 16:17:54.203727] subscribing...
> [2023-11-20 16:17:54.204106] connection closed. Opening a new one...
> [2023-11-20 16:17:55.206132] subscribing...
> [2023-11-20 16:17:55.376738] subscribed

I didn't have this problem with a previous version (I can't recall which one exactly). What could it be?

**Comment by tajelp** [comment]
Ok, maybe I got it. It looks like when a connection has been closed, you cannot iterate through the current persistent websocket but you have to create another one. In fact, it fails for 10 times, then `persistent_tries > 10`, it breaks and creates a new persistent websocket.
So the iterator is not working properly?

**Comment by fselmo** [comment]
Have you resolved this? There seem to be a lot of `while True` statements here. In particular I don't think you need to wrap the `async for tx in w3_wss.ws.listen_to_websocket():` in a `while True`.

```py
while True:  # <--- this seems unnecessary
    async for tx in w3_wss.ws.listen_to_websocket():
        print(tx)
```

Can you try to simplify it and let us know if the problem persists?

**Comment by fselmo** [comment]
Closing this for now, if you feel like it's an issue please ask to reopen.

**Comment by fselmo** [comment]
Indeed the connection closed is in the wrong spot. Without testing, I believe this is closer to the setup you were going for:

```py
persistent_tries = 0

async for w3_wss in AsyncWeb3.persistent_websocket(WebsocketProviderV2(wss_endpoint)):
    try:
        persistent_tries += 1
            
        if persistent_tries > 10:
            break
        
        print(f'[{datetime.datetime.utcnow()}] subscribing...')
        subscription_id = await w3_wss.eth.subscribe("newPendingTransactions", True)
        print(f'[{datetime.datetime.utcnow()}] subscribed')

        async for tx in w3_wss.ws.listen_to_websocket():
            print(tx)

    except websockets.ConnectionClosed:
        print(f'[{datetime.datetime.utcnow()}] connection closed. Opening a new one...')
        # the provider itself has exponential backoff and tries to re-connect up to 5 times by default so
        # this await is not needed.
        # await asyncio.sleep(1)
        continue
```

Again, let us know if you're still having issues.
