### ISSUE TITLE
where can i download the document pdf on web3.py version 6.x

### ISSUE THREAD

**Issue by shifenhutu** [ethereum/web3.py#3152]
https://readthedocs.org/projects/web3py/downloads/

there is no  version 6.x   document  

thank you very much

**Comment by pacrob** [comment]
I've updated to build the Downloadable docs going forward. Unfortunately there doesn't appear to be a way to make them available for past versions. The `latest` is the current state of our docs, and the next numbered version will be available when a new release goes out (within a week).
