### ISSUE TITLE
Can't call a function from a contract, even though I'm transferring all the data correctly

### ISSUE THREAD

**Issue by StasFQ** [ethereum/web3.py#3158]
OS: MacOS
Python: 3.10.7
web3.py: 6.11.2
I am trying to call a function from a smart contract for a token exchange:
<img width="694" alt="Снимок экрана 2023-12-04 в 15 09 38" src="https://github.com/ethereum/web3.py/assets/113999763/7416baac-0c1b-4594-8f46-8bd40373a075">
Got this error:
<img width="1364" alt="Снимок экрана 2023-12-04 в 15 10 10" src="https://github.com/ethereum/web3.py/assets/113999763/23faa934-bffd-442a-a648-bd047719fdf7">
Also, when I pass token, recipient, receive_token as b'0x...', I get this error:
<img width="1361" alt="Снимок экрана 2023-12-04 в 15 12 15" src="https://github.com/ethereum/web3.py/assets/113999763/bdb239aa-b53f-4b2d-8142-f71f05a00242">
How to fix that??

**Comment by pacrob** [comment]
Based on the error message, it looks like you are passing the arguments individually but the function is expecting them to be passed as a single list.

We prefer to use issues for problems with the library itself, but you can check out our [Discord](https://discord.gg/GHryRvPB84) for help with further usage questions.

If there is a problem with the library, please open a new issue with more information.

**Comment by fselmo** [comment]
> Based on the error message, it looks like you are passing the arguments individually but the function is expecting them to be passed as a single list.

I just wanted to point out that this doesn't seem to be the case, in case it creates a false chase - the arguments do seem to be expected individually based on the function signature. Something else is going on but we should resolve it in the Discord as stated above.

**Comment by StasFQ** [comment]
> > Based on the error message, it looks like you are passing the arguments individually but the function is expecting them to be passed as a single list.
> 
> I just wanted to point out that this doesn't seem to be the case, in case it creates a false chase - the arguments do seem to be expected individually based on the function signature. Something else is going on but we should resolve it in the Discord as stated above.

Write on discord about it.web3py room
