### ISSUE TITLE
Add state_override argument to estimate_gas

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#3164]
### What was wrong?

As of geth 1.12.1, `estimate_gas` allows a `state_override` argument. 

### How can it be fixed?

Allow `eth.estimate_gas` to take the `state_override` param. Can follow the existing `eth.call` implementation.

**Comment by reedsa** [comment]
Planning this as part of `v7` (#2854) since this requires an upgrade of `geth` which appears to be a bit more involved.

**Comment by fselmo** [comment]
no longer `v7` only since #3209 was merged
