### ISSUE TITLE
Consider replacing the use of `lru`

### ISSUE THREAD

**Issue by pacrob** [ethereum/web3.py#3165]
https://github.com/ethereum/web3.py/blob/9eae20a9e96d312196c12af5752681a8daf4928b/web3/middleware/cache.py#L17

It has a single release from 2010: https://pypi.org/project/lru/#history

And the pypi link to github 404s

Probably good to find something better maintained.

**Comment by kclowes** [comment]
Yeah, good call. This is on our list for v7: https://github.com/ethereum/web3.py/issues/2884

**Comment by pacrob** [comment]
Closing as duplicate
