### ISSUE TITLE
False positives returned by `is_valid_ens_name` of `ens.utils`

### ISSUE THREAD

**Issue by Aviksaikat** [ethereum/web3.py#3166]
* Version: 6.12.0
* Python: 3.9.0 
* OS: inux
* `pip freeze` output. Using `pdm`.

```py
dependencies = [
    "eth-ape>=0.6.27",
    "structlog>=23.2.0",
    "semver>=3.0.2",
    "websocket-client>=1.6.4",
    "swarm-cid-py>=0.1.2",
    "eth-pydantic-types>=0.1.0a3",
    "web3>=6.12.0",
]
```

### What was wrong?

The `is_valid_ens_name` is returning wrong values when invalid `ENS` values are passed. Here are some examples

```py
In [1]: from ens.utils import is_valid_ens_name

In [2]: is_valid_ens_name("-example.eth")
Out[2]: True

In [3]: is_valid_ens_name("-example.eth-")
Out[3]: True

In [4]: is_valid_ens_name("-example-.eth-")
Out[4]: True
```

### How can it be fixed?

Maybe a regex to check first. I'm going to implement something similar [here](https://github.com/alienrobotninja/bee-py/blob/main/src/bee_py/utils/type.py) as I think this might take a while. If everything works out I can make a PR.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by djstrong** [comment]
These examples are valid ENS names. You can validate it e.g. at https://www.nameguard.io/ or https://adraffy.github.io/ens-normalize.js/test/resolver.html

**Comment by Aviksaikat** [comment]
Thank you it was very confusing. I think I was wrong & this is working just fine.
