### ISSUE TITLE
Doc still has protocol_version

### ISSUE THREAD

**Issue by antonio-fr** [ethereum/web3.py#3182]
* Version: 6.13.0
* Python: 3

### What was wrong?

The documentation should not describe methods that were deleted. Eth protocol_version was fully removed, even the snake_case version.

On [May 2022, many deprecated Eth methods were finally deleted](https://github.com/ethereum/web3.py/pull/2432/files#diff-a4febcc4a144425c1b38bea6ba7a8e5e3f80823a76696e096f43f648ddb79515). This is still present in the documentation.

### How can it be fixed?

Remove from the doc the no more relevant Eth methods, such as protocol_version.

**Comment by pacrob** [comment]
Thanks @antonio-fr ! We'll get that removed.
