### ISSUE TITLE
Optional parameter in `fee_history` causes problems when omitted

### ISSUE THREAD

**Issue by antazoey** [ethereum/web3.py#3184]
* Version: 6.13.0
* Python: 3.10.13
* OS: macos
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

We have been doing this in our code:

```python
fee_history = self.web3.eth.fee_history(1, BlockNumber(latest_block_number))
```

However, it now failed with the following error:

```
ValueError: {'code': -32602, 'message': 'Errors encountered in param 2: Invalid value null supplied to : Array<Float number> | undefined', 'data': {'message': 'Errors encountered in param 2: Invalid value null supplied to : Array<Float number> | undefined'}}
```

To fix it on my end, I had to change the line to:

```python
fee_history = self.web3.eth.fee_history(1, BlockNumber(latest_block_number), reward_percentiles=[])
```

### How can it be fixed?

If given `None` , change to `[]` in the code implementation.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by antazoey** [comment]
Ok, I am realizing this does not happen on normal geth nodes but does happen on Anvil and Hardhat.

**Comment by antazoey** [comment]
maybe the fix is to actually remove the fee `reward_percentiles` parameter from the arguments list if it is null

**Comment by reedsa** [comment]
Closed in https://github.com/ethereum/web3.py/pull/3185
