### ISSUE TITLE
Update Geth command usage

### ISSUE THREAD

**Issue by reedsa** [ethereum/web3.py#3188]
Newer versions of geth (>= v1.12.x) dropped support for PoW and mining. When invoking geth, some unsupported flags are still used and prevent the test chain from starting.

Basic examples include `--ethash.dagsondisk` and `--miner.etherbase` used within the go_ethereum.py fixture generator.

Several other commands invoke geth within integration tests and should be updated if necessary.

**Comment by fselmo** [comment]
closed by #3191 and #3209
