### ISSUE TITLE
Donating Funds to Web3.py

### ISSUE THREAD

**Issue by Lfada** [ethereum/web3.py#3190]
Hi Web3.py maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[Octant](https://octant.build/) (a project from the Golem Foundation) has been using https://github.com/ethereum/web3.py. It's one of their most critical dependencies!

Octant’s core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it? 
cc: @pipermerriam, @kclowes, @wolovim, @fselmo

**Comment by kclowes** [comment]
Sweet, thanks @Lfada. You can talk to me!

**Comment by Lfada** [comment]
Hey @kclowes 

For Context, this is part of a Dependency Funding initiative to donate/support FOSS repositories. Octant is donating these funds to Web3.py via Drips, which is a continuous streaming and splitting platform. 

What Drips allows you to do, is to claim parts of the donations and then split them into your critical dependencies. A great example is Ethers.js, that's splitting 40% of all incoming funds to their dependencies as you can see [here](https://www.drips.network/app/projects/github/ethers-io/ethers.js)

[Here's](https://www.drips.network/app/projects/github/ethereum/web3.py?exact) Web3.py profile in Drips. A maintainer/admin of this GH repo would need to claim the profile to retrieve the funds. 

For a step-by-step guide on the claim process, watch [this video](https://www.youtube.com/watch?v=AOl_XkgWv-A) and for more detailed information, [here](https://docs.drips.network/claim-your-repository/) you can find the docs. 

Please let me know if you have any questions. Feel free to contact me here or on tw/X: @lukfada

**Comment by Lfada** [comment]
@kclowes let me know if you prefer us to talk on tw, discord, tg, signal...

**Comment by kclowes** [comment]
That sounds great, thanks so much @Lfada! Our team needs to work out a few details around tax implications before we claim the funds. We'll try to get that figured out ASAP, but do the funds expire/do we need to claim them by a certain time?

**Comment by Lfada** [comment]
Hi @kclowes, the funds will be there :) But I must say we would love you to claim as soon as possible. The reason is that if you don't need 100% of those funds, we ask you to split it into your critical dependencies. This way we see a tree of dependency funding flowing to other projects in need of funds. 

Let me know if you have any questions or blockers :)
