### ISSUE TITLE
Generating Signature Error

### ISSUE THREAD

**Issue by Liguangyyu** [ethereum/web3.py#3214]
* Version: 6.14.0
* Python: 3.8
* OS: win11
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?
When I run Generate Signature, I get the message  "AttributeError: SECP256K1_CONTEXT_SIGN"

Please include any of the following that are applicable:

code that generates an error:
private_key = keys
address = add
rqc = "https://rpc.sepolia.org"
w3 = Web3(HTTPProvider(rqc))

msg = Web3.solidity_keccak(['address','uint256'],[address,0])
print(f"Mes:{msg.hex()}")

message = encode_defunct(hexstr=msg.hex())

signed_message = w3.eth.account.sign_message(message,private_key=private_key)
print(f"sig:{signed_message['signature'].hex()}")

Screenshot of the error message
![image](https://github.com/ethereum/web3.py/assets/126438727/31e86f4b-0c52-4083-a0c8-b490602ea019)

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
I cannot reproduce this using Sepolia and the following code:

```py
from eth_account import Account

acct = Account.create()

msg = Web3.solidity_keccak(['address','uint256'],[acct.address,0])
print(f"Mes:{msg.hex()}")

message = encode_defunct(hexstr=msg.hex())

signed_message = w3.eth.account.sign_message(message,private_key=acct.key)
print(f"sig:{signed_message['signature'].hex()}")
