### ISSUE TITLE
Use `Web3Exception` for all exceptions within the library

### ISSUE THREAD

**Issue by fselmo** [ethereum/web3.py#3241]
All exceptions for the library should inherit from `Web3Exception` for UX improvements on user-side exception handling

closes #1864

**Comment by MRLab12** [comment]
@fselmo Hey, I started looking into this and could get a PR up to handle exceptions. I believe we could handle all `ValueError` and `KeyError` exceptions in `web3/manager.py` as suggested in [#1864](https://github.com/ethereum/web3.py/issues/1864).
