### ISSUE TITLE
Add `pop` method to `web3.datastructures.AttributeDict`

### ISSUE THREAD

**Issue by antazoey** [ethereum/web3.py#3326]
### What feature should we add?

Right now, this confusingly fails:

```python
data = eth_tester_provider.web3.eth.get_block("latest")
size = data.pop("size", None)
```

 AttributeError: 'AttributeDict' object has no attribute 'pop'

My workaround is this:

```python
data = {**eth_tester_provider.web3.eth.get_block("latest")}
size = data.pop("size", None)
```

**My feature request is to add the `pop` method to `AttributeDict` so it works the same as regular dicts in that regard.**

**Comment by pacrob** [comment]
`AttributeDict` was created with the idea that it should be immutable. It seems like if you want to pop things from it, copying then popping would be the way to go.
