### ISSUE TITLE
Web3 memory consumption

### ISSUE THREAD

**Issue by mike8368** [ethereum/web3.py#3335]
### What happened?

This code consumes almost 100MB of memory

from web3 import Web3
bsc = "https://bsc-dataseed1.binance.org/"
w3=Web3(Web3.HTTPProvider(bsc))
input("")

Is this normal? How can I reduce memory usage?

### web3 Version
6.16.0

### Python Version
3.9.6

### Operating System
windows

**Comment by fselmo** [comment]
Please use the Discord or another avenue for questions.
