### ISSUE TITLE
Logistics for v4 Development

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#336]
Let's create a plan for developing and releasing version 4.

Proposal: we create a v3 branch for backporting important bugfixes, then implement the planned breaking changes on master for release as v4.

Pull Requests:

 * v4-only changes belong in a PR to master
 * v3 & v4 changes go in a PR to master for review. After green-lit, open another PR to `v3` branch, for insta-merge after tests pass.

Timeline:

 * ~October:
   * Create v3 branch
   * Deprecation warning in v3
   * Start merging in breaking changes to master
 * ~November:
   * Finish breaking change merges to master, then release as v4.0.0-beta
   * Backport any important bugfixes to v3
 * ~December:
   * Normal development progresses on master, delete cruft for backwards-compatible support
   * Release master as v4.0.0-stable
 * ~January: Stop backporting anything but critical security fixes to v3 ([no earlier](https://medium.com/@pipermerriam/dropping-python-2-support-d781e7b48160))
 * ~April: Stop all backporting and support for v3

Prefer to get all breaking changes in before v4-beta, but they _must_ all go in before v4-stable.

To address a couple in-flight projects:

 * steps 1-2 of #294 can go in v3, and step 3 can go in master (v4)
 * #324 is a bit trickier: it would be nice to release in v3, but it depends on an alpha package. Maybe it's best to just go in master, to avoid maintaining a v3-beta branch.

**Comment by pipermerriam** [comment]
This looks solid to me.  Might be good to create some labels for categorizing issues and pull requests.

**Comment by carver** [comment]
v4 launched Apr 2.
