### ISSUE TITLE
Add `blob_versioned_hashes` for EIP-4844 transactions in `transaction` dict

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/web3.py#3392]
### What feature should we add?

If you create the following:

```python
    transaction = {
        "from": from_address,
        "to": to_address,
        "nonce": w3.eth.get_transaction_count(from_address),
        "type": "0x3",
        "blob_versioned_hashes": [
"0x99dc8862181785c55f63ea8006779f872f3a9ef0ad600250473719fb97a828aa53a99bcebadfacaa537ba5b4c8edb22d"
        ],
    }

signed = w3.eth.account.sign_transaction(transaction, private_key)
```

Attempting to sign this transaction will result in:

```
File "/xxx/rlp/sedes/serializable.py", line 51, in validate_args_and_kwargs
    raise TypeError(f"Unknown kwargs: {sorted(unknown_kwargs)}")
TypeError: Unknown kwargs: ['blob_versioned_hashes']
```

However, according to [eip-4844](https://eips.ethereum.org/EIPS/eip-4844#blob-transaction) this should be a supported key in the transaction struct.

**Comment by fselmo** [comment]
@PatrickAlphaC `blob_versioned_hashes` mean nothing without blob data. It's used to communicate solely to the execution layer that blob data was sent and stored in the CL so the API is a bit different in that regard. Please refer to the [blog post](https://snakecharmers.ethereum.org/blobs/) in your previous issue for how to send blob transactions and raise relevant issue in the *eth-account* repository if the API still doesn't seem to be working.

**Comment by fselmo** [comment]
>  if the API still doesn't seem to be working.

And also if you feel like there can be improvements!

**Comment by fselmo** [comment]
I don't believe this should have raised that particular error with "unkown kwarg", however. Make sure *eth-account* version includes the Cancun changes in there and that your *web3* version supports it. But if you are experiencing any strange issues, the [eth-account](https://www.github.com/ethereum/eth-account) repository would be the best place to raise them.

**Comment by PatrickAlphaC** [comment]
I see, thanks!
