### ISSUE TITLE
Padding bytes were not empty: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00A'

### ISSUE THREAD

**Issue by RiddhishLogistic** [ethereum/web3.py#3398]
### What happened?

I'm trying to decode transaction input for trc20 transaction using contract.decode_function_input(transaction["input"]) , it's working for some transaction but for other transaction it gives an error

**Comment by kclowes** [comment]
This is not reproducible. For usage questions, please ask in [the python discord](https://discord.gg/GHryRvPB84).
