### ISSUE TITLE
Support parse human readable function signature to abi json

### ISSUE THREAD

**Issue by yihuang** [ethereum/web3.py#3427]
similar to ethersjs's `parseSignature` function.

**Comment by 0xSt1ng3R** [comment]
+1

[https://github.com/blockpipe/eth-abi-parser](https://github.com/blockpipe/eth-abi-parser)

**Comment by 0xSt1ng3R** [comment]
> +1
> 
> https://github.com/blockpipe/eth-abi-parser

wrote a working lib for that:
https://github.com/0xSt1ng3R/abi-dehumanizer

**Comment by pacrob** [comment]
I think `collapse_if_tuple` from the `eth_abi` [library](https://github.com/ethereum/eth-abi) should solve your problem. Please re-open if not.

**Comment by yihuang** [comment]
> I think `collapse_if_tuple` from the `eth_abi` [library](https://github.com/ethereum/eth-abi) should solve your problem. Please re-open if not.

i think the request is the reverse of `collapse_if_tuple`.
