### ISSUE TITLE
web3 version 7.0.0: what happened to web3.middleware construct_sign_and_send_raw_middleware and pythonic_middleware?

### ISSUE THREAD

**Issue by brent-ridian** [ethereum/web3.py#3461]
### What happened?

Today we tried updating our Python project's requirements.txt files to use the latest version of 3rd party dependencies.

One of the dependencies that got updated was web3 went from version 6.20.2 --> 7.0.0

Our code had this import line that used to work in version 6.20.2:
`from web3.middleware import construct_sign_and_send_raw_middleware, geth_poa_middleware, pythonic_middleware
`

**After the update to version 7.0.0, PyCharm says that all 3 of those items on that import line cannot be found.**

[From this section of the v6 to v7 Migration Guide](https://web3py.readthedocs.io/en/stable/migration.html#middleware-renaming-and-removals), I see that I need to replace
`geth_poa_middleware --> ExtraDataToPOAMiddleware`

_That works._

**The problem is those other 2 middleware:**
`construct_sign_and_send_raw_middleware    and    pythonic_middleware`

I can find no mention of them in the v6 to v7 Migration Guide, nor did a web search find anything related to how they changed in version 7.0.0.

_What happened to them?  Renamed?  Totally removed?_

This change has broke my code.

At a minimum, the v6 to v7 Migration Guide needs to tell me how to cope, and it is a documentation bug that it is currently unmentioned.

### Code that produced the error

```python
from web3.middleware import construct_sign_and_send_raw_middleware, geth_poa_middleware, pythonic_middleware
```

### Fill this section in if you know how this could or should be fixed

Update the v6 to v7 Migration Guide

### web3 Version

7.0.0

### Python Version

3.12.4

### Operating System

win

### Output from `pip freeze`

```shell
I do not feel comfortable posting my project's complete list of dependencies here.

I hope that it is sufficient to note that this is what pip freeze prints regarding web3:

web3==7.0.0
```

**Comment by kclowes** [comment]
Thank you for the report. We will get a PR in ASAP to the migration guide. In the meantime, `pythonic_middleware` -> `PythonicMiddleware`, and `construct_sign_and_send_raw_middleware` -> `SignAndSendRawMiddlewareBuilder`. Docs for SignAndSendRawMiddlewareBuilder are [here](https://web3py.readthedocs.io/en/stable/middleware.html#web3.middleware.SignAndSendRawMiddlewareBuilder)

**Comment by brent-ridian** [comment]
kclowes: thanks much for your speedy response.

Yes, those 2 new renamings now import fine.

From the link that you gave me, I think that I also need to update my code that uses construct_sign_and_send_raw_middleware .

The old line
`self.w3.middleware_onion.add( construct_sign_and_send_raw_middleware(self.account) )`

looks like it should now be:
`self.w3.middleware_onion.add( SignAndSendRawMiddlewareBuilder.build(self.account) )`

My remaining problem is with PythonicMiddleware.

My old line that used it was
`self.w3.middleware_onion.add(pythonic_middleware)`

If I simply try using the new name
`self.w3.middleware_onion.add(PythonicMiddleware)`

then my test code fails with this stack trace:
```
    self.w3.middleware_onion.add(PythonicMiddleware)
  File "C:\brilly\virtualenvs\backend-venv\Lib\site-packages\web3\datastructures.py", line 191, in add
    raise Web3ValueError(
web3.exceptions.Web3ValueError: You can't add the same name again, use replace instead
```

The error message says to use replace instead of add.

I experimented a little, but could not get it to work.

Do you have a suggestion here too?

This as well should be updated in the documentation.

**Comment by brent-ridian** [comment]
I want to follow up on that PythonicMiddleware stack trace that I posted above.

**It seems wrong to me that it prints the error message**
`web3.exceptions.Web3ValueError: You can't add the same name again, use replace instead`

I say this because I added this line of code before the add call:
`print("\n" + f"{self.w3.middleware_onion.middleware = }")`

This new line should print all the existing middleware.  If that error message is really correct, then I should see something related to Pythonic in its output.

But this is what the new line prints (after some hand editing to make it more readable):
```
self.w3.middleware_onion.middleware = [
(<class 'web3.middleware.gas_price_strategy.GasPriceStrategyMiddleware'>, 'gas_price_strategy'),
(<class 'web3.middleware.names.ENSNameToAddressMiddleware'>, 'ens_name_to_address'),
(<class 'web3.middleware.attrdict.AttributeDictMiddleware'>, 'attrdict'),
(<function FormattingMiddlewareBuilder.build at 0x00000267685420C0>, 'validation'),
(<class 'web3.middleware.buffered_gas_estimate.BufferedGasEstimateMiddleware'>, 'gas_estimate'),
(<function FormattingMiddlewareBuilder.build at 0x00000267685420C0>, '
<function FormattingMiddlewareBuilder.build at 0x00000267685420C0>')
]
```

I do not see anything in there related to PythonicMiddleware .

**So, why does the error message tell me that it is already in there, and that I should use replace?**

Or, is it the case that in version 7.0.0 that PythonicMiddleware is always present by default, I no longer need to add it?

**Comment by fselmo** [comment]
@brent-ridian since we can't debug your code directly, breaking it down into a simpler snippet helps us attempt to reproduce it. The simplest example I can think of is importing only the essentials that are giving you issue and debugging any problems that arise. However, I cannot reproduce what you are seeing by running the following snippet, and I will ask you to try the same. Are you certain that your code is not attempting to add this middleware more than once?

```py
from web3 import Web3
from web3.middleware import PythonicMiddleware

w3 = Web3(Web3.HTTPProvider(...))
w3.middleware_onion.add(PythonicMiddleware)  # no issues

# adding the following gives the error you are seeing:
# w3.middleware_onion.add(PythonicMiddleware)  # attempt to add the middleware once more
```

> Or, is it the case that in version 7.0.0 that PythonicMiddleware is always present by default, I no longer need to add it?

This is not the case.

**Comment by brent-ridian** [comment]
fselmo, thanks much for getting back to me.

A stripped down version of our web3 code (e.g. removing comments, arg checks, log lines--but not removing any web3 code) is this:
```
def __init__(self, contract_address: Optional[Union[Address, ChecksumAddress, ENS]], contract_abi: any) -> None:
	self.w3: Web3 = Web3( Web3.HTTPProvider(self.POLYGON_INFURA_URL) )
	
	self.w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer = 0)
	
	self.w3.middleware_onion.add(PythonicMiddleware)
	
	self.account: LocalAccount = self.w3.eth.account.from_key(self.POLYGON_ACCOUNT_PRIVATE_KEY)
	
	self.w3.middleware_onion.add( SignAndSendRawMiddlewareBuilder.build(self.account) )
	
	self.contract: Contract = self.w3.eth.contract(address = contract_address, abi = contract_abi)
```

That code (using the old names) worked fine in web3 version 6.20.2.

In web3 version 7.0.0, it fails on the line
`self.w3.middleware_onion.add(PythonicMiddleware)`

with the error message
`web3.exceptions.Web3ValueError: You can't add the same name again, use replace instead`

Comparing my code to yours, note that my first middleware call is to
`self.w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer = 0)`
which your example code lacks.

I hope that this allows you to reproduce the error.

**Comment by fselmo** [comment]
This closed automatically. Re-opening since this isn't yet resolved.

**Comment by fselmo** [comment]
Thanks @brent-ridian that did help to reproduce. It looks like unnamed builder classes are getting the same name assigned under the hood. For now, you can get unstuck by giving an explicit `name` to each of the middleware:

```py
from web3 import Web3
from web3.middleware import (
    ExtraDataToPOAMiddleware,
    PythonicMiddleware,
)

w3 = Web3(Web3.HTTPProvider(...))
w3.middleware_onion.inject(ExtraDataToPOAMiddleware, name="extradata_to_poa", layer=0)
w3.middleware_onion.add(PythonicMiddleware, "pythonic")
```

Thanks again for submitting. We'll get a fix in asap 👌🏼

**Comment by bh0717-dev** [comment]
from web3.middleware import ExtraDataToPOAMiddleware
web3.middleware_onion.inject(ExtraDataToPOAMiddleware, name="extradata_to_poa", layer=0)

I am getting same issue now.
Here is my issue.
The field extraData is 278 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#proof-of-authority for more details.

I'd really appreciate if someone could help me solve this issue.

**Comment by fselmo** [comment]
@bh717 This is not the same issue. There are tests for the `ExtraDataToPOAMiddleware` and a simplified snippet does not yield any errors. Please run the following snippet and grow the complexity from there to mimic your setup.

```py
from web3 import Web3
from web3.middleware import ExtraDataToPOAMiddleware

w3 = Web3(Web3.HTTPProvider(provider_url))
w3.middleware_onion.inject(ExtraDataToPOAMiddleware, name="extradata_to_poa", layer=0)
w3.eth.block_number
```

Please open a new issue in this repository if you do find a bug. As it stands, I cannot reproduce what you are seeing. Best of luck.

**Comment by brent-ridian** [comment]
fselmo: I can verify that your suggestion to use a name arg as a temporary work around of the bug works.

Looking forward to the bug fix version.

Thank you for all your hard work.  If you ever make it out to Miami, your first 10 beers are on me.

**Comment by fselmo** [comment]
Thanks again @brent-ridian. *web3.py* [v7.1.0](https://web3py.readthedocs.io/en/latest/release_notes.html#web3-py-v7-1-0-2024-08-28) was just released with this fix.
