### ISSUE TITLE
The field extraData is 278 bytes, but should be 32. It is quite likely that you are connected to a POA chain.

### ISSUE THREAD

**Issue by bh717** [ethereum/web3.py#3464]
### What happened?

Now I am getting this error message.
The field extraData is 278 bytes, but should be 32. It is quite likely that you are connected to a POA chain.

Here is my current code.
from web3 import Web3
from web3.middleware import ExtraDataToPOAMiddleware
INFURA_URL = os.getenv('BSC_TESTNET_INFURA_URL')
web3.middleware_onion.inject(ExtraDataToPOAMiddleware, name="extradata_to_poa", layer=0)
web3.eth.block_number

I'd really appreciate it if someone could help me for solve this problem.

**Comment by fselmo** [comment]
I can't reproduce this. I see the same problem was asked on Discord and others can't reproduce as well. Discord is a good place to keep your conversation going. If this issue persists, don't hesitate to ask to re-open.

```py
In [1]: from web3 import Web3
   ...: from web3.middleware import ExtraDataToPOAMiddleware
   ...: 
   ...: w3 = Web3(Web3.HTTPProvider('https://bsc-testnet-rpc.publicnode.com'))
   ...: w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)

In [2]: w3.eth.block_number
Out[2]: 43349001

In [3]: latest_block = w3.eth.get_block('latest')
   ...: base_fee = latest_block['baseFeePerGas']
   ...: w3.eth.max_priority_fee
Out[3]: 5000000000
```
