### ISSUE TITLE
Make `HTTPProvider.get_request_headers()` a class-level method

### ISSUE THREAD

**Issue by antazoey** [ethereum/web3.py#3466]
### What feature should we add?

At the time of writing this issue, the method is defined here:
https://github.com/ethereum/web3.py/blob/main/web3/providers/rpc/rpc.py#L119-L123

It is:

```python
    def get_request_headers(self) -> Dict[str, str]:
        return {
            "Content-Type": "application/json",
            "User-Agent": construct_user_agent(str(type(self))),
        }
```

I am requesting this method be exposed at the class-level, to be re-written as:

```python
    @classmethod
    def get_request_headers(cls) -> Dict[str, str]:
        return {
            "Content-Type": "application/json",
            "User-Agent": construct_user_agent(str(cls)),
        }
```

Use-case: This allows me to grab the default headers _before_ constructing an `HTTPProvider` object for the purpose of modifying them / appending to them, without having to redefine.

**Comment by kclowes** [comment]
Yep, we can do that!

**Comment by fselmo** [comment]
@antazoey this was just released in *web3.py* `v7.2.0` in case you need to reach for it.

**Comment by antazoey** [comment]
> @antazoey this was just released in *web3.py* `v7.2.0` in case you need to reach for it.

Thanks, for reasons of my own doing, we are not able to officially update web3.py until Ape's 0.9 release
