### ISSUE TITLE
Support for fallback functions

### ISSUE THREAD

**Issue by Aviah** [ethereum/web3.py#353]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?
Web3 currently supports only named functions

### How can it be fixed?
Add a ```fallback``` arg to ```call``` and ```transact```
```def call(self, transaction=None, fallback=False)```
```def transact(self, transaction=None, fallback=False```
when callings with ```contract.transact({...},fallback=True)```, send the transaction directly

**Comment by carver** [comment]
Sounds good. I'll toy with this and other API options.

---

For others who come across this issue, the way to accomplish this in the meantime is:

```python
w3.eth.sendTransaction({'to':contractAddress})
```

**Comment by carver** [comment]
@Aviah What do you think about this API?

```
contract.sendTransaction({...})
```

I like that it:

 * is consistent with the `w3.eth.sendTransaction(...)` API
 * doesn't break the invariant that `contract.transact({...})` returns an object with callable attributes.

I don't like that:

`sendTransaction` might not be the first name users think of when figuring out how to trigger `function() { ... }` in their Solidity contract. An alternative would be something like `contract.fallback({...})`, although that word isn't used in Solidity syntax, either.

**Comment by carver** [comment]
#419 Is going to resolve this by introducing `contract.fallback.transact()`
