### ISSUE TITLE
Filters don't last very long

### ISSUE THREAD

**Issue by bamos01** [ethereum/web3.py#354]
* Version: web3.py
* Python: 3.5
* OS: linux

### What was wrong?

i am running a script that that creates a web3.eth.filter('pending') and uses it to listen to all incoming transactions,  It is set up to run indefinitely.  It works fine for about 2-3 hours but then it starts to fail with "filter not found" exceptions or sometimes without any exception.  the node is working fine.

Any advice?

Thanks

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
That exceptions indicates that your node has dropped the filter.  There is work underway to revamp the filter api via #294 

In the meantime, I would recommend adding an additional wrapper that catches this exception and re-installs the filter.

**Comment by bamos01** [comment]
Thanks - I was able to do that - but one complication was that even after filter was dropped - the call to filter.running still returned true  - this makes it hard to detect when dropped

**Comment by bamos01** [comment]
Also - not trivial to catch an exception that occurs in a thread - would appreciate any input on how to do this with the filter.

**Comment by pipermerriam** [comment]
I'd suggest not using the `watch` API and using the `filter.get` API directy.  That lets you control the whole API and put it all in one thread rather than having to watch a thread and re-initialize it.  Does that help?

**Comment by djrtwo** [comment]
Should this be closed due to the removal of asynchronous filters?
