### ISSUE TITLE
Replace `black`, `isort` and `flake8` with `ruff`

### ISSUE THREAD

**Issue by souliane** [ethereum/web3.py#3552]
### What feature should we add?

https://github.com/astral-sh/ruff can advantageously replace those 3, it does the work faster and better (auto-fixes...).

**Comment by pacrob** [comment]
Thanks for the idea, @souliane. We're watching the python packaging world -  both `ruff` and `uv` are getting attention. We will likely our tooling in the future, but have no plans to do so soon.
