### ISSUE TITLE
ENS .eth Registrar Integration

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#379]
Add in the ENS .eth Registrar functionality. #342 only needed the resolver setup and lookup.

Participating in the .eth auctions can be added after the v4 beta launches, without disruption. The main thing that held up this functionality inclusion in #343 was building out a cleaner test suite (with integrated tests, and minimal mock usage).

**Comment by pipermerriam** [comment]
Not sure if this is useful, but you could theoretically leverage some of the python3 async to deal with the *waiting* for transactions part.

**Comment by marcgarreau** [comment]
**[old issue cleanup]**

My gut is that Web3.py probably shouldn't have primitives for leasing ENS names, and that functionality should remain with the ENS app (or be built as needed by dapp devs). Agree/disagree? Is there any other functionality included in "Registrar Integration" that should be considered?

**Comment by carver** [comment]
Yup, agree. At most, maybe it's useful to know if/when a lease on a name ends, because it can affect how trustworthy a name is. (Maybe we ought to reject resolving names where ownership has already expired, for example).

But that's a pretty advanced feature, and belongs far enough down on the priority list that it should just be re-opened as an issue when it's time.
