### ISSUE TITLE
Add new Filter examples to docs

### ISSUE THREAD

**Issue by djrtwo** [ethereum/web3.py#394]
### What was wrong?

New Filter API does not have any examples in the docs. Could use some synchronous and a-synchronous examples.

### How can it be fixed?
Add some examples!

*Potential Examples*
- How to wrap a filter in a thread.
- How to listen for new pending transactions.
- How to listen for newly mined blocks.
- How to manually filter for log entries (not using a contract)
- How to filter for a Contract instance's log entries.

**Comment by carver** [comment]
Can you also add a deprecation warning to async usages on the `v3` branch? (noting that the synchronous version is coming in v4)

**Comment by dylanjw** [comment]
Fixed in #631
