### ISSUE TITLE
Add custom parity shh module

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#403]
* Version: 4

### What was wrong?

The parity whisper api has drifted from the globally defined json-rpc api.

See #384 

### How can it be fixed?

Write a custom parity whisper module, noting the drift. It should not be added as a default Web3 submodule.

**Comment by ConnorChristie** [comment]
Resolved by #784?

**Comment by carver** [comment]
It was built using the geth APIs. I'm not certain Parity is API-compatible.

I would want to see a parity integration test before closing this. (but #402 looks good :+1: )

**Comment by marcgarreau** [comment]
`wontfix`, because Whisper is now gone from both Geth and OpenEthereum/Parity.
