### ISSUE TITLE
Security Audit on web3.eth.account and ethereum-keys

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#431]
Before going v4-stable

**Comment by marcgarreau** [comment]
**[old issue cleanup]**

Not sure of all the context here, but if any action still required, it should be tracked in the relevant libs.

**Comment by carver** [comment]
Yeah, it's fine. Apart from forgetting about it, I think the only to-do left is to publish the audit. Unfortunately, the audit was tied to web3.js, which never really got resolved. Anyway, :+1: to close.
