### ISSUE TITLE
Edit link on stable docs is dead

### ISSUE THREAD

**Issue by techtonik** [ethereum/web3.py#464]
### What was wrong?

1. Go http://web3py.readthedocs.io/en/stable/
2. Click Edit link

### How can it be fixed?

Can be fixed upstream. https://github.com/rtfd/readthedocs.org/pull/3302

**Comment by carver** [comment]
This appears to be fixed upstream, thanks @techtonik !

Now, when I click edit on the stable documentation, it takes me to the commit on the latest stable tag.

Please re-open explaining expected behavior if I missed something.
