### ISSUE TITLE
`web3.utils.events.get_event_data` is rather slow

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/web3.py#469]
* Version: 3.16.3
* Python: 3.5
* OS: linux

### What was wrong?

Processing events with `web3.utils.events.get_event_data` takes a rather long time, in the order of 1ms per event. This becomes quickly noticeable, when trying to decode event data for thousands of events. 

Please see my benchmarking script & output at https://gist.github.com/konradkonrad/87d76dd2526f39e6f5bad19b85374948

### How can it be fixed?

I don't want to rule out any user error here -- maybe there is a more efficient way to parse events data?

**Comment by pipermerriam** [comment]
At a glance, there may be *some* low hanging fruit in there:

I know there is in-efficiency in the address utilities that could probably be optimized.

```
   110000    0.079    0.000    2.413    0.000 /usr/local/lib/python3.5/site-packages/web3/utils/abi.py:464(map_to_typed_data)
    30000    0.021    0.000    2.259    0.000 /usr/local/lib/python3.5/site-packages/web3/utils/normalizers.py:7(addresses_checksummed)
    20000    0.052    0.000    2.115    0.000 /usr/local/lib/python3.5/site-packages/eth_utils/address.py:124(to_normalized_address)
10000 0.065 0.000 2.007 0.000 /usr/local/lib/python3.5/site-packages/eth_utils/address.py:176(to_checksum_address)
```

Also the use of `coerce_return_to_text` and other related utils are both slow and recently discovered to be *wrong* and capable of returning string data encoded as latin-1 which is very confusing.
