### ISSUE TITLE
PyInstaller error: ModuleNotFoundError: No module named 'cytoolz.utils'

### ISSUE THREAD

**Issue by wcraig2012** [ethereum/web3.py#484]
* Version: 4.0_b3
* Python: 3.6
* OS: win
Both using "from web3 import Web3, HTTPProvider, IPCProvider" in a python script and running the script are ok.
But when using the pyinstaller to transfer the script into .exe file, it goes run with error:"ModuleNotFoundError: No module named 'cytoolz.utils',
[17504] Failed to execute script t2"
Does anybody know anything about this?
I'm in a hurry.Thanks a lot.

**Comment by carver** [comment]
I don't see cytoolz on the list of `pyinstaller`'s supported packages: https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages

Other than that quick google result, I'm not familiar with the project. It sounds like something you'd have to ask them about.

**Comment by wcraig2012** [comment]
Is there any other method of changing the script into .exe file with web3.py package?

**Comment by pipermerriam** [comment]
@wcraig2012 the `toolz` library is a drop in replacement for `cytoolz`.  You should be able to swap them out for each other and the `toolz` one does not use C-extensions.
