### ISSUE TITLE
Investigate switching go-ethereum integration tests to use POA dev chain

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#507]
### What was wrong?

The integration tests against go-ethereum currently use a POW chain.  This means that we cannot reasonably test anything in our CI environment that requires a block to be mined *during* the test suite run.

### How can it be fixed?

I *think* newer versions of geth support POA dev chains which in-turn I *think* support on-demand block mining.

If this is the case, we should convert that the test suite to make use of a dev POA chain so that we can better test *things*

**Comment by carver** [comment]
One issue here (that has to be solved anyway) is that the geth dev chain uses a non-compliant amount of `extraData`, much more than 32 bytes. So we have to decide if we want to accept invalid `extraData` when parsing block results.

**Comment by marcgarreau** [comment]
**[old issue cleanup]**

Closing due to age; testing infra must have evolved a ton since this was written. New issue warranted if necessary.
