### ISSUE TITLE
Add caching middleware

### ISSUE THREAD

**Issue by kevinday** [ethereum/web3.py#510]
### What was wrong?

Please include any of the following that are applicable:

For dapps that aggressively poll for state, adding a caching layer can greatly help to reduce the load that gets put on the node. This is implemented as a [subprovider](https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js) in web3.js, and it would be great if something similar existed in web3.py

### How can it be fixed?

web3.py should have an optional middleware that caches rpc requests and gets invalidated on new blocks or reorgs.

**Comment by carver** [comment]
Closed by #534
