### ISSUE TITLE
web3.eth.estimateGas is broken

### ISSUE THREAD

**Issue by bolshoy** [ethereum/web3.py#512]
* Version:3.16.4
* Python: 2.7
* OS: osx

### What was wrong?

`web3.eth.estimateGas` raises `'<function apply_formatters_to_dict at 0x10ac79758> is not JSON serializable`

**Comment by pipermerriam** [comment]
@bolshoy can you provide a bit more context.  

* Code that triggered this error
* Full stacktrace of the error

**Comment by bolshoy** [comment]
@pipermerriam 
the code was similar to this:
```python
    def estimate_tx_gas(self, tx):
        gas_buffer = 10000 if tx['data'] else 5000
        try:
            from web3.utils.transactions import get_buffered_gas_estimate
            return get_buffered_gas_estimate(self.web3, tx, gas_buffer=gas_buffer)
        except Exception as e:
            logging.warning('cannot estimate gas for transaction: ' + str(e))
            return DEFAULT_GAS_PER_TX
```
have no stacktrace, I removed it already

**Comment by bolshoy** [comment]
this was caused by a string 'value' in transaction instead of integer, closing the issue.
