### ISSUE TITLE
AttributeError calling watch() on a BlockFilter instance

### ISSUE THREAD

**Issue by miller46** [ethereum/web3.py#522]
* Version: 4.0.0b4
* Python: 3.6.3
* OS: osx

I am attempting to listen for new blocks as they are added to the network.  I attempt to set up a blockfilter like so:

```
block_filter = self.web3.eth.filter('latest')
block_filter.watch(new_block_callback)
```

and I receive the following error:

`
AttributeError: 'BlockFilter' object has no attribute 'watch'
`

Am I doing something wrong?  This worked for me previously with an earlier version of web3.py, and this is nearly identical to the example in the docs.

**Comment by carver** [comment]
Ah thanks for pointing that out. The examples that use `watch()` should be changed in the latest documentation.

Note the deprecation warning above `watch()` in the stable docs, and that `watch()` is no longer listed in the latest docs:
-http://web3py.readthedocs.io/en/stable/filters.html#web3.utils.filters.Filter.watch
-http://web3py.readthedocs.io/en/latest/filters.html

Instead, you should periodically call `get_new_entries()` to see the latest filter results. It works just like the log filter: http://web3py.readthedocs.io/en/latest/filters.html#web3.utils.filters.LogFilter.get_new_entries

---

I'll leave the issue open until the docs are updated.
