### ISSUE TITLE
Add section to docs about contract argument types

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#527]
* Version: 4

### What was wrong?

Which argument types to pass in are never explicitly stated. Many people try to pass in hex strings to ABI `bytes*` types, which doesn't work in v3. It works in v4, and should be more natural, but should still be documented

### How can it be fixed?

Add a section to the docs describing which native types correspond to which ABI types in contract arguments.

**Comment by wcraig2012** [comment]
thank a lot
