### ISSUE TITLE
Instruction for installation in windows?

### ISSUE THREAD

**Issue by jorgeog96** [ethereum/web3.py#532]
* Version: x.x.x
* Python: 3.6
* OS: win10

### What was wrong?

Please guys, can you type a little guide talking about install web3.py in a windows machine, for example, using PowerShell. Also, give a complete list of required tools.

**Comment by carver** [comment]
At this point, it seems likely that the windows install simply doesn't work, since the Windows CI is failing: #166 

Once that's successful, then we should revisit if any Windows-specific instructions are necessary.

**Comment by jorgeog96** [comment]
Yesterday late, I could install web3.py directly on my windows machine. 
SO. Windows 10 64 bits

-Install latest version python for windows 64bits, in this case, python 3.6.

-Check if "python" is an environment variable or not, typing python on the cmd console in my case.

-If the console doesn´t recognize the command python giving you the version, you have to add the variable to environment variable and PATH. Python provides a tool for this purpose in this directory: Appdata->Local->Programs->Python->Python36-32->Tools->Scripts->win_add2path.py 
Sometimes this tool doesn´t work, so in that case, you have to add manually the variable to PATH.

-After had done that process, you cmd should recognize your python version.Furthermore, he should recognize also pip package manager high-tool for python. I prefer use pip versus virtualenv. 

-Next step, it's installed Visual C++ Build Tools 2d5 on your windows machine, if you didn´t have installed before. You need that tool in the process of web3.py installation. 

-pip install web3. 

I also have node.js and npm installed on my device, I don´t know if those tools have something related to this process. 

I don´t know if these steps are correct or not, but for me, the installation didn´t give me any error.

**Comment by carver** [comment]
Thanks for writing these down. Any interest in contributing them to the public docs where they will get a lot more visibility? We'd love to have your contribution.

> I prefer use pip versus virtualenv.

The real magic is when you use these two together. Use pip inside of an environment made with virtualenv to get a reproducible set of libraries that you know is the same as everyone else.
