### ISSUE TITLE
How to transfer private key(byte) into hex string?

### ISSUE THREAD

**Issue by wcraig2012** [ethereum/web3.py#539]
* Version: 4.0.0 b4
* Python: 3.6
* OS: win

Could you please tell me how to transfer private key into hex string?
Like changing b"\xb2\\}\xe4\xc4rm\x03[6\xec\xf1\xe5\xb3d........" into "0x........".
Thanks a lot.

**Comment by carver** [comment]
You can convert many different formats (including `bytes`) into a hex string with: http://web3py.readthedocs.io/en/latest/overview.html#Web3.toHex

FYI, most of the functions in web3.eth.account accept either `bytes` or a hex string. See http://web3py.readthedocs.io/en/latest/web3.eth.account.html#web3.account.Account.signTransaction for example.

**Comment by wcraig2012** [comment]
thank a lot
