### ISSUE TITLE
any plan to support parity specific methods?

### ISSUE THREAD

**Issue by guanqun** [ethereum/web3.py#544]
This is not a bug report, so I removed the template...

I'd like to know if we have any plans to support parity specific RPC calls as listed here: https://paritytech.github.io/wiki/JSONRPC-parity-module

I searched the issue list and didn't find any previous discussion about this.

Is this https://github.com/ethereum/web3.py/issues/381 a prerequisite?

**Comment by pipermerriam** [comment]
We do support custom modules though it's not documented.

See:

- https://github.com/ethereum/web3.py/blob/master/web3/module.py
- https://github.com/ethereum/web3.py/blob/master/web3/main.py#L106-L110

If you wanted to implement a `Parity` module I think we'd be open to including it as a non-default module that users could *opt-in* to including in the modules list.

**Comment by guanqun** [comment]
Thank you for the response, I'd like to add some support for Parity, as my current project depends on that.
