### ISSUE TITLE
Events are basically undocumented

### ISSUE THREAD

**Issue by posix4e** [ethereum/web3.py#550]
* Version: * (3x)
* Python: * (3.5)
* OS: * (linux)

### What was wrong?
It's not clear to me that it's documented how to do anything other than print that events happend. Decoding it seems very difficult.

### How can it be fixed?
Someone can provide an example here and I will update the docs.

```
  logs = W3.eth.getFilterLogs(filter_.filter_id)
    for log in logs:

        print("#topics:{}".format(len(log['topics'])))
        for topic in log['topics']:
            try:
                print("topic:{}".format(W3.toText(topic)))
            except UnicodeDecodeError:
                pass

```
Can never translate the topic to text, even if i pass it arguments of the correct type

**Comment by IridiumMaster** [comment]
Just to comment on this myself...
I created and deployed the following code along the lines of the quickstart.
`pragma solidity ^0.4.0;

contract aClaimsV4 {
    string public greeting;
    event contractStringChanged(string change);
    
    function aClaimsV4() public {
        greeting = 'Hello';
    }

    function setGreeting(string _greeting) public {
        greeting = _greeting;
        contractStringChanged(_greeting);
    }

    function greet() public constant returns (string) {
        return greeting;
    }
}`

I then accessed it using the following Python program:
`import json
import web3
import sys

from web3 import Web3, HTTPProvider, TestRPCProvider
from solc import compile_source
from web3.contract import ConciseContract
from web3 import IPCProvider
from web3 import utils
from web3.utils import filters
from web3.utils.filters import LogFilter
from web3.utils import events
from web3 import eth
'''
Requires launching geth with the following parameters
geth -rinkeby
Then attach to it via:
geth attach /home/travistheadmin/.ethereum/rinkeby/geth.ipc

and run this command
admin.startRPC("localhost", 8545, "*", "web3,personal,admin,debug,db,net,eth,miner,rpc,txpool")
'''
provider = HTTPProvider('http://localhost:8545')
web3 = Web3(provider)
web3.personal.unlockAccount('MY-ACCOUNT-ADDRESS', 'MY-PASSWORD')
abiDef = '[ { \"constant\": false, \"inputs\": [ { \"name\": \"_greeting\", \"type\": \"string\" } ], \"name\": \"setGreeting\", \"outputs\": [], \"payable\": false, \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"constant\": true, \"inputs\": [], \"name\": \"greet\", \"outputs\": [ { \"name\": \"\", \"type\": \"string\", \"value\": \"Hello\" } ], \"payable\": false, \"stateMutability\": \"view\", \"type\": \"function\" }, { \"constant\": true, \"inputs\": [], \"name\": \"greeting\", \"outputs\": [ { \"name\": \"\", \"type\": \"string\", \"value\": \"Hello\" } ], \"payable\": false, \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [], \"payable\": false, \"stateMutability\": \"nonpayable\", \"type\": \"constructor\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": false, \"name\": \"change\", \"type\": \"string\" } ], \"name\": \"contractStringChanged\", \"type\": \"event\" } ]'
abiFinal = json.loads(abiDef)
contractAddress = 'MY-CONTRACT-ADDRESS'
web3.eth.defaultAccount = 'MY-ACCOUNT-ADDRESS'
web3.eth.defaultBlock = "latest"
myContract = web3.eth.contract(abi=abiDef, address=contractAddress)

contract_instance = web3.eth.contract(abiFinal, contractAddress, ContractFactoryClass=ConciseContract)
contract_instance.greet()

contract_instance.setGreeting('I changed this value to something else', transact={'from': web3.eth.accounts[0]})

f2 = web3.eth.filter({'address': contractAddress, 'fromBlock':1570338});
myLogs = web3.eth.getFilterLogs(f2.filter_id)`

Decoding the text using web3.toText results in strings with a lot of random padding, along the lines of:

>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00 >\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00I changed this value to something else

**Comment by posix4e** [comment]
This was actually enough explanation for me to get going. Perhaps we can get some of this in a doc,especially with the work to do. Now all i have to do is figure out how filter event params.

**Comment by IridiumMaster** [comment]
Ha ha ha, glad to hear it. But did you find any function that cleanly removes the padding from the data field? I've been playing with various things with no luck. I'm reluctant to just regex it.

**Comment by posix4e** [comment]
```
def _get_all_manifests():
    filter_ = W3.eth.filter({})
    logs = W3.eth.getFilterLogs(filter_.filter_id)
    for log in logs:
        try:
            print("Pending:{}".format(get_event_data(pending_api, log)['args']['manifest']))
        except:
            pass
```
Worked for print args

**Comment by IridiumMaster** [comment]
What are you using for your abi definition? Did you hand code it? I'm using the definition from the Mist ethereum wallet export and get_event_data blows up. Here's my example code with all relevant strings embedded. :

`abiDef = '''
[ { "constant": false, "inputs": [ { "name": "_greeting", "type": "string" } ], "name": "setGreeting", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "greet", "outputs": [ { "name": "", "type": "string", "value": "Hello" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "greeting", "outputs": [ { "name": "", "type": "string", "value": "Hello" } ], "payable": false, "stateMutability": "view", "type": "function" }, { "inputs": [], "payable": false, "stateMutability": "nonpayable", "type": "constructor" }, { "anonymous": false, "inputs": [ { "indexed": false, "name": "change", "type": "string" } ], "name": "contractStringChanged", "type": "event" } ]
'''

result = '''
[{'address': '0xA89628b286F7BFB5A84c0bc41c73392D758BF12D',
  'blockHash': '0xe40abe1c2119710c4234d7f1bee2c453c0d472ce583c656928e00918537d1d9d',
  'blockNumber': 1581187,
  'data': '0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000065472617669730000000000000000000000000000000000000000000000000000',
  'logIndex': 0,
  'removed': False,
  'topics': ['0x8d2fb3b836f237c6c5dd7197ff087c079ff881bd0e921b55a3ca39546cf62043'],
  'transactionHash': '0x84d7e3276aefd8b1aea5bc71dcf813458405132dcbe03e7419e2d3819123d7ca',
  'transactionIndex': 0},
 {'address': '0xA89628b286F7BFB5A84c0bc41c73392D758BF12D',
  'blockHash': '0x48c14d8f46e1bff6a84e868616eacc00da62d63dd5234ee08840eefb57d13a86',
  'blockNumber': 1581225,
  'data': '0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002649206368616e67656420746869732076616c756520746f20736f6d657468696e6720656c73650000000000000000000000000000000000000000000000000000',
  'logIndex': 0,
  'removed': False,
  'topics': ['0x8d2fb3b836f237c6c5dd7197ff087c079ff881bd0e921b55a3ca39546cf62043'],
  'transactionHash': '0xe5cf7e267873250dbd95e69c363aa560200fe1c4fc5a980ffb061a2ffafb8211',
  'transactionIndex': 0}]
'''


for log in result:
            get_event_data(log_entry = log, event_abi=abiDef)`

**Comment by carver** [comment]
Yes, events can clearly use a lot of work. I'll leave this issue open as a workaround thread. But the full solution is being discussed in #429, and @dylanjw is just starting to take a look.

---

@IridiumMaster FYI, code blocks happen with triple ticks at the beginning and end. You can get python formatting with:

```
> ```py
> code here
> ```
```

I updated your comments.

**Comment by nueverest** [comment]
I used an abi in array form **not** string form and it worked.  You need to capitalize `true` and `false` if you do this.  I'm impressed.

```
contract_abi = [{"constant":True,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"from","type":"address"},{"name":"amountToBurn","type":"uint256"}],"name":"burnTokens","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"initialSupply","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCall","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"treasuryFee","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"target","type":"address"},{"name":"mintedAmount","type":"uint256"}],"name":"mintTokens","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":False,"stateMutability":"nonpayable","type":"constructor"},{"payable":False,"stateMutability":"nonpayable","type":"fallback"},{"anonymous":False,"inputs":[{"indexed":True,"name":"from","type":"address"},{"indexed":True,"name":"to","type":"address"},{"indexed":False,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"from","type":"address"},{"indexed":False,"name":"value","type":"uint256"}],"name":"Burn","type":"event"}]
```

**Comment by araa47** [comment]
Did anyone figure this out yet? @nueverest I have tried using both the list format with capitalizing true and false so python doesn't complain and I have tried the string format as used by @IridiumMaster . I am however still running into the same problem. 

```
Traceback (most recent call last):
  File "eventlistener.py", line 75, in <module>
    print (get_event_data(abi, str(log)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/utils/events.py", line 154, in get_event_data
    if event_abi['anonymous']:
TypeError: list indices must be integers or slices, not str
```


Code to set up everything:

```
import json
import web3
from web3 import Web3, HTTPProvider, TestRPCProvider


w3 = Web3(HTTPProvider(url))
from web3.utils.events import get_event_data

contract_address = "mycontract"
abi = "abi"

f2 = w3.eth.filter({'address': contract_address, 'fromBlock':1570338});
myLogs = w3.eth.getFilterLogs(f2.filter_id)
print(myLogs)
for log in myLogs:
   print (get_event_data(abi, str(log)))
  
```

**Comment by araa47** [comment]
Hey guys, so after some more messing around I solved the errors. 

1) The ABI must be is list format, not string format! 
2) The ABI of a contract actually is a list containing different dictionaries inside. You will need to see which ABI corresponds to your event based on 'name' and 'type' values in the ABI. 
3) Once you identify which event you are looking for you use the same code but only pass the abi specific to this event. Any other events might fail in parsing but all the correct events should be correctly parsed and data returned. 

ABI example
```
contract_abi = [{"constant":True,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"from","type":"address"},{"name":"amountToBurn","type":"uint256"}],"name":"burnTokens","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"initialSupply","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCall","outputs":[{"name":"success","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"treasuryFee","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"target","type":"address"},{"name":"mintedAmount","type":"uint256"}],"name":"mintTokens","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":False,"stateMutability":"nonpayable","type":"constructor"},{"payable":False,"stateMutability":"nonpayable","type":"fallback"},{"anonymous":False,"inputs":[{"indexed":True,"name":"from","type":"address"},{"indexed":True,"name":"to","type":"address"},{"indexed":False,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"from","type":"address"},{"indexed":False,"name":"value","type":"uint256"}],"name":"Burn","type":"event"}]

```

Let's say the event you are looking for is called "Burn", so you look through the above ABI for this event, you will see it is the last entry in the list so we can call this abi[18] which is the exact ABI for the event. 

Now finally we modify the code slightly 

```
for log in myLogs:
   try:
       print (get_event_data(abi[18], str(log)))
   except Exception as e:
       print(e)
```

Finally no more errors :)

**Comment by carver** [comment]
> The ABI must be is list format, not string format!

It should work in both, as long as the string is a valid ABI in serialized json format. If you have a valid ABI as a string that fails somehow, would you open a new issue with an example?

> Once you identify which event you are looking for you use the same code but only pass the abi specific to this event.

All of this manual workaround shouldn't be necessary anymore, if you use a filter generated by the contract object. Try the event style mentioned here: http://web3py.readthedocs.io/en/latest/contracts.html#web3.contract.ContractEvents.myEvent

The rich logs have the arguments already parsed.

**Comment by davehcker** [comment]
For those getting `TypeError: string indices must be integers` and following everything right as: `get_event_data(abi[18], str(log))`, it's because the log is supposed to be a dict and not a `str`. Run as `get_event_data(abi[18], log)` instead.

**Comment by marcgarreau** [comment]
**[old issue cleanup]**

Always room for improvement, but events and filters are better documented these days. Please open another issue for any new bugs.
