### ISSUE TITLE
Trouble getting new events

### ISSUE THREAD

**Issue by glhahn** [ethereum/web3.py#564]
Version: 4.0.0b5
Python: 3.6
OS: OS X

Hi, thanks for the great library. I'm having trouble with getting new events. I haven't been able to get it to work at all with ganache-cli and I can only get previous events when testing with a geth private network.

I'm using a smart contract that simply takes some data and creates an event with it. Example:
```

event UpdatedData(address addr, uint32 data, uint64 timestamp);

function updateData(uint32 data, uint64 timestamp) public {
    UpdatedData(msg.sender, data, timestamp);
}
```

Here's the function I call in my web3.py script to get all events:

```
def process_past_events(contract, event_name):
    event_filter = contract.eventFilter(event_name, {'fromBlock': 0})
    events = event_filter.get_all_entries()
    print_events(events)
```

This is the function that is periodically called to try and get new events:

```
def process_new_events(contract, event_name):
    event_filter = self.contract.eventFilter(event_name, {})
    events = event_filter.get_new_entries()
    print_events(events)
```

That first function works great with the geth private network, but I can't get new events. Neither seems to work at all with ganache-cli. I've also tried different filtering parameters with no luck. Any idea what I'm doing wrong? Thanks!

**Comment by carver** [comment]
Excellent writeup.

Here's your issue:

```py
def process_new_events(contract, event_name):
    event_filter = self.contract.eventFilter(event_name, {})  # <- this installs a new filter each time
    events = event_filter.get_new_entries()  # <- the freshly installed filter will not have any new entries
    print_events(events)
```

What you want to do is create the filter once, save the `event_filter` instance, and then call `events = event_filter.get_new_entries()` on it over and over again.
