### ISSUE TITLE
Error installing web3 on Mac 

### ISSUE THREAD

**Issue by rituccijo86** [ethereum/web3.py#567]
I am having trouble installing web3 python on my mac. I keep getting this error from pycharm? and an error when installing in the terminal. 

  creating build/temp.macosx-10.6-intel-3.6/src
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DLTC_NO_ASM -Isrc/ -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/MD2.c -o build/temp.macosx-10.6-intel-3.6/src/MD2.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for pycryptodome
Failed to build cytoolz pysha3 pycryptodome
Installing collected packages: pysha3, cytoolz, eth-utils, eth-keys, pycryptodome, eth-keyfile, eth-abi, requests, eth-tester, web3
  Running setup.py install for pysha3: started
    Running setup.py install for pysha3: finished with status 'error'
    Complete output from command /Users/JohnathanRitucci/PycharmProjects/webscraper3.6/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/fx/z_vttj7d7bsgb3qncnzg6q300000gn/T/pycharm-packaging/pysha3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/fx/z_vttj7d7bsgb3qncnzg6q300000gn/T/pip-28ypkwiv-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/JohnathanRitucci/PycharmProjects/webscraper3.6/venv/bin/../include/site/python3.6/pysha3:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    copying sha3.py -> build/lib.macosx-10.6-intel-3.6
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building '_pysha3' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/Modules
    creating build/temp.macosx-10.6-intel-3.6/Modules/_sha3
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DPY_WITH_KECCAK=1 -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c Modules/_sha3/sha3module.c -o build/temp.macosx-10.6-intel-3.6/Modules/_sha3/sha3module.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------

  Failed building wheel for cytoolz
  Failed building wheel for pysha3
  Failed building wheel for pycryptodome
Command "/Users/JohnathanRitucci/PycharmProjects/webscraper3.6/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/fx/z_vttj7d7bsgb3qncnzg6q300000gn/T/pycharm-packaging/pysha3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/fx/z_vttj7d7bsgb3qncnzg6q300000gn/T/pip-28ypkwiv-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/JohnathanRitucci/PycharmProjects/webscraper3.6/venv/bin/../include/site/python3.6/pysha3" failed with error code 1 in /private/var/folders/fx/z_vttj7d7bsgb3qncnzg6q300000gn/T/pycharm-packaging/pysha3/

How do I install this?  Thanks

**Comment by carver** [comment]
I'm not on a Mac or PyCharm, so don't have any personal experience with this. Googling around gave me this: https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

So maybe your xcode is not installed correctly. Try one of these two things, from the link:

```sh
xcode-select --install
xcode-select --reset
```

**Comment by marcgarreau** [comment]
stale; for any new installation bugs, please open a new issue.

**Comment by fiedersz** [comment]
The solution was to update the commandline tools, but that didn't go smooth as well, I had to first remove the older version and download Command_Line_Tools_for_Xcode_11.5 from the Apple developer site as a zip file. That install worked and solved the problem of not being able to install my package.

**Comment by MohammadSalek** [comment]
Changing the default python version (from python3.9 to python3.10) in my IDE interpreter worked for me.
