### ISSUE TITLE
Allow specifying KDF function for `web3.eth.account.encrypt` API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#583]
### What was wrong?

`eth-keyfile` supports passing in a `kdf` parameter to specify the key derivation function, but this api is not exposed via the `web3.eth.account.encrypt` API.

### How can it be fixed?

Add an optional keyword parameter `kdf` to allow specifying what KDF you want.

Extra options:

Allow setting the default KDF using both environment variables and via a property on the `web3.eth.account` module.

```python
web3.eth.account.defaultKDF = 'scrypt'
```

**Comment by carver** [comment]
In the next couple of days, eth-account will make its way to https://github.com/ethereum/eth-account -- might want to hold off any major work until that happens.

**Comment by pipermerriam** [comment]
replaced by https://github.com/ethereum/eth-account/issues/3
