### ISSUE TITLE
[4.0.0 beta] No callback ability for events like in the 3.x version?

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#588]
Playing around with the web3py 4.0.0 beta to get familiar with the new library for when its eventually fully released.

I noticed that in the previous version when listening for events using `.watch(callback_function_name)` you would be able to trigger a particular function when a new event shows up. Looking through the documentation for the new version there doesn't appear to be a similar method. 

As such I'm using the following pattern to listen for new events (if there's a better pattern I would love to find out)

```
while True:
    events = eventFilterInstance.get_new_entries()
    if len(events) > 0:
        # do stuff
```

This does work,  but it seems a little awkward.

**Comment by harpangell7** [comment]
I'm pretty sure they pulled it. I'm using celery to handle my events async.

**Comment by postables** [comment]
Ah okay that makes sense. I'll check out celery
