### ISSUE TITLE
The weid things. All blockchain has gone.

### ISSUE THREAD

**Issue by theNewGitt** [ethereum/web3.py#590]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: arch

i'm a newbie in this world, so appologize when you read the inocent things. 
- Firstly, i'm running **geth -rpc** command to rsync.
- After that im running **ethminer -G** ( and don't put my wallet adress here - do nothing just for test )
- For approximately 30 min after i open my wallet when keep running geth and ethminer. I Saw my wallet had **5 eth~ 5120 USD** (can't imagine that) . Can't check this mainnet or testnet( cause of button mainnet has disable - maybe it happened when run geth synchonize ) but i'm really sure that is my mainet adress. 
- And geth has issuse  stuck at "**Regenerated local transaction journal"** - Have no idea and i **control-C** to quit all synchroning and mining.
- See on ethereum wallet - Now this is a interesting My balance suddenly came to 0 eth. lol. And all blockchan has gone start with 0 % sync. 
- So question is: Is that 5 eth is real money that i got and is that a luckily when i mining ( You need approximately 65 years when detected a block right? ) 
Thank you guys. :)
### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
If you have a generic question about ethereum I'd suggest the ethereum stack exchange site.

This repository is for the web3.py python library.  If you have a question about the library please open a new issue and fill in the quested information in the template.

**Comment by theNewGitt** [comment]
so appologize. :D
