### ISSUE TITLE
Still waiting for signed transaction to clear

### ISSUE THREAD

**Issue by harpangell7** [ethereum/web3.py#593]
* Version: 4.0.0b6
* Python: 3.5
* OS: linux

### What was wrong?

I'm working on a test chain created by populus. I'm using the following to create and send a raw transaction. 

        `gas_price = w3.eth.gasPrice
        
        gas_price_hex = Web3.toHex(gas_price)
        gas_limit_hex = Web3.toHex(7000000)
        
        nonce = w3.eth.getTransactionCount(w3.eth.coinbase)
        nonce_hex = Web3.toHex(nonce)

        transaction = {
            'to': address,
            'from': w3.eth.coinbase,
            'data': '',
            'value': 1000,
            'gas': gas_limit_hex,
            'gasPrice': gas_price_hex,
            'nonce': nonce_hex,
            'chainId': 1
        }

        key = decrypt_account(w3.eth.coinbase, 'Coinbase-Master')

        signed = w3.eth.account.signTransaction(transaction, key)

        print(signed)

        tx_hash = w3.eth.sendRawTransaction(signed.rawTransaction)

        print(tx_hash)

        while w3.eth.getTransactionReceipt(tx_hash) == None:
            time.sleep(5)
            print('Waiting on Tranasaction')

        tx_receipt = w3.eth.getTransactionReceipt(tx_hash)

        print(tx_receipt)`

The transaction never gets mined or "confirmed" However, if I use 

`tx_hash = w3.eth.sendTransaction({'to': address, 'from': w3.eth.coinbase, 'value': 1000})`

After unlocking the account, the transaction in mined within seconds. Is there something I'm doing wrong?

Is anybody else having trouble or prob just me? lol I love this product and would really like to know what I'm doing wrong. I can post my genesis.json if thats a problem area?

**Comment by harpangell7** [comment]
Heres the AttributeDict. In the example it shows r and s as hexbytes. Is this the problem?

`AttributeDict({'rawTransaction': HexBytes('0xf86780850430e23400836acfc094729ec65621d4ef975a48244c1373c4356e9119898203e88026a01bca82a7e6243a810a8adcff3cee3604aa6d5eb70b9e441e2a569678c6061851a02f08d9713df59ceb217ad0bbc78e3fd189c3cc2a4a883109a9b58930c9e951c8'), 's': 21274339391888063372739717545903057402080716410845875744289537671013908173256, 'hash': HexBytes('0x66741cb84b881ebc9f2246a83ebf781c34114d9c2a455348897f74ade791fc72'), 'v': 38, 'r': 12570251772406332945300025074538573159520329277164531372497217672440701130833})`

**Comment by harpangell7** [comment]
I solved my problem by setting the chainId to None and removing the chainId setting in the genesis.json.

**Comment by nueverest** [comment]
Where can I find genesis.json?
