### ISSUE TITLE
Add git hook to automatically fix imports [`isort`]

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#600]
### What was wrong?

Finding out you forgot to run `isort` after travis finishes is annoying.

### How can it be fixed?

Build the standard practice of a precommit hook that automatically prevents such issues.

Choose the best way to share the hook. Something like:

- https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
- https://www.darrenlester.com/blog/including-hooks-in-a-git-repository

**Comment by pacrob** [comment]
The addition of `pre-commit` to the python project template (https://github.com/ethereum/ethereum-python-project-template/pull/103) handles this issue. Technically not completed, but will be in the next round of template merges.
