### ISSUE TITLE
Auto flake8 fixup

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#601]
### What was wrong?

Like #600 it would be great to prevent flake8 issues being the only thing preventing a merge. Probably with a shared git hook.

### How can it be fixed?

`flake8` does not have any automatic code cleanup mechanism. Probably have to use something like [yapf](https://github.com/google/yapf#knobs), which requires turning a lot of knobs to mimic our preferred coding style.

**Comment by pacrob** [comment]
The addition of `pre-commit` to the python project template (https://github.com/ethereum/ethereum-python-project-template/pull/103) handles this issue. Technically not completed, but will be in the next round of template merges.
