### ISSUE TITLE
How to properly sign a transction to be used by ecrecover?

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#608]
I can't seem to be able to find any examples using web3py on how to properly sign a transaction such that it can later be used by `ecrecover` in solidity code to recover the address associated with the signature.  I can find examples on how to do this with geth but I can't seem to transpose those examples to web3py.

Thanks.

**Comment by carver** [comment]
@postables are the keys local? Have you tried using this? http://web3py.readthedocs.io/en/latest/web3.eth.account.html#web3.account.Account.signTransaction

r, s, and v are the values ecrecover needs.

Those docs are a little out of date, and will be updated within a week or two. The important bit is that r and s will be return as `int`s. `ecrecover` expects them encoded to `bytes`, zero-left-padded to length 32.

**Comment by postables** [comment]
@carver  I forgot to update the post after some playing around

```
> >>> account = w3.eth.accounts[0]
> >>> account
> '0x......'
> >>> messageHash = Web3.sha3(text="hello")
> >>> sig = w3.eth.sign(account, mHash)
> >>> signature = Web3.toHex(sig)
> >>> signature
> '0x12d27eee594bd1600425cc6a55da74a5f0269c4bf2f183fba63e96da715b586b5ad3faaf1dccf2db3767eb6208664e9c6b091acfc98eaa509762ff96b89226c41c'
> 
```
At that point I'm not sure how to extract `r,s,v`, but I can do the following using the private key for the acocunt I sign the message with above and get something completely different;
```
>>> w3.eth.account.sign(message_text="hello", private_key='........')
AttributeDict({'message': HexBytes('0x68656c6c6f'), 'messageHash': HexBytes('0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750'), 'r': 22580352188726826547809973358706180336404605721545613969295481809239319931794, 's': 49237363076592134837509178716263982254448895484738317713941217200673578449040, 'v': 28, 'signature': HexBytes('0x31ec06c43b2bcf2e8d7e1b31a5bd698a361707f35e6828133355113d8c066b926cdb5c23ac5a4c4f066341951933f1d943b05d2c7db5ce0d3d8de50024d278901c')})
```

**Comment by carver** [comment]
Ok, let's split this into several issues.

1) "how to convert the message signature returned by your node into v, r, s?" This is at least a documentation issue, or *maybe* some kind of tool we want to expose. The one-liner version of the doc is that the signature is concatenation of r + s + v, padding r and s to 32 bytes with 0s. We can continue talking about that on this thread.
2) "why is the signature different from eth.sign and w3.eth.account.sign?" I'm not certain scanning it, but we need something reproducible to talk about. You can use this private key for test cases: `0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318` Can you open separate issue about that in [eth-account](https://github.com/ethereum/eth-account) with the exact inputs, outputs, and expected results?
3) "why is this message recovery failing?" This method accepts the *hash* of the message, which you can calculate with [`w3.eth.account.hashMessage()`](http://eth-account.readthedocs.io/en/latest/eth_account.html#eth_account.account.Account.hashMessage). If that's not clear, can you open a separate issue on [eth-account](https://github.com/ethereum/eth-account) for adding a bit to the docs about recovering the sender from a message?
4) "how do I prepare a message?" The signing methods take the original message, the recovery method takes the message hash (after adding the prefix). So you do not need to take the sha3 of a message before sending for signature. You can do `w3.eth.account.sign(message_text='hello', private...)` and `w3.eth.sign(acct, text="hello")`. We can continue on this thread.

**Comment by postables** [comment]
1. Okay
2. I'll post a test at the end of this thread and open an issue on eth-account.
3. Will do
4. That makes sense and I believe I understand how to do it now (with `w3.eth.account.sign` at least, see hte following example using the provided example private key
```
>>> w3.eth.account.sign(message_text='hello', private_key=0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318)
AttributeDict({'message': HexBytes('0x68656c6c6f'), 'messageHash': HexBytes('0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750'), 'r': 75008893682361613075321033100067373842215849668831618173450334986392439342668, 's': 23948789300193558420516775146517085417438894167413775226527048552817861068889, 'v': 27, 'signature': HexBytes('0xa5d58782075bdf09490159d634d1aae66a8f6777c7247d2f233e9511cfd7c64c34f288cdbcea5370e4863fdbe9f4d86654c2ba1d86589e9ebb64494c649008591b')})
```

**Comment by postables** [comment]
I attempted to use those parameters with a contract, but got a different address:
```

contract Test {
    address public a;
    
    function recover(bytes32 msg, uint8 v, bytes32 r, bytes32 s) public returns (bool) {
        a = ecrecover(msg, v, r, s);   
    }
}
```

Using `"0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750", 27,"0x75008893682361613075321033100067373842215849668831618173450334986392439342668","0x23948789300193558420516775146517085417438894167413775226527048552817861068889"` as my input to `recover` returns the following address `0x8f5524b8170490b9b6db876b3315142b1b7b7dc8` however pasting the private key into mew gives the following address `0x2c7536E3605D9C16a7a3D7b1898e529396a65c23`

**Comment by postables** [comment]
I was able to solve the issue by converting `r` and `s` to hex using these two lines of code before firing the transaction

    r = Web3.toHex(r)
    s = Web3.toHex(s)

Thanks for the help @carver  really helped to point me on the right track

**Comment by carver** [comment]
Glad it worked out!

Here are some new, related docs I've just deployed: http://web3py.readthedocs.io/en/latest/web3.eth.account.html

I would love your thoughts on those docs.

**Comment by postables** [comment]
I think it would be useful to have a section demonstrating  how to sign message hashes that don't include the prefix.

For example, in some of my solidity code I'm attempting to verify that a message `keccak256('hello')` was indeed the message that was signed when recovering address utilizing `ecrecover`. The problem lies that when using the current methods to sign messages, it adds in the prefix before signing it. As such, the message `keccak256('hello')`  can't be used in `ecrecover` but the prefixed message.

**Comment by carver** [comment]
I took a stab at it. It's not *exactly* that case. I think it would hurt more than it helps to try to exhaustively list all the possible combinations. But at least it mentions how to use `hashMessage()` if all you have is the original message. Thoughts?

**Comment by postables** [comment]
Actually now that you mention it I agree it would hurt more than it helps. The reason I needed to reconstruct the message in the first place  (which I ended up figuring out) is a specific use case that wouldn't make sense to clog up the documentation with.

**Comment by kuabhish** [comment]
> I was able to solve the issue by converting `r` and `s` to hex using these two lines of code before firing the transaction
> 
> ```
> r = Web3.toHex(r)
> s = Web3.toHex(s)
> ```
> 
> Thanks for the help @carver really helped to point me on the right track

this is not helping .. invocation failed.. 

Please look at my question and suggest something ..

https://stackoverflow.com/questions/62117851/unable-to-verify-a-signed-message-in-solidity

**Comment by hileamlakB** [comment]
> ecrecover

Is there an official way to sign a message without adding the prefix? I am in the exact situation as you just described, and I couldn't get to match the hash generated by `eth.account.sign_message` and solidity `keccak256`.
