### ISSUE TITLE
Issues combining Celery and web3py for concurrency/async processing: Object of type 'Contract' is not JSON serializable

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#612]
I'm attempting to combine Celery and web3py for async processing.
I have the following file `tasks.py`
```
from celery import Celery

app = Celery('tasks', broker='pyamqp://guest@localhost//')
app.conf.task_serializer = 'json'
@app.task
def awardCoins(bridge, account):
	bridge.functions.awardCoins(toAddr, amount).transact({'from': account})
```

I have the following lines which establishes a web3 IPC connection to a smart contract, address in the `mainNetworkLinkerContract` variable, and the contract abi in the `tempAbi` variable, then attempt to execute the `awardCoins` function
```
from tasks import awardCoins
fameBridge = mainNetListener.manualLoadContract(mainNetworkLinkerContract, tempAbi)
awardFame.delay(fameBridge, mainNetListener.adminAccount)
```

Which returns the error 
`Object of type 'Contract' is not JSON serializable`

**Comment by xibalbas** [comment]
@bonedaddy  how do you fix this?? could you please describe what happened?
