### ISSUE TITLE
w3.eth.account.sign returning incorrect data

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#617]
This account is for a testnet:
```
>>> private
b'\xd8Y\xe3T\xb8\x15\xaaJ\xe6i\xaf\xf9\x02\x8a\xbf\x89#\xf9D\x03\xdd\tc\xf2\xed\xc3\x9eQ\r\x98\xb7|'
>>> signature = w3.eth.account.sign(message_text="hello", private_key=private) 
>>> signature
AttributeDict({'message': HexBytes('0x68656c6c6f'), 'messageHash': HexBytes('0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750'), 'r': 53665784189267139251820747046956462498355115993943239404465477346598658281299, 's': 6629064374810355767282561830725699037469490635953226814818888019755260187756, 'v': 27, 'signature': HexBytes('0x76a5c1e7f682df3375a2bdd6f72ad2171b0cf826fc8a8a3209c33a4e57e88f530ea7eadf8603ba2c4a5c5006571be7665020812aa7e403a614587cfe7a18146c1b')})
>>> h = Web3.toHex(signature.messageHash)
>>> v = signature.v
>>> r = Web3.toHex(signature.r)
>>> s = Web3.toHex(signature.s)
>>> h
'0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750'
>>> v
27
>>> r
'0x76a5c1e7f682df3375a2bdd6f72ad2171b0cf826fc8a8a3209c33a4e57e88f53'
>>> s
'0xea7eadf8603ba2c4a5c5006571be7665020812aa7e403a614587cfe7a18146c'
>>> w3.eth.accounts[1]
'0x069bA77207aD40B7d386F8E2979a9337A36f991c'
```

Attempting to use `ecrecover` in solidity with those parameters returns an inccorect address of `0xb8e89ea04d9ee4b633c56d4a3b728a280e80eb6b`

If you take `s (0xea7eadf8603ba2c4a5c5006571be7665020812aa7e403a614587cfe7a18146c)`
and change it to `0x0ea7eadf8603ba2c4a5c5006571be7665020812aa7e403a614587cfe7a18146c` (now the extra `0` after the x, you receive the proper address `0x069bA77207aD40B7d386F8E2979a9337A36f991c`

This error doesn't appear to be consistent or happen all the time, but it has caused me extreme annoyance trying to debug smart contracts.

Update:

Doing the following returns the correct value for `s`:
```
>>> Web3.toHex(Web3.toBytes(signature.s))
'0x0ea7eadf8603ba2c4a5c5006571be7665020812aa7e403a614587cfe7a18146c'
```

**Comment by pipermerriam** [comment]
Currently we return `r` and `s` in their integer representations which means they are not padded to 32 bytes.   The reason for the inconsistency is that this will only occur when `r` or `s` are small enough that they fit in less than 32 bytes..

I'm pretty sure there is already a conversation about this somewhere but I'm not sure where.  cc @carver as he may know.

**Comment by postables** [comment]
Ah okay that makes sense. I looked on read the docs for the version 4.0.0.7beta and it mentions using `eth_utils.to_hex` and `eth_utils.to_bytes` however my version of eth  utils doesn't have that (could probably just upgrade it though). Would converting both `r` and `s` to bytes first before converting to hex, utilizing `Web3.toBytes` be sufficient to solve this issue?

**Comment by carver** [comment]
> it mentions using eth_utils.to_hex and eth_utils.to_bytes however my version of eth utils doesn't have that

Yeah, I will update that in the docs to use the same functions by a different name: `Web3.toHex()` and `Web3.toBytes()`.

FYI, The next release of web3.py v4 will force the install of the latest eth-utils.

> Would converting both r and s to bytes first before converting to hex, utilizing Web3.toBytes be sufficient to solve this issue?

No, you also have to zero-pad the value to 32 bytes, as the example in the docs does: http://web3py.readthedocs.io/en/latest/web3.eth.account.html#prepare-message-for-ecrecover-in-solidity

This will only byte you about 0.78% of the time, though (when the whole first byte of r or s is 0's).

Any suggestions on improving the docs? If not, I'll close the issue.

**Comment by postables** [comment]
Thanks Carver! The only thing I could recommend is that https://web3py.readthedocs.io/en/latest/web3.eth.account.html#prepare-message-for-ecrecover-in-solidity should indicate explicitly what the function depicted is doing (zero pad -> bytes -> hex).

thanks for all the help :D
