### ISSUE TITLE
Dev Setup Prerequisites

### ISSUE THREAD

**Issue by lazaridiscom** [ethereum/web3.py#632]
Affects #549 

* Version: dev
* Python: 3.5
* OS: ubuntu 16.04

### What was wrong?

I've followed the setup https://github.com/ethereum/web3.py#developer-setup quite literally.

I do not us docker.

Despite using `pytest -k "not goethereum"`, i get loads of test errors, an example:

```
tests/core/eth-module/test_iban.py::test_isValid[XE81ETHXREGGAVOFYORK-True]
  /mnt/p/sand/web3py/venvpy3/lib/python3.5/site-packages/eth_tester/backends/__init__.py:48: UserWarning: Ethereum Tester: No backend was explicitely set, and no *full* backends were available.  Falling back to the `MockBackend` which does not support all EVM functionality.  Please refer to the `eth-tester` documentation for information on what backends are available and how to set them.
    "Ethereum Tester: No backend was explicitely set, and no *full* "
```

> Please refer to the `eth-tester` documentation for information on what backends are available and how to set them.

Are there any prerequisites which are not mentioned in the dev-setup instructions?

**Comment by carver** [comment]
> Are there any prerequisites which are not mentioned in the dev-setup instructions?

Kind of, the "right" section to follow was the "Python 3" one, since the "main" section seems to fallen out of date. I just deleted that old section, replacing it with the Py3 one.

The only change of note is to use: `pip install -e .[tester]`.

**Comment by lazaridiscom** [comment]
@carver , nah, used only the python3 instructions before.

one thing: I noticed on the console during repeat (step `pip install -e .[tester]`) 

`eth-tester 0.1.0b16 does not provide the extra 'py_evm'`

**Comment by carver** [comment]
This still works for me in a fresh checkout, in a fresh venv, with caching turned off.

Can you `pip install --upgrade pip setuptools wheel` and try again?

**Comment by lazaridiscom** [comment]
You mean try the complete installation again, or just the "pip install -e .[tester]" ?

**Comment by lazaridiscom** [comment]
```
(ve3) root@dell-i5-win:/mnt/p/sand/web3py# pip install --upgrade pip setuptools wheel
Requirement already up-to-date: pip in ./ve3/lib/python3.5/site-packages
Requirement already up-to-date: setuptools in ./ve3/lib/python3.5/site-packages
Requirement already up-to-date: wheel in ./ve3/lib/python3.5/site-packages
```

**Comment by lazaridiscom** [comment]
I repeated, without virtualenv. Not sure if virtualenv was the cause, or if the manual installation of py-env helped. 



Test is still green... ... (takes forever).

Ok, still a few errors, but **much much** better:

example error: `FileNotFoundError: [Errno 2] No such file or directory: 'parity'`

So, I'm now running 'pytest -k "not goethereum and not parity", i guess this will work.

All fine:

`967 passed, 33 skipped, 194 deselected, 92 warnings in 455.13 seconds`

### Simplified Docs

The simplified (newcomer-friendly) instructions would be:

```sh
git clone git@github.com:ethereum/web3.py.git
cd web3.py
pip install -r requirements-dev.txt
pip install -e .[tester]
pytest -k "not goethereum and not parity"
```

**Comment by scottydelta** [comment]
try this:

```
python3 -m venv .env
source .env/bin/activate
git clone git@github.com:ethereum/web3.py.git
cd web3.py
pip install -r requirements-dev.txt
pip install -e .[tester]
pytest -k "not goethereum and not parity"
```

**Comment by lazaridiscom** [comment]
@scottydelta , so you suggest this structure:

```
myProjectGroup
  .env
  web3.py
  project-two
  project-n
```

All projects can share the same venv?

**Comment by carver** [comment]
I strongly disagree that the setup instructions should leave out the virtualenv step. It causes many problems when people have conflicting/broken python environments. A fresh venv regularly solves the problem. I don't know anything about Linux Subsystem for Windows -- maybe it breaks virtualenv. Maybe we could put a warning in the docs if you're on LSfW that we have a report of venv not being supported by it.

I could also support adding `-k "not goethereum and not parity"` to the pytest commands in https://github.com/ethereum/web3.py/#testing-setup

**Comment by lazaridiscom** [comment]
I mentioned it wrong: its WSL (Windows Subsystem for Linux). You can install easily e.g. an ubuntu bash shell which acts like a linux machine.

Venv solves problems, introduces others (I have it active now on my side, skcottydeltas suggested method)- anyways, the core thing here was that the instructions did not work on a fresh machine, for some reason. Should be possibly verified sometimes.

**Comment by lazaridiscom** [comment]
its always fun seeing virtualenv ignoring everything I installed a day before...

**Comment by lazaridiscom** [comment]
Closing, its just the usual "venv" hickups.
