### ISSUE TITLE
[RFC] Specify Specification Options

### ISSUE THREAD

**Issue by lazaridiscom** [ethereum/web3.py#634]
Affects #549

### Draft Configuration Options

Those are configuration options for web3.py, which would allow a developer to choose its strictness in 3 levels:

| ConfigOption | default |  description |
| ------------------------------- | --- | --- |
|  **strict** | true | enforces strict yellow-paper (any RFC or number available? ) compliance |
| **dev** | false| development mode, enforces the **actual** `--dev` option behavior of the Reference Implementation (geth)  |
| **custom** | false| custom mode, allows for custom-specs placed in a `custom` folder (e.g. middleware which changes protocol/specs) |

(side-note: for #549, only `strict` and `dev` will be implemented. But care will be taken that the provided constructs can easily extended to provide full customization, if wished so by the project leads. )

Thoughts, comments?

**Comment by carver** [comment]
I don't understand what you're proposing. where would you pass in this config option?

**Comment by lazaridiscom** [comment]
This is not how to pass them. Its just about to clarify/specify which options to have and what they do (passing e.g.: instantiation, config-files, etc. - but not the topic here). Removing the `--` to not imply command-line.

**Comment by lazaridiscom** [comment]
Closing, not needed for simple workaround implementation.
