### ISSUE TITLE
web3.py reconverting data field to hex data

### ISSUE THREAD

**Issue by fivetwentyseven** [ethereum/web3.py#637]
web3 is reconverting data field to hex data type. I don't know how to give the raw data to it. 

```
tx= Transaction ( 
nonce=w3.eth.getTransactionCount("<address>","pending"),
gasprice=gas_price, #@w3.eth.gasPrice,
startgas=100000,
to='',
value=0,
data= b'0xaabb' # it is always conveting to hex
)
```

**Comment by pipermerriam** [comment]
@use-r next time you fill out an issue will you please use the provided template (which should pre-populate the form).  What you've provided doesn't give us much to go on.  I don't know what the `Transaction` object in your example is from, and I don't know what error you're getting.

**Comment by fselmo** [comment]
stale
