### ISSUE TITLE
Accessing Token Contract properties

### ISSUE THREAD

**Issue by nueverest** [ethereum/web3.py#638]
* Version: 3.16.5
* Python: 3.6
* OS: ubuntu

### What was wrong?

First off I'm a noob.  

I want to monitor the `totalSupply` of an ERC20 Token.  However, when I print `totalSupply` I see an object.

Code Snippet
```
contract_concise = w3.eth.contract(
    contract_abi, contract_address, ContractFactoryClass=ConciseContract
)

print('Total Supply', contract_concise.totalSupply)
```

Actual Output
```
Total Supply <web3.contract.ConciseMethod object at 0x7fb194472898>
```

Desired Ouptut
```
11111213700000000000000000
```

### How can it be fixed?

How can I print the totalSupply property as a human friendly integer?

**Comment by pipermerriam** [comment]
you just need to call `contract_concise.totalSupply()`
