### ISSUE TITLE
[TEST] Provide Chain Compatibility Test Cases and Skeletons

### ISSUE THREAD

**Issue by lazaridiscom** [ethereum/web3.py#639]
Affects #549, and web3.py in general

### What is wrong?

Issue #549 asks the author of the solution to provide the test-cases:

>To be complete:
>    A test showing that a long extradata does not raise an error, after adding the new middleware
>    A test showing that a long extradata does raise an error in the default configuration

The issue is:

* a) Those test-cases should be available already
* b) Test-code should be ideally not written by the person which wrote the code it tests

### How can it be fixed?

Can someone who is familiar with the test-system provide the relevant tests, ideally within a test-subgroup of the kind "chain-compatibility"?

This one test would be enough:

> A test showing that a long extradata does raise an error in the default configuration

**Comment by carver** [comment]
> Test-code should be ideally not written by the person which wrote the code it tests

This is not how we work in this repository. The default is to include tests with all code we write. https://github.com/pipermerriam/ethereum-dev-tactical-manual#testing

Tests will be included when the code for #549 is posted. Closing this as a duplicate.

**Comment by lazaridiscom** [comment]
> This is not how we work in this repository. The default is to include tests with all code we write.

I've seen this. The thing is that  writing test can be a task in itself, if the test-system needs to be extended.

>> a) Those test-cases should be available already

This was the main point. I understand that you'll provide them together with the code you announced.

A few notes:

* The test-subsystem does currently not support geth 1.8
* Ideally, a TestProvider simulating alternative specs is made available (and documented)
