### ISSUE TITLE
How to calculate the max amount of data that can fit in a transaction

### ISSUE THREAD

**Issue by use-r** [ethereum/web3.py#640]
Offtopic : Please someone tell me how to calculate the max amount of data that can fit in a transaction. 

Thank you.

**Comment by lazaridiscom** [comment]
@use-r , please try this resource here (i've copied your question there) :

https://gitter.im/ethereum/web3.py?at=5a845338f283b8e5465f3b95

**Comment by pipermerriam** [comment]
@use-r this type of question is out of scope for the type of support we can lend for this library.  I would suggest digging into the ethereum yellow paper if you want to understand protocol rules.
