### ISSUE TITLE
[RFC] Separate Protocol (Specs) Enforcement from Formatting

### ISSUE THREAD

**Issue by lazaridiscom** [ethereum/web3.py#647]
affects #549

### What is wrong?

After reviewing some code within `middleware`, it looks like there is currently no dedicated protocol-enforcement available, most possibly because there was till now only one protocol (specs, yellow-paper) to support.

I have the (gut) feeling that a protocol-verifying code should reside within a separate middleware (like `specs`). The counter-argument is possibly that any further processing results in a compliancy-check. But still, a clean separation would make things cleaner.

### How can it be fixed?

Provide `middleware/compliancy/` or `middleware/specs/ `or `middleware/protocol/` (1), which contains the different middlewares which ensure compliancy to specs like:

- yellow
- poa-geth
- poa-parity
- etc.

Compliancy is loaded before pythonic / formatters. Data-fields are kept compatible to the relevant specification. 

Compliancy should be 'natural', which means that if a user uses web3.py to connect to a chain, web3.py detects the chain-type, and uses the relevant compliancy-middleware.

If this concept hits on implementation-limits, then the protocol-handling can be implemented e.g. directly within a class ChainSpecs and descendants. But it seems that using middleware should be enough.

(1) **protocol**:  'protocol' is used in another context ( 'eth_protocolVersion': '63',). So, this would mean that this term cannot be used.

### Limited Implementation

For the current resolution of #549 (and to avoid introducing to much code-changes) , it would be enough to provide a `/specs/poa_geth` or `/specs/eip225`, which would leave extraData(32) intact (**EXTRA_VANITY**), and move the rest of the data to a 2nd field (**EXTRA_SEAL**, 65 bytes), see ethereum/EIPs/issues/225

.

**Comment by lazaridiscom** [comment]
## Update & Possible Final Solution

> The counter-argument is possibly that any further processing results in a compliancy-check. But still, a clean separation would make things cleaner.

An alternative is to keep formatting-prework and compliancy-check as-is in one file (pythonic), but to **change the naming** here:

- `pythonic` is essentially `specs_pow` (or similar, like `data_pow` or `block_pow`)

Once renamed, see how the code in `manager.py` looks (positive trait: a reviewer can actually spot the specs in the code)

```py
    @staticmethod
    def default_middlewares(web3):
        '''
        List the default middlewares for the request manager.
        Leaving ens unspecified will prevent the middleware from resolving names.
        '''
        return [
            (gas_price_strategy_middleware, 'gas_price_strategy'),
            (name_to_address_middleware(web3), 'name_to_address'),
            (attrdict_middleware, 'attrdict'),
            (specs_pow_middleware, 'specs_pow'),
            (abi_middleware, 'abi'),
        ]
```
the elegant solution for issue #539 comes now closer:

- provide `specs_poa` (inherit specs_pow, apply changes), then...

### Solution A

Instead of providing a modifying middleware for poa, a dedicated poa middleware is provided:

- spot the relevant code, detect the poa network, replace `specs_pow` with `specs_poa`

### Solution B (alternative)

- provide `poa_default_middlewares`
- spot the relevant code, detect the poa network, replace `default_middlewares` with `poa_default_middlewares` (when RequestManager in instantiated)

**Comment by carver** [comment]
If there is an EIP defining the specification for POA, can you link to it? I haven't seen one, but I haven't read every single one.

**Comment by lazaridiscom** [comment]
The closest I found was this one mentioned above( https://github.com/ethereum/EIPs/issues/225 ), but Ii did not look further, neither read the comments, nor asked. Will possibly take a closer look this night.

**Comment by lazaridiscom** [comment]
.

**Comment by carver** [comment]
Thanks for digging this up. It looks to be in very early stages, with only the one geth implementation, and no formal EIP proposal. With that context, I think we should:

1. Follow that EIP and help make sure that it plays nicely with clients like web3.py (I posted one related comment, since chainID is probably not a good way to identify whether the chain is PoA)
2. Add an optional middleware, for compatibility with geth dev. It's okay for there to be a little extra work to connect to a prototype non-standard chain (that work being: add the middleware to your web3 instance when connecting to geth dev).
3. Redesign the approach once a more formal EIP spec is proposed/adopted. Until then, we won't know what it will look like in its final form.

**Comment by lazaridiscom** [comment]
I understand

*  that geth is the most used reference-implementation.
* this eip draft is used on the live testnet

As for your points:

1) As i understood: chainID exists to distinguish between hard-forks which share a networkID, and its not a big problem to support only the main PoAs (and possibly there is a dedicated mechanism to detect them). For now, the public test-net and the 'geth --dev' need to be detected.

2) The little extra-work can introduce usability issues (e.g. using geth in test etc., code needs to be changed etc.)

3) Its a possibly an in-dev spec, but its live, so any software using it (web3.py including), should adapt to it, following it, beeing ideally in-sych with developement.

I don't expect that those spec will change much and often, and in any way: it helps to have the code-base ready to adopt.

In any way, I'm now 99,9% sure that solution A or B is the way to go. But having quite clarity about everything now, I can adapt, once I'm finished. You can use the results to a later point.

When will you publish this middleware you announced yesterday?

**Comment by lazaridiscom** [comment]
You understand that (despite me having taken another path) I can use this code for my task? Is there any way for me to get this before you merge?

**Comment by carver** [comment]
Ignoring the tests, the gist is to add this file: `web3/middleware/geth_dev.py`

```py
from eth_utils.curried import (
    apply_key_map,
)

from web3.middleware.formatting import (
    construct_formatting_middleware,
)

remap_geth_dev_fields = apply_key_map({
    'extraData': 'proofOfAuthorityData',
})

geth_dev_compatibility = construct_formatting_middleware(
    result_formatters={
        'eth_getBlockByHash': remap_geth_dev_fields,
        'eth_getBlockByNumber': remap_geth_dev_fields,
    },
)
```

Then you can set up web3 with something like:

```py
from web3 import Web3, IPCProvider
from web3.middleware.geth_dev import geth_dev_compatibility

w3 = Web3(IPCProvider('/tmp/geth.ipc'))
w3.middleware_stack.insert(0, geth_dev_compatibility)
```

**Comment by lazaridiscom** [comment]
Looks simple enough. I'll try to find a way to integrate this in a more convenient way, as I sense that you are reluctant to take the other path (which I still favor 100%, but... you're the decision taker here).

**Comment by lazaridiscom** [comment]
See https://github.com/lazaridiscom/web3.py/commit/9d1315e0ac490bd4a3906a12713c4eb7cd4fb04c for a very simple implementation, without the need of .insert. 

Followup: #549
