### ISSUE TITLE
Autocomplete doesn't work, exploring in shell is hard

### ISSUE THREAD

**Issue by aljosa** [ethereum/web3.py#654]
* Version: 4.0.0b9
* Python: 3.6
* OS: osx

### What was wrong?

Autocomplete is useless in python shell (ipython, ipdb, dir(), etc.).
I expected that I'll get autocompletion when I, for example, type `contract_instance.[TAB]`.

```python
contract_instance = w3.eth.contract(
    contract_address,
    abi=contract_interface['abi'],
    ContractFactoryClass=ConciseContract)
```

I expected that triggering `contract_instance.` would suggest `contract_instance.myMethod()`.
Contract is just an example, I've noticed that most of the code w/ metaclasses don't have this.

### How can it be fixed?
Looking at the source code it could be possible to add `__all__` to `PropertyCheckingFactory` or something/somewhere similar.

Exploring the API from shell is something that works really well for other python library, would be great if it would work for web3.

**Comment by pipermerriam** [comment]
I've had this same annoyance.

**Comment by grrttedwards** [comment]
I'd like to contribute, could you elaborate on this issue?

Would a decorator like the final section of [this Stackoverflow post](https://stackoverflow.com/questions/44834/can-someone-explain-all-in-python/35710527#35710527) be suitable?

**Comment by pipermerriam** [comment]
Alright, this is an issue specifically with `ConciseContract`.

I see two routes

- Implement a `__dir__` method which returns a tuple of all of the contract function names.
- Change the `__init__` of concise contract to actually populate self with all of the contract functions using the same logic currently present in the `__getattr__`.

The `__dir__` approach seems like the lowest touch, but I think the second solution of actually populating all of the functions onto `self` seems more correct.  It would also allow us to get rid of the `__getattr__` on the class which seems like a bonus.

**Comment by carver** [comment]
:+1: to approach 2 above
