### ISSUE TITLE
getTransactionReceipt propagates error from Geth v1.8.0 when there's no receipt yet

### ISSUE THREAD

**Issue by mathiasestolarz** [ethereum/web3.py#655]
* Version: 4.0.0b7
* Python: 3.5.2
* OS: Ubuntu 16.04

### What was wrong?

I am calling web3.eth.getTransactionReceipt of a hash that doesn't have a receipt yet and as a result it propagates the error from Geth instead of returning None.
I am connected to a private node with Geth v1.8.0.

This is what I get:

```
>>> web3.eth.getTransactionReceipt(txHash)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 188, in getTransactionReceipt
    [transaction_hash],
  File "/usr/local/lib/python3.5/dist-packages/web3/manager.py", line 102, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'unknown transaction'}
```

**Comment by pipermerriam** [comment]
@carver we should look into building a lookup table for exceptions that looks something like `
web3_clientVersion -> error_code -> ExceptionClass` so that we can raise more appropriate exception types for known errors.

**Comment by carver** [comment]
Sounds like a good candidate for a new default middleware. :+1:

**Comment by pipermerriam** [comment]
Looks like error codes are not incredibly granular but still of some use: https://github.com/ethereum/go-ethereum/blob/922c1f8f9f7763948da6ed755abd6e1fcaca2cac/rpc/errors.go
