### ISSUE TITLE
Middleware order is inconsistent

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#658]
* Version: 4

### What was wrong?

The order of the middleware as passed in to Web3, and treated as part of `add` or `insert`, and returned from `list(w3.middleware_stack)` is inconsistent:

1. in `add` (really, `append`), and `insert()`, the beginning is the bottom of the stack, and the end is the top of the stack
2. in `Web3(..., middlewares=[...])` and `list(w3.middleware_stack)`, the beginning is the top of the stack, and the end is the bottom of the stack

(where the bottom of the stack is the part closest to the node and the top of the stack is the part closest to the Web3 invocation)

This is confusing -- it even caused a bug in #648 .

### How can it be fixed?

~~I think the second order is more natural as part of the implementation, and the first order is more natural in semantic understanding (where you usually want to add new middlewares to the top of the stack, so when you append/add it to the end of the list, that should be the top of the stack).~~

~~Proposal: flip the order in `Web3(middlewares)` and `list(w3.middleware_stack)`.~~

Latest Proposal:
- Switch name from `insert` -> `inject` to avoid any confusion with the list API
- Switch to `inject(middleware, name=, layer=)`, where 0 is the inner-most layer
- Leave the ordering as-is on `Web3(middlewares)` and `list(w3.middleware_stack)`
- Remove all references to first/last/top/bottom/left/right in middleware docs. Always use outer or inner

**Comment by pipermerriam** [comment]
Do I understand this correctly

```
middlewares = [a, b, c]

(manager makes request) -> a -> b -> c -> provider -> c -> b -> a -> (manger returns response)

```

**Comment by carver** [comment]
Right, that's the "top of the stack at the front of the list" one.  I'm proposing the reverse.

**Comment by pipermerriam** [comment]
I'm still confused.  Is my first example or my second example your preferred ordering?

**Comment by carver** [comment]
worked it out on chat. New proposal:

- Switch name from `insert` -> `inject` to avoid any confusion with the list API
- Switch to `inject(middleware, name=, layer=)`, where 0 is the inner-most layer
- Leave the ordering as-is on `Web3(middlewares)` and `list(w3.middleware_stack)`
- Remove all references to first/last/top/bottom/left/right in middleware docs. Always use outer or inner

**Comment by lazaridiscom** [comment]
@carver , @pipermerriam - some remarks:

>    Switch name from insert -> inject to avoid any confusion with the list API

`inject` is widely used in context of `dependency injection`, and could confuse/mislead

`place` could be possibly used

>    Switch to inject(middleware, name=, layer=), where 0 is the inner-most layer

`layer` is used in context of `application layer`, thus it could be confusing, too

so lets try with `place`

```python
place(middleware, name=, early=True, relative_to=)
```

I would want to have the optional parameter `relative_to`, to be able to place a MW e.g. like this:

```python
place(middleware_geth_dev, name=, inner=True, relative_to=pythonic_middleware)
```

but this would be cleaner (**first**):

```python
place(middleware_geth_dev, name=, first=True, relative_to=pythonic_middleware)
```

but this even more cleaner:

```python
place_earlier(middleware_geth_dev, name=, relative_to=pythonic_middleware)
```

some random middleware:

```python
place_later(middleware_something)
```

>    Leave the ordering as-is on Web3(middlewares) and list(w3.middleware_stack)

yes, thus stuff does not break.

>    Remove all references to first/last/top/bottom/left/right in middleware docs. Always use outer or inner

yes, but provide a tiny graphic, which shows this "inner / outer" thing.

Although this would introduce one indirection (one has to think which is executed first and last).

So "first/last" have this benefit: one knows immediately when it executed. And it would have compatible naming to the standard python datastructure.

But I would like this "early/late" and "place" thing.

.

Having said all this: naming things is a small hell (as you surely know). It takes time, and then one still does it wrong. For this here, one could do a research to pick some standard-naming.

Possible sources:

* python
* django
* the Ethereum go / C++ / py / etc. implemetations
* [...]

**Comment by carver** [comment]
> `place` could be possibly used

`place` has the issue of being both a noun and a verb. That is something I've been avoiding when possible.

> `inject` is widely used in context of dependency injection, and could confuse/mislead

Since we don't use dependency injection by name anywhere, I don't expect `inject` to cause much confusion in this context. (The backend pattern is similar, but has no naming conflict).

> But I would like this "early/late" and "place" thing.

The problem with using relative-to and early/late is that the before & after semantics switch on the way in and out of the request.

> yes, but provide a tiny graphic, which shows this "inner / outer" thing.

I agree that a visual is important here. I'm not much of a graphics guy, but I'll do what I can with ascii art or something. :)

> Having said all this: naming things is a small hell (as you surely know). It takes time, and then one still does it wrong

No kidding! We could discuss endlessly.

> Possible sources: django

Yes, Piper had the same thought, which was an influence on using the word `layer`: https://docs.djangoproject.com/en/2.0/topics/http/middleware/#middleware-order-and-layering

---

I'll move forward with the `inject` / `layer` naming, and we can address in v5 if we come up with something better later.

**Comment by lazaridiscom** [comment]
@carver, One final 'pass': 

You're totally right with `place`.

I forgot to mention that sentences and visualization help:

* We are on the ground, at **bottom**.
* We have this middleware stack which grows to the **top**
* We can **add** middleware to the stack 
* We can **add** middleware to the stack **relative_to** other middleware

Alternative (Onion):

* We are in the **inner**, in the  **center**
* Requests come in from the **outer**
* We can **add** middleware layers
* We can **inject** middleware to specific numbered **layers**
* The **innermost** **layer** has the **index** 0 (zero)
* The **outermost** **layer** has the highest **index** 

I understand now what you mean "to avoid confusion with lists". The terminology you've choosen seems to be valid (taking in account that "index" should be avoided to not confuse this with list).

**Comment by carver** [comment]
Great, I'd love feedback on the docs describing the new API: http://web3py.readthedocs.io/en/latest/middleware.html#middleware-order

**Comment by lazaridiscom** [comment]
### Onion

Not sure: web3.py should possibly be "the center" of the onion. But this can be verified with a bit lookup.

Naming should be overall. If you decide to go away from stack, then this would mean to change 'Web3.middleware_stack' to 'Web3.middleware_layer` (or even "onion", not sure about the standard-term). Anoterh possible alternative: a neutral `web3.middeware`

### Stack

docs still mention `Web3.middleware_stack` (and not the `onion` model)

An alternative would be to stay for now with "stack", and use a classic stack diagram like this:

![stack](https://marcosh.github.io/presentations/2017/08/30/img/req-mw-resp.png)

Then, inner/outer becomes top/bottom again.

When does the beta end? Or differently: ho much time is left to introduce changes?

**Comment by carver** [comment]
> Not sure: web3.py should possibly be "the center" of the onion.

This doesn't feel right. Going out from the center and then looping around on the outside is much more complex than: going through the center of a sphere and back out, all in a straight line.

> docs still mention Web3.middleware_stack

Right, but all of the text descriptions were moved from stack to "onion" layer. The only thing that remains is the legacy API.

> Then this would mean to change `Web3.middleware_stack` to `Web3.middleware_layer`.

Yeah, the thought occurred to me. I'd like to make as few new breaking changes as possible, especially for things that were released in v3, without deprecation warnings. So I'm thinking this would have to go in v5.

> When does the beta end? Or differently: ho much time is left to introduce changes?

Very soon now. Ideally in the next week or two.

**Comment by lazaridiscom** [comment]
>  I'd like to make as few new breaking changes as possible,

of course, I forgot this.

> Very soon now. Ideally in the next week or two.

Not much time.

The thing: The documentation, as is, confuses me.

* Having "stack" and "onion" is mentally incompatible somehow.
* The "inner/outer" I can mentally apply to "stack" as well.
* I guess the onion-graphic/talk must go (at least for now).  and inner/outer could stay.
* Possibly the overall "onion redesign" should go to v5.

But will be more clear in around 24h.

**Comment by lazaridiscom** [comment]
@carver 

* The onion diagramm confuses (the request should return up to web3.py, not go through downwards to a 2nd web3.py).

But most importantly:

the onion diagram breaks my mental model of a stack that I've since years, and thus when I read "stack" in code, I always apply this mental model.

Then:

http://web3py.readthedocs.io/en/latest/internals.html#request-lifecycle

Shows a stack, but discusses an onion ("You can visualize this relationship like an onion"). This discrepancy totally knocks me out.

I would at this point remove all onion references and diagrams, and stick to "stack".

**Comment by pipermerriam** [comment]
@lazaridiscom it's worth taking into consideration that the middleware API is *low level*.  Most users will either never need to touch it, or they will pile on some extra convenience middlewares with no consideration to ordering.

Not saying any of your confusion is invalid, just that it's a complex mechanism and some confusion isn't surprising as we work on the API and terminology.

**Comment by lazaridiscom** [comment]
@pipermerriam Yes, of course. But those who need to use it (or worser: need to dive into code-internals), will need clean docs. 

Please realize that for me personally, the concepts are crystal-clear (middleware, micro-services, plug-ins etc., stack/onion, queues etc.), they are peanuts. 

What is confusing to me is the documentation, intermixing onion/stack. 

See, this here is very nice: http://web3py.readthedocs.io/en/latest/internals.html#request-lifecycle

Simply build on it:

You then show a further detail-level of the stack, and all fine (hopefully, the current order fits to this diagram, but ok, the worsest thing would be reversed numbering):

```
+-----------------------------+
|            Manager          |
+-----------------------------+
      |                ^
      v                |
+-----------------------------+
|     Global Middlewares      |
+-----------------------------+
| my_nice_middleware          |
| my_nicer_middleware         |   <- middleware.inject()
| my_super_middleware         |
+-----------------------------+
      |                ^
      v                |
+-----------------------------+
|    Provider Middlewares     |
+-----------------------------+
```
-

(i can work a diagram out, like this, saves @carver some time for code. no hard feelings if you finally decide to not use it.)
