### ISSUE TITLE
Sending TX to the test net 

### ISSUE THREAD

**Issue by DrMartiner** [ethereum/web3.py#665]
* Version: 3.16.5
* Python: 3.5
* OS: osx

### Tx was not send to the test net

I **try to send a TX** to test net, but my **balance was not changed** and I **can't find the TX** at [ropsten.etherscan.io](https://ropsten.etherscan.io). Please tell me where I was wrong? I'm  code from the docs.

```python
from web3.personal import Personal
from web3 import Web3, EthereumTesterProvider

# I've got a test tokens from http://faucet.ropsten.be:3001/
w3_instance = Web3(EthereumTesterProvider())
key = w3_instance.sha3(text='12 words phrase....')
person = Personal(w3_instance)
person.importRawKey(private_key=key, passphrase='123')

balance_before = w3_instance.eth.getBalance(w3_instance.eth.coinbase)

# Sign and send TX
txn_params = {
    'to': '0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1',
    'from': w3_instance.eth.coinbase,
    'value': 1,
    'gas': 21000,
    'gas_price': w3_instance.eth.gasPrice,
}
txn_hash = w3_instance.eth.sendTransaction(txn_params)

balance_after = w3_instance.eth.getBalance(w3_instance.eth.coinbase)

print(
    'Before: {}\tAfter: {}\nTX hash: {}'.format(
        balance_before, balance_after, txn_hash
    )
)
```

**Comment by carver** [comment]
`EthereumTesterProvider()` is meant to be used for local testing without connecting to any network.

Try connecting your node (geth/parity/whatever) to the testnet, then connect to the node using the IPCProvider: http://web3py.readthedocs.io/en/stable/providers.html#ipcprovider

In general, ethereum.stackexchange.com is a better forum for "how do I do X?" questions.
