### ISSUE TITLE
2-way SSL / Client side certificates

### ISSUE THREAD

**Issue by anthonygd** [ethereum/web3.py#677]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?

No support for 2-way SSL / client side SSL certificates.

### How can it be fixed?

If support exists, the documentation could be improved.  If support doesn't exist I could start work on it.

**Comment by carver** [comment]
web3.py uses python `requests` under the hood to make connections with the `HTTPProvider`. I would expect it to work out of the box to connect with an https url, but AFAIK there are no tests for it. Have you tried a connection to a server over https? If you're getting an error, what are you getting?

**Comment by anthonygd** [comment]
I think HTTPS is fine.  I'm looking for the client side certs.

Specifically something like http://docs.python-requests.org/en/master/user/advanced/?highlight=client#client-side-certificates but I don't see a way to pass the cert. info to the provider.

**Comment by carver** [comment]
> Specifically something like http://docs.python-requests.org/en/master/user/advanced/?highlight=client#client-side-certificates

Ah, got it. Thanks for the link.

> If support doesn't exist I could start work on it.

We'd welcome the contribution!

**Comment by anthonygd** [comment]
Not sure when it showed up but 4.0.0b11 has what I need, so I'm good now.  Thanks.
