### ISSUE TITLE
Warn that eth-account has not been audited

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#678]
* Version: 4.0.0

## What was wrong?

`eth-account` is pending audit, but there is an expectation that `w3.eth.account` will be included with web3.py v4. We don't want people who see that v4 is going stable to mistake that as a signal that `eth-account` is ready for prod use.

### Do all of these:

- Include a big warning box at the top of http://web3py.readthedocs.io/en/latest/web3.eth.account.html saying something like: "This has not gone through security review"
- Some kind of explicit opt-in process
- Add a section to the docs explaining how to enable `w3.eth.account`

#### Approaches

1. Install "extra" to opt-in
2. Flip runtime flag to opt in
3. ??

#### Approach Detail

1. Don't install `eth-account` unless user installs web3 with `pip install web3[unaudited-private-keys]`. At startup, if `eth_account` is not available, create a `w3.eth.account` property that immediately throws on access, explaining:
    a. what the property is
    b. ask if they meant `w3.eth.accounts`
    c. why it's not enabled by default
    d. how to enable it
2. Always install `eth-account`, but immediately install the throwing `w3.eth.account` property  (see: a, b, c, d from 1). Add a `w3.eth.i_know_private_key_code_is_unaudited = True` property setter that installs `eth-account` to `w3.eth.account`.

#### Tradeoffs

1. Install "extra" to opt-in
   - Benefit: easy to get started; one-time opt-in
   - Downside: if eth-account was already installed (eg~ because they were on the beta), then they can "accidentally" opt in without noticing
2. Flip runtime flag to opt in
   - Benefit: No way to "accidentally" opt in, error message offers a straightforward solution
   - Downside: Have to flip the flag on every run, annoying at terminal

#### Current favorite

Between these, I'm leaning to 2. We can get rid off all this nonsense after the audit. In the meantime, I'd rather have it be a bit more annoying than to have people accidentally opt-in.

In the short term, for people at the terminal, we could guide them to use `from eth_account import Account` directly.

#### Something else?

@pipermerriam any other ideas or thoughts on these?

**Comment by pipermerriam** [comment]
+1 to the long explicit property setter that enables `w3.eth.account`.
