### ISSUE TITLE
Event filtering with `filter.get_new_entries`

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#683]
* Version: 4.0.0-beta.11
* Python: 3.6
* OS: osx

### What was wrong?

I'm trying to listen to events from a contract with the code below. When using `filter.get_all_entries` I correctly get all matching events every time it's called. When using `filter.get_new_entries` I expect(ed) it to behave in the following way:
- On first call it returns all events that happened till the call
- afterwards it just return the delta since the last call

However, I always seem to get the delta, so the result for the first call is always an empty list. Is this misunderstanding from my side or a bug in the library?

```py
    w3 = Web3(HTTPProvider('http://localhost:8545'))
    contract = get_registry_contract(w3)
    filter =contract.eventFilter('TokenAdded', {'fromBlock': 0})

    events = filter.get_new_entries()
    print(f"filter id {filter.filter_id}")
    print(w3.eth.getFilterChanges(filter.filter_id))
    print(f"got new events: {len(events)}")

    for event in events:
        print(event)
```

**Comment by palango** [comment]
I created some simple demo:
```py
import json

import web3
import web3.eth
from web3 import Web3, HTTPProvider
from web3.contract import Contract


ROPSTEN_REGISTRY_ADDRESS = '0x68e1B6eD7d2670E2211A585D68ACFa8b60CCb828'
ABI = '{"abi": [{"constant": true, "inputs": [{"name": "", "type": "address"}], "name": "registry", "outputs": [{"name": "", "type": "address"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": true, "inputs": [{"name": "token_address", "type": "address"}], "name": "channelManagerByToken", "outputs": [{"name": "", "type": "address"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": true, "inputs": [{"name": "", "type": "uint256"}], "name": "tokens", "outputs": [{"name": "", "type": "address"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": true, "inputs": [], "name": "channelManagerAddresses", "outputs": [{"name": "", "type": "address[]"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": true, "inputs": [], "name": "tokenAddresses", "outputs": [{"name": "", "type": "address[]"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": true, "inputs": [], "name": "contract_version", "outputs": [{"name": "", "type": "string"}], "payable": false, "stateMutability": "view", "type": "function"}, {"constant": false, "inputs": [{"name": "token_address", "type": "address"}], "name": "addToken", "outputs": [{"name": "", "type": "address"}], "payable": false, "stateMutability": "nonpayable", "type": "function"}, {"payable": false, "stateMutability": "nonpayable", "type": "fallback"}, {"anonymous": false, "inputs": [{"indexed": false, "name": "token_address", "type": "address"}, {"indexed": false, "name": "channel_manager_address", "type": "address"}], "name": "TokenAdded", "type": "event"}], "checksum": "8cca4d0aff0db07a5578088c29efb7be1f7896bd"}'
ABI_JSON = json.loads(ABI)


def get_registry_contract(w3):
    return w3.eth.contract(
        address=ROPSTEN_REGISTRY_ADDRESS,
        abi=ABI_JSON['abi']
    )


if __name__ == '__main__':
    w3 = Web3(HTTPProvider('http://localhost:8545'))
    contract = get_registry_contract(w3)
    filter =contract.eventFilter('TokenAdded', {'fromBlock': 0})

    events_new = filter.get_new_entries()
    events_all = filter.get_all_entries()

    print(f'events_new: {len(events_new)} events')
    print(f'events_all: {len(events_all)} events')
```

Running this locally gives me the following output:
```
python event_test.py
events_new: 0 events
events_all: 41 events
```

Not sure if it's related, but #674 sounds similar.

**Comment by pipermerriam** [comment]
@palango what type of node are you connecting to?

Reason I ask is that web3 doesn't actually implement any logic related to gathering the appropriate events.  It merely delegates these calls to the node that it's connected to.  So, the error you're seeing is likely not a web3.py one, but something wrong with the node you are connecting to.

Also, there *could* be a race condition at play.  I don't know, but you might see if you get different results if you put a `time.sleep()` between the creation of the filter, and the calls to get the events.

**Comment by palango** [comment]
@pipermerriam 

It's geth 1.8.2-stable

Adding `time.sleep(1)` doesn't help.

Just to be sure: is my expectation right here? I expect that `filter.get_new_entries()` returns all events that fit the conditions before call-time get returned. Afterwards it would return just the events that happened in the mean time.

**Comment by boneyard93501** [comment]
maybe i'm missing something, but since the last transaction on that contract was some 79 days ago, there are no new events (since your last call). so get_new_events() works are expected, no?

**Comment by palango** [comment]
@boneyard93501 The question is more how to interpret the RPC docs:
> Polling method for a filter, which returns an array of logs which occurred since last poll.

I'd argue that since I haven't polled after filter creation the first call should return the same events as `get_all_entries`. But I might misunderstand this as well.

**Comment by boneyard93501** [comment]
if you look at the [geth code](https://github.com/ethereum/go-ethereum/blob/5c83a4e5dd600fcf19502f7fb083dc0b6393f969/eth/filters/api.go) , it seems to me that the timer gets set (the first time) when the filter is installed and that `eth_getFilterChanges` works of that timer element resulting in the observed behavior.
if you go back to the RPC spec, in think that follows from the `eth_newFiliter` def eluding to the filter installation being the initial (temporal) reference point for capturing change change:
```
eth_newFilter
Creates a filter object, based on filter options, to notify when the state changes (logs). To check if  
the state has changed, call eth_getFilterChanges.
```

**Comment by pipermerriam** [comment]
@palango closing as this doesn't seem to be a web3.py issue.  Feel free to continue conversation.
