### ISSUE TITLE
`removed` flag in events

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#684]
* Version: 4.0.0-beta.11
* Python: 3.6
* OS: osx

### What was wrong?

The RPC docs specify that each event has a `removed` flag denoting if the event got removed in a chain reorg. See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges

In the events I get from web3.py I don't see this flag. Is it ommitted for a special reason? (Metaquestion: Is it reliable?)

A sample event I got from querying:

```py
AttributeDict({
    'args': AttributeDict({
        'token_address': '0x0f114A1E9Db192502E7856309cc899952b3db1ED',
        }),
    'event': 'TokenAdded',
    'logIndex': 0,
    'transactionIndex': 0,
    'transactionHash': HexBytes('0xf0a233cd984c910f8321c15e19c0f11efe7ec86b8ff529c944262e5694147c65'),
    'address': '0x68e1B6eD7d2670E2211A585D68ACFa8b60CCb828',
    'blockHash': HexBytes('0x001fd3eab610df5e90f7c2996d9d63d238edb49380c05f92dd4f01b71a807f27'),
    'blockNumber': 1661140
})
```

### How can it be fixed?

Add the `removed` flag.

**Comment by carver** [comment]
Hm, interesting, even the example just below the link does not include the `removed` flag. Presumably, if the key isn't present, then it means it was not removed. Not a good experience though.

At first glance, it seems that it would be good to default the key to `False` if it's not present in the json-rpc response.

**Comment by palango** [comment]
When I looked at this it seemed like it got never emitted by the pyethereum tester provider I used. `geth` emits it but I'm not sure if it's reliable as I couldn't manage to build a reliable chain reorg test.

**Comment by dHonerkamp** [comment]
I'm afraid I couldn't find any reliable source on this. I tried to test it by listening to events for a few hours, but in no case could I encounter an event with said `removed` field.

Therefore my question: Is it known by now whether I can rely on the removed field to identify events that got lost in reorganisations? (And does this field even exist at all in the python implementation)

**Comment by fselmo** [comment]
stale
