### ISSUE TITLE
Adding extra data to transaction via buildTransaction() fails.

### ISSUE THREAD

**Issue by nueverest** [ethereum/web3.py#685]
* Version: 4.0.0b11
* Python: 3.6.3
* OS: linux

### What was wrong?

I am attempting to:

- Add custom data in hexidecimal format `0x349857efdab831` to the input data field (this Fails).

It seems I do not know the correct syntax for adding data to the custom input data field.

* The code 

The method `transact()` allows me to manually sign a transaction, but it is unclear how to add custom data.
```
mintTransaction = contract.functions.mintTokens(
        token_testing,
        200000000000000000000,
    ).transact({
        'from': token_wallet
    })
```

So I tried `buildTransaction()`. With 'input' and 'data' keys.  Neither, separately tested, case worked. The key `data` was not allowed.  The key `input` was not valid.
```
mintTransaction = contract.functions.mintTokens(
        token_testing,
        200000000000000000000,
    ).buildTransaction({
        'from': token_wallet,
        'chainId': w3.version.network,
        'gas': 150000,
        'gasPrice': w3.toWei('1', 'gwei'),
        'nonce': nonce,
#        'input': '0x349857efdab831',
#        'data': '0x349857efdab831'
    })
    print('mintTransaction', mintTransaction)

    tx = w3.eth.sendTransaction(mintTransaction)
    print('tx', tx)
```

* The full output of the error

Without `input` or `data` key I see a popup in the parity node interface requesting a password.  I manually enter the password, and it appears to succeed.  However, I never see the transaction appear as it does when I use `.transact({})`.

> `input` key case
```
raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'Invalid params: unknown field `input`, expected one of `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`, `condition`.'}
```

> `data` key case
```
raise ValueError("Cannot set data in call buildTransaction")
ValueError: Cannot set data in call buildTransaction
```

* What type of node you were connecting to.
Parity 1.8.9

### How can it be fixed?

Maybe what I'm looking for is a way to add a message to a transaction.

**Comment by pipermerriam** [comment]
The reason that `buildTransaction` raises the error you see when `data` is provided is that `buildTransaction` is intended to be used to call contract functions with encoded function parameters.  This data gets encoded into the `data` field for the transaction and thus, if you supply `data` then you aren't actually calling the function in question.

If you want to override, then I suggest simply calling `buildTransaction` without the `data` field, and then modifying the returned transaction dictionary with the `data` you want.  However, at this point, you might as well just call `w3.eth.sendTransaction` if you want to do this.

**Comment by pipermerriam** [comment]
closing as the behavior your seeing is intented.  Please reply if I've mis-understood your question or you need further help.

**Comment by nueverest** [comment]
@pipermerriam It is not clear that the question was understood.

If I look at an ethereum transaction on etherscan I see an "Input Data" field (generally containing 0x).  This field is highlight in red in the image below.  My impression is that the Web3 "data" field is different than the "Input Data" field.  Is this correct?

How do I set the "Input Data" field via Web3 (working code example preferred)?

![eth_transaction_example](https://user-images.githubusercontent.com/2917370/37215959-bb386064-2376-11e8-8846-38322459a3bf.png)

**Comment by pipermerriam** [comment]
You are not correct.  The `data` field in `Web3.py` is the same as the "Input Data" field on etherscan.

**Comment by pipermerriam** [comment]
When working with contracts, the assumption is that the contract instance is going to hangle populating the `data` field (with the encoded arguments for whatever function you are calling.

So, when working with contracts, you won't use the `data` field (other than maybe if you're interacting with the fallback function API.

If you want to send raw data to a contract, you can just use `web3.eth.sendTransaction({..., to: "<the contract address", data=b'<this should be the raw bytes you want to send>'})`

**Comment by nueverest** [comment]
Thank you this helped to clarify my misunderstanding.
