### ISSUE TITLE
Can't load web3 at command line: ImportError: cannot import name 'force_text'

### ISSUE THREAD

**Issue by mowliv** [ethereum/web3.py#690]
* Version: 3.11.1
* Python: 3.6.4
* OS: osx

### What was wrong?

Unable to load Web3 at command line. Please advise - do I need older version of python or some libraries?

```
>>> from web3 import Web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 5, in <module>
    from web3.main import Web3
  File "/usr/local/lib/python3.6/site-packages/web3/main.py", line 3, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'

```

**Comment by pipermerriam** [comment]
This is fixed in the v4 beta (which is very very close to being released as stable).  I recommend you upgrade with `pip install -U --pre web3`

Alternatively you can try downgrading `eth-utils` with `pip install eth-utils<=1.0.0` but I suspect you may still have problems.

**Comment by mowliv** [comment]
Thanks.
