### ISSUE TITLE
Where is mycontract.methods ?

### ISSUE THREAD

**Issue by land-pack** [ethereum/web3.py#695]
* Version: 3.16.5
* Python: 3.6.4
* OS: osx

### Can't see my methods from my Contract instance.
I have try the below code, and then run it on my Mac. Just for check where is my methods.

import redis
from web3 import Web3, HTTPProvider, IPCProvider, RPCProvider
from web3.contract import ConciseContract
from abi import abi

w3 = Web3(HTTPProvider('http://192.168.12.34:9585'))
addr = '0x9548bd8b13ceff478f16d206a4752f23579d7ac6'

contract = w3.eth.contract(abi=abi, address=addr)
print(contract)

def unlock(w3):
    w3.personal.unlockAccount(w3.eth.accounts[0], passphrase='123456')
    return True

unlock(w3)
print(dir(contract))

```
<web3.contract.Contract object at 0x10d108b70>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_encode_abi', '_encode_constructor_data', '_encode_transaction_data', '_find_matching_event_abi', '_find_matching_fn_abi', '_get_function_info', '_prepare_transaction', '_return_data_normalizers', '_source', 'abi', 'address', 'asm', 'ast', 'bytecode', 'bytecode_runtime', 'call', 'clone_bin', 'code', 'code_runtime', 'deploy', 'dev_doc', 'encodeABI', 'estimateGas', 'factory', 'interface', 'metadata', 'on', 'opcodes', 'pastEvents', 'source', 'src_map', 'src_map_runtime', 'transact', 'user_doc', 'web3']
```

* The [docs](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id15) from official . But I can't see my `methods` attribution.

Any one help?

**Comment by pipermerriam** [comment]
The docs you link to are for the javascript web3 library.  Take a look at the python docs here: 

- for `3.x`: http://web3py.readthedocs.io/en/stable/
- for `4.x` (beta): http://web3py.readthedocs.io/en/latest/

If you go ahead and upgrade to v4 beta which is generally recommended, what you are looking for is under `contract.functions`.  There is no equivalent in v3 so you'll have to dig into the contract abi to get a list of functions.
