### ISSUE TITLE
Passing byte32 array to contract

### ISSUE THREAD

**Issue by jpoullet2000** [ethereum/web3.py#706]
* Version: 3.16.5
* Python: 3.6
* OS: linux
### What was wrong?

I have some solidity function: function Voting(bytes32[] candidateNames)
Full `Voting.sol` file is available [here](https://github.com/llSourcell/Your_First_Decentralized_Application/blob/master/voting.sol)
From Python
```python
import json
import web3
from web3 import Web3, HTTPProvider, TestRPCProvider
from solc import compile_source
from web3.contract import ConciseContract
  
contract_file = 'Voting.sol'
with open(contract_file, 'r') as myfile:
    code = myfile.read()
compiled_sol = compile_source(code)
contract_interface = compiled_sol['<stdin>:Voting']
w3 = Web3(TestRPCProvider(port=8546))
# Instantiate and deploy contract
bytecode = contract_interface['bin']
contract = w3.eth.contract(abi=contract_interface['abi'], bytecode=bytecode)
candidates = [b'Rama', b'Niki', b'Jose']
tx_hash = contract.deploy(args=candidates, transaction={'from': w3.eth.accounts[0], 'gas': 410000})
```
Error: 
- `TypeError: Incorrect argument count.  Expected '1'.  Got '3'`

If I replace the line
`candidates = [b'Rama', b'Niki', b'Jose']`
by 
`candidates = [b'Rama']`
I get the error
- `TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: bytes32[]` 

Any idea how I should solve that?

**Comment by dylanjw** [comment]
@jpoullet2000 `args` expects a list, so the last line of your code should be:

```
tx_hash = contract.deploy(args=[candidates], transaction={'from': w3.eth.accounts[0], 'gas': 410000})
```
