### ISSUE TITLE
Test v4 with fresh install in pipenv

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#707]
* Version: v4

### What was wrong?

Claims of dependency mismatches in https://github.com/ethereum/eth-abi/issues/25#issuecomment-370448910

### How can it be fixed?

Probably just some dependency fixups.

**Comment by carver** [comment]
Things are broken, but I can't tell why. Asked for some support in: https://github.com/pypa/pipenv/issues/1802

It's at least possible that it's a `pipenv` issue, so I'm pulling this out of the milestone requirement, since it installs with `pip` without apparent problems.

**Comment by pipermerriam** [comment]
TIL pipenv exists.
