### ISSUE TITLE
Check for POA extra data and throw a helpful exception

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#712]
### What was wrong?

It would be nice to direct users to use the `geth_poa_middleware` when `extraData` conforms to the poa chain form.

### How can it be fixed?

> [Add] a special case that checks if the extraData field looks like a POA chain's and provides an exception message informing them to use the appropriate middleware.

**Comment by voith** [comment]
+1 was bitten by this a few days back!

**Comment by carver** [comment]
@voith this is another good one to work on. I see you personally dealt with it, too :)

**Comment by voith** [comment]
@carver I guess this can be closed now.
