### ISSUE TITLE
gas required exceeds allowance or always failing transaction

### ISSUE THREAD

**Issue by larrymeng** [ethereum/web3.py#721]
* Version: 4.0.0-beta.11
* Python: 3.6.4
* OS: linux

### What was wrong?

code:
gas = contract_instance.functions.halt().estimateGas()

get Error:
ValueError: {'code': -32000, 'message': 'gas required exceeds allowance or always failing transaction'}

Note:
I use rinkeby in infura.

**Comment by pipermerriam** [comment]
@larrymeng it appears that the `halt` function may have a `throw()` in it somewhere.  This is likely why you're seeing this as when it tries to *estimate* the gas needs, all it sees are a transaction which **always** fails.

**Comment by pipermerriam** [comment]
If you still need further assistance, we'll need some example code which we can use to reproduce this.
