### ISSUE TITLE
Add a "Common Problems" page to the documentation

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#728]
### What was wrong?

There are certain issues that are encountered regularly by users.  

### How can it be fixed?

We should add a "Common Problems" page to the documentation which tries to capture these succinctly and provides answers/solutions.

- using `web3.eth.sendTransaction` when connected to infura
- trying to access `web3.personal` API when using parity or when the `personal` API is not enabled with geth.
- trying to call methods off of the `Web3` class rather than an instance of the class.
- improper instantiation of contract instances like trying to call functions off of the contract class.

**Comment by marcgarreau** [comment]
Finally closing this ancient issue after making a couple doc tweaks. I like the pattern of adding an FAQ to the bottom of specific guides, e.g., contracts, otherwise questions that don't fit nicely into one bucket wind up in `Troubleshooting`.
