### ISSUE TITLE
`eth-tester` does not support byzantium

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#729]
Logging this issue here even though it's really a Py-EVM and eth-tester thing because I think it should block the v4 stable.

### What was wrong?

The `EthereumTesterProvider` doesn't support the Byzantium fork rules.

### How can it be fixed?

Needs to be fixed upstream in Py-EVM and eth-tester.

**Comment by carver** [comment]
> I think it should block the v4 stable

`eth-tester` isn't even installed as part of a vanilla web3 install. It's incomplete in other ways as well. Why do you think this in particular is a blocker?
