### ISSUE TITLE
Raise TransactionFailed instead of ValueError when there is an error in the contract

### ISSUE THREAD

**Issue by 4gn3s** [ethereum/web3.py#75]
- Version: 2.0.0
- Python: 2.7
- OS: linux
### What was wrong?

When a contract throws, web3.py raises a `ValueError`, which has the exact type of error (`TransactionFailed`) hidden in its message. A `ValueError` in web3.py can be caused by something entirely different. Checking the fields of `ValueError` to make sure that it indeed is a `TransactionFailed` is inconvenient, and does not fit nicely into `with pytest.raises()` syntax.

I would like to be able to do the following:

``` python
with pytest.raises(TransactionFailed):
      contract.some_method.sendTransaction(invalid_args)
```
#### Cute Animal Picture

![Cute animal picture](http://1funny.com/wp-content/uploads/2011/08/baby-hippo.jpg)

**Comment by 4gn3s** [comment]
Hi @pipermerriam, I will gladly contribute to this. Should this be implemented in `providers/manager/py` lines 25 and 51?

**Comment by carver** [comment]
@4gn3s which kinds of exceptions would you want covered by this? Web3 won't know if the transaction will `throw`, for example.

I'll close if I don't hear back in a week, but feel free to reopen with more info.
