### ISSUE TITLE
web3.eth.account.sign method missing in web3==4.0.0?

### ISSUE THREAD

**Issue by miguelsimon** [ethereum/web3.py#753]
* Version: web3==4.0.0b11 
* Python: 3.6
* OS: ubuntu

### What was wrong?

I recently reinstalled web3==4.0.0b11 with pip and the web3.eth.account.sign method described in the docs seems to be gone: https://github.com/ethereum/web3.py/blob/master/docs/web3.eth.account.rst#sign-a-message

To reproduce:

```
bash-4.2# python3 -m venv env
bash-4.2# source env/bin/activate
(env) bash-4.2# pip install --no-cache-dir web3==4.0.0b11
(env) bash-4.2# python 
Python 3.6.3 (default, Apr  7 2018, 16:26:36) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3.auto import w3
>>> for k in dir(w3.eth.account):
...     print(k)
... 
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
__weakref__
_keys
create
decrypt
encrypt
privateKeyToAccount
recoverHash
recoverTransaction
setKeyBackend
signHash
signTransaction
>>> 
```

A set difference of dir(web3.eth.account) between an old web3==4.0.0b11 build and the new one shows that these methods are no longer there: {'sign', 'recover', 'recoverMessage', 'hashMessage'} while these methods are now present: {'recoverHash', 'signHash', '__init_subclass__'}

**Comment by miguelsimon** [comment]
I hadn't noticed that web3==4.0.0 already came out, I ```pip install --no-cache-dir web3==4.0.0``` and it doesn't seem to be available there either.

**Comment by voith** [comment]
@miguelsimon can you run `pip freeze |  grep 'eth-account' `.
I have `eth-account==0.1.0a2` installed and `sign` works fine.

However, a new version of `eth-account` was released yesterday and that does in fact give me the same error that you're getting.
 
A quick fix for now should be:
`pip install eth-account==0.1.0a2`

**Comment by miguelsimon** [comment]
@voith I have ```eth-account==0.2.0a0```, installing ```eth-account==0.1.0a2``` does indeed fix the issue, thanks for the workaround!

**Comment by voith** [comment]
cc @carver 
I wanted to submit a PR with pinning `eth-account` to `0.1.0a2`(not sure if its the right fix), However there doesn't seem to be a v4 branch.

**Comment by pipermerriam** [comment]
@voith I believe what's going on here is the following (@carver can verify)

The `sign` functionality between web3js, web3py, geth, parity, etc has not been implemented consistently or to any specific standard.  The *most* standardized one (what web3.py does and what geth uses) is fundamentally broken for certain inputs.

So, I think we're either removing `sign` or moving it to different name in preparation for in incoming message signing standard that isn't yet finalized.

**Comment by voith** [comment]
@pipermerriam
I did have a look at the [PR](https://github.com/ethereum/eth-account/pull/13) where `signHash` was introduced and `sign` was deprecated before commenting here. However the PR also mentions that `sign` still works.

> I think we're either removing sign or moving it to different name in preparation

But the docs of v4 still say that `sign` works. So this is either a doc fix or the `eth-account` version needs to be pinned.

**Comment by voith** [comment]
Tests on master are failing because of this!

**Comment by carver** [comment]
> So, I think we're either removing sign or moving it to different name in preparation for in incoming message signing standard that isn't yet finalized.

Correct.

> Tests on master are failing because of this!

Indeed. #758 fixes that.

**Comment by carver** [comment]
Fixed by pinning eth-account to an older version. But note that `sign()` *will* be going away soon. The docs will update with information on how to work around it, at the time that the method is removed.
