### ISSUE TITLE
Cannot set nonce in transaction

### ISSUE THREAD

**Issue by dangell7** [ethereum/web3.py#764]
* Version: 4.1.0
* Python: 3.5
* OS: linux

### What was wrong?

When running the function contract.constructor().buildTransaction() I got the following error:

```
Error Deploying Campaign Contract: Cannot set nonce in transaction
Traceback (most recent call last):
  File "test.py", line 333, in <module>
    test_deploy_new_campaign()
  File "test.py", line 282, in test_deploy_new_campaign
    value=value
  File "/home/harpangell/PycharmProjects/project-x/server/utils/ethereum.py", line 394, in deploy_campaign
    ).buildTransaction(built_transaction)
  File "/home/harpangell/.virtualenvs/samynet/lib/python3.5/site-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/harpangell/.virtualenvs/samynet/lib/python3.5/site-packages/web3/contract.py", line 753, in buildTransaction
    ["data", "to", "nonce"])
  File "/home/harpangell/.virtualenvs/samynet/lib/python3.5/site-packages/web3/contract.py", line 766, in check_forbidden_keys_in_transaction
    raise ValueError("Cannot set {} in transaction".format(', '.join(keys_found)))
ValueError: Cannot set nonce in transaction
```

Here is my code:

```py
built_transaction = {
                'nonce': nonce,
                'gasPrice': gas_price,
                'gas': gas_limit,
                'chainId': chainId,
                'value': eth_value,
            }

transaction = self.campaign_contract.constructor(
                brand_address,
                ambassador_address,
                eth_samy_fee
            ).buildTransaction(built_transaction)

```

If I remove the nonce, I get the following error on the signTransaction() function. 

`TypeError: Not all fields initialized`

### How can it be fixed?

I dont think its a fix, but I think I'm doing something wrong...

**Comment by dangell7** [comment]
Obviously it looks like this check `["data", "to", "nonce"]` is the error. Why can I not set the nonce in the transaction, and where would I set the nonce?

**Comment by dangell7** [comment]
Looks like adding the nonce after the buildTransaction() worked. However, I also have to add the ['to'] = '' as well. I thought there was a pr/merge for this? Do I need to upgrade somehow? I would like to be on the latest version and not the stable. I believe I need something like pip install web3==4.2.0-beta or something?

**Comment by carver** [comment]
I believe the fix is already on master.

We're not currently releasing beta versions right now, since stable releases are coming out pretty often. Next one should be out on ~Monday.

If you want to install the latest version from source, you could use:

```
pip install git+git://github.com/ethereum/web3.py.git#egg=web3
```

---

Protip: you can mark multiline code blocks in github comments with:

<pre>
```
code_here()
and_here()
```
</pre>

I updated your issue with those ^ to make it more readable.

**Comment by dangell7** [comment]
@carver Groovy! Thanks for the pointers!
