### ISSUE TITLE
Dropped data field in modifyTransaction

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#770]
* Version: 4.1.0
* Python: 3.6
* OS: linux

### What was wrong?

Used `web3.eth.modifyTransaction(txn_hash, gasPrice=new_gas_price)`, and it dropped the data field from the original transaction.

### How can it be fixed?

Rename `input` field to `data` when copying data from old transaction.

**Comment by boneyard93501** [comment]
@carver 

want to do it in the param extraction ?
```python
# transactions.py
def extract_valid_transaction_params(transaction_params):
    t_params = {key: transaction_params[key] 
                for key in VALID_TRANSACTION_PARAMS if key in transaction_params}
    if t_params.get('data') is None and t_params.get('input') is not None:
        t_params['data'] = deepcopy(t_params['input'])  
    return t_params
```

**Comment by pipermerriam** [comment]
Um, maybe just use the [`eth_utils.apply_key_map`](https://github.com/ethereum/eth-utils#apply_key_mapformatter_dict-dict_like---dict)?  At least with the latest `eth-utils` it should protect against situations where both `data` and `input` are included and prevent overwritting.  (not super familiar with this issue so disregard if this isn't the right solution).

**Comment by boneyard93501** [comment]
i looked at that but wasn't entirely sure whether data and input could be instantiated; i kinda doubt it. but if its a highly improbably/impossible edge-case, re-keying is definitely the way to go.
