### ISSUE TITLE
Better error message on failed encoding

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#771]
* Version: 4.1.0

### What was wrong?

A field of type `HexBytes` slipped through the pythonic middleware and the web3 provider tried to encode it with json. The only error message was:

> TypeError: Object of type 'HexBytes' is not JSON serializable

### How can it be fixed?

Catch type errors in:

```
~/web3/providers/base.py in encode_rpc_request(self, method, params)
     65             "method": method,
---> 66             "params": params or [],
     67             "id": next(self.request_counter),
     68         }))
     69
```
In case of a `TypeError`, inspect `params` and raise another `TypeError` saying which parameter index was failing to json encode, and (if applicable) which key in the `dict` at that index.

**Comment by boneyard93501** [comment]
@carver i should be able to work on  #770 & #771 this week if you're still looking for help.

**Comment by carver** [comment]
Sure, that would be great! If you can only get to one, #770 has bigger impact

**Comment by boneyard93501** [comment]
@carver  like so?
```python
def encode_rpc_request(self, method, params):
        try:
            return to_bytes(text=json.dumps({
                "jsonrpc": "2.0",
                "method": method,
                "params": params or [],
                "id": next(self.request_counter),
            }))
        except TypeError:
            err_msg = ''
            for i, p in enumerate(params):
                try:
                    json.dumps(p)
                except Exception:
                    err_msg += ' ({},{});'.format(i, repr(p))
            msg = 'encode_rpc_request failure for method {} for invalid (index, parameter): '
            msg += err_msg.rstrip(';') + '.'
            raise TypeError(msg.format(method))
```

**Comment by carver** [comment]
Yeah, that's the idea!

I think minimizing what's in the try block would be better, so we know the `TypeError` came from the `json.dumps`. (and the second try block should just catch `TypeError` as well)

**Comment by boneyard93501** [comment]
k. thx. 
i put in a pr. will start tackling 770 tomorrow.
