### ISSUE TITLE
Incorrect return value example for web3.personal.newAccount

### ISSUE THREAD

**Issue by Gallaecio** [ethereum/web3.py#772]
http://web3py.readthedocs.io/en/stable/web3.personal.html?highlight=newAccount#web3.personal.newAccount

The documentation provides the following example:

```
>>> web3.personal.newAccount('the-passphrase')
['0xd3cda913deb6f67967b99d67acdfa1712c293601']
```

However, the return value is the address as a string, not an array containing it:

```
>>> web3.personal.newAccount('the-passphrase')
'0xd3cda913deb6f67967b99d67acdfa1712c293601'
```

**Comment by carver** [comment]
:+1: doc bug
