### ISSUE TITLE
Mismatch eth-keys version in eth-account and eth-keyfile

### ISSUE THREAD

**Issue by winterjung** [ethereum/web3.py#774]
* web3.py version: 4.1.0
* Python: 3.5
* OS: osx
* pip: 10.0.0
* pipenv: 11.10.0
* eth-account 0.1.0a2 (latest)

### What was wrong?
In commit 15e4097a937c2d7203b0fd251da1687fe08d1b61, `eth-key*` dependencies are droped and moved into `eth-account`

Required `eth-keys` version in `eth-account` is [`eth-keys>=0.2.0b3,<0.3.0`](https://github.com/ethereum/eth-account/blob/f7d174cb38d78d0e9adcf062e7b295b996fa59de/setup.py#L50)
And `eth-account` require `eth-keyfile>=0.5.0,<0.6.0`
But in `eth-keyfile`, required `eth-keys` version is [`eth-keys>=0.1.0-beta.4,<1.0.0`](https://github.com/ethereum/eth-keyfile/blob/1191e522b280b0987f9cd367a7cce38a5b72981a/setup.py#L29)

So mismatched version occur dependency warning like below.

```sh
# in pipenv
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
```

### How can it be fixed?
Bump `eth-keys` version to latest in `eth-keyfile`

**Comment by JungWinter** [comment]
Thanks! `rm -rf Pipfile.lock && rm -rf ~/.cache/pip && rm -rf ~/.cache/pipenv && pipenv install --skip-lock web3 && pipenv lock --pre --clear` works for me!
