### ISSUE TITLE
How to start mining using web3.py?

### ISSUE THREAD

**Issue by 08zhangyi** [ethereum/web3.py#778]
* Version: 3.6.15
* Python: 3.6
* OS: windows10

I have built a private ethereum-network and started its RPC service. The connection is OK when I use the code
```
>>>provider = HTTPProvider('http://localhost:8545')
>>>web3 = Web3(provider)
>>>web3.eth.blockNumber
105

```
to test the connection. But when I use `web3.miner.start(1)`, it returns that
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\web3\miner.py", line 27, in start
    "miner_start", [num_threads],
  File "C:\ProgramData\Anaconda3\lib\site-packages\web3\manager.py", line 96, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method miner_start does not exist/is not available'}
```
But in my geth. the command `miner.start(1)` is OK. How can I solve the problem?

**Comment by voith** [comment]
@08zhangyi Have you enabled the miner api in geth over rpc?
if you haven't try this:
```
geth --rpc --rpcapi web3,eth,personal,miner
```

**Comment by 08zhangyi** [comment]
@voith Thank you for helping me. Now I know what is the mechanism of geth rpc interface.

**Comment by SaiTejaMakani** [comment]
Hello, I am Struck at miner.start() after nothing is mining not sure whether I am mining or not. I tried below command and looks like it is importing all the blocks from test net(I am trying to test this I am a newbie)

geth --rpc --rpcapi web3,eth,personal,miner

1. Could you please explain what the above command will do in detail?
2. after running miner.start() my screen only shows the below lines, does that mean I am mining?
NFO [07-25|11:17:18.967] Updated mining threads                   threads=1
INFO [07-25|11:17:18.967] Transaction pool price threshold updated price=1000000000
INFO [07-25|11:17:18.968] Commit new mining work                   number=1 sealhash=2b9350…71db30 uncles=0 txs=0 gas=0 fees=0 elapsed=108.378µs

**Comment by SaiTejaMakani** [comment]
Update: seems like I have mined one block after computing for straight 14 hrs with two nodes. 

web3.fromWei(web3.eth.getBalance(web3.eth.accounts[0]))
5
