### ISSUE TITLE
Could eventFilter traverse from latest block number(tail) through head?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#779]
* pip 9.0.3
* Python: 3.5.2
* OS: linux (ubuntu)

My question is related to `eventFilter` function related to his opened question: (https://ethereum.stackexchange.com/q/17572/4575)

Following line works as explained in the documentation:

```
blockReadFrom = 1000;
my_filter = contract.eventFilter('LogUser',{'fromBlock':int(blockReadFrom),'toBlock':int(blockReadFrom) + 100})
```

Now, I just want to iterate from greater block number to smaller block number:

_Example:_

```
blockReadFrom = 1000;
my_filter = contract.eventFilter('LogUser',{'fromBlock':int(blockReadFrom+100),'toBlock':int(blockReadFrom)})
```

When I try that to do that, I get following error message:

```
ValueError: {'message': 'invalid from and to block combination: from > to', 'code': -32000}
```

**[Q]** Is this possible with `web3py` to traverse if `from > to`? This is basically reverse traverse operation in order to catch the latest event first. 

**=>** If not possible, would it be considered to be added to `web3py`, which might be helpful functionality.

**Comment by pipermerriam** [comment]
You could just reverse the returned logs assuming your querying for a list of blocks that have already been mined.

**Comment by avatar-lavventura** [comment]
I want to iterate from latest block number to block-number, where my contract is deployed. Whenever I catch the event I will break the `eventFilter` this will help me to catch the latest event. Since I make this call every 10 seconds, storing returned logs might consume memory.Or I just want a fast and efficient way just to catch the latest event.

`For example:` my contract is deployed at blockNumber: 100. later an event is triggered at blockNumber at 110 then at block number 1000 and current block number is 1100. In order to catch latest event, instead of iterating from `100=>1100`, I thought that iterating from `1100=>100` would help me the catch the latest event at block number: 1000 right away and than break the `watch()`. @pipermerriam

**Comment by pipermerriam** [comment]
Since event filtering happens on the node itself I'm not aware of anything we can do from the web3.py side.  This would require a change to the JSON-RPC API itself to allow for reversed event log filters.

**Comment by pipermerriam** [comment]
Again, you can request **all** changes for a block range of `[deploy_block, 'latest']`, reverse the returned logs and grab the first one (or equivalently, just grab the last log entry from the returned values).  Not ideal since it requires polling, but it's the best solution I can think of.

**Comment by avatar-lavventura** [comment]
Thanks for the input @pipermerriam
