### ISSUE TITLE
Convert an AttributeDict with bytes values to a json string

### ISSUE THREAD

**Issue by githubcyc** [ethereum/web3.py#782]
* Version: 4.2.1

### What was wrong?

`w3.eth.getTransaction()` returns an `AttributeDict`, which I want to send as a string, say over HTTP. I couldn't find a convenient way to make this conversion.

### How can it be fixed?

A new method that converts an `AttributeDict` to a json string:

```py
txn = w3.eth.getTransaction(txn_hash)
txn_json = Web3.toJson(txn)
```

**Comment by voith** [comment]
try this:
```python
import json

from hexbytes import HexBytes

class HexJsonEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, HexBytes):
            return obj.hex()
        return super().default(obj)


tx = web3.eth.getTransaction(transaction_hash)
tx_dict = dict(tx)
json_tx = json.dumps(tx_dict, cls=HexJsonEncoder)
```

**Comment by carver** [comment]
Seems like a custom JSON encoder could reasonably live in Web3.py. If we do it right, we could even replace some of the middleware with it.

Something like:
```py
tx = web3.eth.getTransaction(transaction_hash)
tx_json = json.dumps(tx, cls=Web3.JsonEncoder)
```

or:

```py
tx = web3.eth.getTransaction(transaction_hash)
tx_json = Web3.toJson(tx)
```
which would do something like the first thing under the hood.

**Comment by pipermerriam** [comment]
👍 to `Web3.toJson(...)`

**Comment by pipermerriam** [comment]
@carver we could also add  `AttrDict.to_json()` to the actual `AttrDict` class.

**Comment by carver** [comment]
> we could also add AttrDict.to_json() to the actual AttrDict class.

Eh, I don't like the idea that `AttributeDict` would know anything about `HexBytes`.

**Comment by vindard** [comment]
I came across this issue as well a while back. I solved it a bit differently though:
```
def toDict(dictToParse):
    # convert any 'AttributeDict' type found to 'dict'
    parsedDict = dict(dictToParse)
    for key, val in parsedDict.items():
        # check for nested dict structures to iterate through
        if  'dict' in str(type(val)).lower():
            parsedDict[key] = toDict(val)
        # convert 'HexBytes' type to 'str'
        elif 'HexBytes' in str(type(val)):
            parsedDict[key] = val.hex()
    return parsedDict
```
This way had the additional benefit for me of finding `AttributeDict`'s that may have been nested in other dicts (which I did actually come across). To convert to json I'd simply `json.dumps(toDict(tx))`. Hope this helps others as well.

**Comment by iNomaD** [comment]
Modified @vindard example to work with lists also:
```
def toDict(dictToParse):
    # convert any 'AttributeDict' type found to 'dict'
    parsedDict = dict(dictToParse)
    for key, val in parsedDict.items():
        if 'list' in str(type(val)):
            parsedDict[key] = [_parseValue(x) for x in val]
        else:
            parsedDict[key] = _parseValue(val)
    return parsedDict


def _parseValue(val):
    # check for nested dict structures to iterate through
    if 'dict' in str(type(val)).lower():
        return toDict(val)
    # convert 'HexBytes' type to 'str'
    elif 'HexBytes' in str(type(val)):
        return val.hex()
```
