### ISSUE TITLE
Compatibility with rlp v1.*

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#794]
### What was wrong?

pyrlp went through a major upgrade, web3.py should support both v0 and the new v1.

### How can it be fixed?

_Maybe_ the only requirement is to upgrade eth-tester after https://github.com/ethereum/eth-tester/pull/84 is merged and released. Will have to wait and test it out.

**Comment by dylanjw** [comment]
> Maybe the only requirement is to upgrade eth-tester after ethereum/eth-tester#84 is merged and released. Will have to wait and test it out.

This appears to be the case...

**Comment by carver** [comment]
Cool, how did you test it?

**Comment by dylanjw** [comment]
circleci has been running with rlp==1.0.2.  Is that sufficient, or is there a more intentional test I could do?

**Comment by carver** [comment]
Ah, well that tests v1, but not v0. I don't necessarily think we have to add an rlp v0 and v1 test to CI, but at least try it with a local checkout of rlp v0.

**Comment by dylanjw** [comment]
Almost all tests fail with rlp=0.6.0 because py-evm requires rlp>=1.

All of the failures Ive looked at are because the 0.6.0 `eth.rlp.accounts.Account` does not have a copy method.

**Comment by dylanjw** [comment]
Im sort of confused why we need to have support for rlp v0 when rlp is only an eth-tester/py-evm dependency.  eth-tester and py-evm are not backwards compatible with rlp v0.  

Do all web3 changes that rely on tests that rely on the latest py-evm need to be removed and put in the next major version bump?

**Comment by carver** [comment]
> Im sort of confused why we need to have support for rlp v0 when rlp is only an eth-tester/py-evm dependency. eth-tester and py-evm are not backwards compatible with rlp v0.

Ah, I didn't remember that. No need to support rlp v0, then. Thanks for diving into it.
