### ISSUE TITLE
How to use signAndSendTransaction in 4.0?

### ISSUE THREAD

**Issue by yihuang** [ethereum/web3.py#796]
It seems api ``personal.signAndSendTransaction`` no longer exists in 4.0, how to migrate?
Thanks.

**Comment by carver** [comment]
Correct, that method was raising deprecation warnings in v3: https://github.com/ethereum/web3.py/blob/v3.16.5/web3/personal.py#L75-L81

Use `personal.sendTransaction()` instead.
