### ISSUE TITLE
Add new autoproviders for geth --dev and Infura

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#797]
### What was wrong?

Connecting to common places is still a little hairy. For example `geth --dev` and Infura.

Inspired by #719 

### How can it be fixed?

Add new auto providers:

- [ ] Add a `from web3.auto.gethdev import w3`
- [ ] Add a `from web3.auto.infura import w3`

**Comment by bartleyg** [comment]
@carver can this be closed?
