### ISSUE TITLE
token contract returns zero balance

### ISSUE THREAD

**Issue by Liuch10** [ethereum/web3.py#804]
* Version: 4.1.0
* Python: 3.5
* OS:  osx

### What was wrong?
i was trying to deploy the simplest erc20 token, with solidity of 

```
pragma solidity ^0.4.21;
import 'StandardToken.sol';
contract FoYoToken is StandardToken {
   string public constant name = 'xxtoken';
   string public constant symbol = 'xx';
   uint256 public constant decimals = 18;
   uint256 public constant INITIAL_SUPPLY = 2000000000 * 10 ** decimals;
function constructor()  public {
     totalSupply_ = INITIAL_SUPPLY;
     balances[msg.sender] = INITIAL_SUPPLY;
   }
}
```
the compilation works smoothly i use constructor().transact() to deploy the token on my own private chain :

```
contract.constructor().transact({'from':w3.eth.coinbase})
```

after deployment, i can get the contract address, as well as  public members (name, symbols, etc) by using

```
contract_instance = w3.eth.contract(abi=$abi$, bytecode=$bin$, address=$add$, ContractFactoryClass=ConciseContract)
contract_instance.name() or contract_instanct.symbol
```

However, the token seems not fully successfully deployed because the following two commands both return 0

```
contract_instance.totalSupply_()   (=0)

contract_instance.balanceof(w3.eth.coinbase)  (=0)
```

It seems the contract doesn't run the  constructor() function?

**Comment by Lebski** [comment]
You can use ``` for codeblocks 

***What was wrong?***

i was trying to deploy the simplest erc20 token, with solidity of
```
pragma solidity ^0.4.21;
import 'StandardToken.sol';
contract FoYoToken is StandardToken {
string public constant name = 'xxtoken';
string public constant symbol = 'xx';
uint256 public constant decimals = 18;
uint256 public constant INITIAL_SUPPLY = 2000000000 * 10 ** decimals;
function constructor() public {
totalSupply_ = INITIAL_SUPPLY;
balances[msg.sender] = INITIAL_SUPPLY;
}
}
```
the compilation works smoothly i use constructor().transact() to deploy the token on my own private chain :
```
contract.constructor().transact({'from':w3.eth.coinbase})
```

after deployment, i can get the contract address, as well as public members (name, symbols, etc) by using
```
contract_instance = w3.eth.contract(abi=$abi$, bytecode=$bin$, address=$add$, ContractFactoryClass=ConciseContract)
contract_instance.name() or contract_instanct.symbol
```
However, the token seems not fully successfully deployed because the following two commands both return 0
```
contract_instance.totalSupply_() (=0)

contract_instance.balanceof(w3.eth.coinbase) (=0)
```

It seems the contract doesn't run the constructor() function?

**Comment by Lebski** [comment]
The constructor has the same name as the contract. 
In your case this would be `function FoYoToken()`
