### ISSUE TITLE
ERC-20 Token Transfer Error (unable to locate corresponding Transfer event log), check with sender.

### ISSUE THREAD

**Issue by wenbo228228** [ethereum/web3.py#812]
* Version: 4.0.0
* Python: 3.6
* OS: win8.1

### I try to send some EOS from one address to another,below are the codes:

```#send token on etherium network

from ethtoken.abi import EIP20_ABI
from web3 import Web3, HTTPProvider

infura_provider = HTTPProvider('https://mainnet.infura.io/CMI5Z7n7hAy8CP7nx95s')
w3 = Web3(infura_provider)
w3.eth.enable_unaudited_features()



contract_Address=w3.toChecksumAddress("0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0")
unicorns = w3.eth.contract(contract_Address, abi=EIP20_ABI)

nonce = w3.eth.getTransactionCount('0x030eC1E9E2AfA4A59a7C56F2B761505E1a414b45')

unicorn_txn = unicorns.functions.transfer(
     '0xFe0196504dF34c4Bf30D3089EfFf86cFe3B34617',
     1,
 ).buildTransaction({
     'chainId': 1,
     'gas': 200000,
     'value': int(0.1*(10**18)),   #EOS:18 decimals
     'gasPrice': w3.toWei('4', 'gwei'),
     'nonce': nonce,
 })

private_key = 'my private key'
signed_txn = w3.eth.account.signTransaction(unicorn_txn, private_key=private_key)


TxHash=w3.eth.sendRawTransaction(signed_txn.rawTransaction)
print(TxHash.hex())
```

Anyone know how to fix this?Thanks!

**Comment by carver** [comment]
@wenbo228228 What happens when you run the code?

**Comment by wenbo228228** [comment]
The program run successfully and exit with no error.
Then the transaction was boradcast to the network.
I went to etherscan to check the transaction,for a while,it said pending;a few minutes later,it said transaction failed.
This is the transaction information:
[https://etherscan.io/tx/0x9b2fad048600d8b0e809e397a0df4681235061501f31a42cc20a50cbee661dd6](url)

**Comment by pipermerriam** [comment]
@wenbo228228 Not a web3 error.  Your transaction just errored out during execution.

**Comment by wenbo228228** [comment]
@pipermerriam   Yep.But I don't have a clue what's wrong,you got any idea?

**Comment by carver** [comment]
Sounds like a question for https://ethereum.stackexchange.com

You will get better/faster answers if your question has a minimal, complete, and verifiable example: https://stackoverflow.com/help/mcve

**Comment by pawarvijay** [comment]
this solution helped me 

[https://ethereum.stackexchange.com/a/37024/41470](https://ethereum.stackexchange.com/a/37024/41470
)

I reDeployed my contract with higher gaslimit of 3000000 then it worked
