### ISSUE TITLE
indicate ValueError: No matching functions found when call the method in abi json file

### ISSUE THREAD

**Issue by FrancisJen** [ethereum/web3.py#821]
[env]:
python3.6

[description]:

1. part of abi source file which contains the deposit function:  details of abi json file is displayed after running.
        {
        "constant": false,
        "inputs": [],
        "name": "deposit",
        "outputs": [],
        "payable": true,
        "stateMutability": "payable",
        "type": "function"
    },
  abi has been loaded as dict"
      with open(self.R1_CONTRACT_PATH) as load_f:
            abi = json.load(load_f)

2.the contract object is :
        self.R1 = self.w3.eth.contract(address=self.R1_CONTRACT_ADDRESS, abi=abi) 

3.the method of eth sending will call the deposit method of self.R1
    def send_ether_to_contract(self, amount_in_ether):

        amount_in_wei = self.w3.toWei(amount_in_ether, 'ether')

        nonce = self.w3.eth.getTransactionCount(self.wallet_address)

        a = self.R1.functions.deposit
        print(a)
        print('----------')

        txn = self.R1.functions.deposit(
            self.wallet_address, 1,
        ).buildTransaction({
            'chainId': 1,
            'gas': 170000,
            'value': amount_in_wei,
            'gasPrice': self.w3.toWei('1', 'gwei'),
            'nonce': nonce,
        })

```

Error:
onnect_kovan.py
[{'constant': True, 'inputs': [], 'name': 'withdrawEnabled', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'withdrawAllowance', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'depositToken', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'bytes32'}], 'name': 'withdrawn', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[11][]'}, {'name': 'values', 'type': 'uint256[10][]'}, {'name': 'v', 'type': 'uint8[2][]'}, {'name': 'r', 'type': 'bytes32[2][]'}, {'name': 's', 'type': 'bytes32[2][]'}], 'name': 'batchTrade', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}], 'name': 'admins', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'admin', 'type': 'address'}, {'name': 'isAdmin', 'type': 'bool'}], 'name': 'setAdmin', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'bytes32'}], 'name': 'buyOrderFilled', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[11]'}, {'name': 'values', 'type': 'uint256[10]'}, {'name': 'v', 'type': 'uint8[2]'}, {'name': 'r', 'type': 'bytes32[2]'}, {'name': 's', 'type': 'bytes32[2]'}], 'name': 'trade', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'latestApply', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'withdrawNoLimit', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[3]'}, {'name': 'values', 'type': 'uint256[3]'}, {'name': 'v', 'type': 'uint8'}, {'name': 'r', 'type': 'bytes32'}, {'name': 's', 'type': 'bytes32'}], 'name': 'adminWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [], 'name': 'acceptOwnership', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'owner', 'outputs': [{'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'enabled', 'type': 'bool'}], 'name': 'enableWithdraw', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'lock', 'type': 'uint256'}], 'name': 'changeLockTime', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'feeRate', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'acc', 'type': 'address'}, {'name': 'asFee', 'type': 'bool'}], 'name': 'setFeeAccount', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'applyWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': '_newOwner', 'type': 'address'}], 'name': 'changeOwner', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'tokenBuy', 'type': 'address'}, {'name': 'amountBuy', 'type': 'uint256'}, {'name': 'tokenSell', 'type': 'address'}, {'name': 'amountSell', 'type': 'uint256'}, {'name': 'base', 'type': 'address'}, {'name': 'expires', 'type': 'uint256'}, {'name': 'nonce', 'type': 'uint256'}, {'name': 'feeToken', 'type': 'address'}], 'name': 'getOrderHash', 'outputs': [{'name': '', 'type': 'bytes32'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'fr', 'type': 'uint256'}], 'name': 'changeFeeRate', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'user', 'type': 'address'}, {'name': 'tokens', 'type': 'address[]'}], 'name': 'refund', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'user', 'type': 'address'}], 'name': 'approveWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [], 'name': 'deposit', 'outputs': [], 'payable': True, 'stateMutability': 'payable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'applyList', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'tokenList', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}], 'name': 'feeAccounts', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'bytes32'}], 'name': 'sellOrderFilled', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'hash', 'type': 'bytes32'}, {'name': 'v', 'type': 'uint8'}, {'name': 'r', 'type': 'bytes32'}, {'name': 's', 'type': 'bytes32'}], 'name': 'verify', 'outputs': [{'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'applyWait', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'withdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'user', 'type': 'address'}], 'name': 'balanceOf', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'VERSION', 'outputs': [{'name': '', 'type': 'string'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'inputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'}, {'payable': False, 'stateMutability': 'nonpayable', 'type': 'fallback'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'balance', 'type': 'uint256'}], 'name': 'Deposit', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'balance', 'type': 'uint256'}], 'name': 'Withdraw', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'time', 'type': 'uint256'}], 'name': 'ApplyWithdraw', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': '_prevOwner', 'type': 'address'}, {'indexed': False, 'name': '_newOwner', 'type': 'address'}], 'name': 'OwnerUpdate', 'type': 'event'}]
<web3.utils.datatypes.Contract object at 0x10624dcc0>
<class 'web3.utils.datatypes.Contract'>
7184644
<class 'web3.utils.datatypes.deposit'>
Traceback (most recent call last):
----------
  File "/Users/renyiguang/Project/py3interface/util/connect_kovan.py", line 84, in <module>
    kovan.send_ether_to_contract(0.0001)
  File "/Users/renyiguang/Project/py3interface/util/connect_kovan.py", line 55, in send_ether_to_contract
    self.wallet_address, 1,
  File "/Users/XXX/.virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/web3/contract.py", line 919, in __init__
    self._set_function_info()
  File "/Users/xxx/.virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/web3/contract.py", line 925, in _set_function_info
    self.kwargs)
  File "/Users/xxx/.virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/web3/utils/contracts.py", line 100, in find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found

Process finished with exit code 1

```

**Comment by pipermerriam** [comment]
Try wrapping your `abi` in a list.  The `abi` value should be a list of dicts.

**Comment by carver** [comment]
Closing, since this is not likely a Web3.py issue. Feel free to continue the discussion here.

**Comment by FrancisJen** [comment]
It was list

`[{'constant': True, 'inputs': [], 'name': 'withdrawEnabled', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'withdrawAllowance', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'depositToken', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'bytes32'}], 'name': 'withdrawn', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[11][]'}, {'name': 'values', 'type': 'uint256[10][]'}, {'name': 'v', 'type': 'uint8[2][]'}, {'name': 'r', 'type': 'bytes32[2][]'}, {'name': 's', 'type': 'bytes32[2][]'}], 'name': 'batchTrade', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}], 'name': 'admins', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'admin', 'type': 'address'}, {'name': 'isAdmin', 'type': 'bool'}], 'name': 'setAdmin', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'bytes32'}], 'name': 'buyOrderFilled', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[11]'}, {'name': 'values', 'type': 'uint256[10]'}, {'name': 'v', 'type': 'uint8[2]'}, {'name': 'r', 'type': 'bytes32[2]'}, {'name': 's', 'type': 'bytes32[2]'}], 'name': 'trade', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'latestApply', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'withdrawNoLimit', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'addresses', 'type': 'address[3]'}, {'name': 'values', 'type': 'uint256[3]'}, {'name': 'v', 'type': 'uint8'}, {'name': 'r', 'type': 'bytes32'}, {'name': 's', 'type': 'bytes32'}], 'name': 'adminWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [], 'name': 'acceptOwnership', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'owner', 'outputs': [{'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'enabled', 'type': 'bool'}], 'name': 'enableWithdraw', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'lock', 'type': 'uint256'}], 'name': 'changeLockTime', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'feeRate', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'acc', 'type': 'address'}, {'name': 'asFee', 'type': 'bool'}], 'name': 'setFeeAccount', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'applyWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': '_newOwner', 'type': 'address'}], 'name': 'changeOwner', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'tokenBuy', 'type': 'address'}, {'name': 'amountBuy', 'type': 'uint256'}, {'name': 'tokenSell', 'type': 'address'}, {'name': 'amountSell', 'type': 'uint256'}, {'name': 'base', 'type': 'address'}, {'name': 'expires', 'type': 'uint256'}, {'name': 'nonce', 'type': 'uint256'}, {'name': 'feeToken', 'type': 'address'}], 'name': 'getOrderHash', 'outputs': [{'name': '', 'type': 'bytes32'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'fr', 'type': 'uint256'}], 'name': 'changeFeeRate', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'user', 'type': 'address'}, {'name': 'tokens', 'type': 'address[]'}], 'name': 'refund', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'user', 'type': 'address'}], 'name': 'approveWithdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [], 'name': 'deposit', 'outputs': [], 'payable': True, 'stateMutability': 'payable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'applyList', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'address'}], 'name': 'tokenList', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}], 'name': 'feeAccounts', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': '', 'type': 'address'}, {'name': '', 'type': 'bytes32'}], 'name': 'sellOrderFilled', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'hash', 'type': 'bytes32'}, {'name': 'v', 'type': 'uint8'}, {'name': 'r', 'type': 'bytes32'}, {'name': 's', 'type': 'bytes32'}], 'name': 'verify', 'outputs': [{'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'applyWait', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'amount', 'type': 'uint256'}], 'name': 'withdraw', 'outputs': [{'name': 'success', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'name': 'token', 'type': 'address'}, {'name': 'user', 'type': 'address'}], 'name': 'balanceOf', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'VERSION', 'outputs': [{'name': '', 'type': 'string'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'inputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'}, {'payable': False, 'stateMutability': 'nonpayable', 'type': 'fallback'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'balance', 'type': 'uint256'}], 'name': 'Deposit', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'balance', 'type': 'uint256'}], 'name': 'Withdraw', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': 'token', 'type': 'address'}, {'indexed': False, 'name': 'user', 'type': 'address'}, {'indexed': False, 'name': 'amount', 'type': 'uint256'}, {'indexed': False, 'name': 'time', 'type': 'uint256'}], 'name': 'ApplyWithdraw', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'name': '_prevOwner', 'type': 'address'}, {'indexed': False, 'name': '_newOwner', 'type': 'address'}], 'name': 'OwnerUpdate', 'type': 'event'}]
`

**Comment by FrancisJen** [comment]
@pipermerriam It was list

**Comment by carver** [comment]
>  `{'constant': False, 'inputs': [], 'name': 'deposit', 'outputs': [], 'payable': True, 'stateMutability': 'payable', 'type': 'function'}`

The `deposit` function does not take any arguments, but you supplied some, so the function ABI doesn't match. I recommend upgrading to v4.2.0, which will give you somewhat better error messages in this scenario.
