### ISSUE TITLE
How to send tokens to 100 different address in a single transaction?

### ISSUE THREAD

**Issue by wenbo228228** [ethereum/web3.py#824]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

Now,I can use the following code to transfer EOS from one address to another.
But I need to do this action for 100 different address,can I send tokens to 100 address in a single transaction?

`    
from ethtoken.abi import EIP20_ABI
from web3 import Web3, HTTPProvider

infura_provider = HTTPProvider('https://mainnet.infura.io/CMI5Z7n7hAy8CP7nx95s')
w3 = Web3(infura_provider)
w3.eth.enable_unaudited_features()

contract_Address=w3.toChecksumAddress("0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0")
unicorns = w3.eth.contract(contract_Address, abi=EIP20_ABI)

nonce = w3.eth.getTransactionCount('0x030eC1E9E2AfA4A59a7C56F2B761505E1a414b45')

unicorn_txn = unicorns.functions.transfer(
     '0x86BBB3938bf9DD47898f9cbCB49C3809B4d29F7a',
    int(0.0001 * (10 ** 18)),    #EOS decimal is 18
 ).buildTransaction({
     'chainId': 1,
     'gas': 200000,
     'gasPrice': w3.toWei('2', 'gwei'),
     'nonce': nonce,
 })

private_key = ''
signed_txn = w3.eth.account.signTransaction(unicorn_txn, private_key=private_key)

TxHash=w3.eth.sendRawTransaction(signed_txn.rawTransaction)
print(TxHash.hex())
`

**Comment by pipermerriam** [comment]
@wenbo228228 this question is out of scope for the type of support we can provide in this codebase. You can try asking your question on the ethereum stack exchange site, or reach out in the gitter channel and see if anyone there is able to help you.

**Comment by wenbo228228** [comment]
@pipermerriam Yep,thanks.
