### ISSUE TITLE
generateGasPrice division by zero exception

### ISSUE THREAD

**Issue by kolosovvs** [ethereum/web3.py#825]
At this method generateGasPrice() I have division by zero exception
It's because `_get_avg_block_time` will return zero in some cases
```
def _get_avg_block_time(w3, sample_size):
    latest = w3.eth.getBlock('latest')

    if latest['number'] == 0 or sample_size == 0: # <-- here
        return 0

    constrained_sample_size = min(sample_size, latest['number'])
    oldest = w3.eth.getBlock(latest['number'] - constrained_sample_size)
    return (latest['timestamp'] - oldest['timestamp']) / constrained_sample_size
```

**Comment by pipermerriam** [comment]
This should be a reasonably easy thing to fix.  I think that if the average block time returned is `0` then we need to default to a *safe* default block time.  For now I'm fine with this being hard coded to `15` unless someone has a better idea.
