### ISSUE TITLE
how do i call ens.setup_owner() with a signed trnasaction

### ISSUE THREAD

**Issue by owocki** [ethereum/web3.py#852]
* Version: latest
* Python: 3.5
* OS: osx

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

i am trying to use this code to register a subdomain https://github.com/ethereum/web3.py/blob/master/ens/main.py#L211

```
                assignee_address = settings.ENS_OWNER_ACCOUNT
                transaction = {
                    'to': ENS_MAINNET_ADDR,
                    'from': settings.ENS_OWNER_ACCOUNT,
                    'value': 0,
                    'nonce': w3.eth.getTransactionCount(settings.ENS_OWNER_ACCOUNT),
                    'gas': 100000,
                    'gasPrice': recommend_min_gas_price_to_confirm_in_time(1) * 10**9
                }
                signed = w3.eth.account.signTransaction(transaction, settings.ENS_PRIVATE_KEY)
                txn_hash = ns.setup_owner(f'owocki.vikashbajaj.eth', assignee_address, signed)

````

but i seem to always get this exception back

```
*** ens.exceptions.UnauthorizedError: in order to modify 'owocki.vikashbajaj.eth', you must control account '0xdaD14C58D7577Fd76FEeFecEae577FC907708BFD', which owns 'vikashbajaj.eth'
```

### How can it be fixed?

Could anyone assist me in passing in the signed transaction correctly into this method?  Or do I *need* a local node to make this work?

**Comment by pipermerriam** [comment]
### Most user friendly way to do this.

You'll need the middleware from #649 .  With that you can load the private key for the account you're trying to sign into that middleware and it will intercept the `sendTransaction` call, sign it, and send it as a raw transaction.

### Less UX friendly way: option A

Use infura for *read* operations.  Build the transaction object using `contract.functions.theFunction(param, param2).buildTransaction({"from": ...})` to create an unsigned transaction dictionary.

Then using `w3.eth.account` API load your private key in and use the transaction signing API on the account object.  The signed transaction will have a `rawTransaction` attribute that you can then send over `w3.eth.sendRawTransaction`

### Less UX friendly option B

Use a local node with the appropriate private key unlocked, call code like *normal*.

**Comment by pipermerriam** [comment]
Also cc @carver since he's actually the original author of the ENS apis and may has something to say on the subject.

**Comment by carver** [comment]
I agree, the best way to do this is with the signing middleware (since there are a series of transactions that need to be signed).

There will probably need to be some changes to #649 support that, actually. I think the best way will be to add an intercept to the signing middleware that inserts the private key addresses into the response for `eth_accounts`.

**Comment by voith** [comment]
I see what the problem is:
https://github.com/ethereum/web3.py/blob/0890875a83ec3578a68844ea28fc638af8182939/ens/main.py#L252-L258

There's a forced check to allow only accounts in `web3.eth.accounts`(local accounts in your node).

@owocki A quick dirty solution for now is to monkey patch `_claim_ownership`.
In your code `ns._claim_ownership = lambda *_: True`

**Comment by carver** [comment]
That monkeypatch will help only after using the signing middleware. The ENS setup code is all built assuming that your node can sign transactions. There isn't a quick workaround, because several different transactions may need to be issued. So the method can't, say, return a single unsigned transaction for local signing. (the equivalent of `buildTransaction()`)

**Comment by voith** [comment]
> That monkeypatch will help only after using the signing middleware.

Oh yeah, intended to mean the same, Should have been more explicit!

@owocki Also to plug the middleware:
```python
w3.middleware_stack.add(construct_sign_and_send_raw_middleware('ENS_OWNER_PRIVATE_KEY'))
```
May be this is obvious, but want  to make sure that  you're not missing out any info.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/web3.py/issues/853

**Comment by owocki** [comment]
thanks for your help yall,

I just got the middlware and monkey patch stitched together over at https://github.com/gitcoinco/web/pull/509/files#diff-f569e34d4c10568aa2b7e1d6138e60a6R69

but i am getting a random 405 response from  https://mainnet.infura.io/ when i try to run it.

```
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 103
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 103
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 103
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 43
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 44
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mainnet.infura.io:443 "POST / HTTP/1.1" 405 0
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://mainnet.infura.io/
```

trying to figure out why i'm getting that response now.. if anyone has any bright ideas i'd love to hear them!

**Comment by owocki** [comment]
hmmm... itd be useful to know what infura method is returning the 405 response.. that way I could confirm if there is a workaround available.

**Comment by pipermerriam** [comment]
@owocki almost definitely `eth_sendTransaction`

**Comment by pipermerriam** [comment]
link: https://github.com/ethereum/web3.py/issues/854 to make debugging this type of thing easier.

**Comment by voith** [comment]
@owocki I just  tested `sendRawTransaction` using infura on rinkeby net.  It worked fine.

**Comment by owocki** [comment]
hmm.. i wonder if theres a way to transpose the `ns.setup_owner` call to be a raw transaction.  let me see if i can figure this out

**Comment by voith** [comment]
@owocki The middleware does the `sendRawTransaction` part for you. You don't need to explicitly use `sendRawTransaction`.
The middleware checks if there's any outgoing `eth_sendTransaction` and then tries to sign it with the private key provided and then emits a `eth_sendRawTransaction`

**Comment by owocki** [comment]
ah okay.. so we are likely receiving the 405 _before_ the raw transaction is emitted.  let me `ipdb` through the code to try to figure out where

**Comment by owocki** [comment]
ok.. syncing a local node now. :fingers_crossed:

**Comment by owocki** [comment]
got it working by making my own raw tx and signing it locally... thanks yall
