### ISSUE TITLE
AttributeError: module 'web3.eth' has no attribute 'getBlock'

### ISSUE THREAD

**Issue by tommy2049** [ethereum/web3.py#855]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: Ubuntu 16.04

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by voith** [comment]
@tommy2049 Did you create a web3 instance? Try the following bellow:
```python
from web3 import Web3
# choose a Provider of your choice
w3 = Web3(Web3.IPCProvider())
w3.eth.getBlock('latest')
```

**Comment by carver** [comment]
@tommy2049 help us help you. Please fill out the template in the issue.

**Comment by pipermerriam** [comment]
will re-open if @tommy2049 returns.
