### ISSUE TITLE
Web3.soliditySha3(['bool'], True) does not work

### ISSUE THREAD

**Issue by yoonghm** [ethereum/web3.py#878]
* Version: 4.2.1
* Python: 3.6.5
* OS: win

### What was wrong?

Web3.soliditySha3(['bool'], True)

Please include any of the following that are applicable:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-17e63ddc222d> in <module>()
----> 1 Web3.soliditySha3(['bool'], True)

C:\util\Anaconda3\lib\site-packages\web3\utils\decorators.py in _wrapper(*args, **kwargs)
     14                 return self.method(obj, *args, **kwargs)
     15             else:
---> 16                 return self.method(objtype, *args, **kwargs)
     17         return _wrapper
     18 

```
C:\util\Anaconda3\lib\site-packages\web3\main.py in soliditySha3(cls, abi_types, values)
    169         #         )
    170         # elif len(abi_types) != len(values):
--> 171         if len(abi_types) != len(values):
    172             raise ValueError(
    173                 "Length mismatch between provided abi types and values.  Got "

TypeError: object of type 'bool' has no len()
```

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by carver** [comment]
I think this is actually a bug in [the docs](http://web3py.readthedocs.io/en/stable/overview.html#Web3.soliditySha3) and should be this instead:

```py
>>> Web3.soliditySha3(['bool'], [True])
HexBytes("0x5fe7f977e71dba2ea1a68e21057beebb9be2ac30c6410aa38d4f3fbe41dcffd2")
```

---

Leaving the issue open until the docs are fixed.
