### ISSUE TITLE
ImportError: cannot import name 'KeepAliveRPCProvider'

### ISSUE THREAD

**Issue by lyhistory** [ethereum/web3.py#879]
* Version: 4.2.1
* Python: 3.5
* OS: ubuntu16.04

### What was wrong?

Traceback (most recent call last):
  File "maian.py", line 24, in <module>
    from web3 import Web3, KeepAliveRPCProvider, IPCProvider
ImportError: cannot import name 'KeepAliveRPCProvider'

**Comment by lyhistory** [comment]
sorry, just found KeepAliveRPCProvider has been removed from 3.5.5

**Comment by carver** [comment]
No worries, thanks for cleaning up the issue!

If you're not sure of the best way to connect to your node, check out: http://web3py.readthedocs.io/en/stable/providers.html#choosing-provider

**Comment by 77aq** [comment]
I also met this problem, how did you handle it? And can you use MAIAN now?

**Comment by enderphan94** [comment]
@77aq same issue with me, I'm using MAIAN and it uses this module. Now it got removed.. hell we can do that? :D

**Comment by pipermerriam** [comment]
What is MAIAN?

**Comment by pipermerriam** [comment]
@enderphan94 and @77aq my guess is that you'll need to pin `web3` to a version in the `v4` range prior to when this was removed.

Try `pip install "web3>=4,<5"` and see if that fixes your problem

**Comment by carver** [comment]
lol, `KeepAliveRPCProvider` isn't even used in the module, just imported.

**Comment by enderphan94** [comment]
@pipermerriam  does not work :), no luck

**Comment by dee16pak** [comment]
https://github.com/cryptomental/maian-augur-ci/blob/master/Dockerfile
Try versions giver in Dockerfile. It worked for me except the gui-maian.py
