### ISSUE TITLE
Raise deprecation warning on w3.eth.getTransactionFromBlock

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#888]
### What was wrong?

The deprecated method is missing a warning.

The new getTransactionByBlock and getUncleByBlock also do not have any docs.

### How can it be fixed?

Use the `@deprecated_for` decorator, and add the new docs in `docs/web3.eth.rst`.

**Comment by ankitchiplunkar** [comment]
@carver I can take this up if you want.

**Comment by carver** [comment]
Sounds great, thanks @ankitchiplunkar

**Comment by nemaniarjun** [comment]
@carver I think this should be close :)

**Comment by carver** [comment]
Yes, thanks @nemaniarjun !
