### ISSUE TITLE
Gas price generation using time based method generating low gas prices

### ISSUE THREAD

**Issue by robertmagier** [ethereum/web3.py#894]
* Version: 4.3.0
* Python: 3.6.5
* OS: win
* Node: https://mainnet.infura.io/FiZkoo##Isk3ke######

### What was wrong?
I am using sendRawTransaction to send my transaction to main network using infura node. 
Function returns valid transaction hash, but this hash can't be found on etherscan. 
Few times I got an error message that transaction is under priced, but this is not always the case. 
In most cases it just looks like transaction was send without problems. No error is being returned.

To estimate gas price I am using this code:
```python
            web3.eth.setGasPriceStrategy(medium_gas_price_strategy)
            gasprice = web3.eth.generateGasPrice()

```
It always returns 1 gwei. This is below Infura gas price limit. 

I did a test and changed my code to use 4 gwei, 10 gwei and 20 gwei. In this case transaction was successfully send to blockchain, but then after using generateGasPrice my problem returned. 

Below is the code I use to call sendRawTransaction. 

```python
from web3 import Web3, HTTPProvider
from web3.contract import ConciseContract
from web3.auto import w3
from web3.middleware import geth_poa_middleware
from web3.gas_strategies.time_based import fast_gas_price_strategy, slow_gas_price_strategy,medium_gas_price_strategy


    file = open('contractdef.js',"r")
    abiData = json.loads(file.read())
    contract_address = we3.toChecksumAddress(app.config['ETHEREUM_CONTRACT'])
    contract_instance = we3.eth.contract(contract_address,abi=abiData)

    w3.eth.enable_unaudited_features()
    we3 = Web3(HTTPProvider(app.config['PROVIDER']))
    we3.eth.enable_unaudited_features()
    we3.middleware_stack.inject(geth_poa_middleware, layer=0)

    we3.eth.setGasPriceStrategy(medium_gas_price_strategy)
    gasprice = we3.eth.generateGasPrice()
    
    owner_address = app.config['PUBLIC_ADDRESS']
    claimed_address = app.config['CLAIMED_ADDRESS']

    amount = 10
    
    gas = contract_instance.functions.transfer(claimed_address,amount).estimateGas({'from':owner_address})
    nonce = we3.eth.getTransactionCount(we3.toChecksumAddress(owner_address),'pending')

    txn = contract_instance.functions.transfer(claim.claimed_address,amount).buildTransaction({
            'from':owner_address,
            'chainId':1,
            'gas':gas,
            'gasPrice':gasprice,
            'nonce': nonce
            })

    private_key = app.config['PRIVATE_KEY']
    signed_txn = we3.eth.account.signTransaction(txn,private_key=private_key)

    tx = we3.eth.sendRawTransaction(we3.toHex(signed_txn.rawTransaction))
    print ('Transaction Number:',we3.toHex(tx))

```

This gives me result as:

`
Transaction Number: 0x5fd2e7724d7581879db346ea5b9b8cd81a424f6fe3ee08e2287964a91d66f72b
`
But, I can't find this transaction on etherscan. Even if I wait one day. 

There are two problems:

1. generateGasPrice returns wrong estimiated gasPrice ( 1 gwei seems like impossible)
2. sendRawTransaction doesn't throw errror when transaction is underpriced. It happened few times, but usually there is nothing.  

I don't know if this Infura problem or web3.py. I don't get any error message from web3.py after calling sendRawTransaction so maybe the problem is here. I will ask Infura as well.

**Comment by dylanjw** [comment]
Having the gas price calculation come to 1 gwei does seem like a bug in the web3 estimated gas price.

The following code block in `_compute_probabilities` in `web3/gas_strategies/time_based.py` could have a better estimate for `number_of_blocks_accepting_price`.

```python
for idx in range(len(miner_data_by_price)):
        minimum_gas_price = miner_data_by_price[idx].minimum_gas_price
        num_blocks_accepting_price = sum(m.num_blocks for m in miner_data_by_price[idx:])
```

Summing all blocks with the minimum gas price or under is making the assumption that all transactions with that price have an equal chance of being accepted by that miner.  Maybe replacing the minimum gas price with a low percentile could improve the estimate.  Im opening a pull request.
