### ISSUE TITLE
rename geth_poa_middleware to something more generic

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#899]
### What was wrong?

It seems like many other chains have set higher length for `extraData`.  see #898

### How can it be fixed?

Should `geth_poa_middleware` be renamed to something like `long_extraData_middleware`?  Or could the extraData length be configurable?

**Comment by carver** [comment]
> Should geth_poa_middleware be renamed to something like long_extraData_middleware?

The geth poa middleware makes some assumptions about what the `extraData` is (naming it proof of authority).

Maybe something like:

```py
def construct_move_extraData(rename_to='nonStandardExtraData'):
    ...

move_extraData_middleware = construct_move_extraData()
```

```py
geth_poa_middleware = construct_move_extraData(rename_to='proofOfAuthorityData')
```

> Or could the extraData length be configurable?

The middleware approach seems fine.

**Comment by fselmo** [comment]
This rename could be considered for `v7` #2854
