### ISSUE TITLE
Eth.waitForTransactionReceipt throws Timeout exception instead of returning None

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#903]
* Version: 4.3.0
* Python: 3.6
* OS: linux

### What was wrong?

If timeout is reached calling `web3.eth.waitForTransactionReceipt` a Timeout exception is thrown instead of returning None, as stated in the docs: http://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.waitForTransactionReceipt

### How can it be fixed?

Return None if timeout is reached or change the docs

**Comment by pipermerriam** [comment]
Docs should be updated to indicate that a timeout exception is thrown.

**Comment by Uxio0** [comment]
I will prepare a PR

**Comment by carver** [comment]
Thanks @Uxio0 !
