### ISSUE TITLE
Vyper sample Example Open Auction, One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, uint256

### ISSUE THREAD

**Issue by PaulSka** [ethereum/web3.py#906]
* Version: 4.3.0
* Python: 3.6.2
* OS: linux

### What was wrong?

I try to run example https://vyper.readthedocs.io/en/latest/vyper-by-example.html#simple-open-auction

When i pass arguments to constructor, an error occur :
```
OAuction.constructor(_beneficiary=web3.eth.accounts[0], bidding_time=datetime.timedelta(minutes=10)).transact()
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, uint256
```
How to convert with web3py address to Vyper Address uint256 ?

**Comment by voith** [comment]
@PaulSka `datetime.timedelta(minutes=10)` will return a `timedelta` object.  From the exception message I can see that the function expects `uint256`. If `bidding_time` expects time in seconds then you could probably do `datetime.timedelta(minutes=10).seconds` (which returns an integer).

**Comment by PaulSka** [comment]
@voith Thanks but i think it's different

With a sample contract like this
```
sender: public(address)
current: public(address)
message: bytes[20]

@public
def __init__(_sender: address, _message: bytes[20]):
    self.current = _sender
    self.message = _message
    
@public
def showAddress() -> address:
    return self.current
    
@public
def showMessage() -> bytes[20]:
    return self.message
```
It's return the same error
```
OAddress.constructor(_sender=web3.eth.accounts[1], _message="a").transact()
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, bytes
```

If __init__ take only 1 parameters, it's fine
```
sender: public(address)
current: public(address)

@public
def __init__(_sender: address):
    self.current = _sender
    
@public
def showAddress() -> address:
    return self.current
```

```
OAddress.constructor(_sender=web3.eth.accounts[1]).transact()
OK !
```

**Comment by PaulSka** [comment]
I try your version @voith, it's work

I don't understand :/

**Comment by PaulSka** [comment]
It's OK :(
Passing str when i declare bytes, no chance 
Thanks you @voith
