### ISSUE TITLE
web3 4.3.0 has requirement websockets<5.0.0,>=4.0.1, but you'll have websockets 5.0.1 which is incompatible.

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/web3.py#908]
is there any good way to avoid this version conflict ?

https://github.com/energywebfoundation/bond/issues/6#issuecomment-398098093

at the moment, when not giving any versions, that [list of dependencies](https://gist.github.com/drandreaskrueger/6a6259f9d0856535f1ed1f1585c2bc33) can just not be installed. 

Problematic are `resin-sdk 4.7.0` and `web3 4.3.0`.

Thanks.

* Version: 4.3.0
* Python: 3.5
* OS: linux

**Comment by pipermerriam** [comment]
Our standard practice is to pin within major versions.  However, we can open up testing to v5 of websockets and see if everything still works as expected.

**Comment by drandreaskrueger** [comment]
thx a lot!

**Comment by voith** [comment]
@pipermerriam `websockets` v5 has some breaking changes which were causing  tests to fail. Which is why I pinned the websockets version in #860. But I did not dig in to find the changes that were causing the failures.

**Comment by pipermerriam** [comment]
Good to know.   Going to open a separate issue for this.

**Comment by pipermerriam** [comment]
@drandreaskrueger closing as this doesn't appear to be a bug.   You can pin your websockets dependency to `<5`

**Comment by voith** [comment]
@drandreaskrueger have a look at #912
