### ISSUE TITLE
AutoProvider does not support https url in WEB3_PROVIDER_URI environment variable

### ISSUE THREAD

**Issue by bartleyg** [ethereum/web3.py#918]
* Version: 4.3.0
* Python: 3.6
* OS: osx

### What was wrong?

Specifying a https provider in the WEB3_PROVIDER_URI environment variable fails with a NotImplementedError exception.

```$ WEB3_PROVIDER_URI='https://mainnet.infura.io' python3 -c 'from web3.auto import w3; print(w3.isConnected())'```

Results:

```NotImplementedError: Web3 does not know how to connect to scheme 'https' in 'https://mainnet.infura.io'```

Expected:

```True```

### How can it be fixed?

in web3/providers/auto.py:
in def load_provider_from_environment():
change:
```python
elif uri.scheme == 'http':
```
to
```python
elif uri.scheme == 'http' or uri.scheme == 'https':
```

**Comment by carver** [comment]
Will go out with the next release. (probably in the next 24 hrs or so)
