### ISSUE TITLE
'code': -32602, 'message': 'invalid argument 1: json: cannot unmarshal number into Go value of type string'

### ISSUE THREAD

**Issue by TaikerLiang** [ethereum/web3.py#920]
* Version: 4.3.0
* Python: 3.5.2
* OS: ubuntu 16.04
* Node: Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.9.4 

### What was wrong?

Please include any of the following that are applicable:

> mycode
```
web3.personal.unlockAccount(web3.eth.accounts[3], 20)
res = web3.eth.sendTransaction({'to': web3.eth.accounts[4], 'from': web3.eth.accounts[3], 'value': 1000})
print(res)
```

> output

```
ValueError: {'message': 'invalid argument 1: json: cannot unmarshal number into Go value of type string', 'code': -32602}
```

anything wrong in my code?

**Comment by voith** [comment]
> web3.personal.unlockAccount(web3.eth.accounts[3], 20)

is 20 your account password? and shouldn't it be a string?
