### ISSUE TITLE
web3.py middleware.http_retry_request_middleware()

### ISSUE THREAD

**Issue by TimRi91** [ethereum/web3.py#922]
*web.py 
* Python: 3.6
* OS: win

I want to send multiple txs and want to make sure if a tx could not be send due to http-errors, my script will try it again with the command:
`web3.middleware.http_retry_request_middleware(web3.eth.sendTransaction({ .... }))`

But i get this error:
`TypeError: http_retry_request_middleware() missing 1 required positional argument: 'web3'`

Please help what do i miss here?
How can it be fixed?
Thank you!

**Comment by voith** [comment]
@TimRi91 That is not the right way to use a middleware. Middlewares are designed to be plugged into a `w3` instance:
```python
w3.middleware_stack.add(http_retry_request_middleware)
```
