### ISSUE TITLE
Home Directory Path Shortcut doesn't work in Linux

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/web3.py#925]
* Version: 4.4.0
* Python: 3.6.5 **(P.S. this field is old!)**
* OS: linux

### What was wrong?
In linux, the home directory path shortcut `~` doesn't work

```python
w3 = Web3(Web3.IPCProvider("/home/bryant/.ethereum/testnet/geth.ipc")); w3.isConnected()
True

w3 = Web3(Web3.IPCProvider("~/.ethereum/testnet/geth.ipc")); w3.isConnected()
False
```
### How can it be fixed?
![IDK](https://secure.i.telegraph.co.uk/multimedia/archive/03246/shrug_3246314b.jpg)

**Comment by pipermerriam** [comment]
I think we recently merged https://github.com/ethereum/web3.py/pull/921 which allows for `pathlib.Path` objects.  I think what we need to do now, is invert that and do the following.

```python
if isinstance(ipc_path, str):
    ipc_path = pathlib.Path(ipc_path)
elif not isinstance(ipc_path, pathlib.Path):
    raise TypeError("helpful error message about what types are accepted")

ipc_path_str = ipc_path.expanduser().resolve()
```

This should handle conversion to an absolute path as well as handling `~`.
