### ISSUE TITLE
Parity (sometimes) returns transaction receipts before they are mined

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#936]
* Version: 4.4.0

Tested on:
* Python: 3.6
* OS: linux

### What was wrong?

Confirmed once for a locally broadcasted transaction: parity will return the "receipt" of a pending transaction:

```py
In [95]: w3.eth.getTransactionReceipt('...')
Out[95]: 
AttributeDict({'blockHash': None,
 'blockNumber': None,
...
)
```

This goes against the [json-rpc spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt):

>  the receipt is not available for pending transactions

### How can it be fixed?

Option 1:

- Add a new parity_compliance middleware
- In middleware, detect if `blockHash` or `blockNumber` are `None`, and if so, return `None` instead of the receipt

Option 2:

- Check for missing hash or number in `web3.eth.Eth.getTransactionReceipt` and return `None` instead

Upside of 2: easier to add a parity module version of getTransactionReceipt that keeps parity's non-standard behavior.
Downside of 2: any other attempts to use `eth_getTransactionReceipt` directly in internal code might forget to check if block hash or number is None.

**Comment by veox** [comment]
According to [this old issue report in `paritytech/parity`](https://github.com/paritytech/parity/issues/3569), Parity returning receipts for pending transactions is (was?..) intentional.

You write "confirmed once" - what were the other outcomes?

* `w3.eth.getTransactionReceipt('...')` returning `None` (i.e. as [the wiki doc](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) says;
* or the transaction having been mined, and so the receipt having a `blockHash` and `blockNumber`?

If the former, then Parity's behaviour is inconsistent, and it's worth reporting upstream.

**Comment by carver** [comment]
> You write "confirmed once" - what were the other outcomes?

The rpc result was `null`, so the python result was `None`. Even for a locally broadcasted transaction, this happened for a little while, but after a couple retries on the same hash, I eventually got the `blockHash=None` receipt.

> If the former, then Parity's behaviour is inconsistent, and it's worth reporting upstream.

It seems that the practice of returning a receipt with `blockHash=None` is necessarily inconsistent, since you might or might not have the transaction in your local transaction pool. If you don't then returning even a "partial receipt" is impossible.

Given Gavin's quote on that parity issue, it seems unlikely that parity is interested in moving toward the wiki-defined behavior:

> as a side note: historically, cpp-ethereum implemented this RPC like parity (and that predated the docs you quote). this is because it gives more information to the user, since you are able to see ahead of time which logs and gas usage the transaction had. geth apparently did it differently. geth's simpler behaviour made its way into the ethereum-foundation-hosted docs that you quote for no good reason.

To be fair, the RPC methods haven't actually gone through any EIP process. So despite being a bit cranky, he's right that it is a bit weak to lean on the wiki as "the standard". Yet another reason to formally define the json-rpc methods in an EIP.

**Comment by fselmo** [comment]
closing as stale / parity deprecated
