### ISSUE TITLE
Fail to install web3 4.4.0 using pip

### ISSUE THREAD

**Issue by smlee729** [ethereum/web3.py#940]
* Version: 4.4.0
* Python: 3.6.6
* OS: osx

### What was wrong?
>> pip install web3

Processing /Users/sjlee/Downloads/web3.py-4.4.0
Collecting eth-abi<2,>=1.1.1 (from web3==4.4.0)
  Using cached https://files.pythonhosted.org/packages/a2/2b/8529812e103639a6084c9d5d62862052989cf3877a76253509fc6f19eab6/eth_abi-1.1.1-py3-none-any.whl
Collecting eth-account<0.3.0,>=0.2.1 (from web3==4.4.0)
  Using cached https://files.pythonhosted.org/packages/1c/f4/752b666464002dbd30d30443426cd25c045f941ae5f5e7b08eda1aee3c68/eth_account-0.2.3-py3-none-any.whl
Collecting eth-pm==0.1.0-alpha.17 (from web3==4.4.0)
  Could not find a version that satisfies the requirement eth-pm==0.1.0-alpha.17 (from web3==4.4.0) (from versions: )
No matching distribution found for eth-pm==0.1.0-alpha.17 (from web3==4.4.0)

### I found that I can install v4.3.0 since there's no dependency on eth-pm there.

**Comment by veox** [comment]
Please try with 4.4.1.

**Comment by smlee729** [comment]
Thank you! 👍
