### ISSUE TITLE
Return values for eth_call are truncated when using revert

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#941]
* Version: 4.4.0
* Python: 3.6
* OS: linux

### What was wrong?

When calling a contract with `eth_call` to a function that has a `revert(string(abi.encodePacked("Hello")));` I would expect a return value like this:

```
0x08c379a0                                                         // Function selector for Error(string)
0000000000000000000000000000000000000000000000000000000000000020 // Data offset
000000000000000000000000000000000000000000000000000000000000001a // String length
4e6f7420656e6f7567682045746865722070726f76696465642e000000000000 // String data
```
As stated in the solidity documentation: http://solidity.readthedocs.io/en/v0.4.24/control-structures.html

Instead, I get the return value truncated:

`0x8c379a000000000000000000000000000000000000000000000000000000000`

If I see the RPC Call that web3 does in Wireshark I see this as the result: 

`0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000001df7`

### How can it be fixed?

Don't truncate the return value

### UPDATE

I can just reproduce the issue calling `mycontract.functions.myfunction().call()`. If I use `eth.call` I get the non truncated output (as it should be)

**Comment by dylanjw** [comment]
The contract function call() method has no handling for error reasons strings.  It fails to detect the errored return value, and attempts to parse the return value according the the function abi.  We need to add a way to detect the error return string, and then parse it according the reason string format.

**Comment by carver** [comment]
>  We need to add a way to detect the error return string, and then parse it according the reason string format.

Also, probably add a new exception type to raise. I'm not sure how standard this is (or might become) across languages, so maybe a `SolidityError`.

**Comment by dylanjw** [comment]
It looks like py-evm/eth-tester will also need to add support for the error return string spec.

**Comment by karlb** [comment]
I'm interested in writing a PR for this. Is there already a test case including a revert that can be used?

**Comment by kclowes** [comment]
@karlb That would be great! I don't think we have any test cases already. Feel free to ping me if you need anything!
