### ISSUE TITLE
Timeout exceeded for HTTPProvider

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#947]
* Version: 4.4.0
* Python: 3.6
* OS: linux

### What was wrong?
Timeout exceeded when using `eth.getLogs` with HTTPProvider. I guess it can be reproduced too with any query to the Ethereum node that last longer than 10 seconds.

Problem is in `kwargs.setdefault('timeout', 10)` for the HTTPProvider

```python
def make_post_request(endpoint_uri, data, *args, **kwargs):
    kwargs.setdefault('timeout', 10)
    session = _get_session(endpoint_uri)
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
    response.raise_for_status()

    return response.content
```

### How can it be fixed?

Make the parameter configurable or accept a kwargs param in eth calls to send a custom timeout

**Comment by voith** [comment]
@Uxio0 `HTTPProvider` already takes `request_kwargs` as a parameter. Try the following:
```python
w3 = Web3(Web3.HTTPProvider(endpoint_uri='http://localhost:8545', request_kwargs={'timeout': 100}))
```

**Comment by Uxio0** [comment]
Nice! Sorry, I haven't seen that in the documentation. Thank you, that fixes my issue
