### ISSUE TITLE
Missing shh.subscribe function on Whisper protocol

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#950]
Whisper Protocol in original has a subscribe function, please see the [Whisper-v5-RPC-API](https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API#shh_subscribe).

> **shh_subscribe**
> 
> Creates and registers a new subscription to receive notifications for inbound whisper messages. Returns the ID of the newly created subscription.

But Web3.py seems like does not have `shh.subscribe` function on its [documentation and implementation](http://web3py.readthedocs.io/en/stable/web3.shh.html#module-web3.shh).

**=>** Would it be implemented? or is it not implemented in purpose?

**Comment by carver** [comment]
Only whisper v6 is supported, since https://github.com/ethereum/web3.py/pull/784
