### ISSUE TITLE
Display errors from server, even if not json-formatted

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#952]
### What was wrong?

In cases like #145 the error messages sent back from the server are not displayed (specifically, when the error message is not formatted as json). Instead, the provider raises a `TimeoutError`, ignoring any "partial" response received from the server.

That response might be something very helpful, like `"Provided Host header is not whitelisted.\n"`. Without that info, the user is blind to the problem that the node is complaining about.

### How can it be fixed?

- [ ] create sub-issues for IPC, WS, and HTTP providers
- [ ] resolve in IPC, either by adding a method to `Timeout` like `set_message_to_raise_on_timeout()` and add the partial response there, or by catching and re-raising the error with the partial response
- [ ] resolve in HTTP, maybe by changing `requests` to use a streaming response
- [ ] resolve in WS

**Comment by fselmo** [comment]
Opt for creating sub issues for each provider, as reported.
