### ISSUE TITLE
Connection to ropsten websocket over infura hang.

### ISSUE THREAD

**Issue by FYJen** [ethereum/web3.py#956]
* Version: 4.4.1
* Python: 3.6
* OS: osx

### What was wrong?

I wasn't able to connect to infura's ropsten websocket. The process hung when I wanted to create the filter object on pending transactions. It worked for both rinkeby's and mainnet's but just not for ropsten network.

I was wondering if anyone is having the same issue. Given that I was able to connect to two other networks it makes it less suspicious that the problem is caused by the web3.py

Below is how I instantiate the filter by following https://web3py.readthedocs.io/en/stable/filters.html#web3.utils.filters.TransactionFilter
```python
In [23]: web3 = Web3(Web3.WebsocketProvider('wss://rinkeby.infura.io/_ws'))

In [24]: new_transaction_filter = web3.eth.filter('pending')

In [25]: new_transaction_filter.get_new_entries()
Out[25]:
[HexBytes('0x4945f39cbeedd911eae93577c75d763d364c37ae01dcb7fb31ff9421a2a92b71'),
 HexBytes('0xae0b88b85163d3f0a918236cbf3ec93ccb589c6ad327e937f69b9591680fbf61'),
```

Process hung on line 27 for a long time. I interrupted. The stacktrace is below.
```python
In [26]: web3 = Web3(Web3.WebsocketProvider('wss://ropsten.infura.io/ws'))

In [27]: new_transaction_filter = web3.eth.filter('pending')

^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-60afc0d44840> in <module>()
----> 1 new_transaction_filter = web3.eth.filter('pending')

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/eth.py in filter(self, filter_params, filter_id)
    319             elif filter_params == "pending":
    320                 filter_id = self.web3.manager.request_blocking(
--> 321                     "eth_newPendingTransactionFilter", [],
    322                 )
    323                 return TransactionFilter(self.web3, filter_id)

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/manager.py in request_blocking(self, method, params)
    105         Make a synchronous request using the provider
    106         """
--> 107         response = self._make_request(method, params)
    108
    109         if "error" in response:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/manager.py in _make_request(self, method, params)
     88             self.logger.debug("Making request. Method: %s", method)
     89             try:
---> 90                 return request_func(method, params)
     91             except CannotHandleRequest:
     92                 continue

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py in middleware(method, params)
     16                     transaction = assoc(transaction, 'gasPrice', generated_gas_price)
     17                     return make_request(method, [transaction])
---> 18         return make_request(method, params)
     19     return middleware

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/cytoolz/functoolz.pyx in cytoolz.functoolz.curry.__call__()

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/formatting.py in apply_formatters(method, params, make_request, request_formatters, result_formatters, error_formatters)
     48         response = make_request(method, formatted_params)
     49     else:
---> 50         response = make_request(method, params)
     51
     52     if 'result' in response and method in result_formatters:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/attrdict.py in middleware(method, params)
     16     """
     17     def middleware(method, params):
---> 18         response = make_request(method, params)
     19
     20         if 'result' in response:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/cytoolz/functoolz.pyx in cytoolz.functoolz.curry.__call__()

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/formatting.py in apply_formatters(method, params, make_request, request_formatters, result_formatters, error_formatters)
     48         response = make_request(method, formatted_params)
     49     else:
---> 50         response = make_request(method, params)
     51
     52     if 'result' in response and method in result_formatters:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/normalize_errors.py in middleware(method, params)
      7 def normalize_errors_middleware(make_request, web3):
      8     def middleware(method, params):
----> 9         result = make_request(method, params)
     10
     11         # As of v1.8, Geth returns errors when you request a

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/cytoolz/functoolz.pyx in cytoolz.functoolz.curry.__call__()

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/formatting.py in apply_formatters(method, params, make_request, request_formatters, result_formatters, error_formatters)
     48         response = make_request(method, formatted_params)
     49     else:
---> 50         response = make_request(method, params)
     51
     52     if 'result' in response and method in result_formatters:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/cytoolz/functoolz.pyx in cytoolz.functoolz.curry.__call__()

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/middleware/formatting.py in apply_formatters(method, params, make_request, request_formatters, result_formatters, error_formatters)
     48         response = make_request(method, formatted_params)
     49     else:
---> 50         response = make_request(method, params)
     51
     52     if 'result' in response and method in result_formatters:

~/pg/some_name/virtualenv_run/lib/python3.6/site-packages/web3/providers/websocket.py in make_request(self, method, params)
    102             WebsocketProvider._loop
    103         )
--> 104         return future.result()

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    425                 return self.__get_result()
    426
--> 427             self._condition.wait(timeout)
    428
    429             if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py in wait(self, timeout)
    293         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    294             if timeout is None:
--> 295                 waiter.acquire()
    296                 gotit = True
    297             else:

KeyboardInterrupt:
```

I have tried both `wss://ropsten.infura.io/ws` and `wss://ropsten.infura.io/_ws`. I have also posted the same question on Infura forum (https://github.com/INFURA/infura/issues/110). Trying to get help on both sides.

### How can it be fixed?

TBD.

**Comment by FYJen** [comment]
@carver: Thanks for the reply here. Interesting, both rinkeby and mainnet filters work for me through infura. If I really need to get the pending transaction filter, is hosting my own local node the only way to go? Or is there any other providers like Infura that I could go for?

**Comment by carver** [comment]
>  If I really need to get the pending transaction filter, is hosting my own local node the only way to go? Or is there any other providers like Infura that I could go for?

Running your local node is the only solution I'm familiar with for getting pending transactions.

**Comment by voith** [comment]
@FYJen Thanks for the report!
I think we probably need to add some default timeout here. IIRC, Websockets waits infinitely if `timeout` is None.
I'll take care of this. But maybe in another 2-3 days(little busy these days).

**Comment by voith** [comment]
Turns out that the `timeout` parameter of `websockets` does not work as expected!
citing from the documentation:
> The timeout parameter defines the maximum wait time in seconds for completing the closing handshake and, only on the client side, for terminating the TCP connection. close() will complete in at most 4 * timeout on the server side and 5 * timeout on the client side.

`websockets` does not provide any other mechanism to timeout connections.

The author suggests using `with asyncio.wait_for(connect(...), your_timeout)`. You can read it [here](https://github.com/aaugustin/websockets/issues/428#issuecomment-397858402).

@carver any thoughts. Can we use the `CancelToken` library here? I haven't dug in but I'm assuming that  canceltoken is some general purpose solution to be used for such cases.

**Comment by carver** [comment]
A cancel token is more useful when there are several services running that all need to cancel simultaneously. The wait_for solution seems fine.

**Comment by pipermerriam** [comment]
`asyncio.wait_for` is probably the better solution for now if there's only a small number of call sites that need timeouts.  The `CancelToken` pattern is more about cascading cancellations for a complex application so that you can trigger cancellation in one spot and all child *things* also get canceled.

**Comment by voith** [comment]
@carver @pipermerriam Thank you for the explanation!

**Comment by voith** [comment]
This is a bug in web3 and has been noted in https://github.com/ethereum/web3.py/issues/1009#issuecomment-414537934. The connection timeout error needs to be fixed too.

**Comment by FYJen** [comment]
@carver: From the [documentation](https://infura.io/docs/wss/eth_newPendingTransactionFilter), Infura's WebSocket API officially supports `eth_newPendingTransactionFilter` JSON RPC.

**Comment by voith** [comment]
@FYJen AFAIK, filters weren't supported by infura for some time. They must have been added recently.
Anyway, this is a bug and should be fixed. 
I'm sorry, I don't get enough free time to code these days. I haven't forgotten about the issue and I'll return to it as soon as I can.
