### ISSUE TITLE
Error: new BigNumber() not a base number

### ISSUE THREAD

**Issue by zhengzetao** [ethereum/web3.py#957]
* Version: geth1.8.1,geth1.8.2
* OS: ubuntu

### What was wrong?
I have built a private chain with two node on two computer. The smart contract was successfully deployed on node1,and i can call the method on node1 ,but when i call the same method on node2,it occur the error new BigNumber not a base 16 number .The two nodes have the same block number.and they return false when execute the command eth.syncing. 

I think the node2 aren't synched but it's strange that they have the same block number.

**Comment by pipermerriam** [comment]
I believe you are on the wrong codebase.
