### ISSUE TITLE
HTTPRequestRetry middleware should accept a parameter for allowing retry on certain methods

### ISSUE THREAD

**Issue by nandubatchu** [ethereum/web3.py#958]
* Version: 4.3.0
* Python: 3.6.5
* OS: osx

This default middleware is not part of the middleware_stack to remove or add during runtime easily. Please provide a mechanism to perform this during runtime and also some mechanism to exclude certain methods from retrying.

**Comment by voith** [comment]
There’s already a list that allows certain methods: https://github.com/ethereum/web3.py/blob/84910278f2ed3ac36f7a9e063f9f0cdb827fb64a/web3/middleware/exception_retry_request.py#L8-L58
Probably, the middleware needs an `exclude_methods` param which avoids retries if a method is present in that list. Let's hear @carver's thoughts on this!
