### ISSUE TITLE
Requests rlp version error

### ISSUE THREAD

**Issue by XiaobaoZhu** [ethereum/web3.py#959]
* Version: x.x.x
* Python: 3.6.1
* OS: os10.13.3

Failed to install web3
In terminal I input:
sudo pip install --ignore-installed  web3
but it always have error as following:
.....
Downloading https://files.pythonhosted.org/packages/b4/dc/a54b93cac06f46ef49b8da6cb06a6bf77ba65bf45dec5c498f51ceefc5c6/rlp-1.0.1-py2.py3-none-any.whl
### **ethjsonrpc 0.3.0 has requirement requests==2.9.1, but you'll have requests 2.19.1 which is incompatible.
**ethereum 1.0.8 has requirement rlp==0.4.4, but you'll have rlp 1.0.1 which is incompatible.****
Installing collected packages: toolz, cytoolz, pycryptodome, eth-hash, eth-utils, six, attrdict, eth-keys, eth-keyfile, hexbytes, rlp, eth-rlp, eth-account, parsimonious, eth-abi, websockets, lru-dict, urllib3, certifi, idna, chardet, requests, web3
Successfully installed attrdict-2.0.0 certifi-2018.4.16 chardet-3.0.4 cytoolz-0.9.0.1 eth-abi-1.1.1 eth-account-0.2.3 eth-hash-0.1.4 eth-keyfile-0.5.1 eth-keys-0.2.0b3 eth-rlp-0.1.2 eth-utils-1.0.3 hexbytes-0.1.0 idna-2.7 lru-dict-1.1.6 parsimonious-0.8.0 pycryptodome-3.6.4 requests-2.19.1 rlp-1.0.1 six-1.11.0 toolz-0.9.0 urllib3-1.23 web3-4.4.1 websockets-5.0.1
### What was wrong?

Can you help me to install web3?
I tried to change requests version from 2.19.1 to 2.9.1 but I failed. I also try to change the version of RLP . But both failed. What can I do next?

**Comment by carver** [comment]
We highly recommend installing inside a virtual environment, which we consider a best practice for all python packages. See http://web3py.readthedocs.io/en/stable/troubleshooting.html#setup-environment

I'm closing as this is unlikely to be a bug. If you are still experiencing problems installing into a fresh virtual environment, feel free to continue commenting to get help.
