### ISSUE TITLE
Doc improvements, esp for people transferring from pyethereum

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#960]
There is no helpful guide for switching from pyethereum to web3.py.

# An example

> "right now i'm digging through the source code of web3.py, because i can't figure out how to set the gas limit of a transction.  i don't see it in the documentation."
"estimateGas() goes out of gas.  i'm not trying to be annoying or anything, but i would already be way past this if i had just used pyethereum.tester"
...
okay we figured out
the problem was we were trying to pass arguments to .transact() and .constructor() as regular python arguments .transact(gas=3000000)
but it wanted them as dict/json objects  .transact({"gas":3100000})

### Improved Contract example
> so i guess the documentation here http://web3py.readthedocs.io/en/stable/contracts.html#contract-deployment-example could be improved by putting some arguments in this line:
```
# Submit the transaction that deploys the contract
tx_hash = Greeter.constructor().transact()
```

### Explicitly list pyethereum tools and how to use web3.py instead

From all the features in:
https://github.com/ethereum/pyethereum/wiki/Using-pyethereum.tester

### Allow usage of keyword args for transaction fields

*Consider* accepting keyword args like `contract.functions.approve(...).transact(gas=100000)`.

**Comment by marcgarreau** [comment]
A crypto-generation removed now 😅
