### ISSUE TITLE
ImportError: cannot import name geth_poa_middleware

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#963]
* web3.version.api says: 3.15.0
* Python: Python 3.5.2
* OS: linux

---------------------

I have followed @carver 's answer related to [Rinkeby failure with web3.py — Could not format value '0x…' as field 'extraData'](https://ethereum.stackexchange.com/a/44131/4575 ): 

Code:

```
from web3 import Web3, IPCProvider
# connect to the default geth --dev IPC location
w3 = Web3(IPCProvider('/home/user/POA/private/geth.ipc'))
from web3.middleware import geth_poa_middleware #<===Error occurs

# inject the poa compatibility middleware to the innermost layer
w3.middleware_stack.inject(geth_poa_middleware, layer=0)

# confirm that the connection succeeded
w3.version.node
```

-----------

Error I am having:

```
Traceback (most recent call last):
  File "coder.py", line 4, in <module>
    from web3.middleware import geth_poa_middleware
ImportError: cannot import name geth_poa_middleware
```

**[Q]** How could I fix this error (`cannot import name geth_poa_middleware`)?

**Comment by dylanjw** [comment]
Can you confirm your version by adding:
`w3.version.api`

**Comment by avatar-lavventura** [comment]
- `w3.version.node` says: `Geth/v1.8.0-unstable-e7610ead/linux-amd64/go1.8`
- `w3.version.api` says: `3.15.0`

**Comment by roigecode** [comment]
For anyone having this issue in version `^7.4.0` the import has changed.

From:
❌ `from web3.middleware import geth_poa_middleware`

To:
✅ `from web3.middleware import ExtraDataToPOAMiddleware`

And you still inject it the same way into the 0th layer of the middleware onion to guarantee it is the first middleware to process the response and modify the `extraData` field as this ensures it processes the field before any other middleware attempts to validate it:
`w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)`

**Comment by h0tgril** [comment]
Would've been nice to leave the old name in for compatibility
