### ISSUE TITLE
Error while trying to execute the quickstart on jupyter

### ISSUE THREAD

**Issue by AlexandreUser** [ethereum/web3.py#966]
Python 3.6.5
Error:
IndexError:Traceback (most recent call last)
<ipython-input-14-5fc48f121d0f> in <module>()
     41 
     42 # Get transaction hash from deployed contract
---> 43 tx_hash = contract.deploy(transaction={'from': w3.eth.accounts[0], 'gas': 410000})
     44 
     45 # Get tx receipt to get contract address

IndexError: list index out of range

**Comment by voith** [comment]
quite likely that `w3.eth.accounts` is an empty list. Have you created an account in your keystore?

**Comment by AlexandreUser** [comment]
thanks, i forgot that.
