### ISSUE TITLE
Can not web3.py work with flask_socketio?

### ISSUE THREAD

**Issue by xshrim** [ethereum/web3.py#972]
* Version: latest
* Python: 3.6
* OS: linux

here is my code:

```python
app = Flask(__name__)
app.debug = True
app.config['SECRET_KEY'] = 'secret'
socketio = SocketIO(app)

thread = None
thread_lock = Lock()

block_filter = w3.eth.filter('latest')

w3 = Web3(Web3.WebsocketProvider("ws://127.0.0.1:8546"))

def background_thread():
    while True:
        socketio.sleep(3)
        for event in block_filter.get_new_entries():  # will be blocked!
            evt = w3.toHex(event)
            socketio.emit('my response', {'data': str(evt)}, namespace='/test')
        # t = time.strftime('%M:%S', time.localtime())  # is ok
        # socketio.emit('my response', {'data': str(t)}, namespace='/test')

@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
    emit('my response', {'data': 'Connected'})

if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=5100)
```

When i call any method provided by web3.py in socketio.start_background_task, the whole program will be blocked.
I have tried to run block_filter in a separate thread to work with socketio:
```python
def handle_event(event):
    print(event)
def log_loop(event_filter, poll_interval):
    while True:
        for event in event_filter.get_new_entries():
            handle_event(event)
        time.sleep(poll_interval)
def main():
    worker = threading.Thread(target=log_loop, args=(block_filter, 1))
    worker.start()
if __name__ == '__main__':
    main()    
    socketio.run(app, host='0.0.0.0', port=5100)
```
but failed again and raise the error:
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7fc35490cf20 epoll pending=0 ref=0 fileno=11>)

It seems that web3.py do not support flask_socketio? Is there any method to solve this problem?

**Comment by carver** [comment]
I don't know anything about `flask_socketio`. It's possible the library does something that interferes with Web3.py's functionality, but can't say for sure. You are likely to get more help debugging your problem on a site like ethereum.stackexchange.com or stackoverflow.com .

Closing, since this is not likely a Web3.py issue. Feel free to continue the discussion here.
