### ISSUE TITLE
Crash in time based gas price strategies

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#979]
* Version: 4.5.0
* Python: 3.6
* OS: osx

### What was wrong?

My script to check the gas price calculation crashes after the update to web3 4.5:
```
python test_gas_price.py                                                                     0:13:21
RPC: 252000000
Traceback (most recent call last):
  File "test_gas_price.py", line 14, in <module>
    print('Slow', w3.eth.generateGasPrice())
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/web3/eth.py", line 385, in generateGasPrice
    return self.gasPriceStrategy(self.web3, transaction_params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/web3/gas_strategies/time_based.py", line 160, in time_based_gas_price_strategy
    sample_size=sample_size,
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/web3/gas_strategies/time_based.py", line 79, in _compute_probabilities
    reverse=True,
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/web3/gas_strategies/time_based.py", line 67, in _aggregate_miner_data
    percentile(gas_prices, percentile=15))
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/web3/utils/math.py", line 5, in percentile
    raise ValueError("Expected a sequence of at least 3 integers, got {0}".format(values))
ValueError: Expected a sequence of at least 3 integers, got {41000000000, 26000000000}
```

The code is the following:
```py
from web3.auto import w3

from web3 import middleware
from web3.gas_strategies.time_based import medium_gas_price_strategy, fast_gas_price_strategy, slow_gas_price_strategy
from web3.gas_strategies.rpc import rpc_gas_price_strategy

w3.middleware_stack.add(middleware.time_based_cache_middleware)
w3.middleware_stack.add(middleware.latest_block_based_cache_middleware)
w3.middleware_stack.add(middleware.simple_cache_middleware)

w3.eth.setGasPriceStrategy(rpc_gas_price_strategy)
print('RPC:', w3.eth.generateGasPrice())
w3.eth.setGasPriceStrategy(slow_gas_price_strategy)
print('Slow', w3.eth.generateGasPrice())
w3.eth.setGasPriceStrategy(medium_gas_price_strategy)
print('Medium:', w3.eth.generateGasPrice())
w3.eth.setGasPriceStrategy(fast_gas_price_strategy)
print('Fast:', w3.eth.generateGasPrice())
```

### How can it be fixed?

It should crash and return a proper gas price.

**Comment by dylanjw** [comment]
The timed_based gas strategies will throw this exception when a block has less than 3 transactions to use to make an estimate.  This could change to just return an average of the 2 transactions or the price of the single transaction, if only 1 or 2 transactions occurred.  But in that case, the estimate isn't going to be very useful.

@carver Do you think that the gas price strategy should be kept to throw an error in this case?  IMO, I would want to handle this case separately, when there is not enough data to make a good estimate.  If I understand correctly, either the block gas limit is being reached with a few transactions, or the network traffic is really low.  Both would be on the edges of the price bell curve, and should probably be dealt with intentionally.

**Comment by carver** [comment]
@palango I updated the web3 version in the issue from 3.5.0 -> 4.5.0, based on the context you provided.

> Do you think that the gas price strategy should be kept to throw an error in this case? 

Well, I suppose you might want to embed the gas strategy to your app, and then test your app against a private network that only has one transaction in a block. Sure, they could disable gas estimation during testing, but why make them.

>  IMO, I would want to handle this case separately, when there is not enough data to make a good estimate.

Yeah, but also it's only an estimate. We could still calculate something with one data point right? It will just be a really rough estimate. The cutoff at 3 seems sort of arbitrary. I'm in favor of giving an answer if we have any data.

**Comment by palango** [comment]
> I updated the web3 version in the issue from 3.5.0 -> 4.5.0, based on the context you provided.

Thanks!

> Sure, they could disable gas estimation during testing, but why make them.

I agree. I tested on ropsten and had lots of blocks with just one or two transactions. I think there should be a fallback, even `eth_gasPrice` would be enough.
