### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by loveagaiagai** [ethereum/web3.py#989]
* Version: 4.5.0
* Python: 3.6
* OS: windows7(64)

My code:

Print ("GO")
Import cytoolz.utils
Import cytoolz._signatures
From Web3 import Web3, HTTPProvider
Web3 = Web3 (HTTPProvider ('https://mainnet.infura.io'))
Count = web3.eth.getTransactionCount ('0x37D6047cA1d327bef7a6e11060d53fF3452AF8A7')
Print (count)

pip list
Package          Version
---------------- ---------
altgraph         0.16.1
attrdict         2.0.0
certifi          2018.4.16
cffi             1.11.5
chardet          3.0.4
cx-Freeze        5.1.1
cytoolz          0.9.0.1
Django           2.1
eth-abi          1.1.1
eth-account      0.3.0
eth-hash         0.1.4
eth-keyfile      0.5.1
eth-keys         0.2.0b3
eth-rlp          0.1.2
eth-utils        1.0.3
future           0.16.0
hexbytes         0.1.0
idna             2.7
lru-dict         1.1.6
macholib         1.10
numpy            1.15.0
parsimonious     0.8.0
pefile           2017.11.5
pip              18.0
py2exe           0.9.2.0
pycparser        2.18
pycryptodome     3.5.1
PyInstaller      3.3.1
pypiwin32        223
pysha3           1.0.2
pytz             2018.5
pywin32          223
requests         2.19.0
rlp              1.0.1
semantic-version 2.6.0
setuptools       39.0.1
six              1.11.0
toolz            0.9.0
urllib3          1.23
web3             4.5.0
websockets       5.0.1 

Already added to the hook-Crypto.py
No problem at runtime
Running wrong after packing with pyinstaller

File "site-packages\eth_hash\backends\auto.py", line 18, in keccak256
  File "site-packages\eth_hash\backends\auto.py", line 11, in _initialize
  File "site-packages\eth_hash\utils.py", line 15, in auto_choose_backend
  File "site-packages\eth_hash\utils.py", line 52, in choose_available_backend
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].

**Comment by carver** [comment]
Pardon? Please give more background if you'd like help.

FWIW, it looks like you should install `pycryptodome`

**Comment by HSC-GBT-DEV2** [comment]
I also faced the same error while running a executable made by pyinstaller:
OS: Ubuntu
python version installed:3.5.2

**Command line error**
root@hscuser-OptiPlex-3050:/home/hscuser/package# dist/wallet/wallet 
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_18-08-09_23.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
LaserWallet Starting
Checking to see if there is an already running glaze...
Glaze starting /usr/bin/glaze --datadir /root/.laser/testnet --testnet --nousb
Connecting to IPC socket /root/.laser/testnet/glaze.ipc
INFO [08-09|11:27:27.932] Maximum peer count                       PTH=25 LES=0 total=25
INFO [08-09|11:27:27.932] Starting peer-to-peer node               instance=glaze/v1.0.0-stable/linux-amd64/go1.10
INFO [08-09|11:27:27.932] Allocated cache and file handles         database=/root/.laser/testnet/glaze/chaindata cache=768 handles=512
INFO [08-09|11:27:28.083] Persisted trie from memory database      nodes=0 size=0.00B time=3.656µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-09|11:27:28.084] Initialised chain configuration          config="{ChainID: 12 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Blaze: 0 Engine: ethash}"
INFO [08-09|11:27:28.084] Disk storage enabled for ethash caches   dir=/root/.laser/testnet/glaze/ethash count=3
INFO [08-09|11:27:28.084] Disk storage enabled for ethash DAGs     dir=/root/.laserhash                  count=2
INFO [08-09|11:27:28.084] Initialising Laser protocol              versions="[63 62]" network=2
INFO [08-09|11:27:28.085] Loaded most recent local header          number=27223 hash=1da4fc…84d3bc td=24994466404
INFO [08-09|11:27:28.085] Loaded most recent local full block      number=27223 hash=1da4fc…84d3bc td=24994466404
INFO [08-09|11:27:28.085] Loaded most recent local fast block      number=27223 hash=1da4fc…84d3bc td=24994466404
INFO [08-09|11:27:28.085] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-09|11:27:28.085] Regenerated local transaction journal    transactions=0 accounts=0
WARN [08-09|11:27:28.086] Blockchain not empty, fast sync disabled 
INFO [08-09|11:27:28.086] Starting P2P networking 
INFO [08-09|11:27:30.320] UDP listener up                          self=enode://8eb9911c3149f2750152ac00cc1c7a5b3d7cb85a167eec86db3a49182b3f4ca99899ce988186f96508453eaa3bab5311a47c8293d65f42477dbc3853c7a00011@[::]:30503
INFO [08-09|11:27:30.320] RLPx listener up                         self=enode://8eb9911c3149f2750152ac00cc1c7a5b3d7cb85a167eec86db3a49182b3f4ca99899ce988186f96508453eaa3bab5311a47c8293d65f42477dbc3853c7a00011@[::]:30503
INFO [08-09|11:27:30.325] IPC endpoint opened                      url=/root/.laser/testnet/glaze.ipc
Connected to IPC socket
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "threading.py", line 914, in _bootstrap_inner
   File "src/nodeipc.py", line 100, in run
   File "src/nodeipc.py", line 417, in handle_request
   File "src/nodeipc.py", line 478, in handle_get_accounts
   File "web3/personal.py", line 24, in listAccounts
   File "web3/manager.py", line 107, in request_blocking
   File "web3/manager.py", line 90, in _make_request
   File "web3/middleware/gas_price_strategy.py", line 18, in middleware
   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
   File "web3/middleware/formatting.py", line 50, in apply_formatters
   File "web3/middleware/attrdict.py", line 18, in middleware
   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
   File "web3/middleware/formatting.py", line 57, in apply_formatters
   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
   File "eth_utils/functional.py", line 22, in inner
   File "web3/utils/formatters.py", line 79, in apply_formatter_to_array
   File "eth_utils/address.py", line 114, in to_checksum_address
   File "eth_utils/crypto.py", line 9, in keccak
   File "eth_hash/main.py", line 38, in __call__
   File "eth_hash/main.py", line 22, in _hasher_first_run
   File "eth_hash/backends/auto.py", line 18, in keccak256
   File "eth_hash/backends/auto.py", line 11, in _initialize
   File "eth_hash/utils.py", line 15, in auto_choose_backend
   File "eth_hash/utils.py", line 52, in choose_available_backend
 ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
 Install with `pip install eth-hash[pycryptodome]`

**packages mentioned in ImportError are already installed:**

root@hscuser-OptiPlex-3050:/home/hscuser/package# pip install pycryptodome
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.5/dist-packages (3.6.4)
root@hscuser-OptiPlex-3050:/home/hscuser/package# pip install pysha3
Requirement already satisfied: pysha3 in /usr/local/lib/python3.5/dist-packages (1.0.2)

Any hint? whats going wrong?

**Comment by Shaptic** [comment]
Take a look at this for the fix that worked for me: pyinstaller/pyinstaller#3681.
