### ISSUE TITLE
Websocket Implementation Question

### ISSUE THREAD

**Issue by webjunkie01** [ethereum/web3.py#990]
* Version: 4.5
* Python: 3.6
* OS: osx

Hi guys,

I've an HTTP API endpoint working very well and now I would like to create a limited Websocket version of my API.

I don't know much about this subject so I'm brute forcing my self into this. So far I have this script working.

```
from web3 import Web3, WebsocketProvider
import json
import asyncio

ws_provider = 'wss://ropsten.infura.io/ws' #this might not work 
web3_provider = WebsocketProvider(ws_provider)
loop = asyncio.get_event_loop()
web3 = Web3(web3_provider)
async def test():
      args = ("eth_getBalance",['0x2075967CFda86234d674402b452E6be47daDDf9E',"latest"])
      res = await loop.run_in_executor(None,web3_provider.make_request,*args)
      return res

res = loop.run_until_complete(test())
print(res)
```
so if I add a while statement and `asyncio.sleep(0.5)` inside the function it will run in a loop and I can add logic to check if the balance has changed or not but I wonder if there's a way to subscribe to the to the eth_getBalance method on my geth node and listen for changes.

Could anyone give me any pointers that could help me?.

**Comment by voith** [comment]
@webjunkie01 Web3 manages its own event loop for `WebsocketProvider`. There's no need for you to create your event loop.
Use  `WebsocketProvider` just like the way you use `HTTPProvider`.
```python
from web3 import Web3
ws_provider = 'wss://ropsten.infura.io/ws' #this might not work
w3 = Web3(Web3. WebsocketProvider(ws_provider))
w3.eth.getBalace('address')
```
However, the code above is blocking and probably doesn't serve your use case.

> if there's a way to subscribe to the to the eth_getBalance method on my geth node and listen for changes

Not that I know of.

**Comment by webjunkie01** [comment]
@voith Got it man, thanks!.
